### ISSUE TITLE
[DRG] Full Thrust Combo Plus locks on jump when lvl 74+

### ISSUE THREAD

**Issue by Blodispic** [Nik-Potokar/XIVSlothCombo#100]
At level **74** or higher when we unlock the **High jump** spell, Full thrust combo locks on Jump

**Comment by Nik-Potokar** [comment]
Oh right forgot about that!

Will deploy a fix as soon as I'm home 
Sorry about that and thanks for pointing it out

**Comment by Nik-Potokar** [comment]
Pushed an update but I am unable to test since my dragoon isn't at that lvl yet

Can you please test and report back if it's working correctly

Thank you!

**Comment by Blodispic** [comment]
Works well now !

**Comment by Blodispic** [comment]
Don't know if it's intended but Mirage Dive is not used on the combo

**Comment by Nik-Potokar** [comment]
Right that's correct for now 

But that will be added along with the rest of the features to make the most optimal "one button combo" 

I am open to any suggestions how that is supposed to look like since currently my drg is only lvl40 so I am unable to test the most optimal combo myself rn
