### ISSUE TITLE
[NIN][BUG] "Hellfrog Medium" not being used for single target between levels 62 to 68

### ISSUE THREAD

**Issue by Spanglish1337** [Nik-Potokar/XIVSlothCombo#1004]
Greetings,

Hellfrog Medium is the only spender NIN has currently between levels 62 towards 68 possible to be casted, even during single target, but it is not being done so. Instead, a gray Bhavacakra shows up. 

This has been tested twice with a lvl 70 nin, in Bardam's Mettle (lvl 65 dungeon) and The Pool of Tribute (lvl 63 trial).

**Comment by ArcanaXVIII** [comment]
Yeah I had noticed this issue and brought it up on Discord at the begining of the month.

https://discord.com/channels/957680331056615506/957949182319157269/1014847083364241450

Devs looked at it, I don't know if it's been fixed internally and just waiting for a new release though.
