### ISSUE TITLE
SMN Request

### ISSUE THREAD

**Issue by Wolfies11681** [Nik-Potokar/XIVSlothCombo#1008]
hello! would it be possible to add the following option:
once titan has engaged and we are spamming gemshine and OR precious brilliance can the icon change to mountain buster after each time we press it? so 1 button combo with gemshine/precious and it weaves in mountain buster

**Comment by GibXIV** [comment]
![image](https://user-images.githubusercontent.com/105976933/192138973-20c93af4-e535-4535-af03-0aac42a16247.png)

These options are already in Sloth, please check what settings you use, and if needed ask on discord in #smn channel for assistance.

**Comment by Wolfies11681** [comment]
No it doesn't. What it does is adds it to the sloth button (number 1 button for me). I would like these combos to be separate. I like the combos, but I don't just want to spam 1 all day. But now that I think of it; could it be linked with egis instead?
For example I press sloth button (#1) constantly; but when demi phase ends; i SPAM titan egi and i get:

topaz rite -> mountain buster -> topaz rite -> mountain buster -> topaz rite -> mountain buster -> topaz rite -> mountain buster

garuda egi:
slipstream -> emerald rite -> emerald rite -> emerald rite -> emerald rite

ifrit egi
ruby rite -> ruby rite -> crimson cyclone -> crimson strike.

Once again; yes they work when you just wanna spam 1 all day; but it would be nice if they could be their own combo chain if that makes sense

**Comment by Genesis-Nova** [comment]
As discussed in the #smn channel with you the other day, this doesn't seem to be something we're looking to implement at the moment.
