### ISSUE TITLE
[MCH] Make alt drill/air feature work with enhanced reassemble

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/XIVSlothCombo#101]
I know this is an old issue, but I am making it official, to keep track of it.

If Reassemble has 1 stack, it won't hold drill/air/chainsaw. It is supposed to hold until no stacks of Reassemble are available.

**Comment by Codemned** [comment]
Alternate Drill/Air Feature on Main Combo functions as intended and exactly as its description.

Try the Drill/Air/Chain Saw Feature On Main Combo instead it might serve your needs better.

If none of this helps you, You could try asking for a Alternate Alternate Drill/Air on Main Combo feature.

**Comment by sauronshotdogs** [comment]
Description says it will add them to combo ONLY if reassemble is active or on CD. Since enhanced reassemble has 2 charges, every time you use one, it would technically be on CD, while you'd still want it to hold until charges are empty though.

**Comment by Iaotle** [comment]
If you describe it really well I can try to work on it. Can you please describe your desired behavior in detail and the reasoning for why the current combo is insufficient?

**Comment by sauronshotdogs** [comment]
The way it works now is that it will not put drill/air/chainsaw into main combo unless reassemble is active OR reassemble is on CD.  at 76 reassemble got 2 charges, meaning if one charge is used, one will still be available to use BUT it will technically be on cd, meaning drill/air/chain will get added to main combo.

I would like it to count reassemble being at 1 charge instead of 2 as not being on cooldown, and to hold until reassemble is active.

**Comment by Astelteyn** [comment]
Ea. Yes, this problem exists. Thus, if there is one not used reassemble, Air/Drill/Chainsaw it is still added to the main combo. And when we go out on the rotation and live by reasable, it turns out that it "as it were" is always in a rollback. 

Да, проблема существует. Если есть один неиспользованный скилл Reassemble, Air/Drill/Chainsaw продолжает добавляться в мейн комбо. А когда мы в бою прожимаем Reassemble постоянно, получается, что он "как бы" всегда на КД.

**Comment by Nik-Potokar** [comment]
Added same check as AST Cards (2stacks) so please let me know if that fixes the issue since im unable to test it myself

**Comment by Astelteyn** [comment]
Not put drill/air/chainsaw into main combo when use first Reassemble.

**Comment by Astelteyn** [comment]
But that better then earler version)

**Comment by sauronshotdogs** [comment]
I have no clue what Astelteyn is talking about at all.

When Reassemble is at 2 charges, it will hold, but it won't put air/drill/chain into the combo until activated for the 2 time. It's like it doesn't acknowledge the first activation and charge being used.

**Comment by sauronshotdogs** [comment]
Still doesn't work for the 1st charge. Same issue as posted above

**Comment by sauronshotdogs** [comment]
` {

                        if (HasEffect(MCH.Buffs.Reassembled) && reassembleCD.CooldownRemaining <= 55 && !airAnchorCD.IsCooldown)
                            return MCH.AirAnchor;
                        if (reassembleCD.CooldownRemaining >= 55 && !chainsawCD.IsCooldown && level >= 90)
                            return MCH.ChainSaw;
                        if (HasEffect(MCH.Buffs.Reassembled) && reassembleCD.CooldownRemaining <= 55 && !drillCD.IsCooldown)
                            return MCH.Drill;
                    }`

Haven't tested below 90 yet, but at 90, this works as advertised. Will hold air/drill/chain if reassemble is available, works with charges.
