### ISSUE TITLE
[GNB] Burst Strike into Double Down feature improvement

### ISSUE THREAD

**Issue by bronzo44** [Nik-Potokar/XIVSlothCombo#1010]
Hello,
let me start with saying that I love this feature, it's the only thing I use Sloth for and I find it amazing, making me save a very needed keybind and at the same time making the BS/DD key feel so... Nice and powerful!

That said, there is one pretty big issue with this: using this feature forces you to drift DD by 1 GCD every minute: this happens because DD's cooldown comes off together with the GCD timer, hence the key is a Burst Strike all the way until the GCD ends, and only after that it becomes DD. So, if you spam the key, you'll fire off a Burst Strike, even if in that GCD DD is already up (but Sloth couldn't change the key in time).

Currently you can either clip the GCD to wait for Sloth's substitution (which will likely lose you the 9th NM gcd) or have a separate keybind for DD to use just occasionally, since you can afford with 2.42 or even 2.45 sets to drift almost all DDs and then reverse drift it with a couple off-CD usages.

Now, both solutions kill the purpose of Sloth. Moreover, the 2.50 set that's been recently proposed and that looks like it could be actually strong in a few fights this tier totally negates the possibility of drifting DD, since the reverse drift cannot happen at 2.50 - which means, if you drift it, you drift it for good and eventually it'll slip out of NM.

**What I think could be a reasonable solution** is to change how the BS-DD key substitution works, making it so the swap happens 1 or 2 seconds before DD comes off CD. This would allow players to have DD on the key before the GCD finishes rolling, and fire it off CD.

This is possible because there is no scenario in which, during NM, you want to fire off a stray BS when DD is coming off CD.

Sorry for the textwall, I wanted to be as precise as possible with this request. Thank you for your attention!

**Comment by k-kz** [comment]
This may have been addressed in #965 (which is pending in the `v3.0.17.3` update) - it's out of my area of expertise so I'm not 100% sure.

@damolitionn

**Comment by k-kz** [comment]
Addressed in #965
