### ISSUE TITLE
FPS drop with setup window open

### ISSUE THREAD

**Issue by Valmere** [Nik-Potokar/XIVSlothCombo#1011]
I noticed a large drop in FPS when the setup window is open and one of the class menus are expanded. The drop is increased when multiple options are selected for a class and increased further when the main settings option "hide conflicting combos" is enabled.

Again this is only when the setup window is open, FPS returns to normal when minimized or closed.

**Comment by Daemeous** [comment]
Aye, that's a problem with imgui. Not one I think we can do much to mitigate, sadly, as we're just using it, not writing it. You should've seen how bad it was when you could have multiple jobs options open at once...

**Comment by k-kz** [comment]
This is something we're fully aware of and have mitigated slightly by forcing job dropdowns to close as others are opened.
As far as I'm aware, we're unsure whether we can fix it at this point, but we'll keep an eye out for any other possible improvements as things go.
