### ISSUE TITLE
Download Failed

### ISSUE THREAD

**Issue by Munhrar** [Nik-Potokar/XIVSlothCombo#1021]
its normal? I searched and updated the link and it's still the same.
![nikpotokar](https://user-images.githubusercontent.com/47261538/193944621-6938dfc8-b159-402a-8e3d-05288b2b0037.jpg)

**Comment by k-kz** [comment]
That isn't the repository link.

Please add `https://raw.githubusercontent.com/Nik-Potokar/MyDalamudPlugins/main/pluginmaster.json`

**Comment by Munhrar** [comment]
I had put that same link, however, I had to delete the old one and put it again, because just pasting the new one in place of the old one, didn't solve it.

Thanks
