### ISSUE TITLE
Single Target DPS Biolysis Option

### ISSUE THREAD

**Issue by PuckAlive** [Nik-Potokar/XIVSlothCombo#1041]
Hello!

Would it be possible to have an option to make the Automatic DoT uptime feature have biolysis replace Ruin II instead of Ruin/Broil?

Thank you!

**Comment by Daemeous** [comment]
Yes, you can activate this feature below the AoE DPS feature.
![image](https://user-images.githubusercontent.com/7772949/194732033-f699e3c6-0a30-4526-bc8b-68fac3cb3152.png)

**Comment by PuckAlive** [comment]
I installed an older version of this and apparently when you do that, trash it, and install this newer version, Dalamud just pretends you installed the older version instead...

Thank you!

**Comment by Daemeous** [comment]
If you downloaded out plugin from a megarepo you will end up with older versions, this has been happening a lot lately.

Please make sure you're getting the version from our official repository:
https://raw.githubusercontent.com/Nik-Potokar/MyDalamudPlugins/main/pluginmaster.json

**Comment by PuckAlive** [comment]
Yeah no worries, I manually did all the things, and is good now.

Before I open a new issue, Biolysis only replaces Ruin II after the DoT falls off and not 3 seconds before, like on the Ruin version. Is that by design, or should I open a ticket?

**Comment by Daemeous** [comment]
You're right, we're actually doing a big rework right now for the next version. I've just passed this on to the right person.
