### ISSUE TITLE
 [SCH] Cant use dps feature without losing access to ruin 2.

### ISSUE THREAD

**Issue by Raionsao** [Nik-Potokar/XIVSlothCombo#105]
if you want to use DPS feature with Broil, Lucid, Bio you can no longer use the instant cast ruin 2 for when u need to move.

would be useful if ruin 2 could be separated from the rest.

**Comment by Nik-Potokar** [comment]
Will remove ruin2 from dps feature later today

**Comment by Nik-Potokar** [comment]
Should be all fixed
