### ISSUE TITLE
[MNK] `Dragon Kick` --> `Bootshine` Feature

### ISSUE THREAD

**Issue by DDD726** [Nik-Potokar/XIVSlothCombo#1059]
Even with the Leaden Fist buff, Bootshine is only more effective than Dragon Kick with Opo-Opo or FF.
Is it possible to update to switch only those cases in a from ?

**Comment by Kagekazu** [comment]
thats already in the code that it only changes to bootshine when it has opo-opo form

**Comment by DDD726** [comment]
![image](https://user-images.githubusercontent.com/34339843/196003494-8470979c-3fe8-43b8-abf3-4b2406018111.png)
Thank you for your reply. It is true that SimpleMode changes to only when it has opo-opo form, but it seems that the conditional expression is different for single function. The code is probably here.

**Comment by Kagekazu** [comment]
ill check the single code out and i can prob whip up the same check on the other ST function that uses it.

**Comment by Kagekazu** [comment]
i just double checked, for every bootshine in a combo, it checks for opo-opo and leaden or formless fist. Is there a combo u got active where it does bootshine where it should do dragon? Then i can check that part exactly for an error.

**Comment by DDD726** [comment]
Duplicate of #1073
I changed the relevant code.

**Comment by Kagekazu** [comment]
i changed it aswell in my "rework" of monk ^.^ #1072
