### ISSUE TITLE
[DRG] Full Thrust Combo Plus breaks on Chaotic Spring

### ISSUE THREAD

**Issue by ask-42** [Nik-Potokar/XIVSlothCombo#106]
You can see the bottom slot (from Full Thrust Combo Plus) doesn't properly upgrade Chaos Thrust to Chaotic Spring
It does upgrade properly in the Chaos Thrust Combo (on the left)

![image](https://user-images.githubusercontent.com/47505079/148493421-26a6aacf-ba0a-4f82-a691-898591877607.png)

**Comment by Nik-Potokar** [comment]
Should be fixed now 

Just as a side note the plus feature isn't finished yet (since I'm unable to test it fully myself )

**Comment by davood456** [comment]
Hi, this still seems to be an issue

**Comment by Nik-Potokar** [comment]
Was updated so the icon issue should be fixed now
