### ISSUE TITLE
[MNK] AOE combo is broken after 6.05

### ISSUE THREAD

**Issue by StevieCoops** [Nik-Potokar/XIVSlothCombo#107]
Currently, the AOE combo doesn't seem to return Four-Point Fury when Shadow of the Arm is used. It still works below 82 when using Arm of the Destroyer though

**Comment by Nik-Potokar** [comment]
But it was working before ?

I've updated it please give it a try and let me know

**Comment by Random-Stack-Random-Day** [comment]
I actually noticed this as well. I came to submit a ticket, I need to test further to see if I can figure it out, but randomly it is getting stuck on Shadow of the Destroyer. It'll tend to randomly fix itself after PB? I haven't quite seem to figure out when it's unbreaking. It'll just be randomly during a pull.

**Comment by Random-Stack-Random-Day** [comment]
I looked at [the function](https://github.com/Nik-Potokar/XIVSlothCombo/blob/main/XIVSlothCombo/Combos/MNK.cs#L74) and honestly it seems right, but in practice it looks like it's only triggering if I start it in Opo-Opo form.

Starting from no form -Endless cycle of the base ability (Shadow of the Destroyer in this case.
Started from Coeurl form - Endless cycle.
Started from Raptor form -Endless cycle
Starting from Opo-opo, proper handling of this function.

**Comment by Nik-Potokar** [comment]
Can you test it with only monk aoe feature enabled please?

Because it seems to be only an issue with shadow and not arm of the destroyer

**Comment by Random-Stack-Random-Day** [comment]
@Nik-Potokar  I tried it with only Monk AoE on, similar results from above.
I tried with both Shadow and Arm (However, it's of course turning Arm into Shadow but has the unique ID of 62 and 25767 respectively.)

It still is only reacting if you're in Opo-opo form, or in Formless. I really can't see why, though.

**Comment by goofy-somebody** [comment]
please forgive this post if it doesn't help, but wouldn't you want to separate the conditionals on each side of the OR?

`if (lastComboMove == MNK.ArmOfTheDestroyer && HasEffect(MNK.Buffs.RaptorForm) && level >= MNK.Levels.FourPointFury || lastComboMove == MNK.ShadowOfTheDestroyer && HasEffect(MNK.Buffs.RaptorForm) && level >= MNK.Levels.FourPointFury)`

TO

`if ((lastComboMove == MNK.ArmOfTheDestroyer && HasEffect(MNK.Buffs.RaptorForm) && level >= MNK.Levels.FourPointFury) || (lastComboMove == MNK.ShadowOfTheDestroyer && HasEffect(MNK.Buffs.RaptorForm) && level >= MNK.Levels.FourPointFury))`

and could it not be simplified by just making the `lastComboMove` be an OR conditional:

`if ((lastComboMove == MNK.ArmOfTheDestroyer || lastComboMove == MNK.ShadowOfTheDestroyer) && HasEffect(MNK.Buffs.RaptorForm) && level >= MNK.Levels.FourPointFury)`

again forgive me, as I know really nothing about the syntax of C#, but using my knowledge of the other programming that I know

**Comment by Nik-Potokar** [comment]
Ive added the suggestion from @goofy-somebody since maybe i just goofed 

Test and let me know please

**Comment by goofy-somebody** [comment]
@Random-Stack-Random-Day 
@StevieCoops 

I don't play MNK, so I was looking at the MNK AoE Rotation and looking at the function here, so please give it a try and see if it's working now.  :)

**Comment by Nik-Potokar** [comment]
Right so ive just managed to level MNK to 82 to test and it does not work but i have found out why and there will be a fix coming.
(For some reason lastcomboaction just dosent work on shadowofthedestroyer)

**Comment by Nik-Potokar** [comment]
New update is out that should fix this along with some other features that got reworked
