### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Flavescent** [Nik-Potokar/XIVSlothCombo#1074]
On Windows 10, FFXIV using this plugin leaks memory, at about 1 MB per task manager tick. This can be replicated by watching the task manager with the plugin enabled or disabled, respectively, while the FFXIV window is in focus. (This is perhaps because I've got the private build for some reason, according to the update log.)

**Comment by k-kz** [comment]
What "private build"?

If you're not using the latest version from the official repo, please uninstall whatever you have and run the current release.

**Comment by Flavescent** [comment]
Just did so and the memory leak disappeared, thanks!
