### ISSUE TITLE
[DRG] Adding Elusive Jump and/or Sprint as Opener Trigger

### ISSUE THREAD

**Issue by Spanglish1337** [Nik-Potokar/XIVSlothCombo#1081]
Greetings,

Good morning!
For bosses that do not have open rings, is it possible to add more options to the opener trigger, like Sprint or Elusive Jump? 

Depends on the arena, Elusive Jump might not be the proper option, but I see a lot of melee players start fights with Sprint so that kind of makes sense if it is possible.

**Comment by damolitionn** [comment]
Too much of a headache to add Sprint as an opener trigger. It'll then trigger every time you're out of combat and using sprint. It could be restricted to within instances but then I'd have to think about how AoE interactions would work with being in an opener state.

**Comment by Spanglish1337** [comment]
> Too much of a headache to add Sprint as an opener trigger. It'll then trigger every time you're out of combat and using sprint. It could be restricted to within instances but then I'd have to think about how AoE interactions would work with being in an opener state.

@damolitionn , a question, please. I might have thought this awfully wrong but I want to confirm as it would just make me just close this thread if my theory is true lol. I understand the sprint being a headache... to be honest I did not think I thought things through. 

Question is... if I press True North, and true north status is over. (Like, if the pull happens 20 seconds after pressing true north, for example). Does the opener is still triggered? Or the opener is triggered if you start combat with True North status active?

I ask because if I can just press true north as soon as I enter any raid instance or revive... then this thread in the first place should be burned with fire.

**Comment by k-kz** [comment]
The `True North` buff needs to be active.

**Comment by Spanglish1337** [comment]
> The `True North` buff needs to be active.

Got it! For now I'll close this thread and wish that people don't instantly enter combat as soon as the instance starts lol :(
