### ISSUE TITLE
[MCH] Update for Recommended 6.2 Changes (Queen, Rotation)

### ISSUE THREAD

**Issue by shoryukenpizza** [Nik-Potokar/XIVSlothCombo#1082]
I'm not entirely sure if Simple MCH or other features had any changes in Sloth due to the 6.2 changes, but Queen timings should be updated to reflect the new permanent 12sec Queen. Or maybe idk somethings wrong with my Simple MCH (I currently use 2.47-2.48, but shouldn't matter entirely too much aside from Queen potency)
![image](https://user-images.githubusercontent.com/112630314/197221483-ce418ef2-25e8-4669-ab83-aacf267f55e6.png)
Please note: if no changes can be made simply because of slight optimization/, I am okay and will understand. I appreciate all of the work Aug and the rest of MCH community does in Sloth.

As Simple MCH stands currently, here's a review of what's currently happening (to me):
1. Queen's "Crown Collider" is not being used within the pot window.
![image](https://user-images.githubusercontent.com/112630314/197225557-bf0af9f8-99b4-4f76-923c-9a31766a222e.png)
imo, I'm lazy (therefore I use Sloth), so a simple change would be to squeeze Crown Collider in here only for the opener. Although, I understand there may be limitations to this and/or I could simply just press the button myself. This leads into...

2. The opener does not follow neither recommended 6.2 openers.
![image](https://user-images.githubusercontent.com/112630314/197227817-257ba1f4-682d-48f0-ae4c-e6c0b6d8e38e.png)
versus
![image](https://user-images.githubusercontent.com/112630314/197228310-4066a0b9-f1ad-409d-835d-021abffa0c89.png)
The early tools opener is no longer used. I'm not entirely sure what this would do to the current rotation. I also noticed the last changes to MCH for 6.2 were on Aug 29, but "Le Balance" MCH opener and recommended uses for Queen were not made public until Sept 9.
![Screenshot 2022-10-21 101809](https://user-images.githubusercontent.com/112630314/197230832-c29cf5a7-4a54-4a43-b1c2-13e29be30f98.png)
Therefore, unless Aug has some secret tech implemented in Simple MCH, we aren't following the new 2.5 (slightly somewhat adjusted) opener. This also kinda correlates with...

3. Queen buff timing incorrect?
It appears now that Queen is released roughly around x:00-x:02, but Queen is missing a few punches under buffs still (or my static is just ass). For example: 
![image](https://user-images.githubusercontent.com/112630314/197239910-19c6a362-248d-4c3a-aaf1-e7d638d7ca25.png)
as compared to using Queen around x:03-x:06:
![image](https://user-images.githubusercontent.com/112630314/197240108-a3d9ccf3-e1e5-4c96-a2b3-3d789618e0b8.png)

4. 2 opener options possible? 
Similar to SCH (Dissipation opener), is it possible to have Delayed Tools opener AND General Purpose opener?

5. ???

**Comment by Spanglish1337** [comment]
This man is a truly min-maxer

**Comment by shoryukenpizza** [comment]
> This man is a truly min-maxer

Haha hardly! But MCH doesn't follow the same guidelines as prior to 6.2 anymore!

**Comment by Kitfox88** [comment]
It'd also be nice to have an option to use Chainsaw and Air Anchor in the AOE simple combo too, if that's not too troublesome, but I didn't know if it'd be cool or not to make a whole second issue _just_ for that when this one's already open about changes. Either way, thanks for all the work on slothcombo, it's made it so much easier to play with arthritis.
