### ISSUE TITLE
[RDM] Scorch bugged with feature 480

### ISSUE THREAD

**Issue by Bun1997** [Nik-Potokar/XIVSlothCombo#1088]
Hey there!

I only have the verfire/verstone feature (#480) enabled, and no other feature. After using verholy/verflare, if i have a proc, then jolt does not turn into scorch, but remains verfire/verstone. Could this be fixed?  (As in give priority to scorch/resolution on the key for jolt after a successful melee finisher)

Thanks a lot in advance!

**Comment by Tartarga** [comment]
The way RDM is setup, you need to setup the Melee Finisher options
