### ISSUE TITLE
[VARIOUS] Request: Tank 'leap' ability on main combo when at 2 charges.

### ISSUE THREAD

**Issue by PapaSteel** [Nik-Potokar/XIVSlothCombo#109]
Intervene for paladins, Rough Divide for gunbreakers, Onslaught for warriors, Plunge for dark knights. They're all ogcds and there are VERY few - if any - fights where sitting on both charges is beneficial.

Also thanks for the amazing work, your version of the combo plugin is the smoothest by far.

**Comment by Nik-Potokar** [comment]
Will test and add tonight as an separate option

**Comment by PapaSteel** [comment]
You're a treasure.

**Comment by Nik-Potokar** [comment]
Test and let me know

**Comment by sauronshotdogs** [comment]
Is the intent to spend all charges, or to just spend one, so they're always recharging?

**Comment by Nik-Potokar** [comment]
Currently so it uses all but can add an option to only use 1 so you always have 1

**Comment by sauronshotdogs** [comment]
I would prefer that, but don't know about OP.

Also, Warrior has 3 charges, so it would need to have 2 charges remaining.

**Comment by Random-Stack-Random-Day** [comment]
I'd agree, if it could leave one charge that'd be perfect. Or use it when remaining CD < 2 seconds or something.

**Comment by sauronshotdogs** [comment]
Having it leave 1 (or 2 in warrior's case) would be optimal then.

**Comment by sauronshotdogs** [comment]
The most recent change works perfectly for GNB and DRK, 

For WAR onslaught feature will use 2, leaving 1, while the Option will use all 3, leaving none (should leave 1/2 depending on lvl)

**Comment by sauronshotdogs** [comment]
Hate to say it, but it still spends all WAR charges as soon as they're available

**Comment by sauronshotdogs** [comment]
Now Feature works as advertised. Option uses only leaves one instead of 2 though.

For warrior, it's supposed to leave 2, as they have 3 charges in total.

**Comment by Codemned** [comment]
It'll leave 1 charge whether it's enhanced or not.

**Comment by sauronshotdogs** [comment]
Is it not possible to have it leave 2?

**Comment by Codemned** [comment]
It's possible to have it leave 3, try that option.

**Comment by sauronshotdogs** [comment]
I really don't get the hostility guy. I just asked a question.

**Comment by Codemned** [comment]
No that's not how it works.

**Comment by sauronshotdogs** [comment]
That is exactly how it works. I have it working on my end

**Comment by sauronshotdogs** [comment]
Thanks

**Comment by Codemned** [comment]
If remaining cooldown is less than 1 second shouldn't be storing 2 charges of a 90 second cooldown but i guess it's another one of the quirks.

**Comment by sauronshotdogs** [comment]
I just tried different values until it worked. Setting it to 15 would use it with 1 charge, with 15 to next charge. How it works now, it uses a charge 1 second before gaining 2 charges.
