### ISSUE TITLE
[DRK] #177 Delayed Bloodspiller is only functional during the opener and does not apply any delay during 2 min burst windows.

### ISSUE THREAD

**Issue by stein-indee** [Nik-Potokar/XIVSlothCombo#1096]
Currently, feature *#177 Delayed Bloodspiller* does not perform the delay outside of the opener. The description indicates that the delay should occur during every 2 minute burst, but this does not happen.

`
//Delayed Delirium
if (IsEnabled(CustomComboPreset.DRK_DelayedBloodspiller) && GetBuffStacks(Buffs.Delirium) > 0 &&
                                ((GetBuffStacks(Buffs.BloodWeapon) <= 2 && CombatEngageDuration().TotalSeconds < 30) || CombatEngageDuration().TotalSeconds >= 30))
                                return Bloodspiller;
`

The check for this feature also seems to indicate that this is how it currently functions.

**Comment by k-kz** [comment]
That's a description issue - the delay is intended to function inside the opener only.
Will get it updated for next release.

**Comment by Tartarga** [comment]
Done, Stale / Pre Dawntrail
Closing
