### ISSUE TITLE
[AST] Request: Level Adjust for DPS Feature

### ISSUE THREAD

**Issue by Ivylia** [Nik-Potokar/XIVSlothCombo#110]
It would be lovely if the various options for the DPS feature for the AST would automatically disable in lower level dungeons if the skill's level is too high for said dungeon. An example would be the 'Auto Card Draw' feature, and having it disable for the duration of a sub level 30 dungeon as 'Draw' is a level 30 skill, and then automatically re-enabling after leaving the dungeon. Thank you!

**Comment by Nik-Potokar** [comment]
Should be fixed now added level checks on everything!
