### ISSUE TITLE
[DRG] Option to have Jump/High Jump + Mirage Dive, Geirskogul, and Nastrond to be oGCD'd with Ranged Uptime feature.

### ISSUE THREAD

**Issue by Spanglish1337** [Nik-Potokar/XIVSlothCombo#1104]
Greetings,

As title suggested, an option to have these abilities to be able to be oGCD'd during ranged uptime feature would be good.

I have been found in certain situations that, due to the previous mentioned not happening as the boss moves or mechanics that makes us be out of range (+ bad boss positioning), it would help not miss timings, and also to have Nastrond just keep being used in range, as it does not happen unless you press it manually (at least, for me)

I do not mention Stardiver here because that one is indeed a gapcloser vs jump / high jump.

**Comment by Tartarga** [comment]
Obsolete with Dawntrail
