### ISSUE TITLE
[SMN] Crimson Cyclone melee range check

### ISSUE THREAD

**Issue by ctrlsoul** [Nik-Potokar/XIVSlothCombo#1105]
First of all, thank all devs for working on this great plugin. I am new to savage and currently progging p5s on pf using SMN. I am using the simple SMN rotation feature for now. However, I found that Crimson Cyclone sometimes became available when I was spreading out (e.g. during Ruby 5 spread) and it charged me to the boss that eventually wiped the team. It would be super helpful to avoid using Cyclone when it's not at melee range. Thank you all again!

**Comment by sauronshotdogs** [comment]
I just disabled it, and manually used it during p5s. It would be nice to get a melee check, just like some DRG features

**Comment by Genesis-Nova** [comment]
> I just disabled it, and manually used it during p5s. It would be nice to get a melee check, just like some DRG features

Generally that's what I'd recommend.
Movement type damage abilities shouldn't really be used as part of a "one button" rotation anyways, it's just included for feature completeness.
I manually use ifrit combo during that phase.
