### ISSUE TITLE
patch 11/14 issue with sam opener

### ISSUE THREAD

**Issue by XCZA** [Nik-Potokar/XIVSlothCombo#1114]
as of patch 11/14, SAM opener combo doesnt work. after getting all three stickers it doesn't use iaijutsu, just loops the Yukikaze combo unless you use Ogi Namikiri. Ogi Namikiri also overwrites iaijutsu, so unlesss you disable the combo the opener is super scuffed.

**Comment by Kagekazu** [comment]
Heya! for me the opener works perfectly.

is it possible to do /scombo debug sam in game and post the logfile of it? It might be a forked repo or some weird stuff.

**Comment by XCZA** [comment]
i disable Ogi Namikiri on Main combo and left the child option active (use in even and burst) and it appears to be working now, i had that checked in the past and it didnt interact in this way.
