### ISSUE TITLE
[DRG] IsMoving option for the dives. 

### ISSUE THREAD

**Issue by Spanglish1337** [Nik-Potokar/XIVSlothCombo#1115]
Greetings,

I would ask if it is possible to add a IsMoving option for Spineshatter, Dragonfiredive, and StarDiver if possible. 

There are times where while you move to dodge mechanics, because of the lock, it can still hit you. Maybe it could help? But I understand if it need to be considered and tested a lot first if it is possible.

**Comment by Rabalaba** [comment]
It is possible, they added it for summoner's ifrit spells if I remember correctly, IsMoving is just a bool that return true if your icon on the minimap is moving.

**Comment by k-kz** [comment]
Yeah, it's possible - I added the `Consideration Needed` tag to mark it as something we'll be discussing for the update after next.
I don't see any reason why we can't add it as a sub-option, though.

**Comment by Spanglish1337** [comment]
I did not know IsMoving could be added as a sub-option! That would be awesome! I think the more sub-options the better but I am biased because I like customization a lot. Like #1104 if it can be added as sub-options, the merrier! Just to not have to cast Nastrond manually on range lol. I need to take more calcium
