### ISSUE TITLE
Cross Reaping / Void Reaping not being added to main combo during enshroud

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/XIVSlothCombo#1128]
During enshoud, the main combo will try to put the 123 combo instead of the enshroud combo, preventing any abilities from being used from main combo.

I am on the git version, if that makes a difference

![image](https://user-images.githubusercontent.com/95890035/204121601-77de8796-0999-49fe-8972-03ed181c3d51.png)

https://i.imgur.com/wpx8eh6.mp4

**Comment by sauronshotdogs** [comment]
It will sometimes fix itself if I turn the option of void/cross reaping on and off again.

**Comment by k-kz** [comment]
Tested this with your options across a few dungeons and a dummy earlier and am totally unable to replicate the issue.

Regardless, please use the release version to avoid encountering features that are unfinished/broken/in testing etc.

**Comment by sauronshotdogs** [comment]
Super weird. It would happen to me regardless of target. I've gone back to stable, and that works perfectly fine.
