### ISSUE TITLE
possible Bug on multiple jobs  

### ISSUE THREAD

**Issue by doh666** [Nik-Potokar/XIVSlothCombo#1129]
Hello I have been seeing an issue on Warrior and Machinist. Where it tries to activate the next skill in a rotation but doesn't activate. Makes a sound like its trying to activate then stops. Specifically on infuriate on war and ricochet and gauss round on machinist could be a ping issue. My ms. is 21 and my Gcd. is 2.42s for both

**Comment by Taurenkey** [comment]
These issues tend to rise whenever you swap jobs. It's not actually a Sloth bug, but one you can replicate without plugins.
