### ISSUE TITLE
[DRK] AOE combo replacements

### ISSUE THREAD

**Issue by Elypha** [Nik-Potokar/XIVSlothCombo#1136]
Hello, I'm just simply wondering why the AOE combo function replaces the first skill (Overpower) in the combo for WAR but the second one (Stalwart Soul) for DRK. Is there any consideration on this?

edit: My problem is that, I think it could be better if similar logics can be applied to all the 4 tank jobs

**Comment by Tartarga** [comment]
Stale / Pre Dawntrail
Closing
