### ISSUE TITLE
AST- Draw on Play module slows game tremendously when solo and DPS card comes up

### ISSUE THREAD

**Issue by QueenLinuxGlitch** [Nik-Potokar/XIVSlothCombo#1137]
hopefully self-explanatory

**Comment by Genesis-Nova** [comment]
Are you able to replicate this with no other plugins active?
I can't exactly test right at the moment but it'd be nice to be able to know for sure that it's sloth causing the problem or not.

**Comment by QueenLinuxGlitch** [comment]
Will test w/o other plugins, currently have tested toggling all options within Sloth, and with/without ACT. This is the first real problem I've seen with it

**Comment by QueenLinuxGlitch** [comment]
Have not been able to replicate, appears to have been isolated to the last few days. Closing willingly

**Comment by Genesis-Nova** [comment]
Feel free to let us know if you can get it to happen again.
