### ISSUE TITLE
[AST] - Cards Overcap Protection

### ISSUE THREAD

**Issue by Megasder** [Nik-Potokar/XIVSlothCombo#1139]
This is a small thing so I didn't want to open a full thread in discord and I read that you guys are already working on the AST code, but just in case i'm posting this, if you already working on it you can just close this.

Just notice playing AST that the draw cards effect on yourself have unlimited time
![image](https://user-images.githubusercontent.com/92712466/209413827-2dffc683-8fee-49eb-bef4-dcf663aaf6e3.png)
And that the draw charges cool down begin to recharge at the time you use the draw skill and not when you use the card
![image](https://user-images.githubusercontent.com/92712466/209413851-b7f0ca58-52dd-45c5-a7a5-902abc4bcc50.png)
So it should be a good option to have that outside of combat with 2 stacks of Draw (even with targeting a enemy) malefic turns into draw, then you use draw and because of that the Draw Skill its already recharging, even if you are not using the card on a party member, so when the fight starts the skill cool down is almost done and you can use it again. 

The only other thing is if you have 2 stacks and you already have a Draw Card Effect don't use it so you don't waste a card.

**Comment by Tartarga** [comment]
Obsolete
