### ISSUE TITLE
[SGE] Eukrasian Diagnosis Option Not Working?

### ISSUE THREAD

**Issue by cjtylr** [Nik-Potokar/XIVSlothCombo#1145]
Hi there,

Not sure if I'm doing something wrong, but I can't get Sage's Eukrasian Diagnosis Option to actually cast Eukrasia above the target HP %. In fact, the only time I can get it to even show Eukrasia first is by setting the HP % to 100, but of course that means non-Eukrasia Diagnosis is never cast.

Let me know if I'm missing a specific setup that could fix this. Thanks!

**Comment by Tartarga** [comment]
Can you provide a screenshot of your settings?

**Comment by cjtylr** [comment]
Here you go! 
![image](https://user-images.githubusercontent.com/2467883/211184899-7d1422d9-05aa-4bea-b046-512b6970db26.png)

**Comment by Tartarga** [comment]
It's been a long weekend, and I'm having trouble following.

This statement "can't get Sage's Eukrasian Diagnosis Option to actually cast Eukrasia **_above_** the target HP %"

The option description says "When Target HP is **at** or **below** set percentage". Not above. It will not replace Diagnosis with Eukrasia until then, unless you press activate Eukrasia manually.

**Comment by cjtylr** [comment]
Apologies, I may not be explaining well or may be misinterpreting the purpose of the combo option. "Diagnosis becomes Eukrasian Diagnosis if the shield is not applied to the target." is the core description.

I would expect this to always cast Eukrasia and then Eukrasian Diagnosis if there is no shield on the target UNLESS the Target's HP is at or below the percentage set in the sub option, in which case I'd expect it to cast the heal without Eukrasia.

Is that not how the option is meant to function? Thanks!
