### ISSUE TITLE
[RPR] Unchecking Arcane Circle Option in Slice Combo Feature Ignored?

### ISSUE THREAD

**Issue by cjtylr** [Nik-Potokar/XIVSlothCombo#1146]
Hi there,

Not sure if I'm doing something wrong, but Reaper's Slice Combo Feature continues to include Arcane Circle even when Arcane Circle Option is unchecked.

Let me know if I'm missing a specific setup that could fix this. Thanks!

**Comment by Nik-Potokar** [comment]
This is due to having "Level 90 opener" enabled which includes arcane circle even if you disable it since its trying to do the selected opener.

**Comment by cjtylr** [comment]
Thank you very much!
