### ISSUE TITLE
[SAM] shoha 2 not showing in aoe 1 button

### ISSUE THREAD

**Issue by kazumaKiryu542** [Nik-Potokar/XIVSlothCombo#1148]
shoha 2 doesnt show even with 3 meditate stacks when using one button

**Comment by Kagekazu** [comment]
can u show ur options? Cause it shows for me on the AoE combo

**Comment by kazumaKiryu542** [comment]
![image](https://user-images.githubusercontent.com/107214188/211224992-2c5f4fef-26e2-4a47-8b17-dc4369087be4.png)
