### ISSUE TITLE
[PLD] Scornful Spirits feature doesn't account for 90 content.

### ISSUE THREAD

**Issue by PapaSteel** [Nik-Potokar/XIVSlothCombo#115]
This particular option needs to replace Expiacion over Spirits Within at 86+ content for it to still be functional.

**Comment by Codemned** [comment]
It replaces either Spirits Within or Circle of Scorn, just drag either of those to your hotbar and use the feature.

**Comment by PapaSteel** [comment]
Hm, it worked perfectly for me 'til I unlocked the Expiacion trait, and now it still swaps from Circle -> Spirits (which is greyed out) or doesn't change with Expiac on the bar. I'll keep fiddling and will try to find a user error fix.

**Comment by PapaSteel** [comment]
Turns out that fully disabling PLD and re-enabling the options fixed it. Apologies!
