### ISSUE TITLE
XIV Launcher (not updating)

### ISSUE THREAD

**Issue by bostonpsycho** [Nik-Potokar/XIVSlothCombo#1154]
I can see everything successful on the settings, Everything in the game however doesn't seem to be able to update. Looking for a solution or if i just need to wait a little longer for it to be pushed?

**Comment by N7Nobukai** [comment]
Having the same issue

**Comment by KhaozFrost** [comment]
Thats because they haven't updated it for 6.3 yet.
Join their discord and wait until its been pushed out.

**Comment by N7Nobukai** [comment]
Gotcha, just joined the discord and I see availability. Thanks!

**Comment by k-kz** [comment]
@bostonpsycho if you're still having trouble with this, please try uninstalling the plugin, refreshing Dalamud and reinstalling. If that still doesn't work, uninstall, remove and re-add the repository link in Dalamud settings, then reinstall.

Going to pin this and leave it open for now to prevent recurrence.

**Comment by bostonpsycho** [comment]
@k-kz Thank you! it works now. I'm new to Github so i thought the update, times and everything means it pushed already. My fault on ignorance and impatience, i apologize. So far the update works and works pretty well! Thank you again! I joined the discord, from previous comments and that helped a ton. 

Hope you all have a great weekend
