### ISSUE TITLE
[NIN] First Mudra Issue

### ISSUE THREAD

**Issue by baronbeef** [Nik-Potokar/XIVSlothCombo#1155]
When using Simple or Advanced Mode for Ninja, the first mudra for some reason has a recast time of 2.5 seconds.

Link of Issue : https://drive.google.com/file/d/1fbuOeyzBU6P51ogbgAZJARRa-s36FsMj/view?usp=share_link

**Comment by k-kz** [comment]
This is an SE issue unfortunately, and was apparently not fixed (for NIN) in the latest hotfix patch.
I'm hearing NoClippy has a temporary fix they've built to tackle this, so please give that a shot until there's another patch.

Just going to pin this and leave it open for now to prevent recurrence.
