### ISSUE TITLE
GNB bugs V. 3.0.18 - Options: #259 & #270

### ISSUE THREAD

**Issue by NyxOfficials** [Nik-Potokar/XIVSlothCombo#1159]
```
GNB -  259  Cooldowns on Main Combo
   GNB -  261 - Danger Zone/Blasting Zone
```

Not activating properly, as it should be used on CD with or without No Mercy. Sometimes it will work; sometimes, it forgets.

Keep in mind Danger Zone/Blasting Zone 30sec CD. You should have it activated twice. 1st under No Mercy and 2nd outside No Mercy. To avoid drift, it has to be active at all times. A better implementation would be making a stand-alone option for Danger Zone/Blasting Zone uptime, just like WAR Upheaval option.
    

```
GNB - 270 - Gnashing Fang Continuation Combo
   GNB - 271 - No Mercy on Gnashing Fang
```

- When you have full powder gauge ammo No Mercy icon is not on top of Gnashing Fang. You have to start No Mercy to trigger it.
- No Mercy icon goes away a bit fast and is not persistent until activation, even when standing still, requiring manual activation of No Mercy. 

Debug file is attached, and a clip is provided in the Discord thread if you need more info.
[SlothDebug.txt](https://github.com/Nik-Potokar/XIVSlothCombo/files/10435571/SlothDebug.txt)

**Comment by Taurenkey** [comment]
Having looked at the code, it's very stringent in keeping your cooldowns available for the No Mercy window, as it's checking if there's more than 17 seconds remaining on the cooldown for No Mercy to use Danger Zone outside of No Mercy. It won't be forgetting, it's just trying to prevent your No Mercy window from being scuffed. 

The No Mercy weave window is influenced by the Skill Speed feature setting, setting it to < 2.45 changes the weave window for a number of skills, including No Mercy. You may want to consider the alternative setting for that if No Mercy is not hard to activate.
