### ISSUE TITLE
Feature request: text commands to toggle features

### ISSUE THREAD

**Issue by Cadwgan** [Nik-Potokar/XIVSlothCombo#1166]
Assuming feature numbers don't shift between updates, something like:
`/scombo enable 146 147`
`/scombo disable 146 147`
`/scombo toggle 146 147`
`/scombo toggle WAR SpiritDart`

Personally this would be useful as in certain fights you have to face away but want to keep the GCD rolling, and I keep forgetting to reenable said features after.
Something like this would also be useful for when you want to hold burst, I know alternate keys for main combo has been requested, toggling features mid fight with a macro would achieve the same effect.

edit: Didn't realise this was already a thing, either way would appreciate a more user friendly implementation, also with a "toggle" option and the possibility of using it in combat.

**Comment by k-kz** [comment]
> Assuming feature numbers don't shift between updates

They do

> Didn't realise this was already a thing, either way would appreciate a more user friendly implementation

It's not intended as a user-facing feature, really

> also with a "toggle" option 

`/scombo toggle` already exists (check readme)

> and the possibility of using it in combat

Won't be happening I'm afraid. Causes all sorts of weird bugs we can't reliably replicate, among other things.
#911 #759 #763
