### ISSUE TITLE
[PLD] #445 Holy Spirit Feature

### ISSUE THREAD

**Issue by KieWil** [Nik-Potokar/XIVSlothCombo#1172]
Would it be possible to not have '#444 Requiescat Feature' as a prerequisite for '#445 Holy Spirit Feature'? 

I am looking to combine Single Target GCDs without the oGCD 'Requiescat'. 

Something similar to how '#453 Holy Circle Feature' allows you to combine the AOE GCD combo + 'Holy Circle' and will only weave in 'Requiescat' when '#454 AoE Requiescat Feature' is enabled would be great. 

Thanks!

**Comment by Taurenkey** [comment]
Requiescat option isn't required to use Holy Spirit option, so I'm getting a bit confused. In the current version, it will only use Holy Spirit if it's an instant cast from either Divine Might or Requiescat, so even disabling the Requiescat option it will still use it with Divine Might. 

This initial build was mainly to get PLD back into a working state in the plugin, adjustments are going to be made for a bit more customization to the rotation. One such option will be to use Holy Spirit as part of the filler regardless of buffs.

**Comment by k-kz** [comment]
@KieWil we just released a PLD rework with v3.0.18.1 - please try it out and let us know if your request is still needed.

**Comment by KieWil** [comment]
Not needed anymore thank you! I have additional requests, would I be better to close this and open a separate issue, or list them below and/or rename this thread?

**Comment by Taurenkey** [comment]
It would be best you open up a seperate issue. I will close this now and you can start anew.
