### ISSUE TITLE
[PLD] Advanced and Simple AoE not level checking Prominence

### ISSUE THREAD

**Issue by Offskee** [Nik-Potokar/XIVSlothCombo#1176]
As title says, if your below level 40 both AoE modes break as the plugin wants to use Prominence but you are to low level to use it.

**Comment by Taurenkey** [comment]
Already fixed in [dbfbde6](https://github.com/Nik-Potokar/XIVSlothCombo/pull/1170/commits/dbfbde611da6246613803871b88d28f04ac90b2b).

**Comment by Tartarga** [comment]
Stale / Pre Dawntrail
Closing
