### ISSUE TITLE
[PLD] 6.3 Advanced single target - ogcds not being used under fast or riot blade and holy spirit issues

### ISSUE THREAD

**Issue by T-Rique** [Nik-Potokar/XIVSlothCombo#1177]
After playing sloth pld for a few days I've noticed a few issues with Advanced Mode - Single Target.

#436, #443, #438 and #439 are not being used under Fast Blade or Riot Blade, they work under every other gcd. This is causing pld burst to drift occasionally.

#442 When out of range Holy Spirit is being prioritized over #447 making you use Requiescat charges on Holy Spirit instead of Blades combo. As for Holy Spirit in the rotation, like someone else suggested on sloth discord, it would be good to have an option to hold Divine Might/Holy Spirit until the next Royal Authority for better melee uptime.

Amazing work besides those little issues <3

**Comment by Taurenkey** [comment]
Adjustments have been made to balancing to minimize drifting. 

Truth be told, I never actually thought about the range of the blades combo, so thank you for bringing that up. I will look to adjusting that so it's the priority for ranged when under Req.

**Comment by Tartarga** [comment]
Stale / Pre Dawntrail
Closing
