### ISSUE TITLE
Job Requests

### ISSUE THREAD

**Issue by KieWil** [Nik-Potokar/XIVSlothCombo#1179]
Just want to preface and say that I am very grateful for this plugin. Using this has made the game feel really fresh and much more enjoyable so I just want to say a big thank you!

For the most part I am looking for options to combine oGCDs with oGCDS, and GCDs with GCDs whilst still keeping mechanics that utilise unique job gauges separate.

The list is a little lengthy, but my requests are:

[DRK]
- An option to combine Blood Weapon & Delirium

[AST] 
- An option to combine the Single Heal oGCDs Essential Dignity & Celestial Intersection
- An option to combine the AoE Heal oGCDs Collective Unconscious & Celestial Opposition
- An option to combine Lightspeed, Divination, and an optional toggle for Minor Arcana

[WHM]
- An option to combine the Single Heal oGCDs Tetragrammaton & Divine Benison

[SCH]
'657 Fairy Healing Combo Feature'
- Have an option to combine Fey Blessing + Whsipering Dawn without Fey Illumination

[DRG]
- An option to combine Spineshatter Dive + Dragonfire Dive

[MNK]
- An option to combine Snap Punch + Demolish

[BRD]
'68 Bard Buffs Feature'
- Add Radiant Finale as an additional buff option
'69 One Button Song Feature '
- Have an option to combine Mage's Ballad + Army's Paeon without Wanderer's Minuet

[MCH]
- An option to combine Hypercharge & Barrel Stabilizer
'303 Drill/Air Anchor (Hot Shot) Feature'
- Have an option to combine Drill + Air Anchor/Hot Shot without Chain Saw

[RDM]
- An option to combine Corps-a-corps + Engagement 
'517 Verthunder/Veraero Option'
- An option to use Jolt + Verthunder, & Jolt + Veraero independently from each other

Thanks again!

**Comment by Tartarga** [comment]
> An option to use Jolt + Verthunder, & Jolt + Veraero independently from each other

Could you elaborate further? Using the existing options, I play with jolt, thunder, aero on 3 buttons, and jolt becomes fire/stone as needed.

**Comment by KieWil** [comment]
Sure, I'm looking for:

Slot 1 to be Jolt-Verthunder
2 to be Jolt-Veraero
3 Verfire
4 Verstone

Currently it allows for one slot to be Jolt-Verthunder-Jolt-Veraero-Jolt-Verthunder etc, but I'd rather manage the white and black gauges myself without procs. Sorry if my suggestions are kinda niche aha

**Comment by Tartarga** [comment]
Closing this for now as this is kinda stale with Dawntrail
For future requests, please break it up per class
