### ISSUE TITLE
[SCH] Timer slider for Ruin II/Biolysis feature

### ISSUE THREAD

**Issue by PuckAlive** [Nik-Potokar/XIVSlothCombo#1180]
Could we get a slider for the Ruin II > Biolysis feature the way the Single target feature has?

**Comment by Tartarga** [comment]
ruin II > biolysis will be depreciated soon. Single Target DPS feature will allow you to choose which action you want to use sloth on (Broils and/or Ruin II)

**Comment by PuckAlive** [comment]
\o/ Thank you
