### ISSUE TITLE
PLD 6.3 - Resurrected mid-rotation issue.

### ISSUE THREAD

**Issue by kabesama** [Nik-Potokar/XIVSlothCombo#1181]
I'm using Advanced Mode - Single Target.
The rotation doesn't work as expected if you die after the Requiescat, but before Confiteor, and then get resurrected.

The rotation will try to use up the Requiescat stacks by using Confiteor.
However, because you died and got resurrected, you no longer have the stacks, or the buff that makes it possible to use Confiteor.
So the rotation tries to use Confiteor until Fight or Flight is off cooldown again I believe.

This has only happened to me once, so I am not sure if it happens every time, or if the issue 100% is because of being resurrected mid-rotation.

**Comment by Taurenkey** [comment]
I have tested this in a controlled environment and can not get this to happen. When you die, all these buffs are cleared. The plugin is already checking for the existance of these buffs to decide how to proceed, so if there's no Req or Confiteor buff, it will default to other attacks. 

I am going to close this as it seems like an issue with something other than Sloth, but if you ever experience it again feel free to re-open and attach a more detailed report.
