### ISSUE TITLE
[BLM] Ley Line Bug

### ISSUE THREAD

**Issue by Facessco** [Nik-Potokar/XIVSlothCombo#1188]
I'm not sure if it's a bug. But the Layline doesn't seem to work correctly on the function Simple BLM/Advance BLM. It seemed to stutter when it wanted to use a skill before skipping it. I don't know how to explain But it's like in this video.

https://user-images.githubusercontent.com/109278703/216741577-787cecba-b812-4869-8837-a632272800ed.mp4

**Comment by Kagekazu** [comment]
Heya, 

Blm is having a rework in the pipeline. So a bit more patience and then it will all be fixed! ^.^
