### ISSUE TITLE
CTD on SAM when using Meikyo Shisui synced

### ISSUE THREAD

**Issue by MrRamen0** [Nik-Potokar/XIVSlothCombo#1192]
When on SAM and are in a FATE or instance that syncs you, using Meikyo Shisui and using Gekko will cause a crash to desktop showing the Dalamud crash popup. Currently only using the Gekko, Kasha, and, Yukikaza combo options.

**Comment by Taurenkey** [comment]
Unable to replicate, most likely an issue with an installed visual mod.
