### ISSUE TITLE
MNK Meditation Stays Persistent

### ISSUE THREAD

**Issue by MadMadaMim** [Nik-Potokar/XIVSlothCombo#1199]
On Monk, Meditation is added to both Bootshine and Destroyer combos even when it is not selected in the options.

Update: This morning it seems to be working as intended, I'm wondering if something glitched and restarting the game fixed it, I'm also wondering if the issue is with the Meditation Uptime feature as I had turned it on, didn't like it and then turned it off...I don't want to test it as of right now since it's working but if I do test it and that is the issue I will make another update.

**Comment by k-kz** [comment]
All good, please reopen if the issue pops up again and we can look further into it.
