### ISSUE TITLE
[MNK] Option to delay buffs

### ISSUE THREAD

**Issue by corgisaf** [Nik-Potokar/XIVSlothCombo#1200]
Hello, is it possible to add option for monk (maybe other dpses too) to use only GCD combo on dragon kick for example while still having full combo with buffs and everything on another button like bootshine? It would be really useful to delay buff windows.

**Comment by Luschel666** [comment]
The optimal opening skill rotation differs depending on each content, so please make it possible to select the opening skill rotation with a check box.

**Comment by Luschel666** [comment]
> 各コンテンツによって最適な開幕スキル回しが異なりますので、チェックボックスで開幕スキル回しを選択できるようにしてください。

**Elixir Field→Elixir Field**
Elixir Field→Rising Phoenix
Rising Phoenix→Rising Phoenix
Rising Phoenix→Elixir Field
