### ISSUE TITLE
[DRG] Low level ST rotation skips Vorpal thrust / Full thrust

### ISSUE THREAD

**Issue by swolewizard** [Nik-Potokar/XIVSlothCombo#1203]
Around level 26 the DRG ST rotation only spams  
- True Thrust
- Disembowel

It should go
- True Thrust
- Disembowel (Every 25-30seconds)
- True Thrust
- Vorpal Thrust
- Life Surge
- Full Thrust (If available)

**Comment by Kitfox88** [comment]
Same for me just now, synced down into Qarn.

**Comment by RealFluffyGuy** [comment]
Same, just started levelling Lancer.. up to Dragoon at the moment.
