### ISSUE TITLE
[SMN] Ruin III is not replaced when "Simple Summoner Feature" is checked

### ISSUE THREAD

**Issue by illusionag** [Nik-Potokar/XIVSlothCombo#1204]
Ruin III is not replaced when "Simple Summoner Feature" is checked.
Ruin III is not replaced when "Advanced Summoner Feature" is checked.
SMN Lv85

**Comment by Wild-Carrot** [comment]
How are you supposed to use Ruin 1 or Ruin 2 when they both automatically upgrade into Ruin 3? 

As for Outburst / Tridisaster, wouldn't this lead to conflictions when you're trying to do single target vs AoE?

**Comment by Rabalaba** [comment]
no ruin 3 is left unchanged so you can cast manually, I mean you would need to drag ruin1 for single target etc. Changing to ruin3 would not allow lower level summoners to use this feature and would not allow manual casting of ruin3.

**Comment by illusionag** [comment]
I understand that it is a specification. I'm sorry for bothering you. thank you.
