### ISSUE TITLE
[MCH] 8003 - MCH_GaussRoundRicochet - Gauss Round/Richochet don't switch out at lvl 50

### ISSUE THREAD

**Issue by QueenGedren** [Nik-Potokar/XIVSlothCombo#1205]
Gauss Round and Ricochet aren't swicthing out for one another at level 50 when the feature is enabled, at level 51 and above it seems to work as expected.

START DEBUG LOG

Plugin Version: 3.0.18.1

Installation Repo: https://raw.githubusercontent.com/Nik-Potokar/MyDalamudPlugins/main/pluginmaster.json

Current Job: machinist / Machinist / MCH
Current Job Index: 11
Current Job Level: 53

Current Zone: 134
Current Party Size: 0

START ENABLED FEATURES
8000 - MCH_ST_MainCombo
8002 - MCH_Overdrive
8003 - MCH_GaussRoundRicochet
17000 - SMN_Advanced_Combo
17011 - SMN_Advanced_Combo_Ruin4
END ENABLED FEATURES

Redundant IDs found: 0
Status Effect Count: 0
START STATUS EFFECTS
END STATUS EFFECTS

**Comment by Rabalaba** [comment]
its related to line 127 "if (level <= Levels.Ricochet && HasCharges(GaussRound))
                                return GaussRound;" this should be set to "if (level < Levels.Ricochet && HasCharges(GaussRound))
                                return GaussRound;"

**Comment by QueenGedren** [comment]
For this issue with MCH_GaussRoundRicochet the I think problem's line 261:

if (level <= Levels.Ricochet)
                        return GaussRound;

but the same change you suggested could be needed:

if (level < Levels.Ricochet)
                        return GaussRound;

I haven't tested MCH_ST_MainCombo_HeatBlast but if this is the required change line 127 could be cause a similar issue with that feature

**Comment by QueenGedren** [comment]
Closing as this should be fixed by #1149
