### ISSUE TITLE
[DRG] All jumps in 1 Button, Stardiver feature issue

### ISSUE THREAD

**Issue by Yagyu1** [Nik-Potokar/XIVSlothCombo#1206]
Is there any chance to add a feature that allows having all jumps in 1 button?
**1. Stardiver
2. Dragonfire Dive
3. Spineshatter dive**

I'm asking for this since in the Stardiver Feature, **Stardiver** has a priority over **Nastrond** and it's much harder to have **3x Nastrond** during **Life of a Dragon**(you have to go for Stardiver 1st to be able to use Nastrond).

Also, having all jumps in a macro doesn't work even with a "Macro is executed without interruptions" feature. There is only time for 1 jump to be made between GCDs and it mostly executes 2 jumps, ruining the rotation.

**Comment by Rabalaba** [comment]
just add some code like 
uint[] actions = { SpineshatterDive, DragonfireDive, Stardiver };
                        return CalcBestAction(actionID, actions.Where(LevelChecked).ToArray());
 
this will pass the best jump and also level check them like mch has in the chainsaw, drill, and air anchor CalcBestAction section but wiith much less code.
