### ISSUE TITLE
[GNB][DRK] Dark Missionary/Heart of Light prevention similar to PhysRange

### ISSUE THREAD

**Issue by zbee** [Nik-Potokar/XIVSlothCombo#1208]
Phys Range has Adventurer Feature 14: Preventing overlap of Tactician/Troubadour/Shield Samba
![image](https://user-images.githubusercontent.com/1582821/226768738-9775b9d5-1810-4bca-b074-28a07db98345.png)

It would be nice for DRK/GNB to get this as well for Dark Missionary/Heart of Light in the Global Tank Features:
![image](https://user-images.githubusercontent.com/1582821/226768814-87afbcd2-88ed-4d6b-a162-eca18435a832.png)

**Comment by Rabalaba** [comment]
I believe that those skills can stack, unlike Tactician/Troubadour/ and shield samba, those skills cannot be stacked therefore any double casting is wasted.  There may be situations where it is necessary to stack aoe mitigations.

**Comment by zbee** [comment]
Wow it does stack, I've just been wrong the whole time - thank you for your review.
