### ISSUE TITLE
[Request] Option to drop Solid Barrel from GNB rotation

### ISSUE THREAD

**Issue by Neriek** [Nik-Potokar/XIVSlothCombo#1210]
I can't compile the plugin myself for some reason otherwise I would've just done this myself.
Would it be possible for someone to add a tick box to drop Solid Barrel from the GNB rotation? I use this strat often when my healers die and and it usually gives me enough self heals I need to survive until they're revived.
Sure it drops my DPS but that's not the priority when Tanking.

**Comment by Akechi-kun** [comment]
Holy shit I'm late.

Anyway, this is incredibly too niche to add in. You can just spam 1-2 & essentially achieve the same thing. Also, Sloth will not check for if anyone is dead, so even if this was an option, you would have to enable the option manually (which means either before engage or mid-fight, both bad).

This issue can be closed.
