### ISSUE TITLE
[PLD] Prominance breaking AOE combo in Sunken Temple of Qarn

### ISSUE THREAD

**Issue by Rueby** [Nik-Potokar/XIVSlothCombo#1211]
Temple of Qarn Min Lv35- Max Lv37 dungeon
Prominance is a Lv40 PLD AoE skill (second part of the aoe chain)

The aoe combo breaks due to Prominance 'not yet learned' despite it being impossible to use due to the level requirement of the dungeon.

I'm a lv55 PLD with all job quests up until Lv54 done. I'm not missing any skills and certainly not missing Prominance.
![image](https://user-images.githubusercontent.com/92205577/228987452-e18ab45f-c90b-4fa2-bf1d-b629a582cd85.png)

**Comment by Rabalaba** [comment]
looks like this was fixed on january 21st are you using the most recent version?

**Comment by Rueby** [comment]
Uhh...This is a good point. Mine is v3.0.18.1 and it's kinda stuck on that? Is there a way to force an update? I tried uninstalling it and reinstalling it through the dalamud.

I honestly didn't think of that since I checked for updates multiple times and it says there's none.

**Comment by cupcake121** [comment]
This was indeed fixed but the update is not yet public.

3.0.18.1 is the latest public sloth version, however if you want the very latest sloth available you'd have to build the solution yourself.

Personally i just disabled the AoE combo whilst in a low level dungeon. I only had Total Eclipse and Fight or Flight available for AoEs on those levels anyway. Easy to manage manually

**Comment by Rueby** [comment]
Well, here's to hoping it'd get fixed sometime then? I'm not really knowledgable enough to build any solutions myself sadly.
Thanks for responding.  I've checked the main page and seen a few commands, does that apply for disabling the aoe combo? If so could you tell me how to disable this one then?

**Comment by cupcake121** [comment]
![image](https://user-images.githubusercontent.com/102629921/229286821-56d03182-2117-4500-a66b-5d35d1eb7c01.png)
Just untick that feature whenever you're in a lower level dungeon

**Comment by Rueby** [comment]
Ah, okay I thought there was some kind of command! Thanks again

**Comment by k-kz** [comment]
Fixed in #1170
