### ISSUE TITLE
[GNB]#289 Aurora Protection Feature

### ISSUE THREAD

**Issue by lonewuhf** [Nik-Potokar/XIVSlothCombo#1215]
This option says it changes Aurora into Nascent Flash if Aurora's effect is on the player. GNB do not have Nascent Flash (that's WAR). It should change Aurora to Heart of Stone.

**Comment by k-kz** [comment]
The purpose of this feature is to prevent a second (wasted) usage while `Aurora` is up on the player; working as intended. We placed a skill from another job on there as a lazy way to make it fully unusable.
