### ISSUE TITLE
[Request] [PVP] [DRK]

### ISSUE THREAD

**Issue by Alkeyd** [Nik-Potokar/XIVSlothCombo#1216]
Could you put an option to turn on or off separating the Salted Earth from the Burst option?
Sometimes when you come into combat with a single person it's not really worth spending it ; )

**Comment by eggwite9000** [comment]
100% Agree, being able to independently control Salted Earth outside the burst feature would be ideal for DRK in pvp.

**Comment by Tartarga** [comment]
Completed. Stale / Pre Dawntrail
Closing
