### ISSUE TITLE
Rotations break upon leveling

### ISSUE THREAD

**Issue by EmilyNyx** [Nik-Potokar/XIVSlothCombo#1218]
I just hit level 30 as an Archer in the middle of an instance, and the rotation got stuck trying to cast windbite (which presumably unlocks with bard) which I don't have.

**Comment by k-kz** [comment]
This issue is known - we've trialled a workaround fix for this but it likely won't get implemented until we've cleared up a fair few bugs and pushed some job reworks out, unfortunately.
@Taurenkey may have more info (?)

**Comment by Tartarga** [comment]
Closing, Stale w/ Dawntrail
