### ISSUE TITLE
[Request] SMN oGCDs split on Attacks

### ISSUE THREAD

**Issue by luciossjaen** [Nik-Potokar/XIVSlothCombo#1219]
Option to split EnergyDrain/EnergySiphon on Attack Combos (Single/AoE) from Fester/Painflare. 
Basically making two options out of those. (Add ED/ES to Combo and adding Fester/Painflare to Combo).
Potentially with a suboption on ED/ES to use it (again) when stacks are not fully used up yet (otherwise not added to combo until stacks are used up).

**Comment by Tartarga** [comment]
Stale
