### ISSUE TITLE
[Request] [BLM] Split Triplecast/Swiftcast/Xeno on Movement from the full combo

### ISSUE THREAD

**Issue by Warchaild** [Nik-Potokar/XIVSlothCombo#1221]
If possible, I'd like to just have the movement tools split away from the main combo, but still get triggered while moving for x amount of time, please.  It's super helpful for uptime to just have them trigger when I move, but not have to commit to the full combo.

Thanks for all your work on this, I love this plugin.

**Comment by Kagekazu** [comment]
iirc its splitted in the new PR of BLM ( #1109 )

ill doublecheck when i'm on the pc.

**Comment by Kagekazu** [comment]
and we might be able to add them as a seperate option aswell. coffee is still kicking in xD

**Comment by Warchaild** [comment]
Excellent, thank you!
