### ISSUE TITLE
[Bug] SCH Aetherflow Helper Feature

### ISSUE THREAD

**Issue by shinyrukii** [Nik-Potokar/XIVSlothCombo#1228]
Since 6.4, the Aetherflow overwrite works, but once used it does not turn back into the original actions anymore (any of them) and stays as Aetherflow. (#668)

**Comment by k-kz** [comment]
Should be fixed as of #1233 - please reopen if still not working after [v3.0.18.3](https://github.com/Nik-Potokar/XIVSlothCombo/milestone/11).
