### ISSUE TITLE
RPR not so "sloth" any more ><

### ISSUE THREAD

**Issue by jennysoftpaw** [Nik-Potokar/XIVSlothCombo#1229]
Hello, I noticed with the new patch (6.4) key 2 is not auto updating to next spell, like it used to? Am I missing a setting now, or can this be fixed? (sorry, it's nice to be sloth-y) :)

**Comment by k-kz** [comment]
Can you expand on "key 2"?

**Comment by jennysoftpaw** [comment]
Oh, don't worry, a couple days later it was back to normal. When I say Key
2, it's pressing 2 on my gaming mouse, which is linked to action bar,
button 2. Sorry for the mix up! So the debacle fixed itself! Thanks :)
