### ISSUE TITLE
[Suggestion] PLD--replace 'Royal Authority' with 'Holy Spirit' when Divine Might is active

### ISSUE THREAD

**Issue by ksledu** [Nik-Potokar/XIVSlothCombo#1230]
Hi, Dear

Is it possible to add this feature in to PLD rotation? this idea is from another combo plugin. It sounds great after I do a test on it. thank you in advance.

![suggestion](https://github.com/Nik-Potokar/XIVSlothCombo/assets/96337656/23d6eb84-1ca0-4118-9789-100aa55e81e0)

**Comment by Exeter089** [comment]
This is a pretty major missing feature right now. In its current state, the 1-2-3 combo generates a stack for a free holy spirit, which Slothcombo instantly will try to spend before moving on to hitting Royal Authority.
It should not spend the stack early unless Fight or Flight is active or it is about to be overwritten with a new stack by Royal Authority. Keeping the stack allows the PLD to use the free Holy Spirit as a free ranged attack.
