### ISSUE TITLE
GNB third burst phase prioritizing farming cartridges

### ISSUE THREAD

**Issue by Nanobreaker66** [Nik-Potokar/XIVSlothCombo#1235]
I originally noticed it in EX 6, and went to test on a dummy, but if I have all features on a single button, when the 3rd burst phase comes up it will ignore most of my C/D skills, including double down and bloodfest and mostly spam the solid barrel combo as if needing more cartridges.

This doesn't happen with the first or second burst phase, just the third one. I just tested it on a dummy twice too, and both times it did the exact same thing, second for second. In burst phase 3, my double down is on a 12 second c/d so it dumps 2 cartridges for burst strikes, and then does 2 solid barrel combos, instead of dumping a third one and using bloodfest to get max cartridges and jumping into double down. Pic below is an analysis snip of that burst window starting at the no mercy cast:

![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/129707662/ff26b3c4-5085-49c4-9eff-b48307e3285c)

---------------------------
I'm at 2.5 CGD with most options turned on for single target, minus the lightning shot uptime. Pic below is my settings:

![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/129707662/ca7c26ed-9eb1-4e2f-acca-fb8e04a20ca9)

**Comment by Taurenkey** [comment]
I've had a look at this personally and asked a friend more experienced with GNB than myself to aid in this issue. However we can't replicate the issue, and looking at the code leads me to believe all bases are pretty much covered and it's as optimal as it can get for now.
