### ISSUE TITLE
[AST] Quick Target Cards causes FPS drop on AST

### ISSUE THREAD

**Issue by Rueby** [Nik-Potokar/XIVSlothCombo#1236]
This was never an issue in prior to 6.4, disabling the plugin essentially returns everything to a stable fps across all jobs (accounting for the fps hit from other plugins). 

Example with plugin enabled [ooc]
DRG (and mostly other jobs too) 77-80 fps
AST 44-47 fps

With plugin turned off
All jobs around 85 fps (including astro)

Any ideas?

Edit : Narrowed it down to Quick Target Cards. I never had an issue with that dropping my fps before.

**Comment by Taurenkey** [comment]
I need more details as to when this happening.

**Comment by k-kz** [comment]
We've struggled to replicate this on our end so far, but have enough mentions/reports of it to know it's not a user-end thing. We'll look into it as soon as we find a good way to replicate

**Comment by Taurenkey** [comment]
We would really need a list of your other plugins if you don’t mind sharing. It’s very likely a conflict somewhere.On 3 Jun 2023, at 13:03, Anya ***@***.***> wrote:﻿
It happens whenever I switch to AST and have Quick Target Cards enabled, I don't have to do anything else, just being on the job tanks my fps. it happens in every location I went to. I tried going to really low population areas like the Tempest but no luck. Casting down below is drawing cards, ogcds.
Upper Limsa
AST w/o Quick Target Cards : 102FPS Stationary, 84-92FPS casting/in motion
AST w/ Quick Target Card : 42FPS Stationary, 28-31FPS casting/in motion
The Tempest (Macareneses Angle)
AST w/o Quick Target Cards : 152-141FPS Stationary, 131-136FPS casting/in motion
AST w/ Quick Target Card : 57FPS Stationary, 43-45FPS casting/in motion
What else can I provide to help?

**Comment by k-kz** [comment]
@Taurenkey "better targeting system" jumping out at me here, no idea what it is though.

**Comment by k-kz** [comment]
Should be good for now, @Taurenkey will let you know if there's anything else - we're just trying to pick out potential conflicts with other plugins that directly affect the targeting system in any way,
Thanks for your responses so far!

**Comment by Taurenkey** [comment]
The biggest stand-outs to me are Astro (since that is trying to do the same thing), Redirect, ReAction, Boss Mod, Mouseover Action and Better Targeting System.

Of all of these, I'd say turn off Astro & Boss Mod, then if that doesn't resolve, the rest of them. However I do note you have *a lot* of plugins being loaded, which probably doesn't help either.

**Comment by Taurenkey** [comment]
Can you try having Sloth as the only plugin running and see if it does it still?

**Comment by Taurenkey** [comment]
And does having /xllog open show anything?

**Comment by Taurenkey** [comment]
I was just curious if it was spamming errors for whatever reason.

**Comment by k-kz** [comment]
@Rueby closed this for now having merged #1243, please reopen if the issue persists. Thanks!

**Comment by k-kz** [comment]
> The issue still remains even after the merge.

Are you actually building locally or are you using the release version? If the latter, we haven't pushed the update out yet. It'll be in v3.0.18.4

**Comment by Taurenkey** [comment]
Going to re-open this until we actually launch the update and get verification.

**Comment by k-kz** [comment]
@Rueby the v3.0.18.4 update containing the potential fix has been released now - please let us know if anything changes and/or the issue persists. Leaving this open 'til we get further confirmation.

**Comment by Ashe-H** [comment]
Hello, 
I've been having this issue for a month now and never thought of opening an issue here till this morning and luckily a fix was pushed :D 
After a lot of testing I realized that the FPS drops were happening only (99% of times) in dungeons where there only 4 people and If I have a card running on a melee or a caster for example and I draw a card which should go to the same Role then the plugin kinda struggle to find who to give it to or something then the FPS start dropping.
This morning I tried to replicate that again but apparently the update fixed it and there's no more FPS drops.
Thank you
