### ISSUE TITLE
[RPR] Natural Shadow of Death extension

### ISSUE THREAD

**Issue by drpleberino** [Nik-Potokar/XIVSlothCombo#124]
It would be really nice to have an natural SoD extension, meaning the combo only adds it when it was casted manually before.
That would help a lot for not using when you don't want it but still have it extended auto.

**Comment by Nik-Potokar** [comment]
Well i am unable to really track what is cast manually since all casts are manual its just the icons that get replaced when the conditions are met.

So unless you got a really specific case for when you dont want it applied like on P3S darkfires i could add a HP check.
Its not supposed to be perfect in every case

**Comment by drpleberino** [comment]
I noticed when I was running dungeons with monster that only survive 1-2 hits or raids where the small monsters would not be cleaved yet die very fast ST the routine would cast SoD which of course didn't make much sense since they would die immediately anyway.

`Another option that I can add is to only refresh the buff/debuff and not apply it unless you apply it yourself (so that would fix applying the debuff to the targets that you don't want the debuff on aka. if they are about to die soon/have low max HP )`

That's pretty much what I tried to tell, except I think the routine would drop it completely when DoT would run out for example due to boss immunity downtime? I'd still take it!

I also noticed that he would not cast SoD when in transformed reaper mode, is that intended? The routine immediately cast it once the mode has ended tho'

**Comment by Iaotle** [comment]
You don't want to be casting SoD while in reaper form, so that's not a big deal IMO.

If you wanna have more control over the dot, you should probably just bind it to your bar and use it normally. Reaper doesn't have a lot of buttons as it is with XIVCombo.
