### ISSUE TITLE
DRG combo broken

### ISSUE THREAD

**Issue by XCanari043veRX** [Nik-Potokar/XIVSlothCombo#1240]
Hi! Dragoon combo still broken. Any intentions of fix it? Pls i main drg and is horrible to not be able to use sloth combo with it

**Comment by Kagekazu** [comment]
a fix is on the way. But there should only be an issue on low lvl dragoon.

Do u have an issue on high/max lvl dragoon aswell?

**Comment by XCanari043veRX** [comment]
Yes my friend, when u r below lvl 88 and use the elusive jump or true North the pluging try to do the opener but stop to do jumps or offGCD so i fix it my self adding a lvl 88 Check on the respectivo lines
