### ISSUE TITLE
[Suggestion] PvE Tab Targeting selects lowest hp value in dungeon pulls

### ISSUE THREAD

**Issue by kyrioA** [Nik-Potokar/XIVSlothCombo#1247]
Because I am a sloth at heart XD sorry if this is an inappropriate request.

**Comment by k-kz** [comment]
Aside from specific features e.g. AST cards, it's highly unlikely we'd add any functions to do with changing the core targeting system - seems like something far better suited for ReAction or BetterTargetPlugin (?)
