### ISSUE TITLE
[DNC] Simple Daancer combo have delayed Devilment

### ISSUE THREAD

**Issue by Akimata** [Nik-Potokar/XIVSlothCombo#1250]
Hi, dancer simple combo have issue with Devilment being used not right after techinal finish

**Comment by k-kz** [comment]
Already aware of it and have a fix that seems to be working, currently in testing.
Unless we encounter any problems it should come along with next release.

**Comment by Tartarga** [comment]
Stale / Pre Dawntrail
Closing
