### ISSUE TITLE
[GNB] Option to remove Burst Strike and/or Hypervelocity from main combo

### ISSUE THREAD

**Issue by ARoomKey** [Nik-Potokar/XIVSlothCombo#1258]
If you want more control over your OGCDs it can be annoying to accidentally hit hypervelocity because you're spamming the key down.

**Comment by SirDK** [comment]
It's not raid wide buff, personal buff or any other valuable cooldown. oGCD is something you want to use as fast as possible because of timer or overcap. No idea why such feature required. Elaborate use case maybe?

**Comment by Akechi-kun** [comment]
100% not happening. You should always always always use Hypervelocity after you use Burst Strike because Continuation is easily broken by every GCD, just not oGCDs.. which is why it's coded this way. 

This issue can be closed.
