### ISSUE TITLE
[MCH] Remove Bioblaster from aoe combo when target is below 30%

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/XIVSlothCombo#126]

**Comment by Iaotle** [comment]
Why? Seems like a vaguely useful feature.

**Comment by sauronshotdogs** [comment]
Since BioBlaster is used mostly for dungeons and AOE stuff, and not bosses, there are times when it will come off cooldown, only to be used on a target that will have less than 30% of health left, thus effectively wasting it.

Does it not make sense to not cast a dot, when you could cast an instant attack, when the would would only be able to tick for maybe only 2 ticks, where the instant attack would do it's full damage instantly?

It was just an idea, and won't be the end of the world, should any of you choose not to make it.
