### ISSUE TITLE
PvE Features not showing up despite job crystal equipped.

### ISSUE THREAD

**Issue by PeculiarPip** [Nik-Potokar/XIVSlothCombo#1262]
So, I have two characters. One of them I made recently while the other I've had for a month or so. I've set up Character A with the summoner features. Character B is a monk. If I log onto the Monk first, the PvE features won't show up BUT the PvP features will. If I log onto the Summoner first and then the Monk, then the PvE features show up.

Edit; I should have mentioned, I tried closing and opening the game as well as uninstalling the SlothCombo and reinstalling it.

**Comment by inu-goro** [comment]
I still have the same issue. The pve features do not show up although I'm equipped with job crystal.
It doesn't show up even after I change the job. And on a few occasions, the game crashes down some time after opening the slothcombo menu.
