### ISSUE TITLE
[BRD] One Button Song feature does not always offer Mage's Ballad correctly when Army's Paeon is active 

### ISSUE THREAD

**Issue by NikaLeets** [Nik-Potokar/XIVSlothCombo#1278]
If the cooldown rotation for songs get out of sync (which is common in deep dungeons when travelling between mobs), Mage's Ballad is not offered in some circumstances.  While Army's Paeon is active, the correct next song offering if Wanderer's Minuet is on cooldown is to offer Mage's ballad.  Instead, when Army's Paeon is active, Mage's ballad is available and not on cooldown, but Wanderer's minuet IS on cooldown, only Wanderer's minuet is offered, which is on cooldown.

Once Army's Paeon expries, Mage's ballad IS offered correctly if Wanderer's Minuet is still on cooldown, but this is a DPS loss if the remaining cooldown on Wanderer's minuet is < 45 seconds.

I think the logic change here should be as follows: 
If Mage's Ballad is available and Wanderer's Minuet cooldown is < 45 seconds, offer Mage's Ballad.

Alternatively, just offering Mage's ballad all the time when all other songs are on cooldown should also work, at the risk of a facerolling user popping songs too early...

**Comment by Taurenkey** [comment]
I can rewrite the feature to function in accordance to this page from the Balance https://www.thebalanceffxiv.com/jobs/ranged/bard/basic-guide/#song-order

Basically, priority being WM -> MB -> AP, with it not returning the next song until it's spent the required amount of time in that song (so 43s WM, 34s MB & 43s AP) or a higher priority song comes off cooldown in the meantime.
