### ISSUE TITLE
NIN Aeolian to Ninjutsu feature not working

### ISSUE THREAD

**Issue by jul68746** [Nik-Potokar/XIVSlothCombo#1283]
Hi, it doesn't work for me (lv 60 ninja). 
It should display ninjutsu instead of Main Combo when using mudras, but it only works with kuchiyose(failed ninjutsu/bunny).

Other options activated : 
Advanced mode - single target (huraijin and throwing dagger uptime options), 
Advanced mode - aoe(no options), 
Simple mudras feature

**Comment by Taurenkey** [comment]
Simple Mudras does not replace the main combo, it turns the mudras themselves into one button actions.

So it's Ten, Chi & Jin that get changed to follow the path selected.
