### ISSUE TITLE
Warrior "Tomahawk Uptime Option" breaks "Storm's Path Combo Feature"

### ISSUE THREAD

**Issue by samisiddiqui** [Nik-Potokar/XIVSlothCombo#1288]
When "Tomahawk Uptime Option" is ticked, Storm's Path only ever is Tomahawk, regardless of distance. When unticked, "Storm's Path Combo Feature" works correctly.

**Comment by Lusaca87** [comment]
Which Version of Dalamud do you have?
Current its ![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/17047430/a2823662-795e-4a70-be73-cc19b19cc151)

type /xldev in chat to check.

With this version i dont have any problems with them

**Comment by samisiddiqui** [comment]
That was it, I was on c1e8fd35(4239). Upon updating, the issue is resolved.
