### ISSUE TITLE
DNC aoe combo rotation not working.

### ISSUE THREAD

**Issue by Darkinian** [Nik-Potokar/XIVSlothCombo#1289]
The single target rotation switches between the skills as it should but windmill stays stuck to windmill and doesnt activates any combo what so ever breaking the aoe rotation

Simple option or the other, both dont work for aoe, at least for me.

**Comment by nurd6** [comment]
I had no issues with DNC AOE rotation this morning on a level 90 DNC

**Comment by Taurenkey** [comment]
Unable to replicate. I would advise reslotting "Windmill" to your hotbars.
