### ISSUE TITLE
BLM Scathe Issue or Suggestion

### ISSUE THREAD

**Issue by fugnsig** [Nik-Potokar/XIVSlothCombo#1292]
Is it possible to have Scathe as the default starter for the simple BLM one button? Between pulls, I move around and it's sometimes stuck on as Fire 3 and Scathe is no where to be seen. Or possibly an option to separate scathe from the entire rotation and the starter can be Fire 3 for the whole rotation. Cheers!

**Comment by Taurenkey** [comment]
Completed as part of the BLM rework, Fire 1 is now the button for the rotation.
