### ISSUE TITLE
Simple/Advanced AoE BLM Rotation broken?

### ISSUE THREAD

**Issue by Marziko** [Nik-Potokar/XIVSlothCombo#1293]
Hello, since the latest Update (3.1.0.1) the AoE feature for BLM seems to be completely broken for me, tried both Advanced and Simple options, but it flat out just doesn't work in changing skills upon pressing Blizzard II / High Blizzard II

Single target seems to be working just fine.

Tried reinstalling Sloth and deleting the config file as well to no avail.

Any hints as to what I might be doing wrong? It was working fine prior the new update

Thanks

**Comment by Kagekazu** [comment]
are u dragging Blizzard 2 or High blizzard 2 on ur hotbar?

**Comment by Marziko** [comment]
> are u dragging Blizzard 2 or High blizzard 2 on ur hotbar?

Yeah, upon pressing High Blizzard II it just keeps spamming it, aka not doing the proper rotation at all

**Comment by Kagekazu** [comment]
u have to drag blizzard 2 on ur hotbar, it changes to high blizzard 2 for u, but codewise it keeps the id of blizzard2

**Comment by Marziko** [comment]
> u have to drag blizzard 2 on ur hotbar, it changes to high blizzard 2 for u, but codewise it keeps the id of blizzard2

How would I go about doing this? Since you can't drag Blizzard 2 on the hotbar when you hit Level 82

**Comment by Dajova** [comment]
I'm actually having the same issue. High Blizzard 2 is not changing at al. In fact, both Simple and Advanced seems broken.

**Comment by Kagekazu** [comment]
switch from compact view to normal view, then u can drag all skills.
![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/95875972/8b9056b7-7107-4a38-98c4-222714635e31)

![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/95875972/63d2db20-e58c-4ee3-b501-2d4c829f6094)

**Comment by Marziko** [comment]
> switch from compact view to normal view, then u can drag all skills. ![image](https://user-images.githubusercontent.com/95875972/275328751-8b9056b7-7107-4a38-98c4-222714635e31.png)
> 
> ![image](https://user-images.githubusercontent.com/95875972/275328757-63d2db20-e58c-4ee3-b501-2d4c829f6094.png)

Ahh I see, tried it out and it seems to be working now with Blizzard II! Thanks for the clarification
