### ISSUE TITLE
[PLD - Advanced] Shield Lob uptime feature issue

### ISSUE THREAD

**Issue by Lusaca87** [Nik-Potokar/XIVSlothCombo#1298]
Sloth Version: 3.1.0.4
Dalamud: deef16cd(4375)

Problem: On advanced Mode PLD will use Shield Lob uptime feature (#444) every time even if it is deactivated. 

![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/17047430/64a7f230-4980-4a85-aacf-588febedbdc8)

Best Regards

**Comment by Kagekazu** [comment]
Heya! 
is it possible to do `/scombo debug PLD` in game? and then send it here?

**Comment by Lusaca87** [comment]
Of course.
Here will you have it
[SlothDebug.txt](https://github.com/Nik-Potokar/XIVSlothCombo/files/12926794/SlothDebug.txt)

**Comment by Kagekazu** [comment]
tyvm!

i have found the issue and i will PR it for next release quick fix.

**Comment by Lusaca87** [comment]
Your are welcome 
im glad i could help :D
