### ISSUE TITLE
dnc saber dance aoe #172

### ISSUE THREAD

**Issue by doh666** [Nik-Potokar/XIVSlothCombo#1303]
Hello I've added saber dance too the aoe single button. Set it to be used at 50 esprit then tried 100. It keeps trying use it when at 0 and stays on button until standard step comes off cd.  (works fine on the single target tho)

**Comment by Taurenkey** [comment]
The AoE Saber Dance slider has been wired up to the Single Target one by mistake. This will be fixed in the next update, but for the meantime you can toggle single target version of the feature and adjust the slider, you can turn off the feature afterwards if you're not using it for single target.

**Comment by Tartarga** [comment]
Stale / Pre Dawntrail
Closing
