### ISSUE TITLE
gnb aurora protection feature

### ISSUE THREAD

**Issue by longshotleah** [Nik-Potokar/XIVSlothCombo#1304]
Last feature in pve section reads #291: Turns Aurora into Nascent Flash if Aurora's effect is on the player.  Nascent Flash is a WAR ability not a GNB ability. Maybe i'm misunderstanding but wanted to let ya know

**Comment by Kagekazu** [comment]
Heya!

That is intended. As u can't cast nascent flash, aka protecting u from double casting aurora on the same target and wasting a charge.

**Comment by Taurenkey** [comment]
I have adjusted the presentation of the feature to hopefully clear up any misunderstanding, however the intended behaviour is still correct.
