### ISSUE TITLE
[SUGGESTION] [BLU] Swiftcast on Angel Whisper

### ISSUE THREAD

**Issue by GoblinGuide** [Nik-Potokar/XIVSlothCombo#1306]
I assumed this would already exist, but I'm not seeing it. It doesn't seem to be enabled by the default "Healer: Raise Feature" under ADV, and there's not a checkbox for BLU specifically.

Just would like to be able to do it the same way it works with Raise on all the other jobs and have Angel Whisper turn to Swiftcast when Swiftcast is off cooldown.

**Comment by Kagekazu** [comment]
Heya!

I genuinely tought it did xD I will add this on my next PR and add the option!

**Comment by Kagekazu** [comment]
Heya! 

i just looked in game and it already has it.

Its under Global magical ranged features - Magical Ranged DPS : Raise feature.

![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/95875972/0497374d-43ea-4fd1-9947-47cb751b8248)

**Comment by GoblinGuide** [comment]
I had "hide conflicting options" on and SMN's Raise option on. My fault. PEBKAC as usual. Sorry!
