### ISSUE TITLE
WHM (option for only Lucid Dreamin)

### ISSUE THREAD

**Issue by Absolutioo** [Nik-Potokar/XIVSlothCombo#131]
Would it be possible to have an option to only add the Lucid Dreaming without Dia.

**Comment by Nik-Potokar** [comment]
It is possible and I will add it later today!

**Comment by Absolutioo** [comment]
Yes i never swapped glare out on my WHM so it was the wrong one in it. Swapping fixed it.

**Comment by Absolutioo** [comment]
i wanted to ask again if you still gonna add the lucid dreaming funtion without the dia thing

**Comment by Nik-Potokar** [comment]
Will do by tomorrow. Sorry haven't seen it in my log since I see that the issue got closed so I missed it.

**Comment by Absolutioo** [comment]
tyvm :)

**Comment by Nik-Potokar** [comment]
Added sorry for delay again
