### ISSUE TITLE
[SUGGESTION] A modifier button to disable all combos

### ISSUE THREAD

**Issue by Exobrem** [Nik-Potokar/XIVSlothCombo#1312]
Kind of self-explanatory, but I'd like a hold and/or toggle button to disable all combos so that all buttons will do what they're normally supposed to do. 

Being able to enable/disable combos on the fly for things like the opener or niche situations where the combo is bad would be really helpful. 

Thank you

**Comment by Kagekazu** [comment]
![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/95875972/8ceacb22-dbaf-4561-bc47-81ec80b50251)
these are the existing chat commands. 

It is intentional that it doesnt work during combat.
