### ISSUE TITLE
[SUGGESTION] [GNB] Adding a 1s CD check to Gnashing Fang

### ISSUE THREAD

**Issue by AceAkechi123** [Nik-Potokar/XIVSlothCombo#1313]
There are certain instances where Gnashing Fang will come up right as my GCD & will cause GCD to be used instead of Gnashing Fang on a 30s window, causing No Mercy & Gnashing Fang to misalign. iirc there is a certain check on MCH where if you use Drill (i.e.) it comes up about 1s before it is used, pretty much guaranteeing that it is used instead of a 1-2-3. Is it possible to add this same check from MCH to GNB for Gnashing Fang? I feel this would benefit it entirely.

**Comment by Kagekazu** [comment]
@AceAkechi123 close ur things if u add it urself :D
