### ISSUE TITLE
[BUG] PvE Features menu is forced to Variant Dungeons tab

### ISSUE THREAD

**Issue by pikangie** [Nik-Potokar/XIVSlothCombo#1314]
Every time I click on the "Normal" tab, within about 1-2 seconds it reverts back to the "Variant Dungeons" tab, making it near-impossible to change Normal tab settings.

This only started happening after the last update yesterday.

**Comment by pikangie** [comment]
After a while of trying to touch any of the settings, my game will also very often crash a short while after.

**Comment by Taurenkey** [comment]
As it currently stands, this appears to be an isolated incident and I have been unable to replicate this.

If you are still having this issue, please reopen the issue and make sure to include more detail as to what you're clicking, what else you're doing at the time etc.
