### ISSUE TITLE
[Suggestion] Add less automation for dnc

### ISSUE THREAD

**Issue by GregariousJamie** [Nik-Potokar/XIVSlothCombo#1315]
Heya, I usually automate my jobs so that basic 1-2-3 combos plus anything i find annoying gets automated, with stuff like procs having to be manually pressed so that im not just holding down one button. With that being the case, I found that the dnc single target and multi automate too much stuff. 

In short, I would genuinely appreciate if there was just a simple "Cascade to fountain", and a reverse cascade to fountainfall" feature, no replacing the buttons with procs afterward, just two buttons combined into one. Additionally, having standard and technical step swap based on which was avaliable, while keeping the simon says part of the gameplay would make dnc more fun to play, for me at least

**Comment by Tartarga** [comment]
Stale / Pre Dawntrail
Closing
