### ISSUE TITLE
Blm rotation issue

### ISSUE THREAD

**Issue by Hikarichan** [Nik-Potokar/XIVSlothCombo#1316]
Just going to post here because I've had an issue where the single target gets broken and it don't matter if I die or the fight gets resets it gets stuck on fire 4. 

But what it does is it'll have sharpcast and if I activate that but  it seems if I move at all before the next action it breaks and it will do fire 3 then do fire 4 endlessly.  

I have to use transpose or aoe blizzard to get mp back  but the single target button never leaves fire 4 so I had to add a fire 3 button to the bar to even be able to cast fire 4 but it'll just do it endlessly
And it will be like that until I change jobs.  

I've tried deaths and completely resetting the fight but I've had it happen now in the newest 24 man and the new variant dungeon.

**Comment by Kagekazu** [comment]
if it happens, can u try to uncheck the opener and see if it goes unstuck?

**Comment by Tartarga** [comment]
Obsolete
