### ISSUE TITLE
Dragon slight option cursing crashes

### ISSUE THREAD

**Issue by TotallyNotMeow** [Nik-Potokar/XIVSlothCombo#1317]
![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/149897143/918a3011-e705-4a2d-a234-2cb2df16a113)

Hey, I hope it´s possible to open the picture D: If you disable this option, the game will crash directly when starting the rotation, I hope there´ll be a bugfix soon

**Comment by Kagekazu** [comment]
heya,

i havent had any crashes with enabling or disabling this option.
Are u certain it is sloth related?

Do u use Reaction or MO Action?
