### ISSUE TITLE
Defensive Tank oCD to main /aoe combo

### ISSUE THREAD

**Issue by Ariadh** [Nik-Potokar/XIVSlothCombo#1318]
Possible to add Heart of Stone-GNB,  Oblation- DRK- 1 stack , to the advanced rotations?   For the AOE rotations, hoping they can be 2nd or 3rd GCD in order to first tag the mobs with AOE skills.

**Comment by Kagekazu** [comment]
dont think sloth will be adding defensive cooldowns, as it is too situational on when to use them.

**Comment by Akechi-kun** [comment]
Sloth has no plans now or in the future to add any mitigations to the plugin.

This issue can be closed.
