### ISSUE TITLE
[BLM] AoE and single target Thunder spells overwriting each other

### ISSUE THREAD

**Issue by colopatiron** [Nik-Potokar/XIVSlothCombo#1319]
AoE Thunder and single target Thunder are overwriting each other in the rotation instead of waiting for the debuff to fade before reapplying. 

Tested with Thunder 1, 2, 3, and 4. You can reproduce by doing the AoE rotation until Thunder 2 / 4 is applied, then switch to single target rotation. Thunder 1 / 3 will be cast even if there's still a lot of time left in the Thunder debuff.

**Comment by Kagekazu** [comment]
that is correct. it is on my to fix list, just havent found a good solution for it yet :)
