### ISSUE TITLE
WHM's skills are not optimal.

### ISSUE THREAD

**Issue by Nostalgia76** [Nik-Potokar/XIVSlothCombo#1322]
Thank you for all your help.
It has been a while since I changed to white mage and hit the mannequin.
I do not use Presence of mind at the opening, Assize, Lucid Dream.
I went to TRUST (lv.90 ID) to try it out and could not use regen or recovery magic on NPCs, the only way to heal NPS was the Afflatus Rapture used when Lily was about to overflow. You can use it if you log in from the official client. I could use them before...? I think it is a bug and I am reporting it.
I am Japanese so I use translation. Sorry if my English is not accurate.

**Comment by Tartarga** [comment]
Stale, question posed by Kage wasn't answered
