### ISSUE TITLE
[Suggestions and Bug found] Extra hotkeys/Flexability in assignig/creating combos/Unavalaible skills get attempted to be used which breaks the combo

### ISSUE THREAD

**Issue by ExLuck6** [Nik-Potokar/XIVSlothCombo#1327]
[Suggestion] A Hotkey that instantly soft-disables SlothCombos and reverts to the original manually made hotbar icons.

[Suggestion] More sophisticated/detailed combo making, for example, giving us the ability to assign our own combos/rotations with their own if conditions/etc

[Suggestion] Instead of making a skill itself change its icon/skill, make it so that we can assign a specific hotbar key that changes its icon/skill.

[Bug] Sloth switched to unavailable skill icons in the overworld if you reach a specific level that unlocks a skill but you have not actually done the quest to unlock it yet.

**Comment by ExLuck6** [comment]
[Suggestion] Add a "Level limiter" option in Sloth that will "Limit" the usage of the combos depending on what level you are at (This might fix the bug)

**Comment by Kagekazu** [comment]
for the suggestion i will leave it to the other devs, but afaik the skill bug is on purpose, to force people to do their jobquests

**Comment by Taurenkey** [comment]
1. Not something we want to do.
2. Not possible with the way we do things, that would be more suited to its own plugin.
3. Literally not possible with the way this plugin operates, there's no keybind reading at all.
4. This is something we've debated for a long time, it's not strictly a bug as much as a design choice at this stage.
5. Level limiter will never happen.
