### ISSUE TITLE
[BLM] Functions don't work correctly

### ISSUE THREAD

**Issue by MaxYtre** [Nik-Potokar/XIVSlothCombo#1328]
In Advanced (single target) do not work:

1. rotation > standard > "Use Xenoglossy for burst"
Xenoglossy is used on rollback after Blizzard III. Check has no effect on rotation

2. movment options > check "Xenoglossy" 
Does not work. If Xenoglossy is present, it is not substituted into the rotation.

3. Triplecast/Swiftcast Option
Adds Triplecast before Fire III, but needs to be added after

Suggestion:
Make the addition of Xenoglossy switchable from rotation

**Comment by AoiYui** [comment]
2. which will not happen since it doesn't save the charge and automatically uses it even at 1 charge in umbral ice.

**Comment by Kagekazu** [comment]
will be fixed in #1345 where u will have an option to disable xeno

**Comment by Tartarga** [comment]
Closed
