### ISSUE TITLE
[REQUEST] Auto-target rez for healers

### ISSUE THREAD

**Issue by urimusha** [Nik-Potokar/XIVSlothCombo#1329]
I saw that auto-target is possible with AST cards so why not auto-target rez as healers? Would help a lot with controller users such as myself and prioritizing tanks>healers>dps

**Comment by urimusha** [comment]
> You can use ReAction and set your priority -> resurrect action.

Mind telling me more details about it? Where do I find such option?

**Comment by Kagekazu** [comment]
u can do something like this in Reaction - https://raw.githubusercontent.com/UnknownX7/DalamudPluginRepo/master/pluginmaster.json ( this is the repo to add it to ur plugin list )

![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/95875972/ee49a753-ec4e-4d6d-a3b7-b106e23b101a)

**Comment by urimusha** [comment]
This really helps tons as controller user! Pretty much appreciated
