### ISSUE TITLE
PLD  using mitigations cancels requiescat from the auto rotation 

### ISSUE THREAD

**Issue by LordLackusX** [Nik-Potokar/XIVSlothCombo#1332]
just had this tested on a dummy if I am about to do my burst I press fight or flight and if I press mitigation afters it completely cancels out the requiescat and it won't even register it as if it existed.

**Comment by Taurenkey** [comment]
I'll add a 6s window in which it can be weaved, however the original intention is that you double weave FoF into Req as to reduce drift. Weaving something else after FoF doesn't give time to weave Req so it's not recommended to use mitigation at that very specific moment.

**Comment by Tartarga** [comment]
Stale / Pre Dawntrail
Closing
