### ISSUE TITLE
[MCH] Advanced AOE gauss/ricochet option is broken

### ISSUE THREAD

**Issue by wilaw1115** [Nik-Potokar/XIVSlothCombo#1335]
Checking the box does not add gauss/ricochet to the rotation on hypercharge. 

However it DOES work if the sub option "use without hypercharge" is checked, but I only want it to use during hypercharge.

Also, theres a typo on the sub option as "use outwith hypercharge".

**Comment by Taurenkey** [comment]
>Also, theres a typo on the sub option as "use outwith hypercharge".

That's not a typo, the word "outwith" means "outside, or beyond". The meaning of which is that it would use it anytime, not just within the hypercharge buff window.

>Checking the box does not add gauss/ricochet to the rotation on hypercharge.

>However it DOES work if the sub option "use without hypercharge" is checked, but I only want it to use during hypercharge.

I have just tested it and it works as intended. By default, it only uses it in the hypercharge window. Ticking the sub-option allows it to use it whenever as per previous explanation.

**Comment by wilaw1115** [comment]
My apologies for my lack of vocabulary.

Just to clarify, I still couldn't get it to work. I only ticked the Gauss Round/Ricochet in the Advanced mode AoE because I want to control everything else.

However I did manage to get it work in a roundabout way by ticking the (Reassemble Option > Use on Auto Crossbow, and then unticking the Reassemble Option).

**Comment by Taurenkey** [comment]
I feel you're either creating a placebo effect for yourself or you have multiple combo plugins running at the same time, because ticking and unticking something shouldn't make something unrelated just suddenly work.
