### ISSUE TITLE
[MCH] Suggestion: Make the Reassemble option (Adv Singletarget) description a bit more descriptive

### ISSUE THREAD

**Issue by Wild-Carrot** [Nik-Potokar/XIVSlothCombo#1337]
I want to preface this by saying that I have no idea how to properly word this, lol. So if any clarification is needed, let me know.

**Class/Job:** Machinist
**Feature:** Advanced Mode - Single Target (Reassemble)

**Issue:** This one is a suggestion. I've messed with this feature in the past, and maybe it's always worked this way and I forgot, but I find it somewhat unintuitive now should I want to use it in the way that I've done prior. Currently, if you never tick the reassemble box, the Single Target combo will never use Reassemble and will use AA/HS, CS, and Drill (assuming those options are enabled further down the list). Great, I have 1-2-3 and all of the 3 heavy hitters on the same button. But what if I want that button to omit using the heavy hitters when Reassemble is off cooldown, in order to hold them.

Well, this is where I say that it gets unintuitive. That feature exists, but in order to enable it, I have to check the Reassemble box to make another list of sub-options to appear, enable those sub options, then uncheck Reassemble so that it doesn't add Reassemble to the 123 button. Doing this will make my 123 button use AA, CS, and Drill, but only when Reassemble is on cooldown. Otherwise, it holds them until I activate Reassemble, which is perfect for what I want.

This is a very long way of asking: Can the text for the Reassemble option make this interaction clear? It currently only says "Adds Reassemble to the rotation". I feel like it's, at least a little, unintuitive to read that and think it would do anything but add Reassemble to the 123 and that the sub options would work even without Reassemble checked. I get what you guys were going for, but maybe a "Unchecking this box won't disable the sub options" or something of the sort.

**Comment by Taurenkey** [comment]
You've actually discovered a bug. Disabling the reassemble option should make it disregard checking for reassemble altogether and make it so it fires the big 3 hitters on cooldown as it were. This will be addressed in the next update. 

If you disable an option, anything to do with suboptions should just no longer be considered as it makes sense. However because of how complicated reassemble actually is in terms of programming it was an oversight to not check if the option was ticked.
