### ISSUE TITLE
[MCH] Adv AoE Gauss/Ricochet, Ricochet is blocking Gauss round from being used when below level 50

### ISSUE THREAD

**Issue by Wild-Carrot** [Nik-Potokar/XIVSlothCombo#1338]
Alright, I didn't know if I should make this new thread or add this to the other one, but it seems different enough to warrant its own.
This is a leveling issue.

**Class/Job:** Machinist
**Feature:** Advanced Mode - AoE ; Gauss/Ricochet option

**Issue:** Prior to level 50, before you can use Ricochet, this option will try to use Ricochet. Because you can't use it yet, it gets... stuck, I guess? It won't stop you from using Spread Shots (AoE GCD), but it will prevent you from using Gauss Rounds because it gets hung up on you using Ricochet shots as your oGCD, which you can't.

**Comment by Kagekazu** [comment]
lvlcheck for gauss/ricochet will be added, forgot that one on aoe apparently
