### ISSUE TITLE
MCH Single target rotation feature is broken

### ISSUE THREAD

**Issue by BustyboyPrincess** [Nik-Potokar/XIVSlothCombo#1339]
It specifies Split Shot, and thus HEATED split shot does not trigger rotation. I cannot place an non upgraded on my hotbar after obtaining the upgraded one.

**Comment by Wild-Carrot** [comment]
Split Shot can still be put on your bar. Go to your action tab where your skills are located, then click the 3 lines icon in the bottom right of that window, right next to "Compact view". This will change the viewing mode. The left mode will let you drag the unupgraded version onto your bar.

**Comment by Taurenkey** [comment]
This is something that is addressed in the next version, however as there is a workaround it's not a pirority to push out quickly at the minute.
