### ISSUE TITLE
[MCH] Bug Advance Single Button Opener ST

### ISSUE THREAD

**Issue by BungzeroQ** [Nik-Potokar/XIVSlothCombo#1342]
maybe using this feature "Gauss Round/Ricochet"

<img width="174" alt="Screenshot 2023-12-12 103936" src="https://github.com/Nik-Potokar/XIVSlothCombo/assets/139851815/df6d5bc8-a938-4dbb-91da-f1eb977b3b41">

**Comment by Kagekazu** [comment]
are u using this option? 
![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/95875972/00962885-0d3d-42f0-80c6-019cf2e4f37d)
or this one?
![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/95875972/1893b0f5-27ad-444f-a2cf-0839372da077)

cause for now they conflict with standard. can u try turning them off and retrying the opener?

**Comment by BungzeroQ** [comment]
It will be this option. because i try off this option, it's all opener correct!
![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/139851815/a8c6964f-a0f5-4a43-8387-a0ab01ca0b78)

**Comment by Kagekazu** [comment]
Is fixed in current version
