### ISSUE TITLE
[BLU] Level 80 Blu opener

### ISSUE THREAD

**Issue by JordanCogni** [Nik-Potokar/XIVSlothCombo#1344]
Currently you have it cast wing reprobation twice in a row while it should be wing reprobation - feather rain - sea shanty - wing reprobation as the 2 OGCDs in between allow for wing reprobation to be ready again.

Also J-kick should be cast after moon flute not before it

**Comment by Taurenkey** [comment]
Please see #1324, you'll need something like ReAction to deal with Feather Rain.
