### ISSUE TITLE
[PLD][Suggestion] Manual Riot Blade Combo

### ISSUE THREAD

**Issue by BlackWyvern** [Nik-Potokar/XIVSlothCombo#1346]
Healing yourself as a PLD with combo running is a nightmare. There's no way to get to Fast Blade to start a riot blade combo without having to slog through the entire single target rotation and fighting against it to not spam holy while you're trying to get enough MP to Clemency.

Having an option to Fast-Riot on its own would be great, rather than having to fumble into the options menu to disable combos while trying not to die.

**Comment by Kaeris-Tempest** [comment]
The Sloth logic for tanks, DPS and even healers, is primarily focused on damage efficiency. Self-sustain is, _if possible at all_, a secondary concern - as it is ultimately up to you, the player, not to place yourself in situations you do not want to be in.

Re-wiring (or rather, _disregarding_) the entire logic to accommodate a simple 1-2 spam for MP recovery so you can continuously cast Clemency on yourself is... inappropriate at best, as your Atonement combo does a much better job at that _while_ killing the enemy faster.
