### ISSUE TITLE
mnk Perfect Balance/Form Shift issue.

### ISSUE THREAD

**Issue by tita9** [Nik-Potokar/XIVSlothCombo#1348]
Issue: In some cases, sloth will try to trigger form shift while perfect balance is active, leading you to be stuck into perpetually doing form shift until PB wears off. The form shift just misses.

Steps to reproduce: Find a dummy, enter combat by right clicking it, trigger PB, right click the dummy's hp bar > reset enmity, you then exit combat and combo buttons will change to Form Shift, leading you to perpetually do form shift that won't work because PB until you re-enter combat by other means or PB expires.

Possible resolution: Add a condition to check if Perfect Balance is active when deciding if combo buttons should be Form Shift.

**Comment by tita9** [comment]
I am running:
Bootshine Combo
>Masterful Blitz option
>CDs on Main Combo
>>Riddle
>>PB
>Meditation on Main Combo
>>Meditation uptime feature

Arm of the Destroyer combo
>Masterful Blitz
>CDs on AOE combo
>>Riddle of Wind
>>PB
>Meditation on AOE combo

**Comment by Kagekazu** [comment]
Hey,
 can u do /scombo debug MNK and send the file?

This happens because the code says to only use form shift when outside of combat ( and looks if u have the formless fist buff ), and u can only use perfect balance while in combat. 

A rework for monk is in the works, but even then, it can always happen when u leave combat in the middle of perfect balance. Since perfect balance overrules form shift's buff.

I might look for a resolution in the new monk code, but it should be a rare case in general :)

**Comment by tita9** [comment]
I mean, it's not that rare of a case. It can happen several times in a healthy playing day, something like doing my roulettes and a few more runs of random stuff, something like ~2-3 hours of gameplay time. It do be bothersome enough for me to come on here, make an anonymous account to protect my identity, spend like... 30 minutes crafting a scenario to reproduce the issue reliably, and make a report about it. It's also fairly random, some days, it doesn't happen at all, it happens more in other days. It's fairly embarassing when it happens too ?

Here's the bits I'm comfortable sharing, this is while I'm at rest in town:

```
Plugin Version: 3.1.1.3

Installation Repo: https://raw.githubusercontent.com/Nik-Potokar/MyDalamudPlugins/main/pluginmaster.json

Current Job: monk / Monk / MNK
Current Job Index: 20
Current Job Level: 83

Current Zone: New Gridania
Current Party Size: 0

START ENABLED FEATURES
8042 - All_PRanged_Dismantle
9000 - MNK_AoE_SimpleMode
9006 - MNK_ST_SimpleMode
9008 - MNK_ST_Simple_MasterfulBlitz
9009 - MNK_AoE_Simple_MasterfulBlitz
9013 - MNK_ST_Simple_CDs
9014 - MNK_ST_Simple_CDs_RiddleOfWind
9015 - MNK_ST_Simple_CDs_PerfectBalance
9017 - MNK_ST_Simple_Meditation
9019 - MNK_AoE_Simple_CDs
9020 - MNK_AoE_Simple_CDs_RiddleOfWind
9021 - MNK_AoE_Simple_CDs_PerfectBalance
9023 - MNK_AoE_Simple_Meditation
9026 - MNK_ST_ComboHeals
9027 - MNK_AoE_ComboHeals
9028 - MNK_ST_Meditation_Uptime
END ENABLED FEATURES

START CONFIG SETTINGS
MNK_Demolish_Apply - NOT SET
MNK_DisciplinedFist_Apply - NOT SET
MNK_STSecondWindThreshold - 32
MNK_STBloodbathThreshold - 48
MNK_AoESecondWindThreshold - 24
MNK_AoEBloodbathThreshold - 46
MNK_VariantCure - NOT SET
EmergencyHealThreshold - NOT SET
EmergencyGuardThreshold - NOT SET
QuickPurifyStatuses - NOT SET
END CONFIG SETTINGS
```

**Comment by Kagekazu** [comment]
I adjusted it in my reworked monk PR. I apparently already solved it in my ST one, but added it to AoE now aswell.
