### ISSUE TITLE
RDM melee range check fail

### ISSUE THREAD

**Issue by RuBerri** [Nik-Potokar/XIVSlothCombo#1352]
When executing the single target casting combo (verfire/verstone, verthunder/verfire) the embolden-manification combo will replace the casting combo into Reposte when outside of melee range. This was not present in previous versions and seems to have been removed. 
Edit: After further testing, it also seems to be extremely situational if this happens or not. On top of this, it will happen any time both white and black mana exceed 49. Still failing to check if within melee range.

**Comment by tita9** [comment]
Can you clarify exactly what is the issue here ? Your single target button is getting replaced by riposte at range ?
What is the behavior you expect ?
Also, enforced melee range is about your button not switching off the combo once it's initiated.
If you're bothered that riposte appears while you're at range and you can't execute it, you probably haven't check the "Gap close with corps-a-corps" option in Single Target Melee combo options.
If that doesn't help, I would love more info! I can then test further myself and look at the code to find the issue and lay it down in more technical terms for the team. Could you also do a `/scombo debug rdm` right after reproducing the issue and paste the output you get ? I only need the Enabled Features and Config settings sections. You can omit the rest. c:
I hope this helps!

**Comment by RuBerri** [comment]
Yes, sorry. I haven't changed anything in a while, so I'm not sure if an update reverted changes I've made.
Correct, my reposte is replacing the magic combo when outside of melee range. Like, having been in melee range at all during the magic combo. It will weave embolden and manafication at range as well. The expected behavior is that it waits for me to be in melee range to swap to these skills.
The issue you've replicated is the issue I'm having, yes. 
Apologies, I'm not exactly sure what options I had before this issue was present, so I wasn't able to accurately check if everything was identical for before-and-after. I do know that it seemed to happen after a Sunday update, but that's about it.
"Gap close with Corps-a-corps" was not on before however, and did not produce this issue then.
I've been toggling a lot of options on and off while testing if there's a possibility one of the options was toggled in the update, so not all features are exactly as I've had them, but still replicate the issue I'm having. Here is the requested text from the debug: 
START ENABLED FEATURES
8042 - All_PRanged_Dismantle
13000 - RDM_ST_DPS
13110 - RDM_Balance_Opener
13111 - RDM_Balance_Opener_AnyMana
13210 - RDM_ST_ThunderAero
13211 - RDM_ST_ThunderAero_Accel
13212 - RDM_ST_ThunderAero_Accel_Swiftcast
13220 - RDM_ST_FireStone
13240 - RDM_ST_oGCD
13241 - RDM_AoE_oGCD
13310 - RDM_AoE_DPS
13320 - RDM_AoE_Accel
13321 - RDM_AoE_Accel_Swiftcast
13322 - RDM_AoE_Accel_Weave
13410 - RDM_ST_MeleeCombo
13411 - RDM_ST_MeleeCombo_ManaEmbolden
13412 - RDM_ST_MeleeCombo_ManaEmbolden_DoubleCombo
13421 - RDM_AoE_MeleeCombo_ManaEmbolden
13424 - RDM_AoE_MeleeFinisher
13425 - RDM_AoE_Lucid
13440 - RDM_ST_MeleeCombo_UnbalanceMana
13510 - RDM_ST_MeleeFinisher
13610 - RDM_ST_Lucid
13820 - RDM_EmboldenManafication
13821 - RDM_MagickBarrierAddle
100000 - ALL_Tank_Interrupt
100001 - ALL_Tank_Reprisal
100020 - ALL_Caster_Addle
100030 - ALL_Melee_Feint
100031 - ALL_Melee_TrueNorth
100040 - ALL_Ranged_Mitigation
100041 - ALL_Ranged_Interrupt
100093 - ALL_IslandSanctuary_Sprint
100095 - ALL_Ranged_Menu
100096 - ALL_Melee_Menu
100097 - ALL_Caster_Menu
100099 - ALL_Tank_Menu
END ENABLED FEATURES

START CONFIG SETTINGS
RDM_VariantCure - NOT SET
RDM_ST_Lucid_Threshold - NOT SET
RDM_AoE_Lucid_Threshold - 7000
RDM_AoE_MoulinetRange - NOT SET
RDM_ST_oGCD_OnAction_Adv - True
RDM_ST_oGCD_Fleche - True
RDM_ST_oGCD_ContraSixte - True
RDM_ST_oGCD_Engagement - True
RDM_ST_oGCD_Engagement_Pooling - True
RDM_ST_oGCD_CorpACorps - False
RDM_ST_oGCD_CorpACorps_Melee - True
RDM_ST_oGCD_CorpACorps_Pooling - True
RDM_ST_MeleeCombo_Adv - True
RDM_ST_MeleeFinisher_Adv - True
RDM_ST_MeleeEnforced - False
RDM_AoE_oGCD_OnAction_Adv - NOT SET
RDM_AoE_oGCD_Fleche - True
RDM_AoE_oGCD_ContraSixte - True
RDM_AoE_oGCD_Engagement - False
RDM_AoE_oGCD_Engagement_Pooling - True
RDM_AoE_oGCD_CorpACorps - False
RDM_AoE_oGCD_CorpACorps_Melee - True
RDM_AoE_oGCD_CorpACorps_Pooling - True
RDM_AoE_MeleeCombo_Adv - True
RDM_AoE_MeleeFinisher_Adv - True
RDM_ST_oGCD_OnAction - True, True, True, True
RDM_ST_MeleeCombo_OnAction - True, True
RDM_ST_MeleeFinisher_OnAction - True, True, True
RDM_AoE_oGCD_OnAction - NOT SET
RDM_AoE_MeleeCombo_OnAction - True, True
RDM_AoE_MeleeFinisher_OnAction - True, True, True
EmergencyHealThreshold - NOT SET
EmergencyGuardThreshold - NOT SET
QuickPurifyStatuses - NOT SET
END CONFIG SETTINGS

**Comment by tita9** [comment]
Steps to reproduce: Run the single target combo rotation with both Corp a Corps options off and melee combo on, at which point it will be replaced by Riposte, soft-locking you out of continuing your dps, unless you're paying attention and go into melee manually.

How I resolved it:
Combos/PVE/RDM.cs Line ~386 (the series of conditions to check for usage of the buffs)
Added `&& (InMeleeRange() && BuffsMeleeCheck == true || BuffsMeleeCheck == false)`

Combos/PVE/RDM.cs Line ~529 (the hook that returns riposte)
Added a condition check to the Riposte return, looks like this:
`if(InMeleeRange() && RiposteMeleeCheck == true || RiposteMeleeCheck == false)
    return OriginalHook(Riposte);`

The two booleans here are just hardcoded toggles I made to test this. x)
Would probably be nice to make these into respective settings ? I don't know actually!
Can confirm that adding these conditions make it feel a lot more like RDM used to play when I used it with sloth back in the days ie: your ranged rotation continues up to even overcapping on mana except it's much tighter than it used to be, I tried it in a dungeon run and loved it.. 

I hope this helps! ♥

**Comment by RuBerri** [comment]
Sometimes, mechanics force me to stay out of melee range for a while, but if embolden and manafication are up, it switches to them regardless of being in or out of melee range. 

Thank you much! 
Sorry, how do I put those lines in? Or will we wait till the next update to the plugin to see them implemented?

Much appreciated!

**Comment by tita9** [comment]
Probably better to wait until the next update, I do this to save some time to actual contributors, since I have a lot of time on my hands myself rofl. I've been messing around with my own custom build for about 2 weeks at this point and I'm getting pretty familiar with sloth, at least the comboing/replacing buttons part of it.

**Comment by Taurenkey** [comment]
Fix pushed
