### ISSUE TITLE
[MCH] Suggestion: Adv SingleTarget - Option to hold our big hitters when Reassemble is not on cooldown

### ISSUE THREAD

**Issue by Wild-Carrot** [Nik-Potokar/XIVSlothCombo#1353]
**Class/Job:** Machinist
**Feature:** Advanced Mode - Single Target

**Issue:** So, I'd like to suggest an option that HOLDS our big hitters (Air Anchor, Drill, Chainsaw) when Reassemble is not on cooldown. This functionality existed prior, but as was mentioned in the last thread discussing this, the option was actually a bug. And the option was fixed, which led to this functionality being axed.

The way it was, using the bug, if reassemble had a charge, it would use 1-2-3 like usual, but instead of putting the big hitters on the button, it would just be the normal 1-2-3, which means the big hitters would wait until you manually used Reassemble before the 1-2-3 would change to them. If Reassemble _didn't_ have any charges (as in, is on cooldown), it would use the big hitters on cooldown.

This was great for giving control over when your burst was occurring. This was lost when the bug was fixed.

The way it is now, it just fires them off on cooldown. If you disable them, that means you have to manually fire them every time. While I think these are perfectly fine as options, I feel like having an option to tie them to "Does the player have the have the Reassemble buff / Is Reassemble on cooldown" for players who want a bit more control over their burst at the press (or lack thereof) of a button would just be a good thing.

Maybe this is a disaster waiting to happen, though. I don't really know. All I do know is I liked the playstyle it created. The closest I can come to mimicking it is to disable the heavy hitters on the 1-2-3 button. So, here is the request.

**Comment by sauronshotdogs** [comment]
+1
