### ISSUE TITLE
DRG Abilities Getting Stuck

### ISSUE THREAD

**Issue by Ojjeorago** [Nik-Potokar/XIVSlothCombo#1355]
I'm experiencing an issue where unusable replacement skills are getting stuck on my hotbar when playing Dragoon. In this particular case, True Thrust is replaced by Wheeling Thrust, but I don't have Wheel in Motion so I can't actually use that. I was teleporting around doing Elite Marks when it happened, so it might be something with stopping mid combat? Zoning and changing classes didn't clear the issue.
[SlothDebug.txt](https://github.com/Nik-Potokar/XIVSlothCombo/files/14275852/SlothDebug.txt)
![Screenshot 2024-02-13 230146](https://github.com/Nik-Potokar/XIVSlothCombo/assets/13925442/6ba9fddd-370f-4cbd-96f6-f0e551bc87d6)

**Comment by Kagekazu** [comment]
can u try to 
- enable advanced mode
- use everything except the opener
- test again.

i think the issue is with the zoning and it gets stuck in the opener.
