### ISSUE TITLE
Feature Request Level Lock

### ISSUE THREAD

**Issue by opengrip** [Nik-Potokar/XIVSlothCombo#1357]
Would be really nice to have a feature for each job to lock the level of each job. Especially at cap levels, 50, 60, 70, 80. This way if someone is out leveling there story progression stuff doesn't break when you get higher level without unlocking the abilities.

**Comment by Taurenkey** [comment]
No, we don't want this, it promotes bad play

**Comment by opengrip** [comment]
Its not really about bad play. For example: If you do the MSQ you get to level 50 and then by the time you get to Heavensward you are midway through your 50s due to extra quests/time that it takes to get through post patch questing etc There is no way to unlock your abilities until you reach the next expansion each time.
