### ISSUE TITLE
Separate button feature. 

### ISSUE THREAD

**Issue by opengrip** [Nik-Potokar/XIVSlothCombo#1359]
Not sure if this is possible but is there anyway we could make the one button features work on a separate version of the skill. For example: On Drg have 2 versions of True thrust at the same time. One version which acts like the original skill and another which abides by sloth rules. This way I can maintain a regular setup of my skills and use them normally or switch into lazy mode depending on my mood without having to toggle sloth on and off.

**Comment by Taurenkey** [comment]
Not possible
