### ISSUE TITLE
[BLU] Adding BLU Options

### ISSUE THREAD

**Issue by damolitionn** [Nik-Potokar/XIVSlothCombo#136]
I took a break from P4S progging to do some BLU savages and I 1-buttoned the Moon Flute Opener, Final Sting, and a buffed Song of Torment for my own ease.  
Curious to see if you guys want this added as it's pretty niche and there aren't a lot of BLU raiders. Keep in mind, your DPS loadout would have to be more or less the same as the one given by Blue Academy to get the full range of the Moon Flute Opener.

**Comment by Iaotle** [comment]
I meeeeeeeeeeeeeeeeeeeean.... Yes? Yes please?

**Comment by Iaotle** [comment]
Make sure to add a description that allows someone to figure out what they need for your options to work though.

**Comment by PapaSteel** [comment]
Absolutely.

**Comment by damolitionn** [comment]
Added:
1. Buffed Song of Torment
2. Moon Flute Opener
3. Final Sting Combo

I hadn't really thought about adding Off-guard into the combo because I'm a greedy DPS and I don't want to waste a GCD if one of the Blu Tanks could do it, but I'll get around to it in the future even though it's just two lines of code to check if the buff is on the boss.
