### ISSUE TITLE
[SGE] Suggestion: (AoE) Dyskrasia No-Target Option - Change "no target" to "no enemy target"

### ISSUE THREAD

**Issue by Wild-Carrot** [Nik-Potokar/XIVSlothCombo#1362]
**Class/Job:** Sage
**Feature:** AoE DPS Feature
**Sub-feature:** Dyskrasia No-Target Option

**Issue:**

AoE DPS feature replaces Phlegma with various options. One such feature is Dyskrasia. What's the difference between the two? Phlegma hits much harder, but has a cooldown. Dyskrasia is always available. However, there is another difference and why this feature exists to begin with: Dyskrasia doesn't require a target, it's just point-blank and Phlegma requires an **enemy** target.

So where does the issue with "No-Target Dyksrasia" come in? Well, it's not so much an issue with Dyskrasia as much as it is an issue with Phlegma. Because of how the suboption works, it will swap back to Phlegma even if you target an ally / yourself and unlike Dyskrasia Phlegma cannot be used anything other than enemy targets.

My suggestion is to make it so that with this option enabled, it only reverts back to Phlegma if targeting an enemy. This becomes very noticeable in something like FATEs with a lot of people where you might want to spam an AoE that doesn't require an enemy like Dyskrasia.

If there are arguments against this, I'd like to hear them. As far as I know, this change wouldn't step on anyone's toes, but maybe I'm overlooking something.

**Comment by Tartarga** [comment]
I've been mulling over the idea of having redoing the AoE on Dyskrasia.
Dyskrasia the base
Toxikon if valid target
Phlegma if valid target and in range

**Comment by tita9** [comment]
Temporary solution would be to use reaction (another plugin that works really well with sloth) to snap to your nearest target when you don't have one ? That way you're never stuck with phlegma on your bar with no target.
That might help until this update goes through ? It's a band aid fix but better than nothing.

**Comment by Tartarga** [comment]
Closing this due to the function being rewritten to accommodate the upcoming "Eukrasia Dyskrasia" (AoE DoT attack).  Dyskrasia will be the primary action that will transform to either Phlegma or Toxikon, instead of Phlegma to Dyskrasia or Toxikon
