### ISSUE TITLE
SAM issue for low level on main rotations

### ISSUE THREAD

**Issue by jul68746** [Nik-Potokar/XIVSlothCombo#1364]
The issue concerns Gekko Combo and Mangetsu Combo, between level 35 to 50, the rotation is not optimal or stuck.

Gekko : after lv40 and before lv50 the rotation stops (you can only use Hakaze again and again) when you get Getsu and Ka, so you have to use Tenka Goken before being able to use the combos again, which is not really optimal for single target dps at this stage. 
Toggled for this combo : Enpi uptime, Yukikaze combo on main combo, Kasha combo on main combo, CDs on main combo (to get access to Samurai overcap feature.

Mangetsu : from lv 35 to 40, Mangetsu combo stops if you don't use Higanbana (solo dot cast),
from lv40 to 45, the combo starts with Hakaze-Shifu-Kasha(single target combo), then Fuga-Mangetsu but it's a bit odd and really not optimal for multi target dps. I get it is to get access to Tenka Goken final blow, but the one target combo is too long so it is not worth the cost. It would be better to have only Fuga-Mangetsu at this stage.
Toggled for this combo : Oka to Mangetsu feature (still issued if you toggle it off)

**Comment by Kagekazu** [comment]
I would have to check for the aoe. 

But for the ST, below lvl 50, what do u expect will be used as iajutsu? Since setsugekka is lvl 50

**Comment by jul68746** [comment]
Sorry i didn't precise above, but i'm talking about the custom combos, not the simple ones.

I would like the single target combo to continue without iajutsu, even if the conditions are met to use it, (it works just fine at lv50+). This way you can start the next 3hit-chain and use iajutsu when you see fit. This allows to move more freely during the fight, avoiding aoe or following a moving foe.

The problem here is that it completely stops the combo chain until you use iajutsu.

**Comment by Kagekazu** [comment]
AoE issue using ST is fixed next update

**Comment by Tartarga** [comment]
Fixed in #1711
