### ISSUE TITLE
[MCH] Manual use of Flamethrower sets Advanced AoE Combo to invalid skill Savage Blade

### ISSUE THREAD

**Issue by Serfrost** [Nik-Potokar/XIVSlothCombo#1369]
Bonus: "Outwith" instead of "Without"

![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/19275542/8aa3955c-5539-4cd1-8dd6-e19d0a0f51d0)

![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/19275542/e2a6b705-51e1-4bc1-a6ee-90be58cef756)

[SlothDebug.txt](https://github.com/Nik-Potokar/XIVSlothCombo/files/14933401/SlothDebug.txt)

**Comment by Kagekazu** [comment]
that is intented, because flamethrower is a channeled skill, and it makes it so u cant accidently stop the skill. 

its the same as the double feint or double addle protection.
