### ISSUE TITLE
Suggestion: SAM Higanbana DPS

### ISSUE THREAD

**Issue by DoomXIII** [Nik-Potokar/XIVSlothCombo#1371]
Right now it seems Higanbana is aplied as soon as you have Fugetsu active. Id's sugest also checking for Fuka, while this would delay Higanbana from coming out it would net an over all DPS gain in longer fights.

**Comment by Kagekazu** [comment]
is there a difference for it to be later on in the rotation? Since Fugestsu is the dmg buff, Fuka only increases the recast timer, no?
And is it on lvl 90 or lower lvl?

**Comment by DoomXIII** [comment]
Yes! Cause the buff boosts the skill speed and as we can see from here 
![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/62778492/1be37d8e-d2cc-46af-9bb8-2cc5536f315b)

this means that it's overall a DPS gain to wait 2 GCD's to apply it with both buffs up, this would be both level 90 and post level 90 since we get both buffs pretty early on. ♥

**Comment by Kagekazu** [comment]
On level 90 it already does what's recommended by the balance with opener and the rotation tho. 

For below lvl 90 I can see ur point.

**Comment by DoomXIII** [comment]
Aye sorry I do agree that the level 90 rotation from the balance has both, I say level 90 as well cause once/if it goes back to freestyle it still no longer checks for both buffs being up (god forbid you die or what not) ♥
