### ISSUE TITLE
Suggestion. [MNK] Adding Six sided star as a rotation option.

### ISSUE THREAD

**Issue by Lordgimpet** [Nik-Potokar/XIVSlothCombo#1372]
while i know in a general sense this ability is often ignored, but I've been messing about with it and found a use for it but while next difficult to pull of manually vis sloth it should not be an issue to weave. as its a hard hitting ability and timing it right does not affect the flow of weapon skill rotation

so to have it as an option to be added

due to how it affects the weapon skill GCD after use but abilities are not affected, for sloth to use it it would require conditions to be met, it would only be used if 1-2 abilities are available, 
so it would only SSS, if it can use Forbidden chakra into perfect balance etc.
not sure if it easier to set it open to all abilities, or a specific list that can be tailored

**Comment by tita9** [comment]
Six Sided Star costs you 2 gcd's for 550 potency.
Dragon Kick + Bootshine costs you 2 gcd's for 630 potency.
Six Sided Star is not weavable, it's a GCD skill.

**Comment by Lordgimpet** [comment]
I think you miss my whole point, being that in the CD window post SSS you can use 2+ OGCD. 
have you tried it manually like i have, or are you just basing things purely on paper math which often does not corelate into in game use. its does not break optimal rotation, i've tried all this manually before i made the suggestion. note i also point out that its to be used pending the ability to use Abilities which are the OGCD after SSS to not break flow. further more I requested that its an option so you can just not check it if you dont want it.

**Comment by Lordgimpet** [comment]
um no, just going to respond to this, as this isn't my first rodeo, I'm not ignorant of Balance, and I'm not new to theory crafting. was theory crafting for Death Knights and Rogues for WoW for years. and PUG/MNK since ps3 beta days, so I'm not some sprout with rookie ideas here, while I could just go to Balance and put my findings there. one thing I have learned when developing the Wow equivalents to sloth, is the addons tent to have limitations and or a way to do things that cant be performed as good or better than a human in some ways. thus some actions or talents or abilities overlooked or whatever can perform better via addon use, but just suck to do manually.  if this was not the case it would just be a simple case of the sloth devs just getting and using the API simulators use and we would all have perfect flawless rotations that even account for various fight variables, but we dont. 
sorry while this isn't pertinent to my initial requests, your responses just bristled me a little. but no harm no foul

**Comment by Jagerka** [comment]
Thanks for your input.

**Comment by Tartarga** [comment]
Obsolete
