### ISSUE TITLE
[MCH] Reassemble/Drill interaction not correct at level 60 (Big PotD/HoH QoL issue)

### ISSUE THREAD

**Issue by NikaLeets** [Nik-Potokar/XIVSlothCombo#1374]
Prior to the MCH rework, if Reassemble was off cooldown, Drill was not offered until under the Reassemble buff.  In PotD, this is a high value feature because it is very important to be able to control when using Reassemble/Drill to prevent it to be wasted on a low HP mob.  After the MCH rework, when using advanced mode, if Drill is added to the single target rotation, it is now offered regardless of the state of Reassemble.  For PotD, this is a very significant regression compared to before the MCH rework.

I think there are a few ways to address this.
1) a "level 90" compatible solution:  Add an option to "hold at least N Drill/Air anchor/chainsaw for Reassemble"  The idea would be to hold Drill/Air Anchor/Chainsaw until the reassemble buff was active.  In this case N should be the number of current charges of reassemble ready.  This would allow control of pooling for bursts and to do 2 reassembled high value attacks.
NOTE:  This proposed solution would STILL be broken in PotD because of the Hot Shot/drill potency difference at lvl 60.  I.e., If implemented this way, Hot Shot should be excluded from the "hold list" compared to Air Anchor.
2) Revert to the pre-rework behavior prior for Lvl 60 & Lvl 70.  The old "hold drill for reassemble" behavior is only problematic at lvl 90 due to the addition of Air Anchor/Chainsaw.  Ideally, pre-70, we would just use the old logic, but it would also be fine to have a checkbox to select this behavior if that is easier.
2a) This would be a "nice to have" feature, but if there was an ability to control the max "hold for reassemble" time via an optional slider, that would be pretty nice.  The range should be 0-20 to reflect the cooldown of Drill.  The reason for this is that in PotD/HoH, if drill's cooldown is slightly out of sync from reassemble, (which happens a bunch, thanks to Reassembles odd cooldown) you want to actually hold drill even if Reassemble is "soon to be off cooldown".  The default value of this should probably be something like 5 seconds, but it would be nice to be able to adjust this.

**Comment by Kagekazu** [comment]
think this will be solved in the next mch update, at DT afaik.
