### ISSUE TITLE
[Request] [RPR] Ranged Filler Option enhancement request

### ISSUE THREAD

**Issue by Xswno** [Nik-Potokar/XIVSlothCombo#1376]
Hello,

Can you add a check mark box for Harvest Moon to be optional under the Ranged Filler Option of Slice Combo Feature please?
For example, Harpe would be default and Harvest Moon would be optional if a user wants to have both.

**Comment by Kagekazu** [comment]
i will add this when next update goes out!

**Comment by Xswno** [comment]
> i will add this when next update goes out!

Thank you Kage <3

**Comment by Kagekazu** [comment]
![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/95875972/d9753f4c-7d98-40ed-b5cc-50ba218b6b3b)

**Comment by Xswno** [comment]
@Kagekazu Thank you so much for your effort!
