### ISSUE TITLE
Crash with sloth config open. Also FPS weirdness.

### ISSUE THREAD

**Issue by Soltheron** [Nik-Potokar/XIVSlothCombo#1381]
I've noticed this in the past as well where the only time Sloth will crash my game is if the configuration window is open.

I wasn't even in combat and was just running around clicking config settings (Machinist ones if that matters), and the game crashed. This has happened in the past, too.

I haven't had any other crashes in this game for a very long time now so I doubt it's something else.

Another issue is that just having the /scombo window open will drop my FPS down by 10 frames, which is odd.

**Comment by Kagekazu** [comment]
got any crash logs? otherwise its pretty hard to find what is causing the crash.

Especially since its the first time someone tells us sloth crashes their game.

**Comment by Soltheron** [comment]
It closed the game abruptly so I don't know if there are any. What files do you want, specifically?

**Comment by Kagekazu** [comment]
%appdata%\XIVLauncher\dalamud.log
%appdata%\XIVLauncher\dalamud.boot.log

only send them after it crashed, but before u start ur game again. Cause they get reset when u start the game again.

**Comment by Soltheron** [comment]
Alright, I'll see if I can crash it again lol...
