### ISSUE TITLE
[SUM] Egi summon are always blocked by Demi.

### ISSUE THREAD

**Issue by tex111** [Nik-Potokar/XIVSlothCombo#1385]
Summoner (Advanced Summoner Feature)

Egi summons are blocked by a Demi being off cooldown even if the option that adds Demi summons to the combo is disabled.

**Comment by Kagekazu** [comment]
thanks for letting us know! ill see to fix it in next release after Dawntrail!

**Comment by Genesis-Nova** [comment]
Fixed with #1404.
