### ISSUE TITLE
Seem not to be able to Install it atm

### ISSUE THREAD

**Issue by elmigo69** [Nik-Potokar/XIVSlothCombo#1414]
With the release of dawntrail, cant Install the plugin, say its not up to date

**Comment by Kagekazu** [comment]
thats because it has not been updated yet :D

**Comment by elmigo69** [comment]
haaa, explains a lot, any idea/timing on update?

**Comment by halcyonight** [comment]
I'd suppose they at least need to update all jobs to feature the new dawntrail skills before they push an update. From what I can see they have yet to update BLM, DNC, DRG, DRK, MNK, NIN, RDM, SAM, WAR, and the healers. 

...It will take a while

**Comment by Kagekazu** [comment]
Should work now 😀

**Comment by elmigo69** [comment]
Semm to work now indeed, great, looking forward to bard to be added :) great work
