### ISSUE TITLE
[Question] Difference between WAR combos

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/XIVSlothCombo#142]
What's the difference between the Fell Cleave/Decimate option, and the newly added StormsPathComboFeature and SteelCycloneFeature?

![image](https://user-images.githubusercontent.com/95890035/149788928-00f68f7e-7c55-4fb1-9169-1ea17b70fb6e.png)

**Comment by Nik-Potokar** [comment]
All options with star next to it are PVP combos you can hide/show them by ticking the 1st option on the plugin

**Comment by sauronshotdogs** [comment]
Do they need all other combos to be deactivated? I can't seem to make any of them actually work.

**Comment by Nik-Potokar** [comment]
Nope since they are seperate you just need to be in a pvp area

**Comment by sauronshotdogs** [comment]
OH, I completely misunderstood you then.  

Does this mean that they will override the existing pvp combos?

**Comment by Nik-Potokar** [comment]
Yes
