### ISSUE TITLE
XIVSlothCombo 3.2.0.0 - [VPR]+[PLD] Issues

### ISSUE THREAD

**Issue by Scjaro** [Nik-Potokar/XIVSlothCombo#1424]
VPR: Reawaken is in "Advanced Mode - AoE" Rotation even if its disabled. 
PLD: "Goring Blade" in "Simple Mode - Single Target" and in "Advanced Mode - Single Target" is not spend if its activated.

Sorry for my bad English. :-)

**Comment by Lusaca87** [comment]
i guess i see the issue. It in both mode it is designed for level 100 with the new skill "Blade of Honor".

**Comment by Akechi-kun** [comment]
PLD issue fixed in next update

**Comment by Kagekazu** [comment]
VPR fixed next update
