### ISSUE TITLE
SlothCombo V3.2.0.0 MCH issue

### ISSUE THREAD

**Issue by Doomgineer** [Nik-Potokar/XIVSlothCombo#1425]
MCH "Simple Mode - AoE" seems to include Savage Blade GLD ability in it's rotation.
![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/57538398/17773285-5bed-4b4b-88ea-a7cd67d41230)

**Comment by Kagekazu** [comment]
That is when u use flamethrower, so u don't end it prematurely.
