### ISSUE TITLE
VPR Request - Allow Dreadwinder/Pit Combos without cooldown inclusion

### ISSUE THREAD

**Issue by hugesloth** [Nik-Potokar/XIVSlothCombo#1428]
It would be great to be able to enable "Dreadwinder Combo" and "Pit of Dread" combo under their respective Advanced Modes without enabling the "parent" cooldowns of Dreadwinder/Pit of Dread.

Currently selecting their combos enables the inclusion of Dreadwinder/Pit of Dread, and while you can uncheck them manually, the combos are disabled regardless of checkbox state.

Use Case: I want control of my Dreadwinder/Pit cooldown usage outside of the single button combo, but I want to press the single button (Steel Fangs/Steel Maw) to spam the combo actions once I activate Dread/Pit.

**Comment by Kagekazu** [comment]
Heya,

That's an easy one, I'll add it to my fixes list.
