### ISSUE TITLE
RDM manafication is broken

### ISSUE THREAD

**Issue by AnonLoid** [Nik-Potokar/XIVSlothCombo#1430]
Manafication ability changed in DT, it's no more grants mana, but grants 3 "enchanced swordplay" buffs, but Sloth still waits mana to hit 50/50 after casting manafication, simply wasting this ability.
![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/43205986/d1529585-621d-487e-93b1-675ac1d623e5)

**Comment by AnonLoid** [comment]
Also, vice of thorns ignored by Sloth completely.

**Comment by Kagekazu** [comment]
RDM isnt updated for lvl 100 iirc.

**Comment by Tartarga** [comment]
working on it. Solution to AoE tested and working, not ideal but investigating
