### ISSUE TITLE
RDM AOE Combo only needs 50/50 mana in DT

### ISSUE THREAD

**Issue by StellarJay77** [Nik-Potokar/XIVSlothCombo#1432]
In DT RDM doesn't need 60/60 Black and White Mana anymore to start the AOE combo. It is now 50/50 just like the single target combo. 20/20, 15/15, and 15/15 respectively.

**Comment by Tartarga** [comment]
Does it work at 50/50? I think I just forgot to update the description

**Comment by Cadwgan** [comment]
Just tested, it is triggering the AoE melee combo at 50/50.
