### ISSUE TITLE
MCH - not using wildfire in any variation of the burst

### ISSUE THREAD

**Issue by leahminka** [Nik-Potokar/XIVSlothCombo#1435]
I have tried simple as well as advanced, tried turning off reassemble as well as richochet/guass just incase it was a latency/ping issue. turn on/off the level 100 opener. in every instance  it uses reassemble(if checked< chainsaw < barrel stabilizer<hypercharge< heatblast/blazing shot - and for a split second i see it attempting to select wildfire before disappearing and continuing to only use hatblast/blazing shot.

afterwards it continues to never use wildfire until the next  time i achieve 50 heat in which it will resume its rotation as normal, wildfire included.    Tried on a level 91 mch

**Comment by Kagekazu** [comment]
should be better in the next update. testing it as a lvl 90 MCH and i seem to have no issues

**Comment by Tomato619** [comment]
My lvl 100 MCH (680 ilvl) Doesnt use wildfire other than in the opener. Once the wildfire cooldown has reset, it doesnt use it at the 2 min burst. Even tested to see if it would use at 4 min.

Tested both simple and advanced.

**Comment by Kagekazu** [comment]
should also be better with the update.
