### ISSUE TITLE
[DNC] Further optimizations

### ISSUE THREAD

**Issue by PapaSteel** [Nik-Potokar/XIVSlothCombo#144]
Dancer has already received a ton of love, but there's a few final adjustments that could be make to make it extremely fluid.

Standard Step and Technical Step can share a button, with the latter taking priority. (One button for both dances, since they're used whenever possible.)
Saber Dance should share a button with the Fan Dance combo, with the latter taking priority. (Dump espirit when fan dance and its relevant procs aren't available.)

As always, you're absolutely amazing, and thank you.

**Comment by Iaotle** [comment]
That would make dancer what, a 2-button job? Jesus...

**Comment by Nik-Potokar** [comment]
Will add both features in the next update
