### ISSUE TITLE
Debug log being flooded with exceptions - AST

### ISSUE THREAD

**Issue by acfrazier** [Nik-Potokar/XIVSlothCombo#1445]
I was wondering why the size of dalamud.log was rapidly increasing on my disk and, while not even on the AST job, I discovered that sloth was constantly logging the below error. Once disabled, the log activity ceased.

```
19:13:25.244 | ERR | Exception during raise of "Void <InvokeSafely>b__0()"
	System.MissingMethodException: Method not found: 'Dalamud.Game.ClientState.JobGauge.Enums.CardType Dalamud.Game.ClientState.JobGauge.Types.ASTGauge.get_DrawnCard()'.
	   at XIVSlothCombo.Combos.JobHelpers.AST.CheckCards(IFramework framework)
	   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\Utility\EventHandlerExtensions.cs:line 124
```
This appears to have no other negative impact other than the log writing, but I wanted to bring it up here.

**Comment by Kaeris-Tempest** [comment]
This is happening due to a Dalamud update that was pushed a few hours ago. It changed the NIN and AST gauges.
[https://github.com/goatcorp/Dalamud/commit/3727940b5c61a146abb2bf273842dd40b8eb6b48](https://github.com/goatcorp/Dalamud/commit/3727940b5c61a146abb2bf273842dd40b8eb6b48)

**Comment by Taurenkey** [comment]
It has been resolved now
