### ISSUE TITLE
[MCH] Clipping GCD after Hypercharge window

### ISSUE THREAD

**Issue by DeebsIno** [Nik-Potokar/XIVSlothCombo#1447]
Currently after performing 5 Heatblasts and exiting your Hypercharge window, it tries to double weave after the last heatblast and clips the next gcd afterwards because its not possible to double weave with a 1.5s gcd. Currently these are the only options I have ticked. 

![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/174912954/2f5fabfc-de33-4f25-b597-79b83d00044b)

**Comment by Kagekazu** [comment]
that was an oversight on my part, i added it to simple mode, but forgot to paste it into advanced. will be fixed in this PR

**Comment by DeebsIno** [comment]
> that was an oversight on my part, i added it to simple mode, but forgot to paste it into advanced. will be fixed in this PR

Hi, that PR seems it will force only single weaves even outside of Hypercharge windows. Is there no better way to prevent that clipping without forcing single weaves outside of those windows? I don't remember having this problem pre-DT.

**Comment by Kagekazu** [comment]
it also did the clipping pre DT, since its the same code as from pre DT.

I will see if i can find another solution, but no guarantees. Its also not alot of dps loss, as long as it gets everyting inside buffs/pots

**Comment by DeebsIno** [comment]
No problem, thanks for the help :)

**Comment by Kagekazu** [comment]
found a solution, so ittl be resolved :)
