### ISSUE TITLE
[GNB] Advance AoE Sonic Break not working as purpose?

### ISSUE THREAD

**Issue by Shiratama-works** [Nik-Potokar/XIVSlothCombo#1451]
As one button Aoe Feature hava Sonic Break on AoE Feature it does use it. But after using it once it is still want to use it again even it is imposiable as it can only use once during No Mercy

**Comment by ibigfire** [comment]
This was marked as completed, but even though the update happened that as far as I can tell was supposed to include the fix, it does not seem to be wholly fixed.  When the "Sonic Break on AoE Option" is enabled it will continue to want to use Sonic Break despite the skill only being able to be used during "Ready to Break".

This may be a Dawntrail related change to the ability, as the ability was changed in Dawntrail.

**Comment by Taurenkey** [comment]
This has not be pushed live yet. My merge time was after the update went out.

**Comment by ibigfire** [comment]
Gotcha, my bad.  Thanks so much for all the hard work you and the team put out! ^_^
