### ISSUE TITLE
[MCH] Issue with Single Target Rotation for MCH in FFXIVcombo (Drill and Reassemble)

### ISSUE THREAD

**Issue by MoMoore1990** [Nik-Potokar/XIVSlothCombo#1452]
First of all, I would like to express my gratitude for your comtributions to the FFXIVcombo. I am experiencing an issue with the Single Target Rotation for MCH job, and I hope you can provide some guidance.
Before the 2024 remake to MCH portion of the Combo, the inclusion of Drill, Air Anchor, and Chain Saw (hereinafter referred to as Drill) in the Single Target Rotation was conditional based on the Reassemble cooldown status:

If Reassemble is on cooldown: Drill would not replace Split Shot (as shown in Image 1).
![1](https://github.com/Nik-Potokar/XIVSlothCombo/assets/174933078/3f89018e-bd14-4b96-9e0c-a0e668d2053f)

If Reassemble is available but the Reassemble Buff is active: Drill would replace Split Shot (as shown in Image 2).
![2](https://github.com/Nik-Potokar/XIVSlothCombo/assets/174933078/0e7748c6-ff61-4ace-982f-6001f9e5f89d)

If Reassemble is not on cooldown: Drill would automatically be included in the Single Target Rotation (as shown in Image 3).
![3](https://github.com/Nik-Potokar/XIVSlothCombo/assets/174933078/bd5e7042-ea41-4fc4-b683-f7a7a4725d95)

However, in the new version of the MCH script, Drill, Air Anchor, and Chain Saw always replace Split Shot, regardless of the Reassemble cooldown status.

How can I achieve the previous functionality with the current version of the script, where Drill, Air Anchor, and Chain Saw inclusion in the Single Target Rotation is conditional based on the Reassemble cooldown status?

**Comment by Kagekazu** [comment]
in this build u cannot. 

U want it to be ONLY used when reassemble is off cooldown, which is not possible

in this one it uses all the options ( as in u select to add drill to the rotation, so it will ALWAYS put drill on the rotation )
and then u got the option of what u want it to use reassemble on. But if u select Drill, u have 2 charges of Drill on a 20 sec cooldown, and 2 charges of Reassemble on a 55 sec cooldown.

So it will use reassemble when Drill is off cooldown, but it will also use Drill even when there are no charges of Reassemble. Otherwise it would only do 6 drills in a whole fight instead of 12.

**Comment by MoMoore1990** [comment]
Thank you for your detailed responses.
I apologize for any confusion caused by my previous message regarding the cooldown status. Let me clarify the functionality I am looking for:

1. When Reassemble is available (1 charge or 2 charges) without Reassemble Buff, Drill, Air Anchor, and Chain Saw should not be put in the rotation.

2. When the Reassemble Buff is active, Split Shot is replaced by Drill, Air Anchor, or Chain Saw.

3. When Reassemble is unavailable (0 charge), Drill, Air Anchor, and Chain Saw are always in the rotation.

If possible, I would like to humbly suggest an additional sub-option under the “Drill, Air Anchor, and Chain Saw Option”:
"If Reassemble is available (1 charge or 2 charges) and the Reassemble Buff is not active, Drill, Air Anchor, and Chain Saw should not enter the rotation."

This would help achieve the desired behavior while maintaining the current functionality for those who prefer it.Thank you for considering this suggestion!

Best regards
