### ISSUE TITLE
[MCH] [Request] - Standalone Gauss Round/Ricochet Feature

### ISSUE THREAD

**Issue by TheTweets** [Nik-Potokar/XIVSlothCombo#1456]
Simply put, I'd like to use a single button to use both of these, akin to the standalone Drill/Air Anchor feature. 

As these skills have 2-3 charges each, it would prioritise whichever has the most charges.

**Comment by Kagekazu** [comment]
Iirc that's already in there.

I will have a look when I'm home

**Comment by TheTweets** [comment]
Ah, I've just gone back to see what's going on, and it's because I had the Gauss Round/Ricochet Option enabled in the AoE section. Because of that, it was hiding the Feature.

Sorry to waste your time!
