### ISSUE TITLE
[VPR] Pit of Dread Combo not working as stand alone

### ISSUE THREAD

**Issue by Thork8** [Nik-Potokar/XIVSlothCombo#1457]
![7576546](https://github.com/Nik-Potokar/XIVSlothCombo/assets/58894366/b3ebf803-109b-4392-82d6-7dacf577459e)

i want to have all the Dread Pit combos in the rotation BUT i want to press Dread Pit myself.
if i tick the boxes like that, all the Dread Pit combos will not be used, even i use Dread Pit myself.

the full combo works as intended if both the checkboxes are ticked, but then i dont have controll over when Dread Pit is used.

would it be possible to have all the combo be used AFTER i use Dread Pit manualy, like in the picture?

(Same for Uncoiled Fury would be awsome)

**Comment by Kagekazu** [comment]
Already fixed in PR.

Same as #1428
