### ISSUE TITLE
Pld issue Shield lob option

### ISSUE THREAD

**Issue by jul68746** [Nik-Potokar/XIVSlothCombo#1459]
In advanced mode single target, Shield lob option doesn't work when not Moving. Tested with pld lvl 70, don't know about other levels

**Comment by Akechi-kun** [comment]
So I assume when you’re not moving, it uses Holy Spirit? 🤔

**Comment by jul68746** [comment]
No it displays Fast blade instead and mb the other 2 skills from main combo. I didn't activate many options in advanced single mode, only Spirits within and Shield lob
