### ISSUE TITLE
[VPR] Standard Double Reawaken option?

### ISSUE THREAD

**Issue by Shiratama-works** [Nik-Potokar/XIVSlothCombo#1460]
2 MIN Burst windows currenty only play one reawaken during the window. Maybe add the Double Reawaken rotation from Balance?

**Comment by Kagekazu** [comment]
Is already planned in my various fixes PR

**Comment by moreime** [comment]
do we have an approximate time for that hotfix or

**Comment by Kagekazu** [comment]
depends on when the lead devs push the trigger, i cant merge the PR's.
