### ISSUE TITLE
[SGE] AOE Heal Feature: Eukrasian Prognosis Option #37 does not use Prognosis II 

### ISSUE THREAD

**Issue by BaexTower** [Nik-Potokar/XIVSlothCombo#1467]
As descired in title. Eukrasian Prognosis Option #37 does not use Prognosis II, with our without "Ignore Shield Check" selected.  And will even become stuck on Prognosis even if Addersgall charges are avaliable.

**Comment by TeranFethril** [comment]
see: https://github.com/Nik-Potokar/XIVSlothCombo/issues/1436
