### ISSUE TITLE
[GNB] extremely small window to use No mercy

### ISSUE THREAD

**Issue by Kairusy** [Nik-Potokar/XIVSlothCombo#1471]
Using the [Gnashing Fang Continuation Combo Feature] with [No Mercy on Gnashing Fang Option] enabled you have less than a second to press No Mercy before it just changed back to the Gnashing Fang skill and won't show No Mercy again until you've competed another round of your 1 2 3 combo, then once again only changes to No Mercy for a split second.

**Comment by Akechi-kun** [comment]
adjusted this to be reliant on what SkS option you have chosen.
If 2.45 option, it will lateweave NM.
If 2.5 option, it will use immediately
