### ISSUE TITLE
[MCH] Single Button Heat Blast Feature doesn't equate for its upgrade

### ISSUE THREAD

**Issue by Kairusy** [Nik-Potokar/XIVSlothCombo#1472]
having the feature enabled doesn't change Heat Blast's upgraded skill; Blazing Shot rendering the feature useless.

**Comment by Kagekazu** [comment]
which feature? cause the advanced and simple rotation uses blazing shot.

**Comment by Kagekazu** [comment]
every heatblast function in this PR is upgraded to blazing shot when u have the required level.
