### ISSUE TITLE
[VPR] Advance AoE cannot  disabled Reawaken 

### ISSUE THREAD

**Issue by BungzeroQ** [Nik-Potokar/XIVSlothCombo#1473]
![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/139851815/62a3d0af-4d6d-4adc-95c1-cc66836e7a98)

I conducted a test using the Advance AoE of VPR feature. It seems that the Reawaken checkbox is not working. Upon checking, I found that the condition is incorrect. I'm not sure if you have fixed this issue yet?

**Comment by Kagekazu** [comment]
yeah, is known, forgot to edit it. will be fixed in above PR
