### ISSUE TITLE
[PLD] Late Spend Attonement Option Not Working

### ISSUE THREAD

**Issue by Vexus221** [Nik-Potokar/XIVSlothCombo#1475]
Level 100 Paladin. I have both late spend holy spirit and late spend attonement option selected. The 1 button rotation is forcing me to use the attonement combo before starting a new basic combo.

Previously this worked as;
Basic combo (1-2-3) into Basic combo (1-2), then use Attonement/holy spirit to save royal authority for use under FoF

Since the expansion update it works as
Basic combo (1-2-3) into forced Attonement combo Basic combo (1-2), holy spirit.

The latter situation results in using lower potency skills under FoF buff window.

**Comment by thomas-henley** [comment]
Should be fixed in 3.2.0.2

**Comment by Vexus221** [comment]
Bless you for the hard work

**Comment by Tartarga** [comment]
Stale
