### ISSUE TITLE
[MCH] AoE - Savage Blade appears in rotation

### ISSUE THREAD

**Issue by DrPhilPhD** [Nik-Potokar/XIVSlothCombo#1476]
Just as title says-- no idea how this is even happening!

![Screenshot 2024-07-08 234742](https://github.com/Nik-Potokar/XIVSlothCombo/assets/175081063/31ad67b9-a75a-4c99-afa7-04700199eff3)

**Comment by StevieCoops** [comment]
It's on purpose to prevent you from cancelling Flamethrower

**Comment by DrPhilPhD** [comment]
> It's on purpose to prevent you from cancelling Flamethrower

Ah, good to know! My bad. I'll close this out, then. Thank you!
