### ISSUE TITLE
[SGE] AoE Heal Feature won´t change to Eukrasian Prognosis II

### ISSUE THREAD

**Issue by NikolaiDragneel** [Nik-Potokar/XIVSlothCombo#1477]
Hi there is a bug where in the AoE Heal Feature that if  Eukrasi is active it change to Eukrasian Prognosis and not to Eukrasian Prognosis II if available. It is grayed out in this moment.

![grafik](https://github.com/Nik-Potokar/XIVSlothCombo/assets/38686613/df1b5055-a593-4afd-9efe-932521d3c347)

**Comment by TeranFethril** [comment]
See https://github.com/Nik-Potokar/XIVSlothCombo/issues/1436

**Comment by Tartarga** [comment]
Fixed by ed2c710
