### ISSUE TITLE
MCH

### ISSUE THREAD

**Issue by elmigo69** [Nik-Potokar/XIVSlothCombo#1485]
![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/119017196/ac726d87-5f3d-40f5-b448-f52f6e2fcb08)

The new excavator follow up to chain saw is not inclueded yet in the drill anchor combo (tried it to see if its just the tooltip but wasnt used)

**Comment by Kagekazu** [comment]
Has been renamed to `Big Hitter Feature` now and will include Excavator with next update.
