### ISSUE TITLE
Major FPS drop on any combo currently

### ISSUE THREAD

**Issue by pete-nerantzinis** [Nik-Potokar/XIVSlothCombo#1487]
Happens on any job currently available I'm on v3.2.0.1 atm
`START DEBUG LOG

Plugin Version: 3.2.0.1

Installation Repo: https://raw.githubusercontent.com/Nik-Potokar/MyDalamudPlugins/main/pluginmaster.json

Current Job: viper / Viper / VPR
Current Job Index: 41
Current Job Level: 100

Current Zone: Shirogane
Current Party Size: 0

START ENABLED FEATURES
30001 - VPR_ST_AdvancedMode
30002 - VPR_ST_Opener
30003 - VPR_ST_NoxiousGnash
30004 - VPR_ST_CDs
30005 - VPR_ST_SerpentsIre
30006 - VPR_ST_Dreadwinder
30007 - VPR_ST_DreadwinderCombo
30008 - VPR_ST_SerpentsTail
30009 - VPR_ST_UncoiledFury
30010 - VPR_ST_UncoiledFuryCombo
30011 - VPR_ST_Reawaken
30012 - VPR_ST_ReawakenCombo
30096 - VPR_ST_RangedUptime
30097 - VPR_ST_RangedUptimeUncoiledFury
30101 - VPR_AoE_AdvancedMode
30102 - VPR_AoE_NoxiousGnash
30103 - VPR_AoE_CDs
30105 - VPR_AoE_PitOfDread
30106 - VPR_AoE_PitOfDreadCombo
30107 - VPR_AoE_SerpentsTail
30108 - VPR_AoE_UncoiledFury
30109 - VPR_AoE_UncoiledFuryCombo
30110 - VPR_AoE_Reawaken
30112 - VPR_AoE_ReawakenCombo
END ENABLED FEATURES

START CONFIG SETTINGS
---INT VALUES---
VPR_AoE_BloodbathThreshold - 40
VPR_AoE_SecondWindThreshold - 25
VPR_AoE_UncoiledFury_HoldCharges - 0
VPR_Positional - 0
VPR_ReawakenLegacyButton - 0
VPR_ST_BloodbathThreshold - 40
VPR_ST_SecondWindThreshold - 25
VPR_ST_UncoiledFury_HoldCharges - 1

---FLOAT VALUES---
VPR_AoE_NoxiousDebuffRefresh - 12
VPR_AoE_Reawaken_Usage - 3
VPR_ST_NoxiousDebuffRefresh - 12
VPR_ST_Reawaken_Usage - 3

---BOOL VALUES---

---BOOL ARRAY VALUES---
END CONFIG SETTINGS

Redundant IDs found: 0
Status Effect Count: 0
START STATUS EFFECTS
END STATUS EFFECTS
END DEBUG LOG
`

**Comment by pete-nerantzinis** [comment]
Nevermind the issue was a conflicting plugin when this was enabled as well, the plugin was jobbars

**Comment by Constmar** [comment]
it actually interferes with this setting 
![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/122679192/1a75c99d-1889-429e-9def-769d3f116f82)
66666666
