### ISSUE TITLE
MCH Issues

### ISSUE THREAD

**Issue by junkokoro** [Nik-Potokar/XIVSlothCombo#1488]
It seems that for some reason, when i check the "Advanced Mode - Single Target" option, my game starts dropping a lot of frames, it is borderline unplayable :(

**Comment by Kagekazu** [comment]
are u sure this is sloth related? i have been playing MCH all day and i got steady FPS.

Also, can u check if u just close the menu if it goes back up?

**Comment by junkokoro** [comment]
yeah, it seems so, i use sloth for a long time, it is the first time this seems to happen, i tested with other options both in game and plugin-wise as well as other jobs to make sure MCH was the only one affected

it did not help closing the menu, but it goes back to normal as soon as i uncheck the single target options (seems like simple mode is also affecting)

**Comment by Cadwgan** [comment]
It's possible, I tried to replicate this specific issue but framerate was perfectly stable.

However, attempting to use any action tanked framerate to as low as 8hz, actions on cooldown also lower framerate to varying degrees, disabling icon replacement in JobBars cleared it up.

**Comment by junkokoro** [comment]
yup, looks like it was and issue with job bars update then, thanks for the help guys
