### ISSUE TITLE
Huge fps drop on SlothCombo usage

### ISSUE THREAD

**Issue by Cengaveraso** [Nik-Potokar/XIVSlothCombo#1490]
I decided try VPR PVE features and i opened nearly all options but i noticed the moment i get in combat and spam button my fps drops from 100+ to 25 fps. I assume it is happening because i open too much option but it is still weird cause i have already pretty strong pc. i am adding debug file also. I tried to close all options still fps dropping to 25 the moment i close plugin everything turns back to normal
[SlothDebug.txt](https://github.com/user-attachments/files/16167923/SlothDebug.txt)

**Comment by Omnicrone** [comment]
can attest that this is happening when entering combat with any jobs with sloth combo enabled.

**Comment by greatestfall** [comment]
hi guys, just wondering are you using jobbars plugin?  right now that plugin is dealing with some issues and is causing fps drops like the ones you are describing.

**Comment by Omnicrone** [comment]
Just disabled it and it is definitely the source of the problem. Job Bars + Sloth Combo are dropping fps. Job Bars by itself or Sloth Combo by itself aren't. But the problem is most likely with Job Bars' latest update.

**Comment by Cadwgan** [comment]
Issue specifically seems to be icon replacement feature in JobBars, there may be something actively conflicting there.

**Comment by moreime** [comment]
jobbars got an update today and it definitely messed something up cus it wasnt an issue yesterday
