### ISSUE TITLE
[MCH] Wildfire

### ISSUE THREAD

**Issue by Facessco** [Nik-Potokar/XIVSlothCombo#1493]
I'm not sure if this is a bug, but I noticed that around the two-minute burst, sometimes the Sloth combo activates Hypercharge before Wildfire's cooldown is ready. After that, when Hypercharge is unavailable, the Sloth combo won't activate Wildfire again, even though the Heatguage would allow for Hypercharge or after use Barrel Stabilizer . Additionally, Hypercharge won't be used for the rest of the fight.

![image](https://github.com/Nik-Potokar/XIVSlothCombo/assets/109278703/f52c987e-6530-4aef-9def-078776489009)

**Comment by Kagekazu** [comment]
same as issue #1435

**Comment by elmigo69** [comment]
Any idea when the next update is planned?

**Comment by Kagekazu** [comment]
today~
