### ISSUE TITLE
[MCH] Plugin does not replace heated split shot

### ISSUE THREAD

**Issue by sleepylinde** [Nik-Potokar/XIVSlothCombo#1494]
Hi,

I'm using the plugin successfully on other jobs that are currently available but it's just not working on MCH for whatever reason. I have nothing in my verbose Dalamud Logs that'd point me to anything. 

[XIVSlothCombo.json](https://github.com/user-attachments/files/16174818/XIVSlothCombo.json)

Despite having simple mode or advanced mode checked heated splitshot is not changing.

https://media.discordapp.net/attachments/457492922808664066/1260899623263010920/image.png?ex=6690ffc8&is=668fae48&hm=0bd26295f1d090d4c75cd4aa6bd5ffef7127ef5e48c8ea7398403a2546f54b07&

**Comment by Kagekazu** [comment]
same as #1431

**Comment by sleepylinde** [comment]
Oh thank you!
