### ISSUE TITLE
[MCH] Adv AoE Gauss/Ricochet - None are being used during Auto Crossbow

### ISSUE THREAD

**Issue by Wild-Carrot** [Nik-Potokar/XIVSlothCombo#1495]
**Class/Job:** Machinist
**Feature:** Advanced Mode - AoE ; Gauss/Ricochet option

**Issue:** 
With Advanced Mode AoE enabled and Gauss Round / Ricochet enabled, the two oGCDs are never used during Hypercharge windows when using Auto Crossbow.

It seems to wait until Hypercharge is over, regardless of if "Use Outwith Hypercharge" is enabled or not.

It works fine with Blazing Shot / Heat Blast, just not Auto Crossbow.

**Comment by Kagekazu** [comment]
correct. will be fixed in next update.
