### ISSUE TITLE
[BRD] AoE option #10 switches Ladonsbite to Wide Volley instead of Shadowbite

### ISSUE THREAD

**Issue by ElBoufon** [Nik-Potokar/XIVSlothCombo#1499]
When activating BRD PvE option #10 Ladonsbite switches to Wide Volley instead of Shadowbite and prevents its use while under the Hawk's Eye effect.

**Comment by NebulousByte** [comment]
What level?

**Comment by ElBoufon** [comment]
Level 92 currently

**Comment by sylvainmoindron** [comment]
i've got the same bug at level 98

**Comment by meenanox** [comment]
got it happening at 100 too.
