### ISSUE TITLE
[SMN] Enkindle getting used immediately after summoning demi

### ISSUE THREAD

**Issue by Armeggadon** [Nik-Potokar/XIVSlothCombo#1503]
I'm only a 98 summoner, but when using the advanced summoner options, when summoning the demis (bahamut and phoenix, presumably also solar bahamut at 100) the button immediately becomes enkindle and will use it before searing light burst. Selecting the "Pooled oGCDs" option doesn't change this behavior, and will still use enkindle immediately after summoning rather than waiting the selected gcd count.

**Comment by NebulousByte** [comment]
What number/slider position is your Pooled oGCDs option? Seems to work fine for me with it set to 2.

**Comment by Armeggadon** [comment]
> What number/slider position is your Pooled oGCDs option? Seems to work fine for me with it set to 2.

I had it set to 3, I'll try setting it to 2 and see what happens. I tried 2 and it still swaps to enkindle immediately, but then does seem to change to searing light faster, so if you're just mashing it will still use enkindle, but I can try to just slow down when going into demi phase for now.

**Comment by NebulousByte** [comment]
I just tried 3 and it still works fine for me in the current version. I had previously reported the exact same issue pre-3.2.0.2 and tested the branch before it got pulled, but it got fixed for this most recent update. Might be silly, but can you confirm the version?

**Comment by Armeggadon** [comment]
Bah yep, looks like I was on 3.2.0.1 and didn't notice an update was available. Just updated to 3.2.0.2 and it seems to be working fine now. Should have double checked that first but that's on me, thanks for the assistance.
