### ISSUE TITLE
[DRK] Dark Knight rotation uses Shadowstride (gap closer) during burst.

### ISSUE THREAD

**Issue by ChardeeMacDennisX** [Nik-Potokar/XIVSlothCombo#1505]
DRK rotation uses Shadowstride (gap closer) during burst in the 3.2.0.2 update.

**Comment by zbee** [comment]
Shadowstride is not in the DRK code at all. Are you using another combo plugin?

If you are not: could you give an fflog link / an act log file?

**Comment by ChardeeMacDennisX** [comment]
Oops, you're right! I had another plugin enabled that was using Shadowstride on auto cast. My bad!
