### ISSUE TITLE
[PLD] + [VPR] + [all melee?]

### ISSUE THREAD

**Issue by Thork8** [Nik-Potokar/XIVSlothCombo#1506]
PLD: have a checkbox to prevent Intervene (the gap closer) being used when character is moving.

encountered couple times where right at Confiteor range combo, I tried to move out of Boss' aoe but due Intervene beeing pooled for burst, it kept dashing right back to the boss.

i dont mean the "only use when in melee" this one works fine, its more like greeding 1 last GCD before moving out and its still considered melee range, tho running out. then Intervene will launch us back into the hit box and point blank aoe.
____________________
VPR: have the odd minute reawaken be placed at the 1 minute mark, rather than right as it comes up. since this one is flexible, this could be held for potential dps gain under AST cards or other 1 minute buffs. or maybe even have a specifically checked if AST card buff is present -> go into reawaken (with checking to not drop personal buffs ofc)

VPR: Noxious Gnash debuff is falling off during double reawaken, even with Gnash timer set to maximum of 20sec.
____________________
All Melee?: additional checkbox for the opener only: to use True North before positional attacks. i notice often on VPR when im about to hit positionals, tanks would still be positioning the boss which makes positionals "sometimes" goes wild. i tend to use True North myself mostly for convinience, but could be a feature within Sloth maybe?

**Comment by Kagekazu** [comment]
for VPR : this is fixed in #1543 
All melees also have TN in their options : 
![image](https://github.com/user-attachments/assets/3f374b32-239f-43d4-8216-d4c2e2f22837)

for PLD i have no clue, best to ask @Kaeris-Tempest

**Comment by Kaeris-Tempest** [comment]
To my surprise there really is no movement check in the current advanced PLD logic (but there is on simple mode that we updated recently).

We're in the process of overhauling PLD with an entirely new revision and features, so if you could wait a little longer for that it'd be great. This is also addressed there.
