### ISSUE TITLE
[Suggestion] [VPR] True North after Dread Winder/Pit of Dread

### ISSUE THREAD

**Issue by Crosis4028** [Nik-Potokar/XIVSlothCombo#1510]
Whenever Dread Winder/Pit of Dread is used, True North is immediately used in preparation for the Twinblade combos.

OR alternatively

True North is automatically used before Dread Winder/Pit of Dread as an option

**Comment by Kagekazu** [comment]
so add it with the ogcd ones aswell, or remove the ones on the combo and just add it to dreadwinder?

**Comment by Crosis4028** [comment]
Let's change that to 2 Toggle features.

1. Use True North after Dreadwinder and Pit of Dread 
2. Save True North for Dreadwinder and Pit of Dread only

**Comment by Kagekazu** [comment]
Ill make a button like on RPR where u can say to save 1 charge for Dreadwinder, since 1 charge covers both positionals
( Also Pit of Dread is AoE and doesnt have positionals :D )

**Comment by Crosis4028** [comment]
That would be incredible. Thank you! :)
