### ISSUE TITLE
Reaper Lv 100 Opener Harpe Toggle

### ISSUE THREAD

**Issue by Totokia** [Nik-Potokar/XIVSlothCombo#1512]
Hello! Thank you for your good work!

Is it possible to have a toggle to use/not use Harpe during the Reaper lv 100 opener? If someone early pulls, we are forced to cast harpe still, losing on DPS.

Casting it manually would be the greatest!

**Comment by Kagekazu** [comment]
Harpe was added as a starter of the opener, since it copies the balance. I can see what I can do to make it a toggle, but no promises.

**Comment by Kagekazu** [comment]
So,  i looked and i can not make it into a toggle.

Or i remove the prepull completly where u have to do it manually, or it stays as is.

**Comment by Thork8** [comment]
i would rather remove it, because of the case Totokia described. If someone early Pulls or even in dungeon bosses or sync down content, people rarely if ever wait for a proper countdown. having to go through Harb cast in those situations is kinda awkward

**Comment by Kagekazu** [comment]
> i would rather remove it, because of the case Totokia described. If someone early Pulls or even in dungeon bosses or sync down content, people rarely if ever wait for a proper countdown. having to go through Harb cast in those situations is kinda awkward

i removed it.

But just an fyi, openers only works when ur lvl 100 in lvl 100 content ^.^
