### ISSUE TITLE
[AST] Simple heals doesn't work correctly on mouseover

### ISSUE THREAD

**Issue by Nuziatella** [Nik-Potokar/XIVSlothCombo#1513]
[What's Happening]
Using DelvUi and redirect with the plugin doesn't correctly cycle actions when mousing over a unit frame. Only continues to use aspected benefic unless a target is selected.

[What should happen]
Actions should cycle as dictated by the rules set in the plugin.

![screen1](https://github.com/user-attachments/assets/90c421d7-839e-44b3-8241-5df3db0f53eb)
![screen2](https://github.com/user-attachments/assets/a499246c-b70e-42f5-8d1d-a2484ccb613f)

**Comment by Taurenkey** [comment]
You will have to disable Automatic Mode in the DelvUI settings.

/delvui -> Misc -> Mouseover -> Untick Automatic Mode.

Then it'll function just like the regular game.
