### ISSUE TITLE
RPR issues

### ISSUE THREAD

**Issue by Xehanort09** [Nik-Potokar/XIVSlothCombo#1517]
Simple gets hard stuck on communio when there is no communio to cast. And advanced just flat out ignores perfectio and executioner from guillotine. Also a togglable harpe opener would be nice or removed.

**Comment by Kagekazu** [comment]
Harpe was added as a starter of the opener, since it copies the balance. I can see what I can do to make it a toggle, but no promises.

**Comment by Kagekazu** [comment]
So,  i looked and i can not make it into a toggle.

Or i remove the prepull completly where u have to do it manually, or it stays as is.
