### ISSUE TITLE
[MCH] Issue

### ISSUE THREAD

**Issue by Scjaro** [Nik-Potokar/XIVSlothCombo#1519]
![image](https://github.com/user-attachments/assets/5fb80f2a-9ef4-4cd8-bc40-5b353eda9326)
![image](https://github.com/user-attachments/assets/ad26ead4-3e52-475c-8c92-6aab345e5fe5)

**Comment by Lusaca87** [comment]
i will wrote this here too @Kagekazu:
With Level 90/91: Hypercharge will be used inside the 8 second window of AA+Drill+CS.

**Comment by Lusaca87** [comment]
With Level 90+ 

If the user want to hold 1 charge of reassemble: it will be only used on Chainsaw.

![image](https://github.com/user-attachments/assets/8ef1709f-a11b-4b31-9335-5ef669cc9ae

**Comment by Kagekazu** [comment]
not using reassmble there is fixed! for the usage i will have to rewrite how it uses reassemble, which wont be in the bugfixes :)
