### ISSUE TITLE
[BRD] core rotation issues - job not funtioning correctly

### ISSUE THREAD

**Issue by skolosk** [Nik-Potokar/XIVSlothCombo#1521]
As the title reads,  I took bard to test it in FATEs, dungeons and single target raids. It would not use offensive cooldowns 

In AoE:
- (BV/RF/RS/Barrage) - and I would have to cast them manually. 
- It does not use pitch perfect / Empyreal arrow when in WM
- It ends songs sometimes prematurely leading toa shorter 3 song cycle where it ends up songless with all songs on CD
- It uses the soul guage properly 

Single target:
- Ignores raging strikes and barrage in even minutes - I initially thought that its probably waiting to go back into WM (since its song cycle doesnt cycle properly) but it uses Radiant finale regardless, sometimes with and sometimes without battle voice - and ignores RS/Barrage
- When I manually use barrage to address this, it doesnt change the single target button to Refulgent Arrow (under barrage new buff), instead, it prioritizes checking for dots. This could maybe be due to Barrage buff being a separate buff than Hawk's eye?  

Wanted to give this feedback. Thank you for you work

**Comment by cjtylr** [comment]
Just wanted to second a couple of these issues, primarily that Pitch Perfect does not seem to be in the Simple Bard Feature at all and songs are getting clipped. Thanks!
