### ISSUE TITLE
[VPR] Reawaken issues, combo finishers issues

### ISSUE THREAD

**Issue by moreime** [Nik-Potokar/XIVSlothCombo#1527]
1. The debuff sometimes runs out before double reawaken,
2. Reawaken isn't used on even/odd minutes after 2 min+, it's usually used when the cooldown on Serpent's Ire is at 70+ seconds, which makes everything not align for later 2 minute bursts,
3. Idk if google docs links are allowed here, but ill try to post one here. After making a copy, the doc shows a 10 minute rotation that could be implemented, at 2.50s GCD, during full uptime. It loops perfectly up until then. I don't know if the devs can be bothered with changing it to this, but it would be nice.
4. There is a specific moment in rotation where it skips a Death Rattle and goes straight into Uncoiled Fury,
5. There are issues with executing some combo finishers where there is just not enough time to execute it and the time on the extra potency finisher runs out.

https://docs.google.com/spreadsheets/d/18haZwiTdqaNaKK3P6_n_i7uFp10c-cDT696owUaETPc/edit?gid=1149453378#gid=1149453378

**Comment by Kagekazu** [comment]
1. This will be solved on next update.
2. the rotation is made for current BiS, aka 2.48 sks (2.1 with SS buff )
https://etro.gg/gearset/3f906d18-f633-467b-8744-7d9fc5f087d5
I calculate when serpents ire is more than 30 GCD's off cooldown in the next update, and then it will casts reawaken for the odd burst ( so 30 *2.1 gcd) is 63 secs
3. i wont make the rotation into a static doc.
4. if u can let me know when it exactly happens i can look into it to see how i can remedy it.
5. same as above, if u can find me some examples of it happening i will gladly look at the code to remedy it.

**Comment by moreime** [comment]
4. https://github.com/user-attachments/assets/5399cd8a-d72b-4df8-9616-613aa082cd57

**Comment by Kagekazu** [comment]
should be fixed in this PR.
