### ISSUE TITLE
Is there a way to replace an ability with a mount?

### ISSUE THREAD

**Issue by rushtothesun** [Nik-Potokar/XIVSlothCombo#153]
I've tried Mount Roulette and specific mounts with the id that SimpleTweaks gives but that ID seams to be wrong.

**Comment by sauronshotdogs** [comment]
Could always give GarlandTools a try

**Comment by rushtothesun** [comment]
> Could always give GarlandTools a try

Unfortunately I haven't found the IDs on GarlandTools
