### ISSUE TITLE
[SUGGESTION] RPR - Allow Enshroud to be not enabled but Burst skills enabled in 1 button 

### ISSUE THREAD

**Issue by Crosis4028** [Nik-Potokar/XIVSlothCombo#1531]
Case Scenario

I want to be able to control WHEN I use enshroud and not include it in the single button rotation
but when I use enshroud, I want my single button rotation to use the burst skills.

TLDR, i want single button rotation, but allow me to separate when I use enshroud.

right now the burst skills are only allowed to be toggled on single button rotation if Enshroud is also included

Previous RPR version in EW allowed for this.

**Comment by Kagekazu** [comment]
u mean like this? where u can choose what to use? :P 
![image](https://github.com/user-attachments/assets/95fa3052-e5d8-4d5b-b90b-8a270d0cc040)
is in the next release
