### ISSUE TITLE
[MCH] Single Button Heat Blast Feature only works with Heat Blast and not Blazing Shot

### ISSUE THREAD

**Issue by aps-kar** [Nik-Potokar/XIVSlothCombo#1534]
As the title suggests, when enabling the Single Button Heat Blast Feature on MCH, Blazing Shot (the upgrade of Heat Blast) is not replaced with Hypercharge (when above 50 Heat Gauge ofc). Blazing Shot is a potency upgrade over Heat Blast and it isnt even possible to assign to a hotbar after getting Blazing Shot (except for macros I guess...).

![mch](https://github.com/user-attachments/assets/0aa33b45-0b33-40bc-ac67-4a30e7fbe825)

**Comment by Kagekazu** [comment]
That is correct. 

I can make it change both in my next PR, for now u can still use heatblast, it upgrades to blazing shot if u put it on ur hotbar, but internally it uses the ID of heatblast.

![image](https://github.com/user-attachments/assets/8f4ce1fb-5e2e-477e-b881-85ee6a64e129)

![image](https://github.com/user-attachments/assets/a61f0ad4-381d-4302-ae19-752e46ead2c9)

**Comment by aps-kar** [comment]
Thank you, that worked
