### ISSUE TITLE
[WAR] LVL 100 Opener issues and other suggestions.

### ISSUE THREAD

**Issue by Ytragof** [Nik-Potokar/XIVSlothCombo#1537]
First time posting here, sorry if my formatting isn't correct.

During WAR's opener segment, using all toggles. Especially the Infuriate in main combo (option 4) takes priority over the Inner Release stacks, thus making you lose one stack of Inner release and not being able to use the new follow-up option after using the three stacks during the allotted time. Could there be a way to tell it to use 1 infuriate and even if you drop to 0 gauge to not re-use the other stack of infuriate until all stacks of Inner Release have been dealt? 

It would be nice to also have the option to keep 1 stack of Infuriate when not in the big party burst window (2 minute window) like with option's 5 slider "Charges to keep ready", that way you could potentially always have 1 charge ready and use your 2 full charges during burst window while also using all the new stacks. Maybe have a way to keep track of Infuriate's cooldown and use it when it's about to cap at 2 charges and with 5 seconds or less to spare, this way it could always keep rolling or to try and keep it rolling as often as possible. (I'm not a coder or dev of any sort, I don't know how "easy" or "complicated" something like this could be to automatize, just an idea).

**Comment by Akechi-kun** [comment]
first one has been addressed & fixed in next update
second one, I added in
