### ISSUE TITLE
[PLD] LVL 100 - Goring Blade - Sometimes weird comboaction.

### ISSUE THREAD

**Issue by Lusaca87** [Nik-Potokar/XIVSlothCombo#1538]
With this segment i have sometime the problem goring blade will immediately used after FoF and not after Blade of Honor like in the Balance burst window. 

![image](https://github.com/user-attachments/assets/2bd0e6dd-5381-485a-aa08-d129777f4d0a)

timeline is from ex1 yesterday, july, 14th 2024

![image](https://github.com/user-attachments/assets/0422a796-4455-4a37-816b-7a56a9c7b2dc)
![image](https://github.com/user-attachments/assets/7864c6e1-0a5f-431f-ac3c-f0e1b16687c8)

**Comment by Lusaca87** [comment]
Additional Log actions to compare, because imperator will not be shown in xivanalysis

![image](https://github.com/user-attachments/assets/89210f58-cbad-426e-bb94-53b37daff125)

**Comment by Kaeris-Tempest** [comment]
I cannot replicate this behavior on my end. You said it only happens sometimes?
It could be an action queue problem. How fast are you spamming the combo button?
Try disabling the Action Change Settings for Fight or Flight so it doesn't automatically turn into Goring Blade.

**Comment by Lusaca87** [comment]
Ok. Maybe it has something to do with it. will give it a try, Thank you

**Comment by Lusaca87** [comment]
Issue found with my client/connection. without automatic action change it worked as intendet
