### ISSUE TITLE
[NIN] Ten Chi Jin

### ISSUE THREAD

**Issue by griminir** [Nik-Potokar/XIVSlothCombo#154]
is it possible to make
ten chi jin have a toggle option well that cast
ten chi jin

ten chi jin -> ten -> chi -> jin -> meisui when suiton is up

**Comment by Iaotle** [comment]
In the future please use normal titles instead of minimum effort, makes it a bit easier to look at.

**Comment by griminir** [comment]
to be fair it was my first ever post and i did not know better

**Comment by Iaotle** [comment]
in order to make an issue you unavoidably have to look at other issues. copying the title style shouldn't be that hard
