### ISSUE TITLE
[VPR] Attack actions disabled when Noxious Gnash abilities are not learned yet

### ISSUE THREAD

**Issue by NikaLeets** [Nik-Potokar/XIVSlothCombo#1540]
This issue affects at least Simple mode Single Target, Advanced Mode Single Target, and Advanced Mode AoE, but based on what I've seen, i'm pretty sure Simple Mode -AoE will be impacted as well.

This issue is when Dread Fangs is not known yet (character level < 10) or Dread Maw is not learned (character level < 35), a disabled Dread Fangs/Dread Maw is offered instead of Steel Fangs/Steel Maw.  This makes these features completely non-functional < lvl 10 for single target and < lvl 35 for AoE.  In the advanced modes, you can work around the issue by removing the Noxious Gnash check in both advanced modes, but it is always present in simple mode.

This is problematic in PotD solo runs while in the first 2 PotD floor sets.

**Comment by Kagekazu** [comment]
![image](https://github.com/user-attachments/assets/897f1fe5-4426-47bc-9335-cf95f3061432)
what are u talking about?

I am in PoTD floor 1, and it just spams steel fang.

Are u sure u are on the current version of 3.2.0.2?

**Comment by Kagekazu** [comment]
just did the first 5 floors of PotTD

1-5 it spams steelfang
5-10 it does steelfang - hunters sting
10+ it incorporates Dreadfang.

can u show a screenshot of ur Repor URL? so that we make sure ur on the correct Sloth version.

**Comment by NikaLeets** [comment]
I will verify and show screenshots as soon as Dalamud re-enables after the patch.

**Comment by Kagekazu** [comment]
current version of sloth is 3.2.0.2.
![image](https://github.com/user-attachments/assets/10359de9-75b6-435b-befd-a08fbdaf7cc2)

please update and see if it happens again.

**Comment by Kagekazu** [comment]
> That was quick. Dalamud is back up. I was running Sloth version 3.2.0.1. I just confirmed that this issue was present on 3.2.0.1, but is fixed on 3.2.0.2. Thanks!

alrighty, no problem! if anything still is weird lemme know and ill see to add it to my bugfixes
