### ISSUE TITLE
[DRG] Life Surge Suggestion 

### ISSUE THREAD

**Issue by Beanslash** [Nik-Potokar/XIVSlothCombo#1545]
Currently Life Surge is used off CD when either Heavens Thrust or Drakesbane is the next GCD. Suggesting to adjust the logic for that to take into account Lance Charge CD. For example holding off on using a Life Surge charge if Lance Charge is coming off CD within an x amount of time.

**Comment by Akechi-kun** [comment]
added Life Surge optimal use (1 in LC, 2 in BL)
