### ISSUE TITLE
RPR Advanced rotation issues

### ISSUE THREAD

**Issue by DaIslandGames** [Nik-Potokar/XIVSlothCombo#1551]
A few issues i have noticed: sometimes for reasons i cant deduce during burst it will get stuck on a button it cant press and you have to finish the burst manually for it to re hook and continue on single button.

Also i have noticed at some time intervals that it forgets about Perfectio and wont use it in rotation for some reason causing it to sometimes drop off.

and another small issue on prepull harpes after dashing into range it wants to make you cast harpe again before applying SOD (admittedly idk if this is a potency loss or not but it seemed odd)

Edit: there also seems to be an issue with it overwriting stacks of Executioner by performing a non positional action instead of the executioner effects causing the stacks to drop. 

so far the rest looks ok! though
IG Setting:
![image](https://github.com/user-attachments/assets/c438c3ce-f0c9-4b19-b377-8c80053c5b73)
![image](https://github.com/user-attachments/assets/a644c915-722f-4a04-b31a-afd7c8d85b32)
![image](https://github.com/user-attachments/assets/4667294a-bac9-4aa6-bc71-6063c350adeb)

**Comment by Kagekazu** [comment]
same as #1515 

fixed in #1532

**Comment by DaIslandGames** [comment]
i shall double check that my version is updated then! also made a change edit to add the gluttony executioner stack issue

**Comment by DaIslandGames** [comment]
> same as #1515
> 
> fixed in #1532

so i disabled, uninstalled, and reinstalled the plugin, still giving me the same issues. is there something i have to to do push the fix from dalamud?

**Comment by Kagekazu** [comment]
no

> > same as #1515
> > fixed in #1532
> 
> so i disabled, uninstalled, and reinstalled the plugin, still giving me the same issues. is there something i have to to do push the fix from dalamud?

no, it will be fixed in next Sloth update. as the PR is still open.

![image](https://github.com/user-attachments/assets/2ec0d5d7-05aa-47a8-b940-06d24bebc8bc)

**Comment by DaIslandGames** [comment]
ahhhhh gotcha gotcha thanks!
