### ISSUE TITLE
[MCH] When using Simple Mode, Wildfire won't fire off sometimes

### ISSUE THREAD

**Issue by fesTo88** [Nik-Potokar/XIVSlothCombo#1552]
After using Barrel Stabilizer, if Wildfire is still on cooldown it'll use Hypercharge and not use Wildfire until you get the free Hypercharge from Barrel Stabilizer again in 2 minutes. I saw this typically only happening with the Wildfire after the opening one.

In my testing, I also saw that it wouldn't use any heat gauge at all if Wildfire wasn't on cooldown, even when sitting at 100 gauge. And when doing the rotation long enough, it would use Barrel Stabilizer but would never use Full Metal Machinist or the free Hypercharge.

I don't know if skill speed is affecting things at all, I'm not melding for it and my GCD is only 2.46 but I thought maybe, so I figured I'd mention it.

**Comment by Kagekazu** [comment]
Same as #1504

**Comment by Kagekazu** [comment]
fixed with merge of #1533 
Can be closed
