### ISSUE TITLE
[RPR] #53: Add Perfectio support to "Shroud -> Communio"

### ISSUE THREAD

**Issue by t-l13** [Nik-Potokar/XIVSlothCombo#1554]
Setting 53 pages Enshroud to Communio while you are Enshrouded. However, when you meet the conditions for Communio to be paged to Perfectio in-game, it doesn't work on this button. Casting Communio causes the button to revert to Enshroud, meaning you still need a dedicated button for Communio in order for you to cast Perfectio.

It would be nice if Enshroud would also page to Perfectio when available.

**Comment by Kagekazu** [comment]
is included in the bugfixes PR.
So will be there in next sloth update.
