### ISSUE TITLE
GNB Having Continuation on Blood Fest

### ISSUE THREAD

**Issue by Yumeji** [Nik-Potokar/XIVSlothCombo#1555]
I prefer weaving on a secondary slot than the main hotkey, and I like having Blood Fest on a separate hotkey too. So it just makes sense to me having Blood Fest be replaced by Continuation whenever it's activated. I hope you'll consider it

**Comment by Akechi-kun** [comment]
Sorry man, but this is almost like a special request. I won't be able to add it in unless it's almost highly suggested, and you're the only one suggesting this kind of addition. Maybe if more people want this, I will add it.. but for now I will leave this out.

_This issue can now be closed._
