### ISSUE TITLE
[RPR] Gibbet/Gallows on Blood Stalk doesn't work

### ISSUE THREAD

**Issue by atodd612** [Nik-Potokar/XIVSlothCombo#1556]
Turning on the Gibbet/Gallows on Blood Stalk feature under Gluttony on Blood Stalk/Grim Swathe doesn't work. Using Blood Stalk/Gluttony will not change it into either option, instead requiring you to use one manually before it begins functioning correctly the next time you use Blood Stalk/Gluttony. I imagine this is because it looks for the empowered buff and shows the corresponding skill.

**Comment by atodd612** [comment]
I've also noticed putting the Enshroud combo option on also doesn't use Lemure's Slice or Communio.

**Comment by Kagekazu** [comment]
fixed in next sloth update.

fixed in PR #1532
