### ISSUE TITLE
[BRD] #1 Heavy Shot into Straight Shot Feature & #9 Aoe Combo Feature

### ISSUE THREAD

**Issue by Nyarshog** [Nik-Potokar/XIVSlothCombo#1558]
Henlo,

I just came across some bugs involving BRD features **1: Heavy Shot into Straight Shot Feature** and **9: Aoe Combo Feature**.

Both are supposed to replace the single/multi target fillers with their "procs" while under _Hawk's Eye_.  On the single target one, it still works like a charm. The aoe one on the other hand, tries to replace the filler with the lv25 version of the spell (Which is a version of the spell that came with Dawntrail that didn't exist in Endwalker).

You can see in the image below while under the effect of _Hawk's Eye_ :
 - 2 = _Burst shot_ gets correctly changed into _Refulgent Arrow_
 - 3 = Tries to use the lv25 version _Wide Volley_
 - 4 = _Shadowbite_ that I manually added
![image](https://github.com/user-attachments/assets/b0bdb24f-566b-411c-9675-8aa155c1b0cc)

I tried to actually press the lv25 spell tho (The idea came to me while writing this post), it actually "works", as in "It shows lv25 spell, but still uses the corect version" (And doesn't seem to be a problem on **11: Simple AoE Bard Feature**, it shows the correct spell)

Another issue that affects both features, is the new version of _Barrage_, who now grants a free use of _Refulgent Arrow_/_Shadowbite_ on top of _Hawk's Eye_ proc. Basically if I just press _Barrage_ without forcing the proc, both combos just ignore the _Barrage_ buff.

That's pretty much it, thanks a lot for your work o/

**Comment by Dajova** [comment]
To add to this, i'm not sure if it's just me, but the AoE Combo feature (#10) option disables itself on each restart. Only that tho, not the other options. I enable it, relog and its disabled again, for no reason.
