### ISSUE TITLE
[PLD suggestion] Holy spirit prepull toggle

### ISSUE THREAD

**Issue by leahminka** [Nik-Potokar/XIVSlothCombo#1559]
in EW PLD had a toggle to turn your gcd combo into holy spirit out of battle, to my knowledge a prepull HS is still the optimal way to pull, so it would be nice if this feature could be readded, ty :)

**Comment by Kaeris-Tempest** [comment]
This functionality is added in the upcoming full-feature rework https://github.com/Nik-Potokar/XIVSlothCombo/pull/1544

However it is not specifically tied to being out of combat. The new Shield Lob option can be configured to hardcast Holy Spirit so long as you are not moving. Of course this restriction is lifted when under Divine Might.
