### ISSUE TITLE
[BRD] Apex Arrow Toggle Option

### ISSUE THREAD

**Issue by DurzoThorn** [Nik-Potokar/XIVSlothCombo#156]
I was curious if someone might be able to tweak the simple bard one button combo feature to not include Apex Arrow by default and just add a toggle button to add it back if people don't want to optimize dps. As it stands not being able to hold Apex Arrow for the 2 min burst window is the only big issue I see with the one button feature. The only other tweak that I can think of that might be way harder to implement is some logic that starts pooling bloodletter charges using 1 if you hit 3 midway through army's paeon so in the buff phase you get to spam them for big dps. Just want to say thank you all for the amazing work on all the jobs this addon makes playing the game an absolute blast.

**Comment by Nik-Potokar** [comment]
Was added
