### ISSUE TITLE
[AST] Using both Lightspeeds in dps opener/rotation 

### ISSUE THREAD

**Issue by Meiby23** [Nik-Potokar/XIVSlothCombo#1562]
Hello, when using the dps opener/rotation for Ast it weaves both light speeds at once. Is it possible to make an option to delay one? Or stop it from doing it as a whole?

**Comment by Kagekazu** [comment]
AST hasnt been updating since they made the patch. It will be so it uses only 1.

**Comment by Meiby23** [comment]
ok thank you !

**Comment by zbee** [comment]
Fixed in a574a25, pending release: should be closed.

**Comment by Meiby23** [comment]
Thank you!
