### ISSUE TITLE
Global Melee DPS Request: Bloodbath and Second Wind

### ISSUE THREAD

**Issue by Scythewind** [Nik-Potokar/XIVSlothCombo#1565]
Would it be possible to add a feature under Global Melee DPS Features that allows the use of Bloodbath and Second Wind at specified HP percentages as part of the rotation?  It may not be possible globally; it will probably need to be Job-specific.

**Comment by thomas-henley** [comment]
Looks like advanced mode already has this -- is there a particular job or use case you were having a problem with?
![image](https://github.com/user-attachments/assets/f49def1f-f616-4919-8b13-8a380fe4ae74)

**Comment by Kagekazu** [comment]
Every job that has second wind or bloodbath has this option.

**Comment by Scythewind** [comment]
I must have overlooked it, apologies!  FWIW, I was on Viper when I was looking.  Sorry for the trouble!
