### ISSUE TITLE
GNB: Reign combo on Main Combo Option / Burst Strike to Bloodfest Feature Problems

### ISSUE THREAD

**Issue by Rubyurek** [Nik-Potokar/XIVSlothCombo#1570]
Unfortunately, both functions have a major problem: In the No Mercy Phase, the 3-piece combo is not displayed when activating Bloodfest. Neither with the Main Combo nor with the Burst Strike. 

Scenario 1: I connect Reign to the main combo and when activating Bloodfest it is not displayed in the main combo.

Scenario 2: Combining Burst Strike with Bloodfest is a good idea, but unfortunately poorly implemented, as you are not transferred to the Reign combo after spending the cartridges if you have no more cartridges for Burst Strike.

**Comment by Akechi-kun** [comment]
> stupidly implemented

Hey man, if you feel you can do a better job, you're more than welcome to do it yourself & submit a PR.  **Poorly implemented** would be a better choice of words. It's cringe when someone is at least _trying_ to update/fix a job & you just call their work stupid. 

GNB got reworked so next update will fix your issues (unless you're using SkS then _good luck_)

**Comment by Rubyurek** [comment]
> > stupidly implemented
> 
> Hey man, if you feel you can do a better job, you're more than welcome to do it yourself & submit a PR. **Poorly implemented** would be a better choice of words. It's cringe when someone is at least _trying_ to update/fix a job & you just call their work stupid.
> 
> GNB got reworked so next update will fix your issues (unless you're using SkS then _good luck_)

Oh, I'm really sorry. I didn't mean it like that at all. I use the translation program Deepl to write texts like that. I'm really sorry that this word slipped in.

**Comment by Akechi-kun** [comment]
No worries. 
Currently the live version is riddled with bugs & obsolette options from Endwalker (such as #2 not having Reign). 
Next update is coming jampacked with QoL, fixes, adjustments, & even some reworks.

**Comment by Rubyurek** [comment]
I'm sorry but I have to open this again. I have tested this now and I have noticed that "burst strike" does not switch to the reign combo mode after activating "Bloodfest", but only wants to burn the cartridges with "Brust Strike + Hypervelocity" but it does not come into the reign combo at all. 

https://github.com/user-attachments/assets/b58f3ec9-bf78-446d-b1df-00f1aed6ca80
