### ISSUE TITLE
[RDM] New DT Opener

### ISSUE THREAD

**Issue by ExoLeviticos** [Nik-Potokar/XIVSlothCombo#1572]
![rdm opener](https://github.com/user-attachments/assets/6e168bb6-063a-4dea-af9e-b8675817fe8a)

Currently the opener for RDM is still the EW combo. There are new openers that take Grand Impact into consideration, and change the buff windows a bit. 

Can we expect an update on the new openers?

**Comment by Tartarga** [comment]
Eventually. Currently getting RDM in a good Dawntrail state before looking at an opener
