### ISSUE TITLE
[SCH] Energy Drain not consuming stacks of Aetherflow on sub 66 content

### ISSUE THREAD

**Issue by Miyulta** [Nik-Potokar/XIVSlothCombo#1573]
Title, with the "Energy Drain Burst Option" on, Energy Drain will NOT consume Aetherflow stacks unless Chain Stratagem its unlocked, tested on a 50, 61 and 67 dungeons

**Comment by Tartarga** [comment]
"Energy Drain Burst Option"
"Holds Energy Drain when Chain Stratagem is ready or has less than 10 seconds cooldown remaining."

I mean, it sounds like it's working as intended. With it off it'll burn aetherflows as normal unless I'm missing something

**Comment by Miyulta** [comment]
Yes, it blocks the consumption of aetherflow when synced below 66

**Comment by zbee** [comment]
Fixed in a574a25, pending release: should be closed.

**Comment by Tartarga** [comment]
Fixed in a574a25
