### ISSUE TITLE
[BLM] New DT Opener and rotation

### ISSUE THREAD

**Issue by Zikahzi** [Nik-Potokar/XIVSlothCombo#1574]
![image](https://github.com/user-attachments/assets/37d22cce-cf3f-4b66-9a74-ccb01ae2cc79)
![image](https://github.com/user-attachments/assets/4abfb93d-7426-44fa-a185-f08522fbbc9b)
![image](https://github.com/user-attachments/assets/1e604f45-33cc-412e-aab9-6d69ad9b302e)

**Comment by Tartarga** [comment]
BLM is being rewritten
