### ISSUE TITLE
[DRG] Rotation incorrect below level 50

### ISSUE THREAD

**Issue by NikaLeets** [Nik-Potokar/XIVSlothCombo#1578]
There are a number of defects in the rotation present below level 50.  This is all observed on Sloth version 3.2.0.2.  

1) Below level 4, after true thrust is used, Vorpal Thrust is offered but not learned yet and breaks to rotation entirely.  Replicate in PotD floor set 1-10
2) Between level 18 and 26, once Disembowel is learned, Vorpal Thrust is never offered again and the rotation is just True Thrust->Disembowel
3) Between level 26 and 50, Full Thrust is never offered.  (I suspect this is the same defect at #2, the issue is that vorpal thrust is never offered between lvl 18 and 50.  Reproducible on PotD floor sets 11-20.
4) Life surge is never offered below Lvl 26 (This one really isn't a big deal though)

Here is my advanced mode single target configuration:
![image](https://github.com/user-attachments/assets/c3ace530-2955-4da4-8982-f3759a9fa4af)

**Comment by Kagekazu** [comment]
Sloth is at version 3.2.0.3.

And there has been some DRG fixes for lower lvls
#1553 
![image](https://github.com/user-attachments/assets/9fee0201-d984-42f3-ada3-61707e3fcbef)

**Comment by Akechi-kun** [comment]
Welp, my PR _should_ have fixed it but I guess it didn't. Gonna recheck this and figure out why it's not working again.

**Comment by Kagekazu** [comment]
> Welp, my PR _should_ have fixed it but I guess it didn't. Gonna recheck this and figure out why it's not working again.

They are checking with the version BEFORE ur PR. So they need to update first before i check anything else.

**Comment by NikaLeets** [comment]
Reproduced this and the other issues on 3.2.0.3.  Here is a URL to video.  Am I doing something wrong?

https://drive.google.com/file/d/12N3nf6vG56Wchw-HgIrretOdwv6jA3tU/view?usp=sharing

**Comment by NikaLeets** [comment]
And here is video showing the missing Vorpal Thrust offer at both lvl 25 and lvl 26 after Full Thrust is learned.  At the end, it also shows how if you manually fire Vorpal Thrust at the correct time, then Full Thrust is indeed offered, so I think the issue is isolated to Vorpal Thrust not being offered after Disembowel is learned but Chaos Thrust is not learned yet.

https://drive.google.com/file/d/1UhsK5yE2U69sexDh3QOS924ir2SZbOj8/view?usp=sharing

**Comment by Akechi-kun** [comment]
> Am I doing something wrong?
Nah the fix probably just didn't work. I'll do some tinkering.

**Comment by Kagekazu** [comment]
> And here is video showing the missing Vorpal Thrust offer at both lvl 25 and lvl 26 after Full Thrust is learned. At the end, it also shows how if you manually fire Vorpal Thrust at the correct time, then Full Thrust is indeed offered, so I think the issue is isolated to Vorpal Thrust not being offered after Disembowel is learned but Chaos Thrust is not learned yet.
> 
> https://drive.google.com/file/d/1UhsK5yE2U69sexDh3QOS924ir2SZbOj8/view?usp=sharing

fixed in PR #1587

**Comment by Kagekazu** [comment]
1-4 is fixed to not show Vorpal Thrust anymore
18 - 50 stopped the disembowel loop for when u havent learned chaos thrust yet
