### ISSUE TITLE
[DRG] LVL 60 single target rotation incomplete

### ISSUE THREAD

**Issue by NikaLeets** [Nik-Potokar/XIVSlothCombo#1579]
At LVL 60, Fang and Claw, Wheeling Thrust, and Geirskogul are never offered in the rotation.  This is not just a lvl 60 issue, but it present from when those respective abilities are learned, up to level 60.  Reproducible on PotD floors 51-60 most easily.

Issue present on Sloth version 3.2.0.2, same single target configuration as the previous issue:
![image](https://github.com/user-attachments/assets/5ebaea88-54a7-4a69-a62f-cfa2ab3b4f99)

**Comment by Kagekazu** [comment]
it does cast em for me.

Can u update to the latest version and see if they still dont go off?

**Comment by NikaLeets** [comment]
Kindly scan forward to 0:30 in the video here:

https://drive.google.com/file/d/12N3nf6vG56Wchw-HgIrretOdwv6jA3tU/view?usp=sharing

This is on 3.2.0.3 and Geirskogul, Wheeling Thrust, and Fang and Claw don't swap in over True Thrust for me.

**Comment by Kagekazu** [comment]
Taken on floor 51-60 of PoTD so, as a lvl 60.

https://github.com/user-attachments/assets/8dee2c18-6321-4537-a0a9-71ba05d49e36

**Comment by NikaLeets** [comment]
So... I don't understand what's going on with me...  I just pulled to 3.2.0.4 and I am seeing the same behavior as 3.2.0.3.  I've also tried your suggestion of disabling and re enabling the feature and i've tried reslotting true trust as well.  For me, even single target simple mode doesn't offer  Geirskogul, Wheeling Thrust, and Fang and Claw.  I guess i'll try deleting sloth from dalamud entirely and installing from scratch.

**Comment by Akechi-kun** [comment]
v3.2.0.4 was an immediate update to fix any changes around 7.05, most notably VPR.
The other changes are still yet to come to live.

**Comment by NikaLeets** [comment]
Ok, fair enough.  Also, I tried deleting sloth in dalamud and reinstalling and I noticed that it preserved all my previous settings, so I don't think removing in dalamud is a "clean" install.  Is there a better method to do purge all state information for the plugin in case my installation is maybe corrupted?

**Comment by NikaLeets** [comment]
Confirmed that this is fixed after completing class quests, so operator error on this one.
