### ISSUE TITLE
[WAR] StormsPathComboFeature dont work.

### ISSUE THREAD

**Issue by Astelteyn** [Nik-Potokar/XIVSlothCombo#158]
StormsPathComboFeature dont work. 
Not replace FellCleave.
And need replace FellCleave when gauge 50 and more. (gauge =50 OR >50)

**Comment by Nik-Potokar** [comment]
Those are PVP combos 
![image](https://user-images.githubusercontent.com/76532587/150635521-aa7c9880-5b7c-4bd1-a8d0-1b463dec3dfa.png)
if you have this enabled all of the combos with the "Star" are pvp combos
![image](https://user-images.githubusercontent.com/76532587/150635544-5580c971-fb8c-463c-92bc-0a4930c7da3c.png)

**Comment by Astelteyn** [comment]
Oh, really. Off it and FellCleave/Decimate Option now work correctly. 
Tsx!)

**Comment by Astelteyn** [comment]
My bad. Ty for help)
