### ISSUE TITLE
[DRG] Single Target abilities offered on Doom Spike

### ISSUE THREAD

**Issue by NikaLeets** [Nik-Potokar/XIVSlothCombo#1581]
This may be by design, but if it is, it is extremely problematic in PotD, and very dangerous and life threatening.  Doom spike is not offered in AoE situations of your character does not have the power surge buff.  Additionally, after LVL 50, after Disembowel, Sloth offers Chaos Thrust instead of Doom Spike.  Once the Power Surge buff wears off, it forces the True Thrust->Disembowel->Chaos Thrust combo before returning to doom spike spam.  

If this is by design, PLEASE add an option to disable this functionality.  This is the rationale for PotD solo runs:
Due to the line nature of doom spike, ideal positioning is generally to have your targeted mob to be as far as possible from the pack of mobs you are AOEing.  This means that when Power Surge wears off and single target abilities are offered, you are generally out of range of the mob you are targeting, and have to do a quick target switch.

Additionally, due to PotD mechanics if you are doing a large AoE pull with witching, Power Surge will generally fall off right as pomander of witching expires.  This puts your character in an extremely dangerous situation with many enemy mobs at low life and you are locked into 3 GCDs of single target actions before you can AoE again to finish the pack.  If you are not careful, this could easily result in death on a pull that would otherwise be safe.

Additionally, Geirskogul doesn't appear to be working on Doom Spike either, but I suspect that is the same issue as the other defect with the single target rotation.

Here is my Advanced AOE configuration:
![image](https://github.com/user-attachments/assets/1f7ec270-cee8-43af-8ae5-f979ea77c7bd)

**Comment by Kagekazu** [comment]
this is intentional as ppl were complaining that they didnt have the dmg buff from ST while using AoE in between Doom Spike and learning Sonic Thrust.

I will add an option for this. but just a reminder that the plugin isnt perfectly made to be used on solo potd runs ( it doesnt check any of the PoTD debuffs for example, nor will it be added in the future for now )

**Comment by NikaLeets** [comment]
The option is working well.  Thanks!
