### ISSUE TITLE
[VPR] Dreadwinder Combo failing during opener

### ISSUE THREAD

**Issue by Crosis4028** [Nik-Potokar/XIVSlothCombo#1582]
![3](https://github.com/user-attachments/assets/abb7740c-b091-4efa-a2e2-5a127b704d0f)
![2](https://github.com/user-attachments/assets/6353970b-c457-4200-b113-b5313ee62c31)

Current Settings Used above

Issue: When I try to do the opener with the settings above, after pressing DREADWINDER MANUALLY, Steelfangs doesn't turn into the Dreadwinder combo. It goes into the next NORMAL COMBO 3 sequence action for some weird reason.

I have been able to replicate this during a re-opener, and also during 2 minute burst if I try to follow the sequence

Combo button 1 --> Serpent's Ire --> Combo button 2 --> Dreadwinder --> THIS PART BREAKS

**Comment by Kagekazu** [comment]
Those are AoE settings.
Can u look at ST settings and see if u forgot something there?

**Comment by Crosis4028** [comment]
updated with ST settings

**Comment by Kagekazu** [comment]
yeah, it looks that it doesnt have the "Ready To Reawaken' buff before it will allow dreadwinder.
Is there any reason why u want to do the opener manually?

**Comment by Crosis4028** [comment]
i want to be able to modify the opener for endgame. Was working perfectly before this update though. *headscratch*

**Comment by Kagekazu** [comment]
Before this update there was an issue with the 2 min burst, to fix all that i had to make some adaptations so it prioritizes Reawaken above the GCD's. Where dreadwinder is unfortunatly falling short now.

Out of curiosity, what part of the opener isnt working on the endgame? Since it is designed to work for endgame especially. Except for ultimates.

I can look into finding a fix for this issue, AFTER all classes are back up and running.

**Comment by Crosis4028** [comment]
hmm say i want to move dreadwinder earlier or later during ultimate phases that are really short would be the only use case i have at the moment. 

i'm fine with it being looked at much later on, i can always do the opener fully manually in spite of the issue 

the dynamic true north and its sub option does not seems to be malfunctioning for dreadwinder though. 

SHould that be opened as a separate issue

**Comment by Kagekazu** [comment]
ill have a look at both at the same time ^.^ ( Also the dreadwinder option works only when dreadwinder is in the one button rotation, since it does TN BEFORE dreadwinder is cast )

**Comment by Crosis4028** [comment]
OOOOOHHHHHHHHH ok ok ok got it. I was hoping for it to be used right after dreadwinder is cast. hahaha okay il wait for that then

**Comment by Kagekazu** [comment]
i can see to swap it around, but had ppl complaining about it then, so i swapped to before :P

**Comment by Crosis4028** [comment]
What was the complaint about TN after dreadwinder? i am curious to know the logic haha
