### ISSUE TITLE
[DNC] Save 4 feathers for 2 min Burst

### ISSUE THREAD

**Issue by program-ui** [Nik-Potokar/XIVSlothCombo#1584]
Currently, it uses 1 feather right away when you have 4 feathers which means you can only carry 3 feathers most of the time into your 2 min burst.

My suggestion is to only use 1 feather when you have 4 feathers + reverse cascade and fountainfall proc. This will ensure you have 4 feathers for burst.

**Comment by zbee** [comment]
Will look to have this in the next update.
