### ISSUE TITLE
[DNC] Priority for GCDs during 2 min bursts leading to overcapping of esprit

### ISSUE THREAD

**Issue by program-ui** [Nik-Potokar/XIVSlothCombo#1586]
I am using Simple Dancer (Single Target) Feature.

I believe the priority for GCDs during 2 min bursts currently are as follows:

1. Finishing Move (whenever cooldown is up)
2. Last Dance
3. Saber Dance if >80 esprit
4. Starfall Dance
5. Tillana
6. Saber Dance

So imagine if you have 75 esprit after using Last Dance + Finishing Move + Starfall Dance, your next priority GCD would be Tillana which means you will lose 25 esprit (75+50 = 125 but you can only hold 100 max). This priority will easily lead to overcapping since Tillana should not be used at 50 esprit or above.

My proposed GCD priority:

1. Finishing Move (whenever cooldown is up)
2. Last Dance
3. Saber Dance if >=50 esprit
4. Tillana
5. Starfall Dance

This will ensure that Tillana will not overcap esprit. Or if you can set a condition that only allows Tillana to be used at below 50 esprit that would be great.

**Comment by zbee** [comment]
Will fix this for the next update.
