### ISSUE TITLE
[VPR] Uncoiled Twinfang and Uncoiled Twinblood not firing off when getting back into melee range

### ISSUE THREAD

**Issue by daijo-bu** [Nik-Potokar/XIVSlothCombo#1588]
When the ranged uptime option is checked and uncoiled fury is checked as well in the Advanced Single Target rotation, Uncoiled Twinfang and Uncoiled Twinblood can be missed in the rotation when you move back into melee range. It should always fire off Uncoiled Twinfang and Uncoiled Twinblood when Uncoiled Fury has been cast even when as you are moving back into melee range.

**Comment by Kagekazu** [comment]
Found the issue,

will be fixed in the PR.
