### ISSUE TITLE
[WAR] Nascent Chaos bug

### ISSUE THREAD

**Issue by atodd612** [Nik-Potokar/XIVSlothCombo#1591]
I'm playing a level 74 WAR right now, and whenever I use infuriate and then Fell Cleave, it remains stuck on Fell Cleave until the Nascent Chaos buff is either removed or falls off. The rotation continues normally if I just use Chaotic Cyclone instead.

**Comment by Akechi-kun** [comment]
Interesting, I just fixed an issue regarding this but now it’s getting stuck on Fell Cleave instead of Decimate. I’ll look into this.
