### ISSUE TITLE
[VPR] Double reawaken instantly after Serpent's Ire

### ISSUE THREAD

**Issue by moreime** [Nik-Potokar/XIVSlothCombo#1593]
Double Reawaken procs instantly after using Serpent's Ire instead of after one combo gcd, causing it to miss damage in buff windows because it starts the sequence way too early.

![viperstandarddoublereawakenv3](https://github.com/user-attachments/assets/f82e8a41-c7a2-46a0-8e78-81391521b9a3)

**Comment by Kagekazu** [comment]
it doesnt use that one..

**Comment by Kagekazu** [comment]
![image](https://github.com/user-attachments/assets/a16cec7e-3307-43d3-ae5c-37afe19e89d9)

This is the one programmed in

**Comment by moreime** [comment]
pain and suffering gg </3

**Comment by Kagekazu** [comment]
scuze you? As long as ouroboros is in party buffs its fine.
And otherwise u can always manually delay it a GCD.
