### ISSUE TITLE
GNB - Locking on Double Down

### ISSUE THREAD

**Issue by Chipmunkaroo** [Nik-Potokar/XIVSlothCombo#1595]
Locking up on Double Down. Attempting to use when there are only 0 or 1 cartridge. This has happened a few times mostly in open world content going randomly between mobs. Image the 1 keybind is Sloth. Using advanced with all options checked.

![image](https://github.com/user-attachments/assets/9f6e997c-3816-496e-b82b-2c765ca0d070)

**Comment by Chipmunkaroo** [comment]
Seems to lock up when starting a fresh combo opener with Keen Edge with 1 cartridge.

**Comment by Akechi-kun** [comment]
Known issue, currently fixing
