### ISSUE TITLE
[RPR] Enshroud condition dropping Sloth function

### ISSUE THREAD

**Issue by Clapper12** [Nik-Potokar/XIVSlothCombo#1596]
As of the last update noticed during 2nd Raid boss that the 4th enshroud triggered and then character no longer performed simple rotation; not even deaths design. Ability to combo returned once 4th Enshroud concluded; Replicated multiple times during 3rd raid boss around battle transition.

Also note during Tender Valley Simple AOE function appeared to malfunction; attempting to serve up Guillotine despite lacking the needed chain buff to perform Guillotine (the AOE version of Gibbet/Gallows) resulting in a malfunction of AOE function.

**Comment by Kagekazu** [comment]
Fixed next PR
