### ISSUE TITLE
(MCH) Reassemble is not working after the opener

### ISSUE THREAD

**Issue by MerpyDerp** [Nik-Potokar/XIVSlothCombo#1597]
![image_2024-07-24_012132007](https://github.com/user-attachments/assets/9cb491d3-dd3d-47e8-b1a3-0b5874995df2)

After MCH opener it will just stop using Reassemble ,and there's no way to trigger it back again until i enter a new combat This is happening in Simple single target, and advanced single target mode

**Comment by Kagekazu** [comment]
Untick and recheck ur options.
