### ISSUE TITLE
(MCH) hypercharge, wildfire and FMF being held even at 100 heat

### ISSUE THREAD

**Issue by davechopz** [Nik-Potokar/XIVSlothCombo#1598]
im having a weird issue with MCH still. im getting to 100 heat with both hypercharge, wildfire and full metal field up. the buff from barrel stabilizer ticks from start to end and never uses FMF. not sure whats happening

**Comment by Kagekazu** [comment]
Do u have noclippy? 
U need to be able to doubleweave for lvl 100 mch to work properly.

I also am adding a more lenient check in when it will be used.

**Comment by davechopz** [comment]
> Do u have noclippy? U need to be able to doubleweave for lvl 100 mch to work properly.
> 
> I also am adding a more lenient check in when it will be used.

yeah i run xivalexander
