### ISSUE TITLE
[MCH] (Heated) Shot Combo isn't properly switching skills

### ISSUE THREAD

**Issue by ask-42** [Nik-Potokar/XIVSlothCombo#160]
I have Heated Clean Shot on my bar, but its not swapping it to split/slug shot properly anymore. I haven't enabled any MCH features besides the ones in this screenshot. I've tried swapping classes and re-adding it to my hotbar.

![image](https://user-images.githubusercontent.com/47505079/150649431-b085fd81-a010-4fa3-aadd-55a11a2900c2.png)

**Comment by Toora** [comment]
I'm having the same issue. Have tried dragging all the variants onto my bar, with no luck. It does add other options onto the button though like Drill or Gauss if you have those enabled, just doesn't continue the main combo itself.

**Comment by Nik-Potokar** [comment]
Quick fix inc
