### ISSUE TITLE
[RPR] SoD not refreshing and weird SoD in Enshrouded unless Arcane is activated or on CD

### ISSUE THREAD

**Issue by IllusionMan** [Nik-Potokar/XIVSlothCombo#1601]
At first it starts with SoD and once it runs out the combo doesn't include gluttony on that, keeps on slice combo. Then I use manually SoD and combo starts over normally but when I use Enshrouded and you can see it adding SoD as first attack, then I use 1 attack and it add SoD again and never change skill, only when I manually use the next combo skill...but everything works fine once I activate Arcane, but when it runs off, everything back to not working properly.

On link you can see a video of how it's working.

https://drive.google.com/file/d/1r_Q0qWJEwCA7XMq_STF-H_5kBW4OtcQp/view?usp=sharing

**Comment by Kagekazu** [comment]
Will be fixed next PR
