### ISSUE TITLE
[SUGGESTION] [VPR] Reawaken - Generation [Steel Fangs] Option.

### ISSUE THREAD

**Issue by Iris4d** [Nik-Potokar/XIVSlothCombo#1602]
Reawaken [Steel Fangs] Option was replaced with [Dread fangs]. Would like to ask adding back the option to use [Steel Fangs] to replace the Full generation - Legacy Combo.

**Comment by Kagekazu** [comment]
Won't happen. Since it conflict with the one button.

I can make it steel fangs, but then u won't be able to use it inside the advanced mode.

**Comment by Iris4d** [comment]
That'd be perfect on my side. I only use the "Reawaken- Generation" option here. If it's not much of an issue to add as an option and not to much work, I'd be grateful.
