### ISSUE TITLE
[DRG] Sometimes chaotic spring is triggered twice in a row.

### ISSUE THREAD

**Issue by titos314** [Nik-Potokar/XIVSlothCombo#1603]
thinking that I'm looking at the cooldown of LanceCharge, but there are times when I use chaotic spring twice in a row during a combo.

**Comment by titos314** [comment]
Whenever the lance charge is available, it always results in a chaotic spring combo, can this be fixed?

**Comment by kanadesilencer** [comment]
The combo route is as follows
Can you fix it?

chaotic spring combo
↓
Heavens' Thrust combo
↓
chaotic spring combo
↓
Heavens' Thrust combo
↓
Heavens' Thrust combo
↓
chaotic spring combo
↓
Heavens' Thrust combo
↓
Heavens' Thrust combo
↓
chaotic spring combo
・
・
・
・

**Comment by ff14shimadaFF14** [comment]
The combo route is as follows
Can you fix it?

chaotic spring combo
↓
Heavens' Thrust combo
↓
chaotic spring combo
↓
Heavens' Thrust combo
↓
Heavens' Thrust combo
↓
chaotic spring combo
↓
Heavens' Thrust combo
↓
Heavens' Thrust combo
↓
chaotic spring combo
・
・
・
・
