### ISSUE TITLE
[MCH] Options to remove Bioblaster and Wildfire from their single-button combos

### ISSUE THREAD

**Issue by ask-42** [Nik-Potokar/XIVSlothCombo#161]
- I'd like to manually choose when to use bioblaster, but still get the benefit of swapping to autocrossbow (and possibly weaving gauss round/ricochet), pulling the feature off the `Spread Shot/Scattergun Heat` combo.

- I'd like to do the same thing with `Single Button Heat Blast`, without it triggering wildfire on its own, but still be able to have it swap to hypercharge and weave gauss/ricochet. Wildfire will activate mid-heat blast combo if you're at 50 energy while its active (so if you hypercharge right at 100 energy, it gets unintentionally weaved in sometimes), and sometimes I'd just like to delay it a bit anyways for better alignment while still spending my energy, and the easiest thing would be to just pull it off the combo and give it a dedicated button while retaining the other features.

**Comment by Nik-Potokar** [comment]
Ill add them as toggles shortly
