### ISSUE TITLE
[RPR] Combo Expiring

### ISSUE THREAD

**Issue by yaboiurgot** [Nik-Potokar/XIVSlothCombo#1616]
Combo chains expiring around the 2 minute burst windows. Consistent across around a dozen runs of EX1. 
![IMG_0350](https://github.com/user-attachments/assets/a8137c0f-ebdb-44c4-a74f-6f830eb9fb1a)

**Comment by yaboiurgot** [comment]
Upon further testing it looks the the combo expires due to prioritizing the second Enshroud(which is on around a 3-4 second CD) despite having the ability to fit a GCD in.

**Comment by yaboiurgot** [comment]
> > Upon further testing it looks the the combo expires due to prioritizing the second Enshroud(which is on around a 3-4 second CD) despite having the ability to fit a GCD in.
> 
> next update has some SoD updates which should make double enshroud more smooth. Can u let me know if it still happens after sloth is on the new version?

Will do. Thanks!

**Comment by yaboiurgot** [comment]
> > Upon further testing it looks the the combo expires due to prioritizing the second Enshroud(which is on around a 3-4 second CD) despite having the ability to fit a GCD in.
> 
> next update has some SoD updates which should make double enshroud more smooth. Can u let me know if it still happens after sloth is on the new version?

Went ahead and pulled your bugfixes PR and issue seems to still be present where Enshroud will sometimes have 3 to 4 seconds left and it’ll opt to wait for it to come off CD instead of filling the combo GCD

**Comment by Kagekazu** [comment]
> > > Upon further testing it looks the the combo expires due to prioritizing the second Enshroud(which is on around a 3-4 second CD) despite having the ability to fit a GCD in.
> 
> > 
> 
> > next update has some SoD updates which should make double enshroud more smooth. Can u let me know if it still happens after sloth is on the new version?
> 
> 
> 
> Went ahead and pulled your bugfixes PR and issue seems to still be present where Enshroud will sometimes have 3 to 4 seconds left and it’ll opt to wait for it to come off CD instead of filling the combo GCD

Ye, that's fixed next commit when I'm back on my pc ^.^

**Comment by Kagekazu** [comment]
@yaboiurgot 
potential fix has been pushed to #1587 

feel free to test it out and see if its better now.

**Comment by yaboiurgot** [comment]
> @yaboiurgot potential fix has been pushed to #1587
> 
> feel free to test it out and see if its better now.

Tested it just now in M1S. Looks like it now will prioritize using Blood Stalk/Gluttony between Enshrouds now.

**Comment by Kagekazu** [comment]
> > @yaboiurgot potential fix has been pushed to #1587
> > feel free to test it out and see if its better now.
> 
> Tested it just now in M1S. Looks like it now will prioritize using Blood Stalk/Gluttony between Enshrouds now.

Heya,

![image](https://github.com/user-attachments/assets/8ec4b05f-eba1-4879-9127-45d705a615f4)

according to the image there should be enough time to do double  enshroud and perfectio before needing to do another combo gcd.

Is the problem that it doesnt do a GCD BEFORE the first enshroud?
Is it possible to send me a log of where it happened? so i can see in depth what the issue might be?

**Comment by Kagekazu** [comment]
> > @yaboiurgot potential fix has been pushed to #1587
> > feel free to test it out and see if its better now.
> 
> Tested it just now in M1S. Looks like it now will prioritize using Blood Stalk/Gluttony between Enshrouds now.

can u try with the latest commit? i rewrote how enshroud works and added some extra checks

**Comment by yaboiurgot** [comment]
Will give the latest commit a try later tonight and pull a log from that. I believe after Perfectio it would opt to skip that last combo GCD and go immediately into Soul Slice/Gluttony.
