### ISSUE TITLE
[smn] opener issues with advanced summoner

### ISSUE THREAD

**Issue by argabarg** [Nik-Potokar/XIVSlothCombo#1618]
The advanced summoner opens with solar bahamut and immediately uses searing light. It should open with ruin into solar into a pot window into a solar gcd and then searing light. I think it's still using the timing from when searing was 30s instead of 20s.

**Comment by Genesis-Nova** [comment]
I'll be taking a look at this once I get home.
Possibly sinceI don't have an in combat check for summoning demis it allows you to summon them immediately rather than after starting combat/casting ruin.

**Comment by Genesis-Nova** [comment]
I've made the requisite changes to always use ruin before casting demis, as well as making sure to use searing after one (or more, depending on cooldowns, etc) uses of a demi's gcd attacks.
I won't be able to test until I get home though.

**Comment by Genesis-Nova** [comment]
Looked for you in the discord, I've gotten the delay for searing and the incombat check for demi summons
The delay for energy drain and the rest of the ogcds are determined by the Pooled oGCDs slider, so set that to whatever you prefer.
![image](https://github.com/user-attachments/assets/66d17239-3f47-42bb-a9b6-9219a7e15ce5)
