### ISSUE TITLE
[GNB] Gnashing Fang Continuation Combo

### ISSUE THREAD

**Issue by rcpoison** [Nik-Potokar/XIVSlothCombo#1623]
Could you split the "Cooldowns on Gnashing Fang" into:
- OGCDs on Gnashing
- Sonic Break on Gnashing
- Burst Strike on Gnashing

Currently you have to pay attention to not accidentally use Burst Strike instead of Reign combo during burst. Also don't want to use Sonic Break on an add thus manual.

Maybe even add an option for Reign combo on Gnashing?

**Comment by Akechi-kun** [comment]
Needs testing, but done.
Next update.
![image_2024-07-26_032822138](https://github.com/user-attachments/assets/85433dbf-c4d9-487c-984c-4cbed7ab5c1d)

**Comment by rcpoison** [comment]
thanks!
