### ISSUE TITLE
[VPR] Advance AoE Applying Nox AoE no matter the timer& Something strange happen from switching AoE to ST (occationly Dungeons)

### ISSUE THREAD

**Issue by Shiratama-works** [Nik-Potokar/XIVSlothCombo#1624]
Advance AoE Applying Nox AoE no matter the timer even at 34 when Pit of Dread is unchecked

**Comment by Shiratama-works** [comment]
![image](https://github.com/user-attachments/assets/35f32911-0b08-4205-ba0d-60f8dea4bbf0)
something is causing it to loop itself on keep alppying Nox

**Comment by Shiratama-works** [comment]
![image](https://github.com/user-attachments/assets/1eb77e64-5ff8-45d5-a69e-3440936eb2df)
from contiunition of AoE and change target to a un noxed target it starts with non nox first combo and go on trying to start burst by using Ire
![image](https://github.com/user-attachments/assets/c8d0cccf-c537-4ce0-8963-06582b71616f)
![image](https://github.com/user-attachments/assets/0fa3a997-69c3-4a10-9a34-5cbadf398380)
until one point it remember that hey lets use some Dreads
![image](https://github.com/user-attachments/assets/02183858-64c7-4fc1-8152-25dcd6a2dbe7)
then remember to use nox but totally forgets about the Ire buff that just when off on 5:42
![image](https://github.com/user-attachments/assets/a26444e9-ac43-4e04-8009-b4985041007b)
![image](https://github.com/user-attachments/assets/7bb6558e-56f8-491c-8ea6-20ca5db8d99e)

**Comment by Kagekazu** [comment]
> ![image](https://private-user-images.githubusercontent.com/65398068/352497602-35f32911-0b08-4205-ba0d-60f8dea4bbf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTM1NDAsIm5iZiI6MTcyMTk5MzI0MCwicGF0aCI6Ii82NTM5ODA2OC8zNTI0OTc2MDItMzVmMzI5MTEtMGIwOC00MjA1LWJhMGQtNjBmOGRlYTRiYmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDExMjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NzdiNTlhNWIxNmZkZTJhN2Y2MGFhNTM3ODIzZjZiZDc0Y2JmNTBkZTcxODI5MzMwYTIwZmI0YjZhM2U0ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ukXzx8_fbESs4dyBxXc9SnvS_9aVC0mTQDbYHbGSJLE) something is causing it to loop itself on keep alppying Nox

fixed in next update

**Comment by Kagekazu** [comment]
> ![image](https://private-user-images.githubusercontent.com/65398068/352498508-1eb77e64-5ff8-45d5-a69e-3440936eb2df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTM1NDAsIm5iZiI6MTcyMTk5MzI0MCwicGF0aCI6Ii82NTM5ODA2OC8zNTI0OTg1MDgtMWViNzdlNjQtNWZmOC00NWQ1LWE2OWUtMzQ0MDkzNmViMmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDExMjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMDg0NWZhNjJkNGQwNWY4ZTFkMzI2YTAxYTk4NTU0MDNjNzQwMWFkNzllZDc1ZDYxMTA1ZjY3ZTJmYzNiZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ehZjMKUpQRmeeHccTmbDmUZgXE8FMHl6hP4DZcUadOM) from contiunition of AoE and change target to a un noxed target it starts with non nox first combo and go on trying to start burst by using Ire ![image](https://private-user-images.githubusercontent.com/65398068/352499340-c8d0cccf-c537-4ce0-8963-06582b71616f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTM1NDAsIm5iZiI6MTcyMTk5MzI0MCwicGF0aCI6Ii82NTM5ODA2OC8zNTI0OTkzNDAtYzhkMGNjY2YtYzUzNy00Y2UwLTg5NjMtMDY1ODJiNzE2MTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDExMjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkN2JhYjlhYzcxZjkyNDhjMWMyMDBkN2EyYTQzMTYwYzNlNjBmODFjNjI3MGU5ODY0NzYwNWI4YWJkYmRkN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wAqakg-GrYB0hu0RuDbjyfDnjiFAzzPld17lehzPLi4) ![image](https://private-user-images.githubusercontent.com/65398068/352499434-0fa3a997-69c3-4a10-9a34-5cbadf398380.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTM1NDAsIm5iZiI6MTcyMTk5MzI0MCwicGF0aCI6Ii82NTM5ODA2OC8zNTI0OTk0MzQtMGZhM2E5OTctNjljMy00YTEwLTlhMzQtNWNiYWRmMzk4MzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDExMjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0Njk2ODFkYmFkZmIxYTNmY2EwNzVkYmY4OGVjMDBkOTNlYWVkMDJmMGQ3YzhlNzNkZGVhNjM2ODNjNWI3NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4uFLB3rVjmB7wCRHgaO6WBKOFJiUC3DMA--viQKi5Ms) until one point it remember that hey lets use some Dreads ![image](https://private-user-images.githubusercontent.com/65398068/352499727-02183858-64c7-4fc1-8152-25dcd6a2dbe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTM1NDAsIm5iZiI6MTcyMTk5MzI0MCwicGF0aCI6Ii82NTM5ODA2OC8zNTI0OTk3MjctMDIxODM4NTgtNjRjNy00ZmMxLTgxNTItMjVkY2Q2YTJkYmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDExMjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3NGM0YTM2NWU2ZGVhYjQ3Yzk1ZDAxMThjZGJiZDE5NzdlNmRjNDRlMTc1NGU1ODI2Nzk1ODQ4MDQ2MjJiMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5qCa8C7wq3XM5jZG_c3AWDSA99Aofe74h6-Oi1PriWk) then remember to use nox but totally forgets about the Ire buff that just when off on 5:42 ![image](https://private-user-images.githubusercontent.com/65398068/352499803-a26444e9-ac43-4e04-8009-b4985041007b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTM1NDAsIm5iZiI6MTcyMTk5MzI0MCwicGF0aCI6Ii82NTM5ODA2OC8zNTI0OTk4MDMtYTI2NDQ0ZTktYWM0My00ZTA0LTgwMDktYjQ5ODUwNDEwMDdiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDExMjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MDUxZTY3MWIxYTJiOGI0MGMyODY0MzQ3MjhlMThhOGJjMmQzODI0MzE1MTM5M2Q2NWEwNGUzNjIzY2RkZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.18yGbLP6i2BQcjILT_v1xAZEmEMna9FZe9HLcx8WfKA)

known issue.
Also fixed next PR
