### ISSUE TITLE
[AST] Request - Option to add automatic job priority to Quick Target Damage Cards

### ISSUE THREAD

**Issue by Dunced** [Nik-Potokar/XIVSlothCombo#1625]
Hello,
Could it please be possible to add an option to the Quick Target Damage Cards that allows us to set our own job priority for buffing ranged or melee players? Currently, the cards appear to select the first suitable player without considering the optimal choice. I would love to always prio Spear the local pictomancer if anything, it seems huge at the moment 😇
Thank you so much!

![ast_card_prio](https://github.com/user-attachments/assets/b40226ec-0d57-4df4-aba0-179239993f03)

**Comment by Taurenkey** [comment]
It's deliberately random as a tradeoff for it being automated for you.
