### ISSUE TITLE
Awakening Combo doesnt add in fourth legacy

### ISSUE THREAD

**Issue by mizukaruu** [Nik-Potokar/XIVSlothCombo#1627]
I noticed, after testing around, when you use the options for awakening combo under advance settings, as well as generations settings (replaces dread fangs) and (reawaken - legacy option turned on, that the game will not add the 4th legacy attack into the rotation. It will do every single Legacy besides the 4th, it always skips 4th.

**Comment by Kagekazu** [comment]
Ye, it's a known issue. Hence why my PR makes both options conflicting (so u can only have 1 option on at the time )

**Comment by mizukaruu** [comment]
You had it working I think a patch or two ago, but then it stopped working
after the recent change (if that helps you any)

**Comment by mizukaruu** [comment]
You had it working I think a patch or two ago, but then it stopped working after the recent change (if that helps you any)

**Comment by Kagekazu** [comment]
duplicate of #1606
