### ISSUE TITLE
GNB Forced Burst Strike.

### ISSUE THREAD

**Issue by Wraithos** [Nik-Potokar/XIVSlothCombo#1628]
Hello,

This isn't a bug so much as a request. Can the forced Burst Strike that replaces your Keen Edge be an option instead of forced? In situations where you want to hold your cartridges for a couple extra GCDs this becomes impossible. Can the base option simple allow the use of the Keen edge combo only as it used to?

**Comment by Akechi-kun** [comment]
The only **two** instances when _Burst Strike_ takes over your one-button is when:
**A**: You have _max_ cartridges and your last action used was **Brutal Shell**
**B**: You have _No Mercy_ & have nothing else left to burn, but have cartridges

You should not be using _Burst Strike_ anywhere else at any level. Unless I am misinterpreting what you're saying, then what I'm reading is you want the overcap protection turned into an option, and that I am not doing as it's the opposite of reccomendations of how to play this job. You never should overcap.

> In situations where you want to hold your cartridges for a couple extra GCDs this becomes impossible.

If you're holding for >= 2 GCDs, then just cast _Burst Strike_ and don't spam your button and it will not force-use _No Mercy_ immediately and cast Solid Barrel for you. Always better this than overcapping.

**Comment by Wraithos** [comment]
Hello Akechi-Kun,

Apologies if I wasn't clear enough in my explanation in what I was referring to. Hopefully I can elaborate better on what is occurring so you can see more clearly why I made the request.

When I am about to enter my two-minute burst window and finish the final cartridge generation with Solid Barrel, my Keen Edge action button turns into Burst Strike so I cannot even use Keen Edge then Brutal Shell the way I was able to do prior. This is an issue for me because I like to drift by one GCD (A use of Keen Edge) before I enter my No Mercy window because this re-aligns everything for me and allows the rotation to flow better (for me personally of course).

I'm sure you would agree that there are many circumstances to which this would be less than ideal during a multitude of encounters, not just because drifting a GCD is my personal preference, but also instances when you want to hold entering to better align with raid buffs exc.

I hope this clears up why I was making the request, and I Truely thank you for taking the time to communicate with me on this!

**Comment by Akechi-kun** [comment]
Okay so let me get this straight:
You are _Lv100 GNB_, you have **2** cartridges, your last action was **Brutal Shell**, and **No Mercy** is about to be off cooldown (<2s)? 

If this is the actual issue, then it's fixed in the next update as I've made major improvements to the logic & tested every scenario to ensure it's capability.
