### ISSUE TITLE
[RPR] SoD Suggestion

### ISSUE THREAD

**Issue by yaboiurgot** [Nik-Potokar/XIVSlothCombo#1630]
Currently in certain situations that require targeting more than one target in a fight(adds in Ex1 for example) it prioritizes getting Deaths Design on the target above most things. Sometimes this leads to Soul Reaver stacks being wasted as instead of using Gallows/Gibbet it’ll opt to use SoD first.

**Comment by Kagekazu** [comment]
it will always opt to use SoD since its ur dmg buff, and doing skills without 10% increased dmg is a waste in the long run

**Comment by yaboiurgot** [comment]
> it will always opt to use SoD since its ur dmg buff, and doing skills without 10% increased dmg is a waste in the long run But it shoudnt opt any attacks where u waste stacks.

For Ex 1 after the add phase I’ve noticed it’ll SoD the boss after it becomes targetable despite having a Soul Reaver stack from the add that just died. Can test it some more tonight to confirm. Doesn’t seem to always happen but can test it out some more.

**Comment by Kagekazu** [comment]
> > it will always opt to use SoD since its ur dmg buff, and doing skills without 10% increased dmg is a waste in the long run But it shoudnt opt any attacks where u waste stacks.
> 
> For Ex 1 after the add phase I’ve noticed it’ll SoD the boss after it becomes targetable despite having a Soul Reaver stack from the add that just died. Can test it some more tonight to confirm. Doesn’t seem to always happen but can test it out some more.

ye, it will not use anything when it doesnt have SoD, since getting the dmg buff on is highest priority.
Also dont forget that sloth doesnt know when a boss goes away or when an add dies. Its on u to not spam when an add is about to die if u dont want to use that skill.
