### ISSUE TITLE
[MCH] AoE Simple mode uses "Savage Blade" skill that has been removed

### ISSUE THREAD

**Issue by ExinX** [Nik-Potokar/XIVSlothCombo#1633]
AoE Simple mode (and probably advanced mode too) uses an obsolete skill called Savage Blade.
![savageblade](https://github.com/user-attachments/assets/631d11c9-fdb5-44e2-8eac-151cea1ddf88)

**Comment by cupcake121** [comment]
Surely you can figure out why that happens by yourself. Read the tooltip for the ability that's being used right before Savage Blade pops up.

Needless to say that's intended behavior. If you want to know why read the tooltips for MCH skills.
