### ISSUE TITLE
WHM Lucid Dreaming not working + requests

### ISSUE THREAD

**Issue by abranon** [Nik-Potokar/XIVSlothCombo#164]
Tested the other healers and WHM is the only one that doesn't seem to activate LD, uninstalled and reinstalled with no luck. 
As for requests, would it be possible to add options to add assize and presence of mind to the DPS rotation?

**Comment by Nik-Potokar** [comment]
Can you give it another try because I've just tested it and it does work on my end?

And yes i can add both of those as options

**Comment by abranon** [comment]
I double-checked to see and it looks like WHM just doesn't want to queue oGCDs on my end, not sure if you'd want my log or to give me options to troubleshoot. I've already tried deleting the folder to reinstall it and disabled all other plugins.

**Comment by Nik-Potokar** [comment]
Double check that you have Glare 3 slotted on your hotbar if it still dosent work can you add me on discord Aki#9251 so i can have a closer look and can fix asap

**Comment by abranon** [comment]
Ope, looks like naturally upgraded glare through levelling was the issue, changed it for the glare 3 and it all worked, so sorry about that!

**Comment by Nik-Potokar** [comment]
No worries just glad its working now
Also the requested features should be live
