### ISSUE TITLE
[Feature] Teaching Mode

### ISSUE THREAD

**Issue by EYEZOexe** [Nik-Potokar/XIVSlothCombo#1645]
Not sure how difficult this would be to implement however instead of replacing one button on the hotbar to highlight the next move on the hotbar.

**Comment by Genesis-Nova** [comment]
Others can feel free to chime in, but that's not really within the scope of this plugin.
The main feature of this plugin (and other combo plugins) is to replace actions with other actions.

**Comment by EYEZOexe** [comment]
That's perfectly valid and understandable, thanks for your time

**Comment by edewen** [comment]
perhaps a combo of sloth and action timeline, a default dalamud plugin,  might get you a better idea of what skills are used when to help learn what sloth is doing?
