### ISSUE TITLE
[VPR] not using "Reawaken" in single target mode simple&advanced 

### ISSUE THREAD

**Issue by niku2561** [Nik-Potokar/XIVSlothCombo#1650]
i was doing my expert rolo today and noticed it never using the Reawaken skill during single target combos but it works fine in the AoE mode

**Comment by Kagekazu** [comment]
correct, since VPR has not been updated for 7.05, so it still checks for noxious gnash debuff.

Will be solved once Sloth updates.

**Comment by niku2561** [comment]
thanks for the quick response
________________________________
