### ISSUE TITLE
[VPR] Steel Fang Simple/Advanced prioritizing buff instead of empowered finishers

### ISSUE THREAD

**Issue by Omnicrone** [Nik-Potokar/XIVSlothCombo#1652]
Ever since the last update Viper's automatic combo for Steel/Reaving Fangs (both simple and advanced) sometimes misses the path towards the current buffed finisher by prioritizing refreshing the current lowest timed self-buff even when the buff timers are over 30s. 

The entire autocombo for Steel Fangs should prioritize the path towards the current buffed finisher instead of trying to refresh the lowest buff every time.

**Comment by Omnicrone** [comment]
After further investigation only a single combo path seems broken and it is the one that needs to end in Hindsbane Fang. Oftentimes when you have Hindsbane Venom the auto combo ends up using Hunter Sting ending up in the Flank side of the finisher gcds and missing the empowered Hindsbane.

**Comment by Kagekazu** [comment]
fixed in PR #1651
