### ISSUE TITLE
DRG issuse rotation a loop between Chaotic Spring combo and The Heavens' Thrust combo

### ISSUE THREAD

**Issue by phuongpham2011** [Nik-Potokar/XIVSlothCombo#1656]
Known DRG rotation bug but currently reducing the dot after opening the bug because it does the Heavensthrust combo twice when the Power Surge buff is ~10s to 6s left despite doing the Heavensthrust combo before

**Comment by ff14shimadaFF14** [comment]
The combo route is as follows
Can you fix it?

chaotic spring combo
↓
Heavens' Thrust combo
↓
chaotic spring combo
↓
Heavens' Thrust combo
↓
Heavens' Thrust combo
↓
chaotic spring combo
↓
Heavens' Thrust combo
↓
Heavens' Thrust combo
↓
chaotic spring combo
・
・
・
・

**Comment by Kagekazu** [comment]
known and fixed in #1587

**Comment by Kagekazu** [comment]
also duplicate of #1599
