### ISSUE TITLE
[DRG] Coerthan Torment Combo issue

### ISSUE THREAD

**Issue by Ats127** [Nik-Potokar/XIVSlothCombo#166]
Sometimes the combo restarts before doing Coerthan Torment.
Basically what it's doing for me atm is Doom->Sonic->Coerthan->Doom->Sonic->Doom->Sonic ...

**Comment by Iaotle** [comment]
I'm not sure we have any DRG players on the dev roster atm so this might not get the attention it needs.

**Comment by Nik-Potokar** [comment]
Give it another try please i changed something so now it should hopefully work

**Comment by Ats127** [comment]
Still broken for me and seems to be very inconsistent.
Sometimes just ends up spamming Doom Spike 2-3 times in a row without continuing the combo.

**Comment by Ats127** [comment]
Ok upon further testing the combo is only broken on some target dummies for some reason and in the open world and dungeons it is actually working correctly.
