### ISSUE TITLE
[RPR] Enshroud AOE combo not activating?

### ISSUE THREAD

**Issue by PaladinPrincess** [Nik-Potokar/XIVSlothCombo#1663]
Been playing reaper again and noticed my settings for RPR were acting funny? the Spinning Slice combo isn't becoming the Enshroud combo when Enshroud is active. In-game pic to work it out. My settings for AOE are present. Was working up until recently. ;w;

![Untitled](https://github.com/user-attachments/assets/321bbf1a-0dce-49b5-a2a0-0af24b5adde5)

**Comment by Kagekazu** [comment]
known issue
fixed in #1587
