### ISSUE TITLE
[DNC] Devilment fix

### ISSUE THREAD

**Issue by PapaSteel** [Nik-Potokar/XIVSlothCombo#167]
While a great idea, this feature could be improved.
Currently puts fan dance 1/3/4 on the main combo whenever any of them are available. Keep Dance III and IV working this way, because it helps to better pop Flourish.
But if you could modify Fan Dance I to **only** be put on the main combo when at 4 stacks, this would turn it into overcap gauge protection AND allow you to dump all fan dances during the devilment buff, which is the optimal dps approach.

For one final additional improvement, Technical Finish -> Devilment would be one excellent feature option as well.

Thanks again for being amazing, holy smokes.

**Comment by Nik-Potokar** [comment]
Changed FanDance1 to only to appear when you have 4 feathers as requested and also added the devilment feature on the combined dance feature

Might not be perfect since it was a quick addition but do let me know and il take a look at it in the morning

**Comment by PapaSteel** [comment]
Fan dance feature works FLAWLESSLY, thanks a ton. Devilment feature has to go after the tech finish I think to function properly.

**Comment by PapaSteel** [comment]
Also reporting a bug. If either of the Overcap features are enabled, if Espirit hits 90+ in the middle of a dance combo, the combo completely breaks and prevents the use of any abilities until the dance times out, because Cascade/Windmill won't turn into Emboite.

**Comment by PapaSteel** [comment]
To clarify, the full combo should be:
Standard Step -> (two dance moves) -> Standard Finish -> Technical Step -> (four dance moves) -> Technical Finish -> Flourish -> Devilment -> Tillana -> Starfall Dance
Then in a perfect target dummy world, the player would just repeat the Standard Step portion twice more before doing this entire chain again.

Is there any way I could help with the code personally?

**Comment by Nik-Potokar** [comment]
@PapaSteel Added requested stuff onto the feature
But i am unable to reproduce the bug in my case if technical is about to come up and im dancing it will wait until the dance is finished.
Maybe it was just a devilment issue since i thought you wanted it after standard step at 1st but now that has been changed.
Anyway let me know if it functions correctly now since i am still unable to test anything above 80 but from quick testing it seems fine

**Comment by PapaSteel** [comment]
That recent fix seems to have solved the freezing, which is awesome.
SOMETHING is still putting devilment in the middle of the combo right after **standard** finish, before tech step starts. It's one of the first five dancer combo options, unrelated to anything that was done in the last few updates here. I'm going to spend the next ten minutes narrowing it down.

(For reference, dancer rotation/opener: https://i.imgur.com/Ff7LvIQ.png)

**Comment by PapaSteel** [comment]
It's **#58: Dance Step Combo.** Right now it's including devilment in a suboptimal fashion instead of just handling the steps.

**Comment by Nik-Potokar** [comment]
ahh right i forgot to add conflict check between the old and new feature

**Comment by PapaSteel** [comment]
After testing, things are looking GORGEOUS.
Flourish is still just kind of hanging out and could probably be included in a main combo better some day, but these changes are the extent of my own requests. 

Thank you. Y'all need a kofi site or something.

**Comment by Nik-Potokar** [comment]
Oh Right forgot to add flourish il add as separate toggle option

**Comment by PapaSteel** [comment]
I can't tell you how thrilled I am. Thanks again, seriously, for all of this.

**Comment by Nik-Potokar** [comment]
@PapaSteel Will be live in a few

**Comment by PapaSteel** [comment]
Flourish taking precedence over the start of Standard Step wouldn't work. SS is used before a pull, and flourish has to take place during the actual combo portion. It might work better right after standard Finish.

**Comment by Nik-Potokar** [comment]
Added check for SS let me know if that works better

**Comment by PapaSteel** [comment]
That did the trick. I think I might have too much skill speed. :P

**Comment by PapaSteel** [comment]
Some _extremely_ minor oddities, but not often enough that I can replicate, Things are good.

**Comment by Nik-Potokar** [comment]
Yeah might not be 100% perfect so id keep and extra skill slot for flourish if possible but il see if i can come up with something else that would make it 100% perfect in the meantime
