### ISSUE TITLE
[NIN]Ask about Ninja the restoration

### ISSUE THREAD

**Issue by rip80066** [Nik-Potokar/XIVSlothCombo#1671]
Hello, when will Ninja's XivslothCombo be repaired? I know you are busy with work, so I am really sorry for pressing you like this. I wonder if you will accept Donate? If so, I can donate a small amount.

Sorry to bother you, because English is not my native language. Please forgive me if I make you feel uncomfortable.

**Comment by mahfujkadir** [comment]
You can use expandest plugin until they do release the best combo plugin

**Comment by Tartarga** [comment]
Closed in #1726
