### ISSUE TITLE
[VPR] Option #38 is not triggering for Swiftskin's Den and Hunter's Den

### ISSUE THREAD

**Issue by sable-xiv** [Nik-Potokar/XIVSlothCombo#1673]
The 38th option for VPR, which combines Serpent's Tail, Twinfang, and Twinblood to one button, is not triggering the Twinfang and Twinblood actions when executing Swiftskin's Den or Hunter's Den, AoE actions that combo off of Vicepit.

**Comment by Kagekazu** [comment]
correct, will be added in the next PR. 
fixed in #1651
