### ISSUE TITLE
[BRD]  Radiant Encore not allowing damage-dealing oGCD weaves to be prioritized ahead of it with Simple Bard

### ISSUE THREAD

**Issue by roobert5** [Nik-Potokar/XIVSlothCombo#1674]
Small bug, but when Radiant Encore is the next GCD being used with Simple Bard, it is receiving a higher priority than oGCDs, which will cause oGCDs like Empyreal Arrow to be ignored until it is pressed.

EDIT:  Buffs like Raging Strikes, Battle Voice, or Barrage do not seem to be affected by this, only damaging oGCDs like Heartbreak Shot, Empyreal Arrow, Pitch Perfect, and Sidewinder

**Comment by edewen** [comment]
![image](https://github.com/user-attachments/assets/fb37be68-22d0-468c-bad0-6f28a85b6ba3)
Im not getting that at all running full one button.  

It only had one ogcd to throw there, barrage but it does it for me.

**Comment by roobert5** [comment]
It is possible that buffs have a higher priority, since it is a toggleable feature, but I can say with absolute certainty that non-toggleable oGCDs (particularly Heartbreak Shot, Empyreal Arrow, and Pitch Perfect) will never be prioritized ahead of Radiant Encore.

Your timeline seems to support what I am saying, I am hard-pressed to believe that you did not have a stack of Heartbreak shot to expend between :08 and :10, which would be queued up in front of any other oGCD.

**Comment by edewen** [comment]
I tried moving it in code and sent you a test version. You know bard better than I clearly. I would never see this.
