### ISSUE TITLE
[VPR] When attempting Balance Opener and going out of range, sloth can get stuck and be unable to cast anything

### ISSUE THREAD

**Issue by daijo-bu** [Nik-Potokar/XIVSlothCombo#1676]
Rotation broke while attempting M2S and was in the middle of Balancer Opener but had to go out of range. Was unable to cast anything after both sets of uncoiled fury went off and used Slither to go back in range of boss. Tried casting different things to get unstuck but was only able to cast again after going out of range and back in.

![image](https://github.com/user-attachments/assets/981b4999-92f0-4e1d-bf63-ba90ce4d1af0)

**Comment by Kagekazu** [comment]
Don't cast for 1/2gcd's and it fixes itself. 

The opener is hardcoded in, so that's not changing.
