### ISSUE TITLE
[SAM] Samirai question

### ISSUE THREAD

**Issue by Stanberrry** [Nik-Potokar/XIVSlothCombo#1678]
Hello. Is there any hope for the samurai to appear in the combo set in the coming month?

**Comment by Kagekazu** [comment]
Once the balance has better info on the rotation.

I have everything added in, but with the 7.05 patch the whole rotation changed and they are still discussing whats the best rotation.

**Comment by Stanberrry** [comment]
Thanks for the reply. Well, I'll wait for the update and hope to see Samurai on the combo list as soon as possible

**Comment by Tartarga** [comment]
Fixed in #1711
