### ISSUE TITLE
Discord server down?

### ISSUE THREAD

**Issue by Elote1** [Nik-Potokar/XIVSlothCombo#1683]
While I was browsing the server, I suddenly got an error message and then the server was gone from my lists. I tried to rejoin, but it is stating that the invite is invalid (not banned, mind you.)

I asked a friend, and they were also unable to see the server in their list anymore. 

Did the server go south?

**Comment by greatestfall** [comment]
have talked to a few people who help work on the project and they're not aware of why this happened either so.. we're all in the dark atm.

**Comment by rotund-sloth** [comment]
> have talked to a few people who help work on the project and they're not aware of why this happened either so.. we're all in the dark atm.

i wonder what happened. hope we get an update soon

**Comment by LynnVianette** [comment]
Hopefully just an accident. Love this project, as I'm sure many do. Hope everything is okay.

**Comment by EliSantana1** [comment]
Glad it's not just me, though I was banned for sec lol. Hopefully it's temporary issue, the Discord and project are invaluable

**Comment by Taurenkey** [comment]
Yes the server is gone/deleted/broken idk pick one. The plugin isn't going anywhere and we'll have an update in the next 12 hours.

**Comment by parttimeachiever** [comment]
thanks for the update

**Comment by edewen** [comment]
As long as its just the discord, I'm sure that puts a lot of peoples minds at ease. Honestly, was thinking you blew it up to stop people from asking when we will get blm.

**Comment by Taurenkey** [comment]
BLM is coming in 8.0, please look forward to it. But yes it's just the Discord that's blown up, I'll definitely have news shortly.

**Comment by StarkITA** [comment]
> Honestly really strange that it just up and poofed. Normally Discord will contact the owner **before** they take any action, so I wonder if this was something that was caused by some kind of new automated tool of theirs.

Not if it got hacked, as it often happens :)

**Comment by Linoa235** [comment]
I was banned or Discord disappeared? But honestly, apart from saying 'thanks' or mentioning a bug, I don't see why I would have been banned.

**Comment by Taurenkey** [comment]
We have moved server to discord.gg/punishxiv. Some of you may already be there, however this will be the new Discord for the plugin going forward.
