### ISSUE TITLE
[BRD] No level check on Rain of Death?

### ISSUE THREAD

**Issue by Offskee** [Nik-Potokar/XIVSlothCombo#1692]
When in lower level content, the AoE rotation keeps trying to queue up RoD. Assuming its missing its level check?

**Comment by edewen** [comment]
I see the issue. Ill get a pr in quick for it. Sadly a wait on merge situation though.

**Comment by Offskee** [comment]
ok, yea it seems when Raging is OFF cooldown it wants to spam it at low levels. Thank yeee

**Comment by edewen** [comment]
you cna keep it on as at that point it is your own aoe ogcd there, so it isnt blocking anything, but it looks funny. I have a fix tested on my fork already for it though. Thx o/
