### ISSUE TITLE
[SAM] Repeated Hinganbana/Iaijutsu Usage

### ISSUE THREAD

**Issue by kazumaKiryu542** [Nik-Potokar/XIVSlothCombo#1694]
(Lv100)
Around the 1m mark of the rotation, Hinganbana is used three times in sucession, refreshing the DoT at about 25 seconds left, then 55 seconds.

Settings:

Advanced Mode - Single Target
- Yukihaze Combo
- Kasha Combo
- Level 100 Opener
- Shinten Option (50 Kenki Overcap, 0 HP threshold)
- CDs on Main Combo (Ikishoten Option, 0% Iaijutsu Option, Ogi Namikiri Option, Zanshin Option, Meikyo Shisui Option, Shoha Option, Senei Option)
- Ranged Uptime Feature
- Combo Heals Option (25% second wind, 40% bloodbath)
- True North Feature

Simple Mode - AoE

**Comment by Kagekazu** [comment]
known issue and will be fixed next sam update

**Comment by Tartarga** [comment]
Fixed in #1711
