### ISSUE TITLE
[SAM] Higanbana not being re-applied

### ISSUE THREAD

**Issue by User252725** [Nik-Potokar/XIVSlothCombo#1696]
Firstly just want to appreciate all the effort gone into making this plug in what it is.

With the update to SAM for 7.05, i noticed on both Simple and Advanced mode for single targets on Samurai - Higanbana is not being re-applied throughout the fight. It is only applied on the opening rotation.

![Screenshot 2024-08-10 164317](https://github.com/user-attachments/assets/4d41cefe-03d6-41a1-9944-3676760441f1)

**Comment by Kagekazu** [comment]
known issue for lvl 100, will be fixed next update ^.^

**Comment by Stanberrry** [comment]
Yeah, it's interesting because up to the 100 level everything works perfect

**Comment by Tartarga** [comment]
Fixed in #1711
