### ISSUE TITLE
[SAM] Suggestion: Enpi over Meikyo when out of combat

### ISSUE THREAD

**Issue by IllusionMan** [Nik-Potokar/XIVSlothCombo#1700]
A suggestion, when on single target "ranged uptime feature" is enabled, Enpi priority goes over Meikyo, so when we are out of combat and want to attack something far, we use Enpi instead.

**Comment by Kagekazu** [comment]
will be added in next sam update!

**Comment by Tartarga** [comment]
Fixed in #1711
