### ISSUE TITLE
[GNB PVP] Gnashing Fang combo

### ISSUE THREAD

**Issue by sikamt** [Nik-Potokar/XIVSlothCombo#1714]
Using Double Down in the middle of a Gnashing Fang combo with Burst Mode on will break the Gnashing Fang combo.

Thanks for the great plugin!
Sorry if it's hard to read as it's a machine translation, thanks!

**Comment by Akechi-kun** [comment]
Excuse my PvP knowledge as I do not really play PvP at all using GNB, but Double Down breaks the Gnashing Fang combo in PvP? I did not know this was a thing, since in PvE, You can use Double Down after Gnashing Fang and it won't break.

**Comment by sikamt** [comment]
Gnashing Fang Combo continues as a game system, but it is no longer part of XIVSloth's burst mode.
For example, using Double Down after the first Gnashing Fang Combo will cause a Solid Barrel Combo to be executed. So, as a result, the Gnashing Fang Combo will be deleted.
Incorrect: Gnashing Fang Combo -> Double Down -> Solid Barrel Combo -> Solid Barrel Combo...

I think it should look like this
Correct: Gnashing Fang Combo→Double Down→Gnashing Fang Combo→Gnashing Fang Combo...

**Comment by sikamt** [comment]
And I am sorry, but I have to add something.
Currently the Gnashing Fang combo is set to take priority over Burst Strike, but since Burst Strike does not erase the Gnashing Fang combo, can you please change it so that Burst Strike takes priority?
Burst Strike in PVP can only be used during a 10 second proc, so it is second only to Double Down and will disappear if not prioritized
