### ISSUE TITLE
[BRD] About buff timing

### ISSUE THREAD

**Issue by AkiNatu** [Nik-Potokar/XIVSlothCombo#1719]
nice to meet you.
I'm not good at English, so I use a translation site.
We are very grateful to "XIVSlothCombo" who always takes care of us.

The reason I posted this is about BRD's ability "Raging Strike".

I'm currently playing with 2.50gcd.

After the second minute, the effect time of "Raging Strike" is no longer applied to "Iron Jaws", and after that the effect time of "Raging Strike" expires and "Iron Jaws" is used. .

Sometimes the effect time of "Battle Voice" is not on.

I've been having this problem since last week. Can you please help me solve it?

Probably, I think it's because the timing of updating "Iron Jaws" is determined by "Radiant Finale".

After 2 minutes,
"Raging Strike" 0 seconds (always)
"Battle Voice" 0 seconds (sometimes)
“Radiant Finale” 2-3 seconds
I'm using "Iron Jaws" at this time.

**Comment by edewen** [comment]
This is addressed in my newest bard pr. As i fixed the buffs to come out consistently. When they drift apart bad things happen. 

new pr, it is tied to raging, and raging comes last, so you will want it set to 5 if you have radiant finale, and can feel free to set it lower to 3 when you dont. And should always have battlevoice due to buff timings.

**Comment by AkiNatu** [comment]
sorry.
I'm sorry if I don't understand, but this is "#19: Easy legging jaws option".
Should I change this scale from 3 to 5?

**Comment by edewen** [comment]
If you are high enough level to have all 3 buffs, yes. Because the extra time it takes to get them all out, setting it to 5 will help make sure it hits all 3.

**Comment by AkiNatu** [comment]
thank you for your reply.

However, I tried setting it to 5 earlier, but there was no change.
Use "Iron Jaws" after the effect time of the two buffs "Raging Strike (0 seconds (always))" and "Battle Voice (0 seconds (sometimes))" has expired.

BRD level is already 100.

**Comment by AkiNatu** [comment]
Immediately after the battle begins, use "Iron Jaw" with all buffs applied.

However, no matter how many times I try, I use "Iron Jaw" after the following two buffs have expired.

This phenomenon always occurs during all bursts, including 2 minutes, 4 minutes, 6 minutes, 8 minutes, and 10 minutes.

As advised, I tried changing the setting from 3 to 5, but the behavior did not change.

"Raging Strike (0 seconds (always))"
 "Battle Voice (0 seconds (sometimes))"

I would like to ask you to reconfirm the behavior.

**Comment by edewen** [comment]
I gave a suggestion that might help. It didn't for you, which sucks. 

This is addressed in my newest bard pr. As I fixed the buffs to come out consistently. Unfortunately, all the is left to do is wait until the next update to see if the fix is accepted and merged.
