### ISSUE TITLE
[MCH] Automaton Queen activation

### ISSUE THREAD

**Issue by Stanberrry** [Nik-Potokar/XIVSlothCombo#1720]
Good afternoon. I noticed that Automaton Queen does not always become active, when it's available, although in Advanced Mode - ST it is checked to include it in rotation. Is it only appears in rotation under some conditions? I remember Automaton Queen used to be in rotation as soon as it became available

**Comment by Kagekazu** [comment]
> Good afternoon. I noticed that Automaton Queen does not always become active, when it's available, although in Advanced Mode - ST it is checked to include it in rotation. Is it only appears in rotation under some conditions? I remember Automaton Queen used to be in rotation as soon as it became available

Hello,
I looked at the code and it should use queen
- in opener
- on one minute with 90 battery
- on odd minutes when battery is over 50
- on odd minutes second queen ( as the balance says) when battery is over 60
- even minutes when battery is 100

**Comment by Stanberrry** [comment]
Oh, I see... thank you for your answer!

**Comment by GR7747** [comment]
This issue is correct. The Automaton Queen will never reach 100 gauge for even numbered windows after the first.

I am observing a random activation at 100 seconds remaining on Wildfire and a random activation at around 30-40 seconds remaining on Wildfire, in addition to the normal 2x odd window activations. 
So it basically works out to the Queen activating every time you reach 50/60 gauge, including during 2 minutes.

**Comment by Kagekazu** [comment]
Never said it wasn't correct. As the issue is still open it means it's not worked at for now. Making it work is annoying, so it will be when I have more time to fix it more in depth.

**Comment by Kagekazu** [comment]
> see...

I might have a potential fix for the even queens not behaving. I will test some more and keep u posted!

**Comment by GR7747** [comment]
My bad on replying to this issue, I noticed the issue posted and conflated it with the one I was experiencing. Just a reading comprehension issue on my part. I just opened a new one to make it simpler.
