### ISSUE TITLE
[DRG] Chaos Spring/Heavens Thrust Sometimes Loops

### ISSUE THREAD

**Issue by Beanslash** [Nik-Potokar/XIVSlothCombo#1721]
Sometimes the DRG rotation with all advanced settings will loop either combo. It looks to break after being out of melee distance for extended amounts of times. This will sometimes cause Lance Charge to drift since it looks like it won't pop it until Power Surge is applied which sometimes it wont use due to repeating Heavens Thrust. Suggesting it just alternates between Heavens Thrust/Chaos Spring combo at all times regardless of duration left on DoT/Power Surge. Below is an M2S log where the only manual input was Piercing Talon during certain mechanics. 

Analysis: https://xivanalysis.com/fflogs/a:W9d6TkLm3wJbYnyM/45/1923
FFLog: https://www.fflogs.com/reports/a:W9d6TkLm3wJbYnyM#fight=45&type=damage-done&source=1923

**Comment by Akechi-kun** [comment]
Known bug that for some reason is fixed by disabling then re-enabling the plugin.

**Comment by Beanslash** [comment]
Disabled and reenabled but looks to still opt to double Chaos Spring combo on the dummy when out of range for a few GCDs instead of just continuing with Heavens Thrust combo when back to melee range. Working as intended?

**Comment by Kagekazu** [comment]
ill have an in depth look once my drg is lvl 100, i know for me it just rotates both on lvl 92

**Comment by Kagekazu** [comment]
> Disabled and reenabled but looks to still opt to double Chaos Spring combo on the dummy when out of range for a few GCDs instead of just continuing with Heavens Thrust combo when back to melee range. Working as intended?

can u get me a log of it happening? since i cant replicate it at all on my end

**Comment by Kagekazu** [comment]
ofcourse it will loop chaos thrust when u dont have uptime, it tries to keep ur buffs up..

**Comment by Beanslash** [comment]
Ah gotcha, Figured it was intentional just definitely felt really strict. Better than repeating Heavens Thrust which disabling and re enabling did fix. Thanks.

**Comment by Kagekazu** [comment]
> Ah gotcha, Figured it was intentional just definitely felt really strict. Better than repeating Heavens Thrust which disabling and re enabling did fix. Thanks.

i can change this so it just checks if u have the debuff on ur target or if ur power surge is below 15 secs ( which is about the same as 1 combo chain)

**Comment by Beanslash** [comment]
> > Ah gotcha, Figured it was intentional just definitely felt really strict. Better than repeating Heavens Thrust which disabling and re enabling did fix. Thanks.
> 
> i can change this so it just checks if u have the debuff on ur target or if ur power surge is below 15 secs ( which is about the same as 1 combo chain)

I personally think the debuff check would work great.

**Comment by Beanslash** [comment]
@Kagekazu Tested the new PR and it works great. Thanks for your hard work! Only thing I've noticed is that the Dynamic True North wasn't working. Didn't test it on other melees but wasn't working for DRG so not true if it's tied to these changes.

**Comment by Kagekazu** [comment]
> @Kagekazu Tested the new PR and it works great. Thanks for your hard work! Only thing I've noticed is that the Dynamic True North wasn't working. Didn't test it on other melees but wasn't working for DRG so not sure if it's tied to these changes. 

Hmm, It should work, I'll test it out and make some changes today if needed!

**Comment by Kagekazu** [comment]
> @Kagekazu Tested the new PR and it works great. Thanks for your hard work! Only thing I've noticed is that the Dynamic True North wasn't working. Didn't test it on other melees but wasn't working for DRG so not sure if it's tied to these changes.

U were correct, this is fixed in latest commit!
