### ISSUE TITLE
[REQUEST] ARC/BRD/MCH/DNC

### ISSUE THREAD

**Issue by tvgide** [Nik-Potokar/XIVSlothCombo#1724]
It would be nice to be able to have the option to enable Peloton to switch to Sprint in combat.

**Comment by edewen** [comment]
Just throwing this out there, I'm not the one who decides a dam thing. But what you want is very easily done with an in game macro. in combat itll sprint. out of combat it would peloton.

![image](https://github.com/user-attachments/assets/f11261dd-7e08-4151-920f-cb407e9af608)

**Comment by tvgide** [comment]
> Just throwing this out there, I'm not the one who decides a dam thing. But what you want is very easily done with an in game macro. in combat itll sprint. out of combat it would peloton.
> 
> ![image](https://private-user-images.githubusercontent.com/174963693/358085269-f11261dd-7e08-4151-920f-cb407e9af608.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTI2NDMsIm5iZiI6MTcyMzc5MjM0MywicGF0aCI6Ii8xNzQ5NjM2OTMvMzU4MDg1MjY5LWYxMTI2MWRkLTdlMDgtNDE1MS05MjBmLWNiNDA3ZTlhZjYwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQwNzEyMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZmQ0MmU4M2ZiZGI2OTViYWIwYzc1YmZjZTEwNWMyNWYxNzliMTA4NmI2ZTAyNmUyMjc0NmU2YTVmNmI4NzRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r-d17XNztUwIJAJqF-h2rQzu62ftHbMatzqCGmcz2AA)

No idea why I didn't just think to do this, works perfectly fine. Thanks!
