### ISSUE TITLE
[DNC] Saber dance on AOE option 

### ISSUE THREAD

**Issue by HrothgarFF14** [Nik-Potokar/XIVSlothCombo#1727]
The Saber Dance skill still appears in the combo in the Advanced Dancer (AOE) feature even when changing the Espirit value

**Comment by zbee** [comment]
Dance of the Dawn and Saber Dance are both set to appear regardless of your Esprit slider option IF:
- You are under Technical Finish
- Esprit >50

This is to prevent overcapping via Tillana.
I will add language to clarify this.
