### ISSUE TITLE
Devilment/CombinedDanceFeature

### ISSUE THREAD

**Issue by Ty0sMatic** [Nik-Potokar/XIVSlothCombo#173]
Not using the new CombinedDanceFeature results in Devilment replacing Standard and Technical after doing Standard and before being able to do Technical 
(original Dance Step Combo ticked, Devilment on Combined Dancte Feature unticked)

**Comment by Nik-Potokar** [comment]
Yep forgot to remove it from old combo while i was testing the new one should be fixed now

**Comment by Ty0sMatic** [comment]
♥
