### ISSUE TITLE
Astrologian Simplified Heals, Helios Conjunction Lockout

### ISSUE THREAD

**Issue by bflaxman92** [Nik-Potokar/XIVSlothCombo#1731]
Please allow players to toggle whether or not they want to replace helios conjunction/aspected helios with regular helios for the AOE heals feature like you do for WHM and Medica. I want to use it to let me weave horoscope without taking up another hotbar space, but I do not want to be locked out of using helios conjunction for doing so. It is optimal most of the time to re-up helios conjunction early rather than use helios.

**Comment by zbee** [comment]
Are you requesting that AST Simple Heals (AoE) have an option added to choose whether the combo replaces Aspected Helios or (normal) Helios?

**Comment by edewen** [comment]
Actually now that its mentioned i kinda want that too. Ast replacing the hot heal vs Whm replacing the not heal just doesn't feel right.
