### ISSUE TITLE
[MCH] Automaton Queen never reaches 100 gauge for even numbered windows.

### ISSUE THREAD

**Issue by GR7747** [Nik-Potokar/XIVSlothCombo#1737]
As part of the Advanced Mode - Single Target feature, the Automaton Queen will never reach 100 gauge for even numbered windows after the first. It always activates as soon as you reach 50/60 gauge after the first 2 minute window passes.

All options are active except Hypercharge and Wildfire. 
0 Reassemble charges are saved, and they are set to use on Excavator, Chain Saw, Air Anchor, and Drill. Clean Shot is unchecked.

I understand that the ability is coded to activate 

- As part of the opener
- On the first odd window with 90 battery
- On all future odd minute windows when gauge is over 50
- A second Queen on odd minutes when gauge is over 60
- Even minutes with full two minute burst when gauge is 100.

For specifics, I am observing a consistent, random activation at around 100 seconds remaining on Wildfire and a random activation at around 30-40 seconds remaining on Wildfire, in addition to the normal 2x odd window activations. It works out to basically activating every time you reach 50/60 gauge after the first 2 minute window.

**Comment by Kagekazu** [comment]
Hello!

i made some fixes and this should be better i think?

![image](https://github.com/user-attachments/assets/158b5306-6ca5-43ed-be80-324db3ce99a7)
