### ISSUE TITLE
barrage bug

### ISSUE THREAD

**Issue by hhharkness** [Nik-Potokar/XIVSlothCombo#1741]
both heavy shot into straight shot and aoe combo feature only proc when hawk's eye is triggered naturally, not when barrage is used

**Comment by edewen** [comment]
Fix is in pr for it. didn't make it for today's merge. 

The issue was Barrage stopped giving hawk's eye and became its own buff

Game will however use the barrage buff before hawk's eye buff so there is a good chance it will just use it before it runs out if you proc a hawks eye naturally.
