### ISSUE TITLE
[PCT] [Request] Simple mode and 

### ISSUE THREAD

**Issue by edewen** [Nik-Potokar/XIVSlothCombo#1746]
Ive look into the differences of simple vs advanced. Is there plans to turn simple into "advanced without the choices"? *if not i can do it i just didn't wanna step on toes*

As it stands now, simple isn't half of what advanced is. Limited movement options, burst window not the same, prepull motifs not there. It really does seem untouched from the first put together of picto. Unoptimized and the reason people wanted picto redone. 

Also, One button motifs, It merges motifs AND muses. Can we, or I, make the muses half an option?

**Comment by Akechi-kun** [comment]
If you want adjustments made to _Simple Mode - Single Target_, then just request them. 
_Simple Mode_ is literally just a hardcoded preset of _Advanced Mode_ made for newcomers to use. If you want certain things done or certain skills used differently, then I suggest you use _Advanced Mode_.

**Comment by edewen** [comment]
just trying not to step on someones toes. As aki expressed they still have plans for pct. 

![image](https://github.com/user-attachments/assets/f1474ddb-e0a9-49de-9ab9-f4676904b12e)
