### ISSUE TITLE
[DRG] Mirage Dive not used at all

### ISSUE THREAD

**Issue by Thork8** [Nik-Potokar/XIVSlothCombo#1748]
In ST Advance mode, Mirage Dive isnt being used at all. (Tested on lvl 90)
The Buff Dive Ready just falls off. Despite #17 being active.

![kllklklk](https://github.com/user-attachments/assets/02bb3062-bcd3-425a-8852-0aa2ff577b1e)

**Comment by Akechi-kun** [comment]
I can't seem to replicate this issue, as _MirageDive_ is working just fine for me on my end on live release. If you could give more details on this particular instance I'm all ears.

**Comment by Kagekazu** [comment]
> In ST Advance mode, Mirage Dive isnt being used at all. (Tested on lvl 90)
> 
> The Buff Dive Ready just falls off. Despite #17 being active.
> 
> 
> 
> ![kllklklk](https://github.com/user-attachments/assets/02bb3062-bcd3-425a-8852-0aa2ff577b1e)
> 
> 

Heya! Can u reset ur drg options? (Untick and retick the options), resloth the starting option and restart ur game? If it still happens, let me know!

**Comment by Thork8** [comment]
A day pass by, so my PC and FF14 was rebooted since. still same issue.
my DRG is lvl 90 maybe its only a behavior below lvl 100?

here is a video of it
https://streamable.com/51090l

**Comment by Thork8** [comment]
Okay, i found the issue.
if conditions are met for Mirage Dive, then Sloth returning "High Jump" as a skill

so in order this to work, ingame this one should be activated:
![fdsadfasafdsfds](https://github.com/user-attachments/assets/85fce110-41ab-49c7-a03b-804da063b347)

i always prefered MD on a seperate button, but that was the issue

**Comment by Kagekazu** [comment]
> Okay, i found the issue.
> 
> if conditions are met for Mirage Dive, then Sloth returning "High Jump" as a skill
> 
> 
> 
> so in order this to work, ingame this one should be activated:
> 
> ![fdsadfasafdsfds](https://github.com/user-attachments/assets/85fce110-41ab-49c7-a03b-804da063b347)
> 
> 
> 
> i always prefered MD on a seperate button, but that was the issue
> 
> 
> 
> on the same note, is it possible to have Sloth return "Mirage Dive" as a skill, rather than High Jump?

Since this is on by default, and drg code hasn't been touched for anything but adding the new skills and fixing the loop, this never was an issue before 7.0 . 

I will make it so it calls miragedive itself and not the original hook. So it should work for both then. 

For now I would say keep it on or use mirage dive urself until the fix is out.
