### ISSUE TITLE
[RPR] Heavy Gluttony drifting

### ISSUE THREAD

**Issue by Thork8** [Nik-Potokar/XIVSlothCombo#1757]
in my testing i noticed Gluttony is drifting a lot as it comes of cd during Enshroud.
https://xivanalysis.com/fflogs/a:gtCbVchQ1WKapfmA/3/7

saw same behavior from Kages log from Discord issues:
https://discord.com/channels/1001823907193552978/1272925365685321738/1273734219058647124
https://xivanalysis.com/fflogs/a:gD97mLBZPNVC3bwF/2/1

since the odd min Enshroud is flexible, have it interact with the Gluttony CD?
or if Gluttony is about to come of cd, dont use the red gauge on Blood Stalk and pool it for Gluttony?

**Comment by Kagekazu** [comment]
Hello,

can u send me ur settings? And possibly reset them?

I have just done a 6 min test on a dummy and i got no issues whatsoever, only drift is the normal drift that they say is normal for ur 2 min windows.

https://xivanalysis.com/fflogs/a:P4jK8169BgA2LQmX/2/5

**Comment by Kagekazu** [comment]
> saw same behavior from Kages log from Discord issues: https://discord.com/channels/1001823907193552978/1272925365685321738/1273734219058647124 https://xivanalysis.com/fflogs/a:gD97mLBZPNVC3bwF/2/1

**Also, my log was on 3.2.0.6, not on 3.2.0.7**

**Comment by Thork8** [comment]
> Hello,
> 
> can u send me ur settings? And possibly reset them?
> 
> I have just done a 6 min test on a dummy and i got no issues whatsoever, only drift is the normal drift for ur 2 min windows.
> 
> https://xivanalysis.com/fflogs/a:P4jK8169BgA2LQmX/2/5

you can see the same on this log of yours.
but after researching some more on balance, looks like its in the norm of optimal usage to delay it to the end of the 2min burst.
felt kinda odd, but if its the way to go then i will close the issue.
