### ISSUE TITLE
[DRK] the DRK_ST_Bloodspiller option only accounts for one of two Delirium buffs.

### ISSUE THREAD

**Issue by GTG3000** [Nik-Potokar/XIVSlothCombo#1764]
It accounts for the 3836 buff, but before lvl 96 the buff id is actually 1972. So the feature doesn't work until you're level 96.

**Comment by edewen** [comment]
![image](https://github.com/user-attachments/assets/c6c990af-9e75-4928-a5ff-5090ab9ca72c)
can concur. while it used all 3 charges. it looks like it gets it to 50 resource before it starts, and just bloodspillers until it can spend it. With it spending at 50 or above, Im not sure if you'll ever lose a stack. But it is possible.

**Comment by zbee** [comment]
Good find! I'll get this in the next update

**Comment by zbee** [comment]
Before: (doesn't use free Bloodspillers <96)
![image](https://github.com/user-attachments/assets/b7c762bc-7b2b-4e49-ae4a-fc1808a7cff3)

After: (uses free Bloodspillers <96) :D
![image](https://github.com/user-attachments/assets/42d17cc2-e527-4b49-a261-2eac7f2d97cc)
