### ISSUE TITLE
[WHM] Requests

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/XIVSlothCombo#177]
[Suggestions]
Holy becomes Misery, when available.
Have Medica feature work with afflatus feature, effectively making medica and medica 2 one button.
Add Thin Air to Medica 1 & 2 and Cure 3 to improve on mana economy.
Replace Cure2 with regen if regen is not currently on target.

EDIT: Thin Air on Raise when available would be nice as well

**Comment by Nik-Potokar** [comment]
Broken as in? because i just tested it and it works as intended all skills that are supposed to turn into the misery/rapture do that

**Comment by sauronshotdogs** [comment]
Thanks for the quick implimentation of the medica features. 

I think I expected Cure 2 and Medica to become Misery, when the Rapture and Solace, because I had the Afflatus feature enabled.

Would it be possible to include a cure 2 feature that changes into Misery also?

**Comment by Nik-Potokar** [comment]
Thin, Cure2 features added havent added main combo one yet since i wanna test some stuff 1st
