### ISSUE TITLE
[DRG] Geirskogul Suggestion

### ISSUE THREAD

**Issue by Beanslash** [Nik-Potokar/XIVSlothCombo#1771]
Hi. I wanted to make a suggestion for DRG when it comes to Geirskogul priority. Sometimes it’ll opt to use other oGCDs like Wyrmwind Thrust before Geirskogul which isn’t a big deal but in longer encounters it can cause drifting to the point where sometimes all the Nastrond casts won’t be able to fall under Litany/Lance Charge and even some other oGCDs won’t fall under Life of the Dragons damage buff due to being cast before Geirskogul. Very minor stuff that can currently be resolved by manually casting Geirskogul yourself the moment it’s up.

**Comment by Kagekazu** [comment]
It should use it as soon as it comes off cooldown. If it doesn't, then I need to check the code.

There are hard cooldowns, that need to be used perfectly when they become available, like battle litany, lance charge, geirskogul,.. 

Then there are hard ogcd's like life surge and wyrmwind thrust, that are used at specific moments

Then there are flexible ogcd's like rise of the dragon, stardiver, starcross,.. 
which are filler ogcd's

**Comment by Kagekazu** [comment]
If it is missing gierskogul usage's because of drifting, then I'll check tomorrow if I need to adapt the priorities

**Comment by Beanslash** [comment]
> If it is missing gierskogul usage's because of drifting, then I'll check tomorrow if I need to adapt the priorities

Sounds good. The other hard CDs like LC/Litany go off perfectly.
