### ISSUE TITLE
[BLM] Low level firestarter being used instantly, potential giveaway of tool usage

### ISSUE THREAD

**Issue by Cadwgan** [Nik-Potokar/XIVSlothCombo#1781]
As per title, same issue as #877

**Comment by Thork8** [comment]
On low level, you are supposed to use it instantly for dmg gain.
the Firestarter proc occurs about at the slide cast window, or when the cast registered by the server.
dont know the exact numbers, but you already know if you have a proc or not before the cast finishes.
and its actualy part of the rotation and "skill" to use those procs immidiately

**Comment by Cadwgan** [comment]
I just checked and at least on 160ms ping Firestarter was granted 9 frames before the GCD completed, that's 150ms for reaction time, the average human reaction time is roughly 250ms.

The reason I bring this up is it's literally being used inhumanly fast and if SE wants to it could be detectable.

**Comment by Thork8** [comment]
> I just checked and at least on 160ms ping Firestarter was granted 9 frames before the GCD completed, that's 150ms for reaction time, the average human reaction time is roughly 250ms.
> 
> The reason I bring this up is it's literally being used inhumanly fast and if SE wants to it could be detectable.

better late than never.
i have about ~10-12ms ping and for me its about ~500ms of reaction time, half a second. i dont even need to be fast, can comfortably hit the firestarter. and since its recommended as per any guide, im sure its just the way to play. no giveaways there
