### ISSUE TITLE
[MNK] Perfect Balance combo not working on low level synced dungeons/raids

### ISSUE THREAD

**Issue by Naab25** [Nik-Potokar/XIVSlothCombo#1782]
Edited screenshot of MNK settings:

I've recently tried leveling monk on Alliance raid and here what settings I used.

![image](https://github.com/user-attachments/assets/d1055976-92bd-46d0-8159-5eadbf51c0e3)

The perfect balance combo does not complete and the Masterful Blitz has to be manually pressed 
![image](https://github.com/user-attachments/assets/c7be13fe-9fa4-45f6-a52a-72e0a0d661ac)
![image](https://github.com/user-attachments/assets/f99c1653-fbef-4150-a083-4bad69975f80)

![image](https://github.com/user-attachments/assets/8a755c5e-f4e1-4796-8bf9-ccb7107f4312)

**Comment by mahfujkadir** [comment]
Same, I get the same issue.
