### ISSUE TITLE
[RPR] one button action

### ISSUE THREAD

**Issue by chase692** [Nik-Potokar/XIVSlothCombo#1788]
on Reaper the one button action only works outside dngs..once inside dngs have to hit as normal if you was doing the rotation and to get  AOE  rotarion is the same but have to hit shadow of death first then it will active the aoe rotation

**Comment by Kagekazu** [comment]
> am i going to get some one to say something about my problem

sorry, i dont check github that much anymore..

i cant seem to replicate ur issue. can u send me ur settings? Also most of the reaper rotation is locked behind having the SoD debuff on the enemy.

Does it lock up when u aoe, and then try to ST or vice versa?

**Comment by chase692** [comment]
https://gyazo.com/2c259be087662f5122c5bb9d4e368f6f
https://gyazo.com/c51237c33df5692482e8f4d97021c455
https://gyazo.com/ebac3c6fc979d1d12f8ce9bfbbf529db
https://gyazo.com/49ecf49608e0a58d82a77eec36fa60c7
but even if i have just the simple mode checked.. works on the strike dummy no problem.. but once in a dng once it goes though the combo i still have to click the other skills to work and the simple mode for aoe only thing that goes is whorl death over and over unless i click shadow of death then it will go though the aoe combo but still have to click soul scythe and so on

**Comment by Kagekazu** [comment]
ill try to replicate it tomorrow, but ive lvled rpr to 100 in dungeons without any issues. 
So i start with ST, and then go into AoE and then it gets stuck on Whorl of Dead?

If possible, can u send me a video when it happens? in the meantime i will see what i can find

**Comment by chase692** [comment]
sorry won't be able to do a video.. i don't have or  even know how to do it

**Comment by chase692** [comment]
on the aoe.. it gets stuck on whol.. unless i start with dead

**Comment by Kagekazu** [comment]
> on the aoe.. it gets stuck on whol.. unless i start with dead

I see u got every option on.. can u try to deselect everything and just use simple mode to test? It might be a conflict somewhere.

**Comment by chase692** [comment]
i have done the single mode and i still have to hit the dead before doing any aoe skills or it just keeps doing  whol.. i don't know why but like i said on the strike dummy i don't all works fine until i go in the dng

**Comment by Kagekazu** [comment]
> i have done the single mode and i still have to hit the dead before doing any aoe skills or it just keeps doing whol.. i don't know why but like i said on the strike dummy i don't all works fine until i go in the dng

do u have any other options on but simple mode like i asked? 
Do u have any other combo plugins active?

Sloth doesnt differentiate if its in a dungeon or not, the rotation is always the same. 

Also i dont think i can help until i can see the issue, u can use OBS to make a video ( its free ) and attach it to this issue, otherwise if no one can replicate the issue i cant solve anything.

**Comment by chase692** [comment]
ok so if you doing the single mode and have advance unchecked you still have to unchick everything else?

**Comment by chase692** [comment]
i do with was a discord just for this stuff.. so people can show their personal setups

**Comment by Kagekazu** [comment]
> i do with was a discord just for this stuff.. so people can show their personal setups

well u can always DM us on discord, which would be easier than here :)

But for the simple mode i mean : 
- untick advanced mode
- tick simple mode
- untick every option in those https://gyazo.com/18e2e73034ec757be26c9597df960dda

test if it still happens then

**Comment by chase692** [comment]
is your name the same in discord as it is in here.. i don't know who to DM

**Comment by Kagekazu** [comment]
> is your name the same in discord as it is in here.. i don't know who to DM

if u go to #combo-general in the discord server, anyone with a yellow name can help.
https://discord.gg/punishxiv

**Comment by chase692** [comment]
well i don't see #combo on that discord
https://gyazo.com/3f72bbf10293412910a4f39fbbecddff

**Comment by zbee** [comment]
> well i don't see #combo on that discord https://gyazo.com/3f72bbf10293412910a4f39fbbecddff

That is not the server he linked you to.

**Comment by chase692** [comment]
erm.. that where it took me too..lol.. but i found it on that server

**Comment by zbee** [comment]
> but i found it on that server

I assume you found XIVCombo, which is not this plugin, we are not on that server, we are on the [Punish server](https://discord.gg/punishxiv).

**Comment by chase692** [comment]
i found it on that server the punish server

**Comment by zbee** [comment]
Regardless of where you found us, the server in your screenshot is not the Punish server.
If [Kage's troubleshooting steps](https://github.com/Nik-Potokar/XIVSlothCombo/issues/1788#issuecomment-2335683436) did not resolve your problem you should come talk to us on Punish Server; here is an alternate link to the correct server if the previous one is indeed somehow broken for you: https://discord.gg/Zzrcc8kmvy
