### ISSUE TITLE
[BRD] Opener stuff

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/XIVSlothCombo#179]
Is there a way for the simplebard to follow the opener?

I figure since all the abilities are there, it's just a batter of changing priorities, but I don't know.

**Comment by ele-starshade** [comment]
Hi Sauron, just to let you know, we've got a preset in Beta right now and are doing some final optimisations, it was a little tricky but it seems to be predictable now.

I'll keep you updated on our progress on getting it finalised!

**Comment by sauronshotdogs** [comment]
I will have a look right away and report back. Thanks for your work!

**Comment by sauronshotdogs** [comment]
![image](https://user-images.githubusercontent.com/95890035/151423683-b7d834ce-2f85-4350-a29a-7a2307a538fa.png)

Looking great, awesome work!
