### ISSUE TITLE
[Ast] Request: Lightspeed Weave for Single Target and AoE heals

### ISSUE THREAD

**Issue by AetherCollective** [Nik-Potokar/XIVSlothCombo#1804]
It would be super handy to be able to weave light speed into the heals like you can do for damage. Can this be implemented?

**Comment by zbee** [comment]
Are you meaning as a movement option in those combos, or an option to use it on cooldown in those combos? Or something else?


Either way, but especially the latter, I am thinking that it would be a big miss - I don't want to hit Lightspeed when I am just trying to throw out an oGCD heal.
I can understand the appeal if you *have* to be putting out a lot of health, but I think that situation is niche enough to warrant manual usage instead - especially when there's macrocosmos, which is also not on the combo.

**Comment by AetherCollective** [comment]
As a movement option, and it would be placed after all the oGCDs are used.

**Comment by zbee** [comment]
As I said, I do understand, but I still think that is uncommon enough to warrant manual intervention in favor of keeping the healing combo to only healing.
This is not not something we plan to implement.

**Comment by AetherCollective** [comment]
What do you not understand? Can you ask clarifying questions or tell me what you do understand?

**Comment by zbee** [comment]
I am saying I _do_ understand, but that this isn't an option we want to add to healing combos.
The DPS combos are the main ones with options like that.

Healing combos rarely need used as much as you described, and in the situations where they are (Hades,Abyssal,etc) will always require manual preparation which is what Lightspeed ought to be in this case as well, and that's how we would like to keep things.

**Comment by AetherCollective** [comment]
I see. I misunderstood sorry
