### ISSUE TITLE
[RPR LvL 71] Adv. Mode - Single Target -> Bloodstalk is not transferred to the rota

### ISSUE THREAD

**Issue by Thyrann82** [Nik-Potokar/XIVSlothCombo#1805]
Heyhey,

I'm at LvL-71 and checked 6,7,9,10 - but it wont work! I'm not sure if 7+10 works or not, but im sure that "Bloodstalk" not works, cause i got alltime 100 Soul Gauge and never get Bloodstalk to my rota to use it.

Active Buttons in Advance Mode - Single Target: 2-7, 9-22 ; 4 (Options: 4seconds & 3%) & 20 (Options: 20% & 40%)

Oh and YES, the dungeon was high enough - I had to use Bloodstalk for myself. ;)

Hope you can find and fix this issue. :-)

**Comment by Kagekazu** [comment]
Same issue as : https://discord.com/channels/1001823907193552978/1277932668545269761

fixed in next version
