### ISSUE TITLE
[SAM] KaitenFeature Option 4

### ISSUE THREAD

**Issue by drpleberino** [Nik-Potokar/XIVSlothCombo#182]
Would it be possible to add Kaiten to Ogi Namikiri

Also since I don't want to add another thread about it but would it be possible to have an Kenki Dump option that would add Senei or Shinten to your next Hakaze/basic combo to prevent overcapping if a certain threshold of Kenki has been reached

**Comment by Nik-Potokar** [comment]
Do you want me to add it like this
on Ikishoten>kaiten>ogi namikiri >kaeshi namikiri

And what would be a good kenki check 90/95?

**Comment by drpleberino** [comment]
if kenki >= 20 then
 kaiten, ogi namikiri, kaeshi namikiri
else
 ogi namikiri, kaeshi namikiri

and for the kenki dump option it would probably nice to have 2 options one for
stay at 75 or lower because it allows to shinten/senei to go to 50 to immediately use ikishoten without loss

and one for 
stay at 85 or lower because I think(not 100% sure) Yuki is to create the most with a generation of 15 (apart from ikishoten)

**Comment by drpleberino** [comment]
Is there any special reason you want ot to be with ishikoten, since ishikoten is weaved it only really makes you accidently use kaiten if you press it too hard. I also noticed the bug that he permanently uses kaiten again and again until he reaches the amount of kenki where he cant use it anymore.

Also would it be possible to use the kenki dump yuki, gekko and kasha combo because the one button has quite several flaws such as not reacting to shisui aswell as starting with the worst skill granting no buff at all yukikaze

**Comment by Nik-Potokar** [comment]
I can put it on any skill but i need to know which one you want. 
Il take a look at the bug ASAP and il add them to each of the standalone combos.
Can you add me on discord(Aki#9251) for ease of communication and so i could have you test out stuff faster and id always love to have a SAM player handy to get other features optimized
