### ISSUE TITLE
RPR Gluttony on Bloodstalk Not also Putting Sacrificium?

### ISSUE THREAD

**Issue by bunnybn** [Nik-Potokar/XIVSlothCombo#1820]
There's no point in putting Gluttony on Bloodstalk if it doesn't also put Sacrificium on the button, as we still have to put Gluttony on the hotbar for that skill then. And I will not use the Enshroud Combo feature as that's too cheaty for me. I don't want one button burst. I just want to reduce button bloat.

**Comment by Kagekazu** [comment]
> There's no point in putting Gluttony on Bloodstalk if it doesn't also put Sacrificium on the button,
instead of saying `there is no point`, u might wanna just ask a feature request to also use sacrificium outside of the enshroud combo option..

I am always open for feedback, but do formulate it better instead of attacking an option.
Tyvm.

I can make an option for sacrificium outside of enshroud.

**Comment by Kagekazu** [comment]
![image](https://github.com/user-attachments/assets/4c3c48f9-72b7-49b5-bdee-acb4688fe4e2)
