### ISSUE TITLE
[RPR] Soul Gauge isn't used at lvl 50

### ISSUE THREAD

**Issue by Kebito** [Nik-Potokar/XIVSlothCombo#1823]
Blood Stalk is available at level 50 so when synced to level 50 content I expect the use of blood stalk as an OGCD on both Simple Mode - Single Target and Simple Mode - AOE modes. Currently Blood Stalk is not being used at all at level 50.

**Comment by Kagekazu** [comment]
is already fixed, just needs to be pushed to live.
