### ISSUE TITLE
[feature request] no twinfang/blood on viper advanced modes

### ISSUE THREAD

**Issue by hhharkness** [Nik-Potokar/XIVSlothCombo#1845]
#1838 

> Doesnt that option already exist?
And if it doesnt, can u give me an example of why u dont want those 2 on the advanced mode?

if it does exist i can't find it - there's an option to add serpent's tail that i keep unchecked but none that i can see for the other two. the reason is that i personally don't like having weaponskills and abilities on the same button so i tend to use the advanced modes as just my weaponskill buttons, and i'm using the combined combo ability feature instead.

**Comment by Kagekazu** [comment]
it does already exist.

Just went digging in the code.

![image](https://github.com/user-attachments/assets/e1153e96-3300-406a-ba33-d34c57506c1f)
![image](https://github.com/user-attachments/assets/051389c6-5267-4ad9-b60f-436196e556bb)
![image](https://github.com/user-attachments/assets/7ccd1c72-abe7-45a1-ad13-010bc9c45174)

**Comment by Kagekazu** [comment]
![image](https://github.com/user-attachments/assets/65cc32d9-b10c-4901-a06a-a8c12fa5a2be)
![image](https://github.com/user-attachments/assets/30cac7e3-0b42-4e56-b928-55c6fc94bfe8)

Added it to ST and AoE.
So next update it will be on live ^.^
