### ISSUE TITLE
AST Opener and Clipping Question

### ISSUE THREAD

**Issue by abranon** [Nik-Potokar/XIVSlothCombo#185]
Saw you have a beta testing version of Bard and was wondering if it'd be difficult to implement a simple AST opener to prevent a crown card from being pulled prior to divination drop. Maybe also adding divination to the dps button? 

As for the question, if two ogcds come off CD at the same time the q mash has them both go through, is there a way to prevent more than one ogcd in a non-instant cast or at least put priority on a GCD, not sure if what I'm asking is possible but figured I'd ask!

**Comment by Nik-Potokar** [comment]
Il have some adjustments coming soon after a bit of testing that will solve the clipping issue. 
Il see into adding div option as well.

**Comment by abranon** [comment]
Oh nice, I didn't know if it'd be possible so really neat, thanks for the quick responses too, enjoy your night mate!
