### ISSUE TITLE
Can‘t find the plugin after set the url and Discord link expired

### ISSUE THREAD

**Issue by MercuryAmber** [Nik-Potokar/XIVSlothCombo#1850]
![image](https://github.com/user-attachments/assets/09c2aec7-eef7-4c92-b1e2-28287cb66051)
![image](https://github.com/user-attachments/assets/e175f259-8490-41ec-8b60-d835e32110b2)
I can't find the plugin after set the url correctly and I tried to solve it on discord ur link has also been expired

**Comment by zbee** [comment]
You can use https://discord.gg/Zzrcc8kmvy instead (which is now the updated link on the repo).

Looks like you are experiencing a Dalamud error from the text at the top, perhaps that is the source of this problem?
Not familiar with the language, but if via CN I know Dalamud works differently somehow; does [this](https://github.com/NightmareXIV/UnbanPluginsCN) software help?

Is there any error in your `/xllog` when you open the Plugin Installer window?

**Comment by MercuryAmber** [comment]
Thank you for replying. I found out what happend. The CN Dalamud somehow banned this plugin so I had to download the bypass. Now the problem has been solved.

**Comment by zbee** [comment]
Good to know for future reference, glad the unblocker worked.
