### ISSUE TITLE
[BRD] Simple Opener feedback

### ISSUE THREAD

**Issue by augporto** [Nik-Potokar/XIVSlothCombo#188]
### Issues found

1.  on step 0 > substep 4, its using all 3 stacks of bloodletter before going to next substep (burstshot/refulgent). 
2.  on step 2 > substep 7 and step 1 > substep 8, ironjaws never fires because there's a check for stormbite duration on it.

 
### Expected behaviors

 1. bloodletter should go off only once at that time, and remaining two charges used on other substeps of step 1 and step 2.
 2. ironjaws at the end must be forced to snapshot the buffs, no need to check the remaining debuffs durations.

the rest seems to be working as intended, nice job!

**Comment by ele-starshade** [comment]
Hey @augporto  - We've pushed some fixes, let me know what you think :)

Thanks!

**Comment by augporto** [comment]
Heya @ele-starshade , just tested it a couple of times on the dummy its pretty awesome now! Just the procs of pitch perfect on manual there make the opener a lot smoother.

A logic to put 3 stack PP proc there I think is not necessary right now , since its very easy to see and react during the opener. You just use two buttons for it now :)

Awesome job and thank you!

**Comment by augporto** [comment]
Oh I almost, I just did a DG and one thing that came to mind was the possibility if we open the combat with or even if the action used is one of [ QuickNock, Ladonsbite, Shadowbite], it would consider the opener done and go back to normal ST.

I had to keep alternating the preset on/off between trash and bosses xD

Thanks!!

**Comment by ele-starshade** [comment]
Thanks @augporto - Let me see what I can do about that, I've only tried it in raids and on dummies so no trash xD

I'll see if I can add the pitch perfect triggers in places where it wouldn't weave incorrectly, and I'll also try to add an override in... Are you using simple bard AOE for your AOE trash fights, as I could put something in there that forces the ST to ignore the opener if you initiate combat with that preset.

Thanks again for trying it out and providing feedback, it's wonderful.

**Comment by augporto** [comment]
Hello @ele-starshade 

Yes I'm using Simple AOE bard for trash ,  I think the override on that preset would be best instead of directly in Simple Bard itself.

Oh btw, during the dg run I found another thing, if you start the fight with less than full Bloodletters , the logic will hang on the EA before the 1st BL.

I'm the one grateful for you to take the time to solve this , thank you very much.

ps: I think I deleted the post that talked about the DG trash stuff because I didn't want to burden you more with it, sorry for messing the story of this issue :O

**Comment by ele-starshade** [comment]
I will see if I can put some protections in for bloodletter :) The opener is done so it's extremely predictable and does the same stuff every time... But I'll see if I can protect those a little :)

**Comment by augporto** [comment]
Hello @ele-starshade , 

I just tested the new protections and PP procs for the opener and its all working really well , thank you for the work on it :)

**Comment by ele-starshade** [comment]
Hi @augporto Thanks so much again for trying it out! I've put in the AOE override as well, so if you use simple bards AOE option to open your AOE trash killing, it will skip the opener on the single target rotation until you leave and re-enter combat.

@Nik-Potokar - I think this one can be closed now! :)
