### ISSUE TITLE
[BRD] Bloodletter and Apex/Blast Arrow presets proposal for simple bard

### ISSUE THREAD

**Issue by augporto** [Nik-Potokar/XIVSlothCombo#189]
Based on the recommendations from the balance and xivanalysis 

> One use of Apex Arrow and Blast Arrow should occur during every Raging Strikes window after the opener. Make sure you have at least 80 Soul Voice Gauge for your buffs.

> At least three uses of Bloodletter or Rain of Death should occur during every Raging Strikes window. Make sure you pool your Bloodletter or Rain of Death charges during Army's Paeon.

> At around 21-19s left in Mage's Ballad, fire it off so long as you have 80 gauge or more. If you get 100 gauge earlier than that, you can Apex then too.

### Proposed behavior

presets to add to the simplebard  feature the possibility to:

1.  Pool bloodletter while under the effect of AP to enter WM with 2 charges after getting to 4 repertoires (or if the timing doesn't allow at 4 , start pooling at 3), for the burst phase, that way being possible to use a minimum of 3 BLs inside the burst window.
    - The occasionally 3rd charge would be used even while on AP to avoid over capping and keep the cd rolling.

2. A toggle to only use Apex Arrow in 2 occasions :
   - Under WM and Raging strikers burst window if at 80 or higher gauge.
   - Under MB  when at 80+ gauge with at least 19s left on it.
      - or only at 100, because I'm quite sure that the timing allows to wait for 100 before the 19s left, and the use before that can be left to the user discretion.

### Final considerations

Dunno how hard would it be to implement, but it would make wonders for the possibility of hitting max optimization.

And if we had to choose I think the Bloodletter pooling is more important atm.

**Comment by ele-starshade** [comment]
Thanks for the feedback Aug! I'll have a look at this tonight as well, and see if I can get a couple of presets setup for the expected behaviour :)

**Comment by augporto** [comment]
To add some info to the proposed behavior of Apex Arrow, one pattern that I found out in the burst window while doing some raids:
   - the best spot for it to happens is right after the usage of barrage, so if barrage is on CD and you have 80+ gauge , fire away and you will be free to use 1 more gcd before using IJ , or just in time to use IJ to snapshot the buffs.

**Comment by augporto** [comment]
Hello @ele-starshade ,

Just tested the pooling on raids, dummy and dgs , its working perfectly , thank you again for the awesome work! :)

**Comment by sauronshotdogs** [comment]
Do you want logs and feedback to optimize more, or are you content with its current iteration?
