### ISSUE TITLE
NIN combo help

### ISSUE THREAD

**Issue by klevox** [Nik-Potokar/XIVSlothCombo#192]
Hello Option: Aeolian Edge Combo #143 is checked. When Aeolian Edge (skill) is on the bar it does not change to Spinning Edge-Gust Slash. Am I doing something wrong? I noticed on DNC and Reaper all combo options seem to work. Is there by any chance an instruction manual some where to learn how your wonderful plug in works? I really enjoy it sorry for the newbish questions.

**Comment by Nik-Potokar** [comment]
I would suggest re-slotting Aeolian Edge from your skill book into hotbar again if that dosent work maybe change jobs and back to NIN.
