### ISSUE TITLE
[Sam] Overcap features for lower levels?

### ISSUE THREAD

**Issue by LemonWaffles** [Nik-Potokar/XIVSlothCombo#198]
This would mainly benefit lower levels so not sure if it's worth the trouble adding.

My suggestion would be to add Hissatsu: Shinten onto main single target combo when kenki is at 75 or more. This option would only be required from levels 62 to 72 when the simple overcap feature 1 can take it's place.

Perhaps the simple overcap feature 1 can be slightly edited so when you're under level 72 and you don't have access to Hissatsu: Senei only only Hissatsu: Shinten will trigger?

Similarly to the single target overcap feature could we have Hissatsu: Kyuten added to Aoe combo when kenki is at 75 or more? 

Both skills proposed are oGCDs. 
Thank you ^^

**Comment by LemonWaffles** [comment]
So i've been checking the new changes and this seems to be the biggest one.

```
    if (IsEnabled(CustomComboPreset.SamuraiOvercapFeature75))
                {

                    if (gauge.Kenki >= 75 && !seneiCD.IsCooldown && actionIDCD.IsCooldown && level >= 72)
                        return SAM.Senei;
                    if (gauge.Kenki >= 75 && seneiCD.IsCooldown && actionIDCD.IsCooldown && level >= 62)
                        return SAM.Shinten;
                }
```
I think something went wrong/not working as intended. 

The level check works in the sense that you no longer get Senei on your hotbar if you're under 72 however Shinten still fails to trigger. I assume it's this condition? 
` && seneiCD.IsCooldown`
It waits for Senei  to go on cooldown but since we're under 72 that will never happen so Shinten won't trigger? But if that condition gets changed it'll mess up the level 72+ combo.

Would something like this work perhaps?

```
    if (IsEnabled(CustomComboPreset.SamuraiOvercapFeature75))
              If (level >= 72)
              {
                    if (gauge.Kenki >= 75 && !seneiCD.IsCooldown && actionIDCD.IsCooldown)
                        return SAM.Senei;
                    if (gauge.Kenki >= 75 && seneiCD.IsCooldown && actionIDCD.IsCooldown)
                        return SAM.Shinten;
                }
              If (level >= 62)
              {
                    if (gauge.Kenki >= 75  && actionIDCD.IsCooldown)
                        return SAM.Shinten;
                }
```

I know it's ugly and clunky i'll have to figure out how to test plugins myself.

**Comment by Nik-Potokar** [comment]
@LemonWaffles I think its just the ordering that i got wrong since i couldn't test until now.
Testing it right now tho

**Comment by Nik-Potokar** [comment]
Should be fixed now
