### ISSUE TITLE
Massive fps loss on some classes

### ISSUE THREAD

**Issue by Ty0sMatic** [Nik-Potokar/XIVSlothCombo#201]
I just figured this out today, when changing jobs my fps drop massively, depending on number of options ticked in Slothcombo suppose. 
Restarting the game fixes until i change job again. Is there any possible workaround for that? Might effectively not even be related to your code but a Dalamud issue

**Comment by Ty0sMatic** [comment]
To further add to this - hiding the hotbars where the icons get replaced kinda helps. So it might actually be related to how the game itself handles it

**Comment by Nik-Potokar** [comment]
@Ty0sMatic Tick Enable PVP Combos and fps should go back to normal its a bug atm but got a new update coming anyway that resolves the issue

**Comment by sunxyw** [comment]
I think this issue still exists in v3.1.2.1, when I switch to WAR from other classes and use AOE, the FPS drops significantly (sometimes even causing the game to crash). Restarting the game will result in no FPS loss.

I can't find the "Enable PVP Combos" option in `/scombo`'s settings, can you tell me where it is?
