### ISSUE TITLE
[SGE]  Phlegma into Dyskrasia option turns whole hotbar into Dyskrasia 2 when Phlegma is used

### ISSUE THREAD

**Issue by Terroosh** [Nik-Potokar/XIVSlothCombo#203]
Happens when there are no charges of Phlegma remaining

![bar](https://user-images.githubusercontent.com/55752005/151688237-5ea716a9-f2e9-4b4b-908b-2a195ec13b18.png)

![menu](https://user-images.githubusercontent.com/55752005/151688242-9af43cad-0d00-4256-928e-0cc409b4dfff.png)

**Comment by Terroosh** [comment]
I think you forgot to include 

if (actionID == SGE.Phlegma || actionID == SGE.Phlegmara || actionID == SGE.Phlegmaga)

**Comment by Nik-Potokar** [comment]
@Terroosh Should be fixed and Custom Hp values are coming back today
