### ISSUE TITLE
[PLD] Fight or Flight Feature Timing

### ISSUE THREAD

**Issue by Trilkin** [Nik-Potokar/XIVSlothCombo#204]
I know it's still in testing, but right now the weave timing for FoF is too late - especially if you use XIVAlex or NoClippy. It's consistently missing the first GCD since it takes about a third of a second to apply. It should be between the last half and 2/3 of the GCD. Right now it's about in the last 3/4 of the GCD. Maybe having two separate options (early and late weave) would help.

**Comment by Nik-Potokar** [comment]
It was currently only tested on 2.43 sks so thats probably the case of it being late.
I could add a custom for user to input that might help solve the issue.

**Comment by Trilkin** [comment]
Yeah that'd work. Lots of good sets at 2.44 and slower.

**Comment by Trilkin** [comment]
Much better! I'd recommend clarifying in the tooltip that '1' represents one full GCD and the value to be inputted is actually percentages of your GCD rather than hard values.

**Comment by Nik-Potokar** [comment]
Yeah i need to improve the tooltips by a lot :D and they can be sometimes bit hard to explain but il try. Thanks for the suggestion will probably do that!

**Comment by Trilkin** [comment]
Closing this issue since it's technically resolved!
