### ISSUE TITLE
"New and improved" 3.0.0 version issues.

### ISSUE THREAD

**Issue by Genesis-Nova** [Nik-Potokar/XIVSlothCombo#205]
So I updated to the 3.0.0 version and was wondering if this is still a wip?
My mnk bars went to looking like this
<img width="570" alt="image" src="https://user-images.githubusercontent.com/12591123/151689955-e3959741-447b-4167-9847-c1b0e29aadc1.png">
from this (pre-3.0.0)
<img width="591" alt="image" src="https://user-images.githubusercontent.com/12591123/151689977-ca8d812a-c76a-4ce2-ba7b-c40346d0365f.png">

Guessing this is from removing actionIDs from CustomComboPreset?

Happens when I turn on MnkBasicComboPlus btw.

**Comment by ele-starshade** [comment]
Hi @Genesis-Nova

We'll be working through and trying to fix these bugs as they show, sorry for the trouble but the update was necessary to bring some improvements to the plugin.

Keep the reports coming and we'll try our best to fix them asap. :)

**Comment by Nik-Potokar** [comment]
Should be fixed
