### ISSUE TITLE
[BLM] Feature requests

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/XIVSlothCombo#206]
When reenabling and testing all the options now that the core has been updated, I wondered somthing about BLM
-Add Xenoglossy to main combo feature
-Apply and maintain thunder buff (Current needs manual cast, and it will fall off 8/10 times)
-Use Paradox whenever available
-Use Amplifier when available
-Use Manafont after Flare or Despair

**Comment by grimgal** [comment]
#283

**Comment by nativepapaya** [comment]
Seems like all these features have been merged which is nice. When trying out the new update I did notice that the Scathe feature does not work properly if you are synced and do not have FIRE IV.

**Comment by grimgal** [comment]
#290 should fix level sync issues pre Fire IV.

**Comment by nativepapaya** [comment]
Would it be possible to add the option to insert Triplecast into the rotation during the next weaving window? For example, after a Thunder or firestarter usage.
