### ISSUE TITLE
[DRG] Full Thrust Combo Plus tries to use Life Surge even when on cooldown

### ISSUE THREAD

**Issue by Hinkiii** [Nik-Potokar/XIVSlothCombo#207]

**Comment by Nik-Potokar** [comment]
Are you still a LNC and not DRG? since i do know that is the issue if you dont have a jobstone yet

**Comment by Hinkiii** [comment]
I should be I had only updated to the latest version and redid my options for the plug-in. I don't think I tried restarting or disabling/reenabling the plug-in though I won't be able to try for quite a few hours.

**Comment by MTTGamer** [comment]
I notice this issue too. I´m DRG job, not LNC. It tries to use Life Surge even when on cooldown.

**Comment by Nik-Potokar** [comment]
Sorry about the delay had to do some tests and got a fix coming in a few

**Comment by MTTGamer** [comment]
> Sorry about the delay had to do some tests and got a fix coming in a few

Thank you! It´s fixed now! :)
