### ISSUE TITLE
[BRD] Simple bard optimizations

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/XIVSlothCombo#208]
Having done a couple of raids now with all the new stuff, I feel like I have a good idea on the few places where optimizations could be made. The new changes are great though, and it will consistently do better than 80% of people on normal.

2 issues I do find though, are the overwriting of procs and drifting Empyreal Arrow, sometimes by quite a bit.
![image](https://user-images.githubusercontent.com/95890035/151692606-868f9857-8f97-4c75-b8c1-8ca48018379a.png)
![image](https://user-images.githubusercontent.com/95890035/151692611-a70210b8-a8fa-4871-ba09-5ff86b81063c.png)

![image](https://user-images.githubusercontent.com/95890035/151692422-10148e58-c8da-469d-82a3-a2ce0dba2805.png)

https://xivanalysis.com/fflogs/PAhD7rZVnNHMjfaq/1/1
https://www.fflogs.com/reports/PAhD7rZVnNHMjfaq/#fight=last

![image](https://user-images.githubusercontent.com/95890035/151692467-2ebfc56b-031f-4f5b-8458-8eac3000cb43.png)

https://xivanalysis.com/fflogs/rCXhLV6qWRYbHp4n/1/1
https://www.fflogs.com/reports/rCXhLV6qWRYbHp4n/#fight=last

I am loving your work, and if it is too much effort, or just not possible to fix these issues, that is completely fine. Thanks again!

**Comment by ele-starshade** [comment]
Hi @sauronshotdogs! Thanks for the feedback.

Another user has requested Apex and Blast optimisations which I am currently looking at.
I'll investigate the amount of work and/or if it's even possible to control the straight shot ready stuff, might take a little bit of time but I'll keep you updated :)

Thanks again!

**Comment by sauronshotdogs** [comment]
Sounds lovely! I mostly miss my apex arrows, cause I accidentally turn the other way when it decides to fire. This isn't the fault of the combo, as you provided a toggle for manual Apex

**Comment by ele-starshade** [comment]
I haven't seen Pitch Perfect triple weave in the opener, let me have a look at that and see if I can resolve it :)

**Comment by sauronshotdogs** [comment]
It it on both the logs I posted

**Comment by ele-starshade** [comment]
Thanks @sauronshotdogs - I'll look into figuring that out :)

**Comment by ele-starshade** [comment]
I believe I fixed the issue with the triple weaving, will be released with the next version :)

I'll have a look into the rest asap!

**Comment by sauronshotdogs** [comment]
> I believe I fixed the issue with the triple weaving, will be released with the next version :)
> 
> I'll have a look into the rest asap!

Tested changes, works perfectly. No more triple weaving.

**Comment by sauronshotdogs** [comment]
What logic are you using for Apex?

Looking at the balance, this is what they're saying>

`What's the best time to use Apex Arrow?
Ideally, you want to treat it as a pseudo-60s cooldown so that every other one lands in buffs. 

At around 21-19s left in Mage's Ballad, fire it off so long as you have 80 gauge or more. If you get 100 gauge earlier than that, you can Apex then too.

Then, hold on to it until all of your 2-minute buffs are up in Wanderer's Minuet. Even if it hits 100 well in advance of this, just sit on it. It's not worth throwing the timing off.
`

**Comment by ele-starshade** [comment]
Yep we've got that in a diff issue that I'm currently working on. I'll post back here when it's in for testing. Thanks!

**Comment by ele-starshade** [comment]
Just to say sorry this is taking a while, I'm unable to focus on this on work days or my brain will fry :D. Will be looking this weekend!

**Comment by sauronshotdogs** [comment]
No worries. It will come when you have time. Please don't stress about it!

**Comment by ele-starshade** [comment]
Hey @sauronshotdogs - I've pushed some optimisations to BRD's weaving and have made it so that apex/blast fire off at the right times according to balance's recommendations. I've also made it so the weaving works over the top of apex/blast because before it wasn't letting you weave some oGCD's during the blast/apex window as well.

This is all based on the BRD's "Simple Opener" feature toggle, as the opener creates the rotation necessary for this to work. Otherwise it will just default back to "Use it whenever", but with the improvements to weaving still intact.

![image](https://user-images.githubusercontent.com/61023752/152639275-7c950d02-24bf-485c-afd4-2df5dfea5843.png)
Little snippet there of my rotation on a dummy with the new improvements.

Let me know how it goes!

**Comment by sauronshotdogs** [comment]
Having only tested on a dummy so far, the changes seem very very nice.

Could you tell me the times Apex is set to go off, so I don't start  moving during Apex windows

**Comment by sauronshotdogs** [comment]
I know this thread if for BRD, but the new Simple DNC will get stuck on Peloton

**Comment by ele-starshade** [comment]
Why don't you want to move during Apex windows? Apex will always hit the target no matter what direction your facing. (The animation might not, but the animation is just fluff, your character will always turn to face the boss for that second the skill goes off.)

The Simple DNC opener says DO NOT USE. ;)

**Comment by sauronshotdogs** [comment]
Wait really? I always thought I had to stand still and face boss, cause the animation would always shoot off into different directions.

Just thought I'd try out the DNC one

**Comment by ele-starshade** [comment]
https://imgur.com/a/4w1ftbV :)

I'm gonna close this issue now that the apex and such are somewhat fixed. If you do have any more issues in the future or think of any further optimisations, please let me know! :D

**Comment by sauronshotdogs** [comment]
Thanks for all your work!
