### ISSUE TITLE
[ALL] Detection of positionals

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/XIVSlothCombo#209]
I was wondering, since it's possible to detect distance to target, maybe it would be possible to detect your position relative to the target.

Would this be possible, it would allow for combos to switch abilities based on position, or weave in True North whenever you would be about to cast on an incorrect position. 

Just a thought

**Comment by Iaotle** [comment]
https://github.com/aulus-asina/resonant read my mind.
