### ISSUE TITLE
Simple Brd issues

### ISSUE THREAD

**Issue by Djota22** [Nik-Potokar/XIVSlothCombo#210]
Not sure if only me but after 3.0 simple bard is not weaving ogcds, aoe simple bard also using only gcds and the icon is not updating to what action is getting used, it shows only burst shot even thou its using other actions.

**Comment by ele-starshade** [comment]
Hi @Djota22!

Aki has just done quite a big update and we're working on testing. Could you try to re-add your skill to the action bar, as this sometimes fixes these kids of issues.

Let me know if that helps or if you're still having problems and I will try to investigate :)

Thanks!

**Comment by sauronshotdogs** [comment]
I had to put burst shot instead of whichever I had as main combo before. After changing it worked again

**Comment by ele-starshade** [comment]
I've tested both Simple Bard and Simple AOE Bard, and both seem to be working as expected. Please re-seat your skills on your hotbar and let us know if you have the issue still.

Thanks!

**Comment by Djota22** [comment]
I was re-adding the base version of the skill heavy shot instead of the upgraded burst shot, thats why it wasnt working, my bad. Thanks for the help guys.
