### ISSUE TITLE
BRD issue after the last update

### ISSUE THREAD

**Issue by MTTGamer** [Nik-Potokar/XIVSlothCombo#213]
Hello,
If you turn on Simple AOE Bard or AoE oGCD Feature, it conflits with Simple Bard. oGCDs, Songs and Buff stops being applied to single target rotation.

**Comment by sauronshotdogs** [comment]
pretty sure it lists that conflict. Simple stuff usually conflicts with everything else

**Comment by MTTGamer** [comment]
Worked until yesterday before the update. Doesn´t say it conflicts with SimpleBard. AOE combo does conflicts with Simple AOE

![image](https://user-images.githubusercontent.com/98697810/151706055-5dc6b089-0f8c-4d5e-b2a8-40af82c6e53a.png)

![image](https://user-images.githubusercontent.com/98697810/151706062-bf07f407-fc0a-45a1-804f-e9dec7f3eccb.png)

**Comment by RADIANTJIN** [comment]
I'm having the same problem. Simple Bard and Simple AOE Bard cannot be used at the same time.

**Comment by sauronshotdogs** [comment]
![image](https://user-images.githubusercontent.com/95890035/151706599-5cc5ce18-e368-4a06-bd58-1839443f3797.png)
this is what I have enabled, and both work perfectly fine

**Comment by RADIANTJIN** [comment]
I tried following the settings the same way, deleted them, and reinstalled them, but the Simple BARD and Simple AOE BARD still don't work at the same time. I could've used it before the update. What's the problem?

**Comment by MTTGamer** [comment]
> I tried following the settings the same way, deleted them, and reinstalled them, but the Simple BARD and Simple AOE BARD still don't work at the same time. I could've used it before the update. What's the problem? When Simple AOE Bard is released, Simple Bard operates normally.

I think it has something to do with oGCD being placed on the combo, if i turn off Simple AOE and turn on AOE oGCD feature, the same issue happens.

**Comment by sauronshotdogs** [comment]
Reset the correct abilities and try again. See other posts about this issue

**Comment by RADIANTJIN** [comment]
> do

Exactly. When I turn off the oGCD, it works without any problems and I tried to do Reset and everything, it still has problem...

**Comment by RADIANTJIN** [comment]
> 



> > I tried following the settings the same way, deleted them, and reinstalled them, but the Simple BARD and Simple AOE BARD still don't work at the same time. I could've used it before the update. What's the problem? When Simple AOE Bard is released, Simple Bard operates normally.
> 
> I think it has something to do with oGCD being placed on the combo, if i turn off Simple AOE and turn on AOE oGCD feature, the same issue happens.

Exactly. When I turn off the oGCD, it works without any problems and I tried to do Reset and everything, it still has problem...

**Comment by sauronshotdogs** [comment]
Simplebard doesn't work with the oGCD feature

**Comment by ele-starshade** [comment]
We've identified something that causes simple bard to not function properly in different levels based on what skill you've got on your hotbar.

A fix in incoming soon.

**Comment by RADIANTJIN** [comment]
> We've identified something that causes simple bard to not function properly in different levels based on what skill you've got on your hotbar.
> 
> A fix is incoming soon.

As expected, there was an error in something. Thank you for your hard work and I look forward to your correction.

**Comment by ele-starshade** [comment]
This has now been pushed, please update your plugin, and let me know if it's still not behaving as intended and I will re-look.

**Comment by RADIANTJIN** [comment]
> 

I think that it is worked well. Thnaks a lot!

**Comment by MTTGamer** [comment]
> This has now been pushed, please update your plugin, and let me know if it's still not behaving as intended and I will re-look.

i had to logoff from the game now but when i get back i will test it. Thank you!
Based on what Radiantjin said it looks like its working.

**Comment by MTTGamer** [comment]
It´s fixed now! Thank you!!
