### ISSUE TITLE
[BRD] SimpleBard and Heavy->Straightshot level check issue

### ISSUE THREAD

**Issue by Hallrider** [Nik-Potokar/XIVSlothCombo#217]
SimpleBard and Heavy Shot into Straight Shot are putting Burst Shot(lvl76)/Refulgent Arrow(lvl70) on the combo at lower level content

**Comment by augporto** [comment]
It conflicts with one another , you have to chose one or the other , cant have both checked.

**Comment by Hallrider** [comment]
I don't have both checked, its either or.
SimpleBard puts Burst Shot on my bar even though my BRD is lvl60
Heavy Shot -> Straight Shot option puts Heavy Shot, but getting the Straight Shot buff switches it to Refulgent Arrow

**Comment by ele-starshade** [comment]
Hi @Hallrider  - Can you show all the toggles you have on, and I will attempt to fix it for you :) Thanks!

**Comment by Hallrider** [comment]
![afbeelding](https://user-images.githubusercontent.com/96447084/151715895-8a20011c-abef-4ec7-9ba4-38b94b88365c.png)
![afbeelding](https://user-images.githubusercontent.com/96447084/151715940-2e47fdee-0d7f-41c5-b0f3-96ab10440ee7.png)
The only other option i have on is the Simple AoE Bard

**Comment by ele-starshade** [comment]
Hi @Hallrider - Just pushed a fix, can you see if that works now please?

**Comment by Hallrider** [comment]
I just updated and it mostly fixed, ty!. Though SimpleBard now starts with Heavy Shot BUT when im Straight Shot Ready it still puts Refulgent Arrow instead of Straight Shot

**Comment by ele-starshade** [comment]
Ahh, ok, yep I see the problem ,we're not level checking refulgent and using straight shot if it's not high enough.

I'll fix it in a sec and let you know when it's ready to re-test. Thanks for the help!!

**Comment by ele-starshade** [comment]
Pushed another fix @Hallrider - Could you let me know if it's working for you now? :)

**Comment by Hallrider** [comment]
Just tested it, all seems to be working now, ty for fixing it!

**Comment by ele-starshade** [comment]
Wonderful, thanks for testing it again and bearing with us :) If you have any more issues, please let us know!!
