### ISSUE TITLE
[DNC] Features lost after new layout

### ISSUE THREAD

**Issue by PapaSteel** [Nik-Potokar/XIVSlothCombo#219]
The last dancer updates had two overcap protection features that were removed, I'm certain in error, during the SubCombo UI rewrite.

- Fan Dance on Cascade combo when at 4 feather stacks
- Fan Dance II on Windmill when at 4 feather stacks

Not the end of the world if these can't be added back in, but I certainly do miss them.
New layout's gorgeous btw, thanks for making this the best addon anywhere.

**Comment by Nik-Potokar** [comment]
![image](https://user-images.githubusercontent.com/76532587/151720932-c435b8c1-c509-4d5b-be75-449480c71428.png)
Make sure that is is NOT ticked at the top

**Comment by PapaSteel** [comment]
I must be blind.
https://i.imgur.com/9nZPHHj.png
