### ISSUE TITLE
[SGE]  SGE Raise Feature turns back to Swiftcast when Swfitcast's buff is gone

### ISSUE THREAD

**Issue by rushtothesun** [Nik-Potokar/XIVSlothCombo#220]
Supposed to be Swiftcast -> Egeiro > Stay Egeiro until Swiftcast CD is back

Currently once Swiftcast's buff is used or expires it switches back to Swiftcast.

**Comment by goofy-somebody** [comment]
Do you have the Raise feature turned on in "All Global Features" AND "Sage"?

**Comment by Nik-Potokar** [comment]
Added as alternative feature

**Comment by rushtothesun** [comment]
> Added as alternative feature

Out of curiosity, what would you use the original option for?

**Comment by Nik-Potokar** [comment]
Just a personal preference, i prefer Swift turning into rez and not the other way around.
