### ISSUE TITLE
[PLD] Confiteor Feature

### ISSUE THREAD

**Issue by Wyny01** [Nik-Potokar/XIVSlothCombo#223]
Hi , Confiteor Feature on PLD dont seems to work , it dint change my holy spirit / circle with confiteor at any point.

**Comment by Nik-Potokar** [comment]
Can you tell me what features got enabled?
Make sure you got Royal Authority slotted (Not the auto upgraded one) Make sure to drag RA from skill book into your hotbar and it should change

**Comment by Wyny01** [comment]
https://i.imgur.com/fsO7O17.jpeg

Thats the options i have enable / disable , also yes royal authority combo work but the issue here are holy spirit / circle dint transform to confiteor

**Comment by Nik-Potokar** [comment]
![image](https://user-images.githubusercontent.com/76532587/151835515-7b7cdae7-94f0-4dbc-a9c8-30c8a119b014.png)
Tick those 2

**Comment by Wyny01** [comment]
It work but with that i cant use my requiescat earlier in the rotation whitout use holy spells instantly after :(

**Comment by Nik-Potokar** [comment]
it only swaps if you are not under FOF buff since it was made in mind with the early req cast.
There are also standalone features at the bottom
