### ISSUE TITLE
[DNC] Saber Dance

### ISSUE THREAD

**Issue by adreeyan** [Nik-Potokar/XIVSlothCombo#225]
When I have the overcap feature on for Saber Dance, if I get close to capoped esprit it sometimes changes everything on my hot bar to Saber Dance. If I am in the middle of a dance sometimes is locks me out from finishing the dance.

**Comment by Nik-Potokar** [comment]
Hmm which overcap do you have turned on because ive just tested it and i cannot replicate the issue.

**Comment by adreeyan** [comment]
https://i.imgur.com/mmHPQcL.png

It doesnt happen all the time but randomly

**Comment by Nik-Potokar** [comment]
hmm il take a deeper look thanks!

**Comment by rushtothesun** [comment]
> hmm il take a deeper look thanks!

It happens when you have no feathers. As soon as you get a feather it fixes itself

**Comment by Nik-Potokar** [comment]
![image](https://user-images.githubusercontent.com/76532587/151889488-823ec58d-8bdd-4827-be22-7f00d3ef091d.png)
Do you have this one enabled?

**Comment by adreeyan** [comment]
I have that one disabled. Only wanted to use it when its close to capping

**Comment by rushtothesun** [comment]
It's when "Fan Dance Combos" is enabled

probably from this:

```
if (gauge.Feathers == 0)
            {
                if (gauge.Esprit >= 90 && level >= DNC.Levels.SaberDance && IsEnabled(CustomComboPreset.DancerOvercapFeature))
                    return DNC.SaberDance;
            }
```

**Comment by Nik-Potokar** [comment]
> It's when "Fan Dance Combos" is enabled
> 
> probably from this:
> 
> ```
> if (gauge.Feathers == 0)
>             {
>                 if (gauge.Esprit >= 90 && level >= DNC.Levels.SaberDance && IsEnabled(CustomComboPreset.DancerOvercapFeature))
>                     return DNC.SaberDance;
>             }
> ```

Yep!

**Comment by Nik-Potokar** [comment]
Should be fixed now!

**Comment by adreeyan** [comment]
thank you! :D
