### ISSUE TITLE
(Request) Chainspell feature for Redmage in Bozja

### ISSUE THREAD

**Issue by Dedoooo** [Nik-Potokar/XIVSlothCombo#236]
always have Verthunder II, Veraero II and Impact on rotation while under the effect of Chainspell

**Comment by Nik-Potokar** [comment]
Added let me know if it works as intended!

**Comment by Dedoooo** [comment]
forgot to mention the single target rotation as well in my comment but for the aoe it works perfectly! --

 jolt 2 verfire and verstone being replaced by veraero 1 and verthunder 1 while under chainspell tysm!
