### ISSUE TITLE
Machinist - Single target and AoE ability parody

### ISSUE THREAD

**Issue by NikkoToska** [Nik-Potokar/XIVSlothCombo#237]
- Add 'Ricochet & Gauss round overcap protection option' to Spreadshot
I'm setting up my machinist now and going through the options, there don't seem to be ones that behave the same way when dealing with single target and AoE. For example, there's a 'Ricochet & Gauss round overcap protection option' which keeps one charge on both for a burst window, but the 'Always Gauss Round/Ricochet on AoE Option' uses them all.

- Add 'Single Button Auto Crossbow'
There's 'Single Button Heat Blast' that switches Heat Blast to Hypercharge, can you add the option to switch Auto Crossbow to Hypercharge as well?  There's no need for the wildfire or ricochet/gauss round options on AoE.  It's just nice so I don't have to keep a second button just for hypercharge on my AoE bar.

- For 'Single Button Heat Blast' and 'Single Button Auto Crossbow' suggested above, add 'Barrel Stabilizer when below 50 heat'
If you have 0-45 heat, then the order would be: Barrel Stabilizer (option) >> Wildfire (option) >> Hypercharge >> Heat Blast/Auto Crossbow.
If you have 50+ heat, then you only have: Wildfire (option) >> Hypercharge (option) >> Heat Blast/Auto Crossbow.
As I said above, no need for a wildfire option on auto crossbow.

- Barrel Stabilizer drift protection feature doesn't seem to be working, or I'm not using it right.  It doesn't seem to get added to my '(Heated) Shot Combo', but I'd prefer it added to single button heat blast/auto crossbow anyway.

And thanks a lot for all the effort you're putting into this!  I hope you don't mind the suggestions!

**Comment by NikkoToska** [comment]
Things are looking good!  Thanks!  I've tried playing with the changed features and thought of another one.  Would it be possible to add BioBlaster to Flamethrower or Flamethrower to BioBlaster?  If I have both up, I would like to use BioBlaster first before activating Flamethrower.  And there are times when you're near the end of a pack of mobs and you wouldn't want to use BioBlaster, but still have to DPS with the main AoE skill. I think this is a better solution than what I had before, so I'll edit that out.  So...

 - "Alternate BioBlaster Feature" Add BioBlaster to Flamethrower.  BioBlaster is used first whenever off cooldown.

**Comment by Iaotle** [comment]
You aren't supposed to use flamethrower anymore since shotgun is more pps
