### ISSUE TITLE
[DRK] Overcap on AoE & Rotation Fix

### ISSUE THREAD

**Issue by PapaSteel** [Nik-Potokar/XIVSlothCombo#241]
Right now, the (fairly unloved) dark knight has a feature called **EoS Overcap**, which puts Edge of Shadow on the main combo when it's about to drop or when mp would max out. It doesn't have this same feature on the aoe combo however, which would be comfy for dungeon grinding. Having this same option with _Flood_ of Shadow on the Unleash/Stalwart Soul button would be very cool.

The way Delirium has been slotted is also somewhat odd. Right now it just slaps bloodspiller on the main bar as soon as the buff it up.
But ideally it would be on the OGD button, and then the main combo would check to see if the delirium buff was up and insert Bloodspiller x3 between the Hard Slash and Syphon Strike portion of the 1-2-3.

So the OGCD button should (I believe) prioritize as follows;
Living Shadow -> Delirium -> Salted Earth -> Carve and Spit -> Salt and Darkness -> Shadowbringer

It's honestly surprising that nobody's made a single-button rotation for the class yet honestly, since most everything is mashed on cooldown except for blood weapon when that ogcd order is correct.

Additional suggestion: oGCD on main combo #321

**Comment by Iaotle** [comment]
Usually it's because nobody plays the job. And who can blame them, DRK is in a terrible state atm.

**Comment by PapaSteel** [comment]
Somebody updated this job and added the FoS Overcap on aoe - thanks!

**Comment by nativepapaya** [comment]
> Usually it's because nobody plays the job. And who can blame them, DRK is in a terrible state atm.

Unfortunately this is the case. The job just feels awful to play. Everything is super clunky. This amazing plugin helps somewhat but SE really needs to do something.

**Comment by k-kz** [comment]
Addressed pretty much in its entirety, in #429 #437 #442 #444 etc
