### ISSUE TITLE
[RPR] A couple of reaper proposals

### ISSUE THREAD

**Issue by LemonWaffles** [Nik-Potokar/XIVSlothCombo#244]
First of all i'm not yet max level so idk if my suggestions make sense later on, however they are useful under 80.

1. Soul Slice for single target and Soul Scythe for AoE. Both these skills increase the soul gauge so if the gauge is <=50 and the skills are off cooldown they could trigger. 

2. Grim Swathe/Gluttony for AoE gauge overcap. When the gauge is over 50, These skills could pop-up in the AoE combo. 

3. I wasn't able to figure out a way to include a single target overcap as well. It would have to somehow dip into the whole Blood Stalk/Enhanced Gibbets/Gallows and pick the appropriate skill when the gauge is high enough.

**Comment by pynom** [comment]
You mean for some kind of all in one button combo?

**Comment by nativepapaya** [comment]
I also like the idea of automatically inserting Soul/gauge spender onto the main combo.

**Comment by nativepapaya** [comment]
Thank you for adding this, it works! Though currently it only uses 1 of the 2 charges on slice/scythe, would it be possible to modify it so that it uses all charges?

**Comment by nativepapaya** [comment]
I have also noticed that there is no level check in place, so when synced below the level you would have these skills available, the combo will still try to insert them in.

**Comment by Iaotle** [comment]
If you want you can have a crack at implementing the logic yourself. Make a PR and we'll review it :)
