### ISSUE TITLE
PLD Confiteor issue

### ISSUE THREAD

**Issue by armourine** [Nik-Potokar/XIVSlothCombo#247]
feature 125

Confiteor feature does not seem to replace Holy Spirit/Circle when 1 stack remains.

**Comment by armourine** [comment]
If I tick #124, my Atonement/Prominence combos will be replaced by Holy Spirit/Circle and Confiteor correctly, but if I have Holy Spirit/Circle on my hotbars they will not be replaced by Confiteor.

**Comment by Nik-Potokar** [comment]
For that you need to tick the standalone feature for HS/HC and then it should replace any HS/HC on your hotbar with confeti combo

**Comment by armourine** [comment]
Thank you, works as instructed.
