### ISSUE TITLE
[MCH] Drill Behavior with Drill/Air/Chain Saw Feature On Main Combo

### ISSUE THREAD

**Issue by DurzoThorn** [Nik-Potokar/XIVSlothCombo#248]
Currently when this option is enabled Drill is being added onto the main combo when Air Anchor is on cool down regardless of Reassemble state also regardless of Chain Saw cd. The way the feature reads it should only add Drill onto the main combo following the usage of Air Anchor. This could be a useful sub option to prevent drill drift but should be toggleable/stated.

**Comment by Iaotle** [comment]
The way the guy wrote it is super weird, I'm not sure if it should be used at all tbh. I just press them manually.

**Comment by k-kz** [comment]
This issue got away from us a bit - apologies for the delay.
I believe this has been fixed across various updates by @augporto since the post was made - please re-open the issue if this is not the case!
