### ISSUE TITLE
[BRD] Apex Arrow/Blast Arrow in Iron Jaws (suggestion)

### ISSUE THREAD

**Issue by ita238124** [Nik-Potokar/XIVSlothCombo#249]
Hi! There's a main feature that activates Apex Arrow/Blast Arrow in Burst Shot when soul gauge is 100 and that's not very good when you have to hold on to the skills for a little bit of time before entering the burst window. 

I’d like to propose, if possible, to put Apex Arrow/Blast Arrow in Iron Jaws when the gauge is full. There’s already a need to have Iron Jaws in the hotbar for snapshotting the dots during burst windows (the dot maintenance option works amazing when you must renew normally, but for burst window dot renewal there’s a need to go to Iron Jaws manually, since they’re not always running out).

Since during buff windows it is demanded to do Apex Arrow+Blast Arrow+Iron Jaws, it could be nice and effective to have them all in a single button, and that wouldn’t compromise the main dot maintenance option and the main Burst Shot/Refulgent Arrow (with barrage) button.

Thank you very much! I really appreciate the plugin and the work that is done by you all. It’s an incredible accessibility tool for me. Tyvm!

**Comment by ele-starshade** [comment]
Hi @ita238124 - Just to confirm what I think you're asking for;

Iron Jaws to be replaced with Apex Arrow / Blast Arrow *after* Iron Jaws?
or
Iron Jaws to be replaced with Apex Arrow / Blast Arrow *before* Iron Jaws?

I think the option is do-able, and once I've gained some clarity on the above I would be happy to look into implementing a feature toggle for that to happen :)

**Comment by ita238124** [comment]
Hi! Thanks a lot for answering!

I'd like to Iron Jaws to be replaced with Apex Arrow / Blast Arrow when Soul Gauge is at 100. Today, the feature 'Burst Shot/Quick Nock into Apex Arrow' makes the Burst Shot become Apex Arrow when gauge is at 100, but during burst/reopeners, we have to hold on into Apex and Blast before all buffs are up. The feature would be "Iron Jaws into Apex Arrow/Burst Shot when soul gauge is at 100".

Since Iron Jaws have to be in the hotbar for the manual dot renewal during burst, if it became Apex and Blast at gauge 100, we would have these 3 gcd buttons that have to be pressed during burst windows in one slot (Apex, Blast and Iron Jaws).

And that wouldn't compromise the Iron Jaws at all. Since the dot maintenance feature is up, Iron Jaws comes up in the Burst Shot button when it's needed; when it requires manual snapshotting during buffs, it can be done after spending the soul gauge with Apex and Blast. 

Thank you very much for taking the time for the suggestion. I really appreciate it. Tyvm!

**Comment by ita238124** [comment]
I'm sorry, I pressed without intention the 'close with comment' button while posting. I tried to reopen and I think it worked.
Thank you very much!

**Comment by ita238124** [comment]
I've given it some more thought right now about the suggestion and there's more nuance to it. 

I wasn't considering that the Iron Jaws button that is in the hotbar is also the button used to apply the dots in the boss in the beginning of the pull (the Iron Jaws feature).

I think the way suggested to insert Apex and Blast in this button would imply that, at soul gauge 100, you couldn't use Caustic Bite+Storm Bite in a target before spending the soul gauge. It is a trade off worth considering.
On that note, the same thing happen with the main feature 'Burst Shot/Quick Nock into Apex Arrow', you have to use the gauge at 100 with the feature on.

With the main feature, you can't use other gcd or hold on to the gauge for a time after it hits 100; with the suggested feature, you can hold on to the gauge and wait for all the buffs to be up, but you can't use Caustic Bite or Storm Bite before using Apex+Blast.

Thank you very much!

**Comment by ele-starshade** [comment]
Thanks @ita238124 - I'll have a look into the best way to implement it, and let you know when it's available to be tested :)

**Comment by ele-starshade** [comment]
Hi @ita238124 - I've pushed a new toggle under the Iron Jaws feature that adds apex to the same button if the gauge is 100, and blast if blast arrow ready. (Also level checking in there etc). Let me know if that is what you were after! :)

**Comment by ita238124** [comment]
Hihi, I just tested it and it is wonderful! It's working perfectly. 

For everyone that will use it, it's important to be mindful that Iron Jaws is becoming Apex&Blast at gauge 100 and that means that the Iron Jaws that will appear in the Burst Shot main button when the dots are running out (dot maintenance option) is gonna push a Apex&Blast if gauge is 100. That is something that usually happens halfway through Mage's Ballad time (the dots running out and the gauge getting at 100 can coincide). What can be done is to refresh the dots with the Iron Jaws button before the gauge hitting 100, then the button is free to become Apex&Blast. 

Also if you switch target to one without dots with 100 soul gauge, the button will trick you into Windbite, but Apex&Blast will happen. The feature functions the same way the "Burst Shot/Quick Nock into Apex Arrow" does - if you get 100 soul gauge, the button will be compromised with Apex&Blast. But since it's not in the main gcd button, Apex&Blast can be hold for better/optimal times.

The feature is perfect! I really appreciate it and I am thankful for you and your work.
Thank you very much!

**Comment by ele-starshade** [comment]
Wonderful, thanks for your feedback! If you have any more suggestions or observations feel free to post!
