### ISSUE TITLE
[PLD] Atonement Drop Feature

### ISSUE THREAD

**Issue by DurzoThorn** [Nik-Potokar/XIVSlothCombo#251]
I was curious if someone might could explain how to properly utilize either the drop feature or the custom value one. Currently I have a 2.43 GCD and when trying to use either option it simply screws up the entire rotation and does not just skip the 3rd Atonement that is not under FoF I was curious if there might be a way to code the main combo rotation to use 3 Atonements when under FoF and only use 2 when not under FoF. Alternatively if it would be easier to take some directions on how to tune the custom value option that would be great.

**Comment by Nik-Potokar** [comment]
So the way it works right now it checks for your gcd cd.

You are meant to input a value from 0.0 - 1.0 meaning % of your gcd cd (1 meaning full gcd )

Example if I enter:

Low: 0.3
High: 0.6

 This will replace maincombo in-between the gcd cd being 30-60%

**Comment by DurzoThorn** [comment]
So the issue appears to be that while it does drop the 3rd Atonement from the main combo when outside of FoF since atonement stacks stick around for 30 seconds in End Walker it uses the previously dropped atonement after the Goring Blade in the second FoF window which means the second Goring Blade falls out of the FoF buff and doesnt get applied before Holy Spirit takes over the main combo. Essentially it drops the 3rd stack but then still uses it so you have 4 atonements inside the FoF window thus losing your second Goring Blade.

**Comment by Iaotle** [comment]
I know what you're saying, just got old to 80 and it drops the last dot in favor of the magic combo. What's the fix for this, delaying Req by one gcd?

**Comment by DurzoThorn** [comment]
Atonement is lower potency than holy spirit and you don't want to have buff alignment issues later in the fights so the solution is to drop 1 atonement stack so FoF and Req stay lined up on the 1 min rotation. The issue with the Combo right now is with the atonement drop feature it does indeed skip the third usage of Atonement after the Confiteor combo but when since the stacks take 30 seconds to fall off it just uses that skipped atonement later screwing up the next FoF window pushing Goring blade out of the combo.

**Comment by PapaSteel** [comment]
It's rough. Right now, I can't even find a way to really make pld more functional in sloth than other alternatives.

**Comment by PapaSteel** [comment]
The best solution to this is to make a macro that simply cancels the Sword Oath buff. Use it whenever you need to drop the last atonement.
