### ISSUE TITLE
Ignore certain hotbars?  Is it possible?

### ISSUE THREAD

**Issue by NikkoToska** [Nik-Potokar/XIVSlothCombo#252]
I'm not sure exactly how it works so it may not be possible, but can you add an option to ignore certain hotbars?  Some of the stacks, for example, it's hard to see the timers for the other abilities.  I use other hotbars to monitor the time remaining on the cooldown so I can plan my next GCD and oGCDs that I'll use.  For example, on machinest, there's an option to replace ricochet and gauss round with whichever one has the most charges.  If I use this, then I can't see how soon it will be before the other one will come off cooldown, but if I could ignore hotbar 5 then I can drop the abilities there and see the timers for each one while I press the stack on cross-hotbar 1.  Thanks for the consideration!

**Comment by Astelteyn** [comment]
Make macro button with custom name.

**Comment by Astelteyn** [comment]
https://i116.fastpic.org/big/2022/0211/33/d6e697c121b886963d33d1c844fa2333.png

**Comment by NikkoToska** [comment]
Good idea!  Still would be nice to ignore certain hotbars so I don't have to go through the trouble of making and having lots of dummy macros.

**Comment by Iaotle** [comment]
Currently no.
