### ISSUE TITLE
[PLD] missing feature and RA bug

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/XIVSlothCombo#258]
The FoF feature with custom timers references a "normal" fof feature, but I can't seem to find that one.

With the Royal Authority combo, when below 60, it will try to insert RA instead of Rage of Halone into the combo, preventing progress.  Started happening at 53 after getting Goring Blade

**Comment by ele-starshade** [comment]
To make the FoF normal, just shove 0.3 and 0.7 in the inputs :)

**Comment by sauronshotdogs** [comment]
gotcha, thanks!

**Comment by ele-starshade** [comment]
Yeah, 0.3 low and 0.7 high. Donno where the normal one went xD But that will make it like the normal one was.

**Comment by sauronshotdogs** [comment]
Thanks once again

**Comment by DurzoThorn** [comment]
You can make it .6-.75 so that it weaves in during the back half of your weave window this allowing you to fit your final goring blade into your FoF window if it's to early in the weave window ie less than .5 you risk the final goring blade not being buffed by FoF.
