### ISSUE TITLE
[SMN] Lazy Fester Feature Possible Tweak

### ISSUE THREAD

**Issue by DurzoThorn** [Nik-Potokar/XIVSlothCombo#263]
I have been running quite a bit of UCOB in the last few weeks and I was curious if it would be possible to tweak the Fester usage to only trigger when under the effect of Searing Light instead of in between astral impulse gcds. If this is an annoying change or more work than its merit would entail that is cool I was simply curious if that would be a possible enhancement that could be made for fringe scenarios where you would be in Bahamut phase not under Searing Light ie P2S before limit cut or lvl 70 ultimates.

**Comment by Iaotle** [comment]
not a hard change to make.

**Comment by Iaotle** [comment]
Honestly, just press it manually. Whatever changes we make to the lazy fester feature will just break it in edge cases anyway.
