### ISSUE TITLE
[GNB] Option to add Ganashing Fang combo to main combo.

### ISSUE THREAD

**Issue by nativepapaya** [Nik-Potokar/XIVSlothCombo#268]
Currently there is the option to manually start the Ganashing Fang combo before inserting it onto the main combo. This option is nice, but would it be possible to add an option to automatically use Ganashing Fang whenever it is off-cooldown?

**Comment by Iaotle** [comment]
It would be counterproductive. As it is, with most options enabled, you already have only 3-4 buttons on GNB that you need to press. Gnashing Fang combo is supposed to be pressed during No Mercy windows, and not before. With any amount of SPS it will be up before No Mercy, thus making you do it on cooldown automatically is a bad idea.

You could always make a pull request with this feature though.
