### ISSUE TITLE
[MNK] Perfect Balance Memory Leak

### ISSUE THREAD

**Issue by Naab25** [Nik-Potokar/XIVSlothCombo#269]
Tried to use all Healers dps combo, some of reapers combo and monk's combo options and skipped the parts with conflicts and noticed that my FFXIV game has memory leak when this plugin is active. 

My stable 1.8GB ram without this plugin, turning the plugin and playing the game for 5 hours plus spiked FFXIV usage to 6GB+ Ram and I logged off and relog and used the plugin with task manager in front and eating around 0.3MB per 2 secs sometimes with the plugin on afking , doing dungeons and just running around the cities. 

I tried doing dungeons without the add on for 3 + hours and I only reached up to stable 1.8GB Ram 
Used the plugin for 3+ hours and I have 2.6GB Ram usage and still ticking higher

**Comment by Naab25** [comment]
Dalamud Settings also reports a slowly rising memory usage of plugins from 600MB at start of the game to 650MB just by AFking in the inn after a while

**Comment by Iaotle** [comment]
Game is stable on my machine. Doesn't go out of control on RAM. Might be something else. If you can pinpoint a specific option maybe I can help.

**Comment by Naab25** [comment]
![image](https://user-images.githubusercontent.com/6531526/154690171-fe60dfcb-566c-4ca4-887a-e747e470de68.png)
Fresh relog of the game around 492+MB without the plugin stable for 30 min
![image](https://user-images.githubusercontent.com/6531526/154690918-777697ea-e233-40d7-8d45-a3a214dac369.png)
3 Minutes into the game just afk at the inn

**Comment by Naab25** [comment]
![image](https://user-images.githubusercontent.com/6531526/154691247-7c040a0e-2c7f-4c0c-8abe-f20c9d4e885e.png)
These are the options I am using atm ( Monk )
![image](https://user-images.githubusercontent.com/6531526/154691431-f6e19711-e6c6-4a1c-95ac-a835fdd50bb5.png)
Reaper options
![image](https://user-images.githubusercontent.com/6531526/154691556-50fd07fd-5f32-48b2-a457-d99b1cb95a23.png)
Lucid dream and dps options for healer

**Comment by Iaotle** [comment]
3rd time: if you can point to a specific combination of combos or combo that causes this, I can investigate. I'm not investigating 10+ combos.

**Comment by Naab25** [comment]
> 3rd time: if you can point to a specific combination of combos or combo that causes this, I can investigate. I'm not investigating 10+ combos.

Okay Isolating every combo that I turned on since I only turned on healers + Reaper and monk , going to reply back in a few minutes

**Comment by Naab25** [comment]
Found the issue, sorry for any trouble
![image](https://user-images.githubusercontent.com/6531526/154694025-fb71ef4a-db9d-4857-8262-0e21b87d8881.png)
![image](https://user-images.githubusercontent.com/6531526/154694054-3edf8100-bc71-485b-867f-b752dd9de724.png)
its the Perfect Balance Feature plus that's causing the slowly high memory ramp up as seen on the screenshot

**Comment by Iaotle** [comment]
@codesuccubus my dude, feel free to rewrite the parts you have an issue with and submit a PR instead of complaining. No other plugin provides as much functionality as this one.

**Comment by Iaotle** [comment]
I have no idea why it's doing that, the code for BalancePlus seems fine. Maybe remove unnecessary vars? Apart from that idk.

**Comment by Iaotle** [comment]
@Naab25 doesn't leak memory on my end.

**Comment by Naab25** [comment]
> @Naab25 doesn't leak memory on my end.

I disabled every options on the plugin cept for that one and I saw dalamud's settings memory spike and go up slowly, the only plugins I've used so far is from the XIVLauncher ofc I didn't install the original XIV combo plugin so it won't interfere too , I will have to try and Isolate every XIVLauncher plugins to see which ones might be conflicting with this one, might take me longer to reply to this one while I isolate every plugin

**Comment by Nik-Potokar** [comment]
@Naab25 Change logging level in `/xldev` under dalamud tab and "set logging level" to **Fatal** its most likely on verbose or debug and that is making your log file fill up with everything that all your addons do.

**Comment by Naab25** [comment]
> @Naab25 Change logging level in `/xldev` under dalamud tab and "set logging level" to **Fatal** its most likely on verbose or debug and that is making your log file fill up with everything that all your addons do.

Just opened it now in a dungeon and its on information
![image](https://user-images.githubusercontent.com/6531526/154795500-524543ae-042b-4747-b3d7-d292d2fa5bb7.png)
Gonna set it to Fatal and see

**Comment by Naab25** [comment]
I've disabled all plugin and just gonna report my findings here , one the issues only persists when I am on the monk job changing jobs stops the memory leak , 2nd doing the /xldev log level to  Fatal helps a bit but the Ram usage increases from time to time only on monk job but haven't tested it for more then 1 hour so my finding on that part might be wrong . 
I've never used /xldev logging level to Fatal and came as is when I downloaded and reinstalled fresh Dalamud , so for novices looking to use this plugin just for the monk combo might have issues if they have to put the log level to Fatal and might mess up Dalamud if they don't know what they are doing

**Comment by codesuccubus** [comment]
> @codesuccubus my dude, feel free to rewrite the parts you have an issue with and submit a PR instead of complaining. No other plugin provides as much functionality as this one.

why would you think that I'm actually complaining and want this plugin, I'm simply stating this plugin has affected draw times of various people and led to mix ups in a toolchain that doesn't allow these types of modifications in the first place. But do please stare at your RDM section some time and see if that CalcBestAction is really needed. I'm not going to help you do something actively harmful to the plugin community.

**Comment by Iaotle** [comment]
@plapl1 maybe instead of being a toxic ass you should take a second and reflect on how you're basically shitting on code written by someone in their free time, for free, for people to use. If you don't like it for any reason, feel free to not use it. If you have some suggestions instead of being a snarky douchebag you can open up a ticket and maybe people will get around to fixing it at some point. Dick.

**Comment by plapl1** [comment]
salty can't play and can't read the entire intent of the codebase you forked from? act like a dick and you deserve to be treated like one lmao, eat shit.

**Comment by Iaotle** [comment]
I fail to see how any of that should concern me, especially coming from a complete clown
