### ISSUE TITLE
Zadnor Buff Limit

### ISSUE THREAD

**Issue by Astelteyn** [Nik-Potokar/XIVSlothCombo#27]
Fate Looks to Die  For. On boss Ayida rotation stuck on Shadow of Death. Infinity reapeat Shadow of Death.

**Comment by Astelteyn** [comment]
Hedetet same.

**Comment by Nik-Potokar** [comment]
That happens on hunts/Fates due too the debuff (Can be increased with another addon iirc) limit.
To fix this Turn On "Display Only Detrimental effects you inflict"
![image](https://user-images.githubusercontent.com/76532587/146821110-52d2d812-7dfb-4659-a300-5d0bb7b89bcd.png)

**Comment by Astelteyn** [comment]
> That happens on hunts/Fates due too the debuff limit (Can be increased with another addon iirc). To fix this Turn On "Display Only Detrimental effects you inflict" ![image](https://user-images.githubusercontent.com/76532587/146821110-52d2d812-7dfb-4659-a300-5d0bb7b89bcd.png)

That set) But stuck)

**Comment by Iaotle** [comment]
I'm pretty sure there is simply a limit on the debuffs in Zadnor. It's not a UI bug.

**Comment by Astelteyn** [comment]
Well, I just said. This manifests itself only in the dope, so it does not carry any larger inconvenience. Just that you would know, otherwise you never know)
