### ISSUE TITLE
Reaper combo option missing feature?

### ISSUE THREAD

**Issue by Dedoooo** [Nik-Potokar/XIVSlothCombo#271]
"Gallows and Gibbet Option" when enabled also has the Enshrouded full combo set to all buttons however, the alternative option to attack from rear first "Gibbets and Gallows Feature Option" doesn't include the Enshrouded full combo on the slice combo like the first one does.

thank you for this great plugin!

**Comment by Iaotle** [comment]
Yep I noticed this as well, it's a bug

**Comment by damolitionn** [comment]
Whoever wrote it forgot to do a check for Void Reaping, so it was only ever doing Cross Reaping. Put a PR up for it.
