### ISSUE TITLE
[WAR] Infuriate feature alternative request and fell cleave / decimate option bug.

### ISSUE THREAD

**Issue by Cadwgan** [Nik-Potokar/XIVSlothCombo#274]
- Requesting a feature that replaces Fell Cleave and Decimate with infuriate when at 0-40 gauge as an alternative to the current Infuriate feature.
- Fell Cleave / Decimate option is allowing the use of said abilities when under the effect of Nascient Chaos (Infuriate Buff) but not under the effect of Surging Tempest, this is not normally possible and would be detectable server side.

![image](https://user-images.githubusercontent.com/8039241/155836822-4e40a6ea-48f2-4edd-852d-428d8f820173.png)

**Comment by BaexTower** [comment]
I can confirm this bug. 

# 243 Storms Path Combo
# 251 Warrior Gauge Overcap Feature
# 255 Fell Cleave / Decimate Option

When *NOT* under the Storm's Eye / Surging Tempest self-buff.  Options # 251 and # 255 will allow Fell Cleave to activate while buffed with Infuriate / Nascent Chaos.  Fell Cleave must change to Inner Chaos when Nascent Chaos buff is active.

However, when using the "one button combo" of # 243 it won't skip Storm's Eye and let the Surging tempest buff drop, thus Fell Cleave always changes to Inner Chaos.

Very tricky bug to notice.

**Comment by k-kz** [comment]
Fixed in #356
