### ISSUE TITLE
[WAR]Request for additional functionality

### ISSUE THREAD

**Issue by Rigaln** [Nik-Potokar/XIVSlothCombo#278]
I would like the ability to replace Inner Release with Primal Rend while Inner Release is in effect.

**Comment by Iaotle** [comment]
so you can choose the order in which you use IR stuff, right? I like it

**Comment by NikkoToska** [comment]
Sorry this took so long.  I thought the game did that by default, but it turns out I had another plugin doing that for me.

**Comment by k-kz** [comment]
Completed in #391
