### ISSUE TITLE
[RDM] oGCD Feature Everywhere

### ISSUE THREAD

**Issue by hokeenthong** [Nik-Potokar/XIVSlothCombo#284]
First of all, I must thank you guys again for this addon. I cannot thank you guys enough and I am thanking you again. 

This oGCD feature is good. However, the oGCD (Contre and Fleche) should be used after the instant cast of Veraero III or Verthunder III. Currently the button will change to oGCD once it is available and could change in the middle of casting jolt II. Thus, it will cause the button to do Jolt II > Contre or Fletche > Veraero III. For it to be efficient, it should do Jolt II > Veraero III > Contre or Fletch. Could you add a logic to it where dualcast is available, or when casting jolt II / verstone / verfire, the following ability should not change to oGCD. 

Thanks.

**Comment by augporto** [comment]
I added a fix for it to the BRD PR I made, should solve those cases, got to wait it to be merged.

**Comment by hokeenthong** [comment]
Thank you. Look forward to see it in action. Thanks again!!!

**Comment by hokeenthong** [comment]
Thanks @augporto !! Love the update.
