### ISSUE TITLE
[AST] Undraw --> Redraw under the effect of Clarifying Draw

### ISSUE THREAD

**Issue by NikkoXIV** [Nik-Potokar/XIVSlothCombo#288]
If I use the "Draw on Play" feature, drawing a card with the wrong sign and then redraw the wrong sign, I can't use my second draw charge because I still have the card drawn and I can only see "Play".  "Redraw" has no use except under "Clarifying Draw", so this would make the two actions on one button and they shouldn't interfere with each other.  There's no reason to "Undraw" except if you're using "Draw on Play" and you've already used "Redraw"/"Clarifying Draw".  This could be a sub-feature to "Draw on Play" because if they're separate, then you can just use Draw.

**Comment by Sylvansnake** [comment]
When I play Astro, I have a macro that goes like this:

/micon Draw
/merror off
/ac Redraw
/ac Draw

With this macro, it will try to use Redraw, but skip it if Clarifying isn't up, then use Draw instead. I don't often use Undraw, but if you wanted to, you could probably put Undraw as the 3rd command, so if Draw is on cooldown, it would Undraw instead.

**Comment by NikkoToska** [comment]
You can do it with reaction (https://github.com/UnknownX7/ReAction) as well, and much cleaner than using a macro, but I thought it would be a better button combination to make use of two buttons that can only be used exclusively to each other.

I guess an alternative could be "Redraw becomes Draw when a card is drawn and you are not under the effect of Clarifying Draw and Draw is not on cooldown"

**Comment by NikkoXIV** [comment]
I'm gonna close this since there have been changes to AST that I haven't played around with recently, so I don't know if it's necessary anymore.
