### ISSUE TITLE
[SAM] Meikyo Shisui queue

### ISSUE THREAD

**Issue by Sylvansnake** [Nik-Potokar/XIVSlothCombo#291]
Can you add a feature to Meikyo Shisui to queue up Kasha, Gekko and Yukikaze?

**Comment by NikkoToska** [comment]
Just something that may need to be considered.  If you activate Meikyo Shisui with Sen already active, it should skip those ones so you don't waste it.  It may be interesting if the feature could also include Kaiten > Midare Setsugekka > Tsubame-gaeshi on the button before going back to finish Meikyo Shisui with priority based on the time remaining on Fugetsu or Fuka.

**Comment by k-kz** [comment]
Yeah I have planned to cover everything you mentioned there as separate features that you can stack on top of one another for the described chain of logic! Will get there eventually @NikkoToska 😁

**Comment by Iaotle** [comment]
SAM getting some changes, should probably wait until then.

**Comment by k-kz** [comment]
SAM completely reworked as of #569
