### ISSUE TITLE
[DNC] Fan dance 3 and 4 features

### ISSUE THREAD

**Issue by ita238124** [Nik-Potokar/XIVSlothCombo#292]
Hey there. I'd like to ask if there could be a way to make 'Fan Dance 3 Feature' (Replace Fan Dance and Fan Dance 2 with Fan Dance 3 when available) and 'Flourishing Fan Dance 4' (Replace Flourish with Fan Dance 4 when available) available in the slothcombo. They are existent features in the 'XIV combo expanded' (see screen shot).
![dancer](https://user-images.githubusercontent.com/99340837/158237903-5bee6ea1-9df0-4045-88dc-8b00756a72cf.png)

Regarding that, I think the 'Fan Dance Combos' (Change Fan Dance and Fan Dance 2 into Fan Dance 3 while flourishing) available in the plugin used to do exactly what the 'Fan Dance 3 Feature' does, but it doesn't seem to be doing that. Fan 1 and 2 are not changing to 3 with the option turned on.

Thank you all very much for the work in the plugin!

**Comment by kiaramasai** [comment]
> Hey there. I'd like to ask if there could be a way to make 'Fan Dance 3 Feature' (Replace Fan Dance and Fan Dance 2 with Fan Dance 3 when available) and 'Flourishing Fan Dance 4' (Replace Flourish with Fan Dance 4 when available) available in the slothcombo. They are existent features in the 'XIV combo expanded' (see screen shot). ![dancer](https://user-images.githubusercontent.com/99340837/158237903-5bee6ea1-9df0-4045-88dc-8b00756a72cf.png)
> 
> Regarding that, I think the 'Fan Dance Combos' (Change Fan Dance and Fan Dance 2 into Fan Dance 3 while flourishing) available in the plugin used to do exactly what the 'Fan Dance 3 Feature' does, but it doesn't seem to be doing that. Fan 1 and 2 are not changing to 3 with the option turned on.
> 
> Thank you all very much for the work in the plugin!

To follow up, specifically the feature shows as available (number 50) but it does NOT do anything at all. Fan Dance 1/2 do NOT convert to 3. This works in native XIVcombo and extended versions but for some reason doesn't in this one (which I quite like for other features). 

If this can be addressed that would be amazing. My muscle memory hates me right now, lol.

Thanks!

**Comment by k-kz** [comment]
Fixed (and enhanced) in #306
