### ISSUE TITLE
[WAR] Storms Path / Eye Combo Enabled when no options selected.

### ISSUE THREAD

**Issue by ShennyUK** [Nik-Potokar/XIVSlothCombo#293]
Despite having no options selected the storms eye / path combo is still present on my bar. Have switched jobs and logged out multiple times to clear it. Only disabling the plugin returns it to normal.

(Bottom icons are in order Heavy Swing, Maim, Storms Path, Storms Eye.)

v3.0.6.7

![image](https://user-images.githubusercontent.com/43541965/158349365-02598001-13ca-4bd7-b253-956dee7a74d6.png)

**Comment by Iaotle** [comment]
maybe fixed
