### ISSUE TITLE
NIN: #125 Assassinate feature bug

### ISSUE THREAD

**Issue by Sylvansnake** [Nik-Potokar/XIVSlothCombo#294]
I think Ninja feature #125 is hooked to the PVP version of Assassinate. Whenever the skill comes up, I get a notice that it can't be used outside PVP.

**Comment by Nik-Potokar** [comment]
I'm having a hard time replicating the issue and i have every option turned on.
Can you replicate it and if so how?

**Comment by k-kz** [comment]
No longer relevant in 6.0 - feature has been replaced/revamped by @Taurenkey
