### ISSUE TITLE
[DNC] Flourish on Combined Dance Feature timing

### ISSUE THREAD

**Issue by dawn-star** [Nik-Potokar/XIVSlothCombo#299]
![image](https://user-images.githubusercontent.com/37399509/159778638-4bf2343f-fa0a-4530-ba00-7467dc5a2f84.png)

As it is now, Flourish will pop up as usable between Standard Finish and Starting Technical Step.

It would be nice if the timing of Flourish came after Devilment and Starfall Dance to align with the standard opener :)

![image](https://user-images.githubusercontent.com/37399509/159786463-adc482c8-a56b-440b-854c-55d9de269d59.png)

**Comment by k-kz** [comment]
This is currently intentional, as it's possible to single-weave Flourish in between SS and TS, so your procs are ready immediately after Starfall Dance.

Doing the above should also reduce negative effects from drifting Flourish if you're not using the SimpleDancer Features.

**Comment by k-kz** [comment]
After a bit of digging, it seems like the pre-Tech Flourish is only a plausible option when your ping is low enough to allow it to be weaved in that space without a hard clip.

Will look into defaulting Flourish to weave after Devilment and consider early `LowPingFlourish` as a sub-option, or something.

**Comment by k-kz** [comment]
See above [comment](https://github.com/Nik-Potokar/XIVSlothCombo/issues/299#issuecomment-1077297705) edit.

> After lots of back-and-forth and testing, the feature will weave `Flourish` before `Technical Step` in the opener (thus, throughout) if your latency is low enough.
If not, it will be held, and used as displayed in the above opener from The Balance.
No optimisation is lost in either regard.
