### ISSUE TITLE
Recent update (3.0.7.1?) broke reaper AOE

### ISSUE THREAD

**Issue by thisischrys** [Nik-Potokar/XIVSlothCombo#301]
I just updated and "Scythe Combo" is no longer working for reaper.

If I enable "Whorl of Death" that still gets added to the button, but after the initial Whorl it just spams "Spinning Scythe" and never goes to "Nightmare Scythe".

I have already tried switching classes and reslotting "Spinning Scythe".

**Comment by k-kz** [comment]
Will look into this asap, but had no issue personally executing full AoE rotations in Lv90 dungeons earlier today

#297 broke it I think - some minor changes have been pushed to main branch in #298 but not in-game yet so maybe that's why I couldn't replicate

**Comment by k-kz** [comment]
Fixed in #302 along with loads of other stuff. Enjoy!
