### ISSUE TITLE
[WAR] Option (Infuriate on Fell Cleave/Decimate when below 50 Beast Gauge)

### ISSUE THREAD

**Issue by NikkoToska** [Nik-Potokar/XIVSlothCombo#308]
I think it would make sense to combine Infuriate with the Beast Gauge abilities when below 50 Beast Gauge to prevent overcap.  How it is right now, there's still a chance to overcap if you get to 60 and press Infuriate, even when using the Overcap Feature and the Fell Cleave/Decimate Option.  And while there is an Infuriate Feature, because it puts fell cleave on Infuriate, you would still need to have Decimate somewhere.  So I'm hoping that you can add "Infuriate on Fell Cleave/Decimate when below 50 Beast Gauge" as an option.

**Comment by k-kz** [comment]
Fixed in #373
