### ISSUE TITLE
[BLM] #34 "Blizzard 1/2/3 Feature" uses wrong Blizzard 2

### ISSUE THREAD

**Issue by Tsusai** [Nik-Potokar/XIVSlothCombo#314]
I had this option on last night. "Freeze becomes Blizzard 2 when synced" kicked in, but it was the disabled pre-Endwalker Blizzard 2, not the current version of Blizzard 2.

**Comment by Tsusai** [comment]
I think this is the relevant spot

Lines 94-99
https://github.com/Nik-Potokar/XIVSlothCombo/blob/main/XIVSlothCombo/Combos/BLM.cs#L94-L99

My limited knowledge, I think is this would be the correct code:

            if (actionID == BLM.Freeze && level < 40) //Freeze is level 40 now
            {
                //return 146u; // The original Line. Not sure what this value is.
                return BLM.Blizzard2; // I think this is the correct response, using the structure at the top for the correct value?
            }

            return actionID;

**Comment by k-kz** [comment]
Yeah it's legacy code from Shadowbringers. Thanks for the submission!
