### ISSUE TITLE
[BLM] Paradox meme rotation

### ISSUE THREAD

**Issue by cupcake121** [Nik-Potokar/XIVSlothCombo#319]
This really shouldn't be prioritized, but in case anyone wants to have some fun with BLM and dares tackle this insanity this is the opener & rotation 

![FHhIg7XagAQZ2wg](https://user-images.githubusercontent.com/102629921/160715106-bbf36125-b49a-4f21-88a3-075403e349c0.jpg)
![FG4b1FmaAAMmycC](https://user-images.githubusercontent.com/102629921/160715113-86efc73d-3b76-4afb-8220-115a28471552.jpg)

**Comment by k-kz** [comment]
Note: Endwalker Paradox meme rotation

**Comment by Iaotle** [comment]
Can we not do this?

**Comment by k-kz** [comment]
> Can we not do this?

Why not?

**Comment by grimgal** [comment]
#638

**Comment by k-kz** [comment]
Addressed in #638
