### ISSUE TITLE
[DRK] oGCD feature on main combo

### ISSUE THREAD

**Issue by Dedoooo** [Nik-Potokar/XIVSlothCombo#321]
maybe or maybe not for now.. better to wait until LL announcement to see if DRK will get some love.

this feature already exists on the oGCDs themselves but it would be nice to have it on the main combo! Thanks devs 💟 !

**Comment by Iaotle** [comment]
Duplicate feature of another oGCD suggestion https://github.com/Nik-Potokar/XIVSlothCombo/issues/241
