### ISSUE TITLE
[RDM] SimpleRedMage issue: fake verstone/verfire when mana >=50

### ISSUE THREAD

**Issue by LittleNightmare** [Nik-Potokar/XIVSlothCombo#325]
when mana>=50, close to target,
the action would change to
![4VF8}$@J LY%LL4RRY`TQ G](https://user-images.githubusercontent.com/19811879/160936424-307514ef-c826-4cae-98ae-917b639fc83a.png)
however, above verstone is fake, it would cast melee combo at my first press.
if i wait a few seconds, above verstone become real, or at my second press

i casuse i cannot dalay melee combo when i close to target.

if this is a feature (really?), i hope enhancement preferences that i can choice dalay melee combo or use immediately

**Comment by augporto** [comment]
@LittleNightmare what features do you have activated ? I just tested here and it not happens to me .

**Comment by augporto** [comment]
@LittleNightmare from what i gathered here, its a conflict with `Smart Single Target`.

Could you confirm for me that disabling it solves it?

**Comment by LittleNightmare** [comment]
> 

it work but i still need delay the melee combo.

therefore, this issue become:

1. hope: add notice that there is a confict between `Simple Red Mage Feature Single Target` and `Smart Single Target`
2. hope: add a delay melee combo option to `Simple Red Mage Feature Single Target`

**Comment by Sylvansnake** [comment]
The melee switch option is a little touchy, as noted in the plugin feature. If it's difficult for you to deal with, I'd recommend just using a different button for the melee combo. It may not be possible for them to fix the issue 100%. But I may be wrong, I don't know the inner workings of these plugins.

**Comment by k-kz** [comment]
No longer relevant (hopefully!) as of #649
