### ISSUE TITLE
[NIN] Option to disable Doton on Simple Aoe

### ISSUE THREAD

**Issue by cupcake121** [Nik-Potokar/XIVSlothCombo#327]
Everything works nicely with the AoE combo, it's just that during pulls, if you want to aoe, doton gets used, you place the circle on the ground and the tank keeps running forward to pull more mobs and you wasted your thingy for nothing.

If you wait till the pull is over to use aoe skills so doton won't be wasted, you're losing a lot of dps.

As a workaround i would just use single target mudras and once they're spent i'd switch to aoe skills so i can aoe on the move with no issues.

___

So yeah, would be nice to have the option to disable doton.

**Comment by Taurenkey** [comment]
Should be addressed in #365 @k-kz

**Comment by k-kz** [comment]
Fixed in #365
