### ISSUE TITLE
[AST] [Additional Enhancement] Earthly Star Feature

### ISSUE THREAD

**Issue by Stockei13** [Nik-Potokar/XIVSlothCombo#328]
Suggestion: Would it be an option to implement the star placement as its off-cd? Its normally placed (on a static rotation) 3-5 seconds before the fight starts, so the option ticked wouldnt influence the opener. 

Most people use some kinda of "Mouseover - 1 - click"-Plugin like Mouseover action plugin or an ingame macro, and since EW, even if you would place it at the side of the arena, 30y range would not make its placement even matter.

Additional Info: The Additional (second) effect of earthly star, which it changes to (Stellar Detonation), shouldnt be triggered by the option.

Its priority should be pretty high and similar to card draw/minor arcana draw, as u wanna line it up pretty straight with your 2min (it has 1min cd).

Greetings/thanks A LOT!

Stocke

**Comment by Stockei13** [comment]
Oh okay - thanks still for the reply! I thought, if the dot's cd is tracked smh, this should be possible as well! But u never can learn enough :) @k-kz , it can go into backlog then!

**Comment by Iaotle** [comment]
oh wait you mean to place it immediately?

you don't wanna do that friend. cooldowns like that should be placed on specific damage spikes

**Comment by Stockei13** [comment]
Good point, ill try that! Is prolly a good case to get used to it! :)
