### ISSUE TITLE
[Tanks] Reprisal Feature

### ISSUE THREAD

**Issue by Alkeyd** [Nik-Potokar/XIVSlothCombo#329]
There would be a way to put some feature in which if my target is under the effect of Reprisal my Reprisal is disabled or becomes something like Low Blow, avoiding using a double Reprisal, the same would work for Feint and Addle.

Thank you!

**Comment by PapaSteel** [comment]
This would actually be really helpful.

**Comment by Iaotle** [comment]
@Alkeyd Faint is when you fall unconscious. Feint is like a false attack. ;)

**Comment by Alkeyd** [comment]
> @Alkeyd Faint is when you fall unconscious. Feint is like a false attack. ;)

![image](https://user-images.githubusercontent.com/94228374/161368649-accd202e-f28c-4488-bd4a-a13f2eb2f790.png)

I was confused, I was talking about this action here

**Comment by k-kz** [comment]
Addressed in #425
