### ISSUE TITLE
[MCH] Simple Single Target / Simple Reassembling possible bug

### ISSUE THREAD

**Issue by Cadwgan** [Nik-Potokar/XIVSlothCombo#338]
At lv76-89 reassemble is not being used on Drill, only on Air Anchor, is this intentional?

>                if (IsOffCooldown(MCH.Drill) && level >= MCH.Levels.Drill)
>                {
>                    if (IsEnabled(CustomComboPreset.MachinistSimpleAssembling) && level < MCH.Levels.AirAnchor && 
>                        !HasEffect(MCH.Buffs.Reassembled) && GetRemainingCharges(MCH.Reassemble) > 0)
>                    {
>                        return MCH.Reassemble;
>                    }
>                    return MCH.Drill;
>                }

Seems a bit of a waste to limit Reassemble to every ~80s between lv76-89.

**Comment by augporto** [comment]
It was intended to be that way, to make the most use of the potency gain , since AA is 40s and Drill is only 20 , the same way that at 90 the reassemble is used on CS , except the 1st one for AA , since with 60s CD you will want it to CDh no matter what.

**Comment by Cadwgan** [comment]
I may be missing something here, but considering all 3 have the same potency it feels like a waste to basically throw 1 use out of 4 in the bin by limiting it to only AA in that level range, when it can be used on either.

**Comment by Iaotle** [comment]
I mean if @augporto says it's higher pps I trust him xD
