### ISSUE TITLE
[SCH] Biolysis combo

### ISSUE THREAD

**Issue by Iaotle** [Nik-Potokar/XIVSlothCombo#34]
Apply Biolysis to target when < 5 seconds remain.

**Comment by Iaotle** [comment]
Should replace Ruin II instead of Broil so it has no drawback.

**Comment by damolitionn** [comment]
Just curious about the logic of putting it under Ruin II instead of Broil and less than 5 seconds. Talking optimally, like WHM's option, it's better to refresh DoTs at 3 seconds than 5 seconds so you can get one last tick of it and, in regards to Ruin II, I might be overthinking it but I'm not sure where the drawback would be in putting it under Broil and not Ruin II, seeing as with the faster cast times Ruin II's been relegated to a movement tool instead of a weaving tool.

**Comment by Iaotle** [comment]
The GCD is 2.5 seconds, so < 3 would also be fine.  < 5 ensures that you have some time to react to the need for refresh, since it's not on a button that you are pressing regularly.

The logic for putting it on Ruin II is to avoid applying biolysis unintentionally. DoTs are mostly applied when they can tick for the full duration. In some cases you want to cast Broil one last time instead of casting a DoT that won't do any damage. 

Since you have an instant in Ruin II that you have to slot anyway, I don't see a reason why you wouldn't just make it a multipurpose tool.

**Comment by damolitionn** [comment]
I see, but how would Biolysis be applied unintentionally if it's triggered to refresh at < 3 seconds/< 5 seconds when it has ticked for its full duration, or at least 1 tick less for 5 seconds (as DoTs tick at 3 second intervals)? Unless I've overthought this and you'd be Broiling over placing a DoT as your final spell and you're chasing a parse?

Either way, I'll have a PR up for it on Ruin II in a few hours after I finish with work.

**Comment by Iaotle** [comment]
It's more about "oh, I need to dot" taking a second to click IMO. But either way should be fine.

**Comment by Nik-Potokar** [comment]
Still needs improvement aka same as whm/ast dps feature
But for some reason wont work at all Broil Skills (Acting Like their ID is wrong)

**Comment by damolitionn** [comment]
I added Biolysis to Ruin II as requested, so it won't work on Broil/Ruin at all. I still think it should be on Broil though which would make it easier to work at all levels seeing as Ruin II is only available at 38 and above
