### ISSUE TITLE
[SAM] Shoha & Shoha II feature option for single target & AoE combo

### ISSUE THREAD

**Issue by Stiopka** [Nik-Potokar/XIVSlothCombo#342]
There is a option for single and aoe combo to add senei and shinten or guren and kyuten to their combo but i didn't saw a option to add shoha and shoha II when meditation is full. is this possible or does that even make sense?

**Comment by Iaotle** [comment]
No clue, ask SAM mains :)

**Comment by Stiopka** [comment]
would it be possible to add that as a extra feature option to the one button combo for single and aoe combo? so you can choose if you want it in the combo or not, so you use immediately the 3 meditation stacks if their are full
