### ISSUE TITLE
[DRG] Unusual Interraction + Suggestions

### ISSUE THREAD

**Issue by S13XIII** [Nik-Potokar/XIVSlothCombo#345]
~~When using the "Full Thrust Combo Plus" feature while sync'd down to any level under 90, High Jump will be weaved after Full Thrust. This isn't advertised in the feature, neither is it optimal in certain duties. Either removing that, or making it a toggle would work, to give users the freedom of choice.~~

Suggestion:

Making Life Surge integration into "Full Thrust Combo Plus" optional. That helps in certain scenarios like P3S add phase, where you want to hold most oGCDs and buffs for a reopener after the phase is over.

**Comment by k-kz** [comment]
Bug fixed in #353 
Feature addition incoming

**Comment by k-kz** [comment]
Added in #408
