### ISSUE TITLE
[MNK] Riddle of Fire & Brotherhood outside of Perfect Balance

### ISSUE THREAD

**Issue by Stiopka** [Nik-Potokar/XIVSlothCombo#349]
hi, is that only supposed to be used when perfect balance is active? in my opinion it would make more sense if it get used off cooldown without PB used for that so u get more out of it. Maybe a extra option for the "basic rotation plus".

**Comment by Stiopka** [comment]
![image](https://user-images.githubusercontent.com/73742622/162042775-6378fc11-d00b-48de-b3b6-59d76503c833.png)
I mean this option, why only using the buffs when perfect balance is up. Doesn't it make sense to keep the buffs active without using perfect balance?

**Comment by grimgal** [comment]
Addressed in #456
