### ISSUE TITLE
[Multiple Jobs] Some features from other plugins

### ISSUE THREAD

**Issue by Megasder** [Nik-Potokar/XIVSlothCombo#355]
I tried to write them in the discord, but they told me to put a issue here to better management, so here we go:

## AST:
1. ~~Helios becomes Lady of Crowns when avaiable.
(With the lazy lord feature Lord of Crowns is used automatically in your combos, but you dont have any way to use Lady of Crowns except that you use a hotbar sloth for Crown Play, so instead Lady of Crowns is like a OGCD version of helios.)~~

## DRG:
1. ~~Replace true/raiden thrust and doom spike/draconian furry with Wyrmwind Thrust.~~
2. ~~Nastrond replaces Stardriver when in life of the dragon, and when you are not in life of the dragon it becomes geirskogul~~

## MNK:
1. ~~Make that out of combat every GCD skill becomes meditation, so you always have all the meditation stacks before starting the fight~~
2. ~~When you are out of combat and have all meditation stacks, bootshine becomes Form Shift (so you always start the fight with raptor form)~~

## PLD:
1. ~~Replace Shield Bash with Low Blow (and make it work with the interrupt feature, the priority should be like this (Interject > Low Blow > Shield Bash))~~

## RPR:
1. ~~When the bloodsown circle buff ends and you have at least 1 stack of immortal sacrifice, slice combo becomes plentiful harvest~~
2. ~~An addition for the above to not overcap shroud gauge, if you have >= 50 shroud gauge and you have at least 1 stack of immortal sacrifice, slice becomes enshroud, so when you exit the enshroud transformation slice combo will become plentiful harvest (thanks to the option above), so you will gain again the 50 shroud gauge that you just used.~~

## RDM:
1. ~~Replaces embolden with manafication if the former is on cooldown and the latter not (just to reduce a hotbar. it should be embolden > manafication)~~
2. ~~Add lucid dreaming to the combos if your mana is less than 8000/9000~~
3. ~~Add the Swiftcast to raise feature too.~~

## SAM:
1. ~~Replace Ikishoten with Ogi namikiri and then kaeshi namikiri~~
2. ~~Replace tsubame-gaeshi or iaijutsu with Ogi namikiri and then kaeshi namikiri if you have ogi namikiri ready~~

## SCH:
1. ~~Change every action that requires aetherflow into aetherflow if you have no aetherflow stacks (exception: Indomitability and Excogiation became avaiable if you used Recitation)~~
2. ~~Fairy feature additional option. Instead of summon Selene you summon eos (The text is wrong in the actual feature, you summon selene, not eos like the feature says)~~

## SMN:
1. ~~Change every action that cannot be used without summoning the carbuncle will become summon carbuncle if is not summoned.~~
2. ~~Add lucid dreaming to the main combos~~
3. ~~Add the Swiftcast to raise feature too.~~

## WHM:
1. ~~Holy/Holy 3 with afflatus misery is ready to be used and you are targeting someone (so if you dont have any target you still can use Holy)~~

**Comment by k-kz** [comment]
Can't speak for the other jobs - I skipped straight to RPR since that's something I've done work on - both features requested there are already planned for!

Great writeup, thanks for taking the time :]

**Comment by k-kz** [comment]
PLD Request handled in #354

**Comment by Iaotle** [comment]
SMN:
1. I don't think this is useful since Egi already on your R3 combo. Why make bars ugly when you can avoid it?
2. Sure, but honestly you can't run out of mana on this job if you very occasionally press it. Maybe if you raise, but you never have swift up on SMN if you are playing it right.
3. Raise feature exists and works already.

**Comment by Megasder** [comment]
1. I suppose you are right, it makes the hotbar ugly, however it only makes it ugly if you dont have the egi out, and that is only if you have changed job since you want your egi up all times, so if you forgot to summon your egi and wanted for example to shield yourself, instead of doing nothing it will summon the egi. Is more for players like myself that like to change jobs a lot and forgets about the summon XD but I can live without it.

2. I normally dont run out of mana too, however if the fight is long or in dungeons I loss more than half my mp, that is why I was asking 

3.I can't find it XD the only Swiftcast features I see are from Garuda and Ifrirt, nothing about Swiftcast Resurrection

**Comment by Iaotle** [comment]
Oh yeah SMN Raise might be gone because I had a global raise working at the time.

**Comment by DurzoThorn** [comment]
> 1. I suppose you are right, it makes the hotbar ugly, however it only makes it ugly if you dont have the egi out, and that is only if you have changed job since you want your egi up all times, so if you forgot to summon your egi and wanted for example to shield yourself, instead of doing nothing it will summon the egi. Is more for players like myself that like to change jobs a lot and forgets about the summon XD but I can live without it.
> 2. I normally dont run out of mana too, however if the fight is long or in dungeons I loss more than half my mp, that is why I was asking
> 3. I can't find it XD the only Swiftcast features I see are from Garuda and Ifrirt, nothing about Swiftcast Resurrection

I think the mana issue is way more prevalent in synced content at lower levels like ultimates as I can go oom in the first 3 mins if I forget a lucid.

**Comment by Iaotle** [comment]
swift for smn done in k's repo

**Comment by grimgal** [comment]
MNK #456 should address changing Bootshine to Meditation/Form Shift.

**Comment by k-kz** [comment]
AST request done in #370

**Comment by NikkoXIV** [comment]
@k-kz I think RDM and WHM can be crossed off.  WHM isn't really solved how it's written, but the AoE feature will show holy and assize when targeting yourself and misery when you're targeting an NPC.  So it's holy to misery instead of misery to holy.  And misery to holy would be weird since misery does nothing 99% of the time.

**Comment by k-kz** [comment]
DRG is the only thing remaining now.
We'll address those points once we get to really cleaning up the DRG file and reworking the dives features etc. (pending)

**Comment by k-kz** [comment]
Final `DRG` stuff should have been addressed in #895!
