### ISSUE TITLE
[RPR] Shadow of Death feature doesn't check level

### ISSUE THREAD

**Issue by KalasB** [Nik-Potokar/XIVSlothCombo#357]
When synced down (Deep Dungeon), the Shadow Of Death feature will put SoD into your combo regardless of whether you can use it (level 10+).

**Comment by k-kz** [comment]
Can't believe I missed that! Easy fix, thanks for pointing it out.

**Comment by k-kz** [comment]
Fixed in ad34fd3f842c45cc876d7f213eddff50fddba7df
