### ISSUE TITLE
[GNB] Rough Divide Option not working as intended

### ISSUE THREAD

**Issue by Megasder** [Nik-Potokar/XIVSlothCombo#358]
Rough Divide Option (leaves 1 stack) doesn't work as intended, it only works if you have 1 stack and then it leaves you with 0 stacks (so if you have 2 stacks, it will never use it, and when you manually use the skill to have 1 stack, it will use it in the combo and leaves you with 0 stacks)

**Comment by k-kz** [comment]
Fixed in #367
