### ISSUE TITLE
[RPR] Gibbet and Gallows Loss Avoidance Feature

### ISSUE THREAD

**Issue by Astelteyn** [Nik-Potokar/XIVSlothCombo#36]
Make Blood Stalk and Gluttony swap to Gibbet and Gallows if they're up. Done to avoid pressing BS/Gluttony twice in a row.

**Comment by Iaotle** [comment]
Ты русский? Вообще ничего не понятно что ты пишешь.

I can't understand what you're saying fam.

**Comment by Astelteyn** [comment]
> Ты русский? Вообще ничего не понятно что ты пишешь.
> 
> I can't understand what you're saying fam.

Да)
В принципе я о чем.
Было бы удобно если бы Blood Stalk и Gluttony  менялись на Gibbet и Gallows, если  Gibbet и Gallows доступны для прожатия.
Лично я часто слакаю и могу прожать 2 подряд в итоге не получив ничего, т.к. при повторном прожатии Blood Stalk или Gluttony минусуется стак Soul Reaver.
