### ISSUE TITLE
[NIN] Hakke Mijinsatsu (AoE Combo) Missing

### ISSUE THREAD

**Issue by SkyChotik** [Nik-Potokar/XIVSlothCombo#364]
Unless I'm blind and not seeing it, I can't seem to find the combo for it out side of the Simple AoE option.

**Comment by Dedoooo** [comment]
it was replaced with Simple AoE. there was a discussion about making simple aoe have options to not include the other stuff and only the combo on discord

**Comment by k-kz** [comment]
This might be a mistake, to be honest. @Dedoooo is correct - but our plans were to create the `Simple` stuff as fully-conflicting with other options, and an "either-or" sort of thing.
Basically, I'm pretty sure this shouldn't have been taken out when it was added to the `Simple AoE` stuff.

@Taurenkey has been doing MAJOR work on NIN recently - they'll likely address this very soon.
Thanks for the submission!

**Comment by Taurenkey** [comment]
It's on my to do list at some point. Probably sometime this week.
