### ISSUE TITLE
[RPR] Soul Slice Option will break Soul Reaver

### ISSUE THREAD

**Issue by NiGuangOwO** [Nik-Potokar/XIVSlothCombo#366]
when you have Soul Reaver ,but at the same times all the Soul Slice are off cooldown,it will replace the Slice Combo to break Soul Reaver
https://user-images.githubusercontent.com/26338524/161513962-72b9c99b-aff3-41bf-814a-75e43c21b7e3.mp4

**Comment by k-kz** [comment]
Thanks for the submission - I'd never encountered that one as I never let Soul Slice get back up to two stacks after I begin combat!

Will be dealt with soon o/

**Comment by k-kz** [comment]
Fixed in ad34fd3f842c45cc876d7f213eddff50fddba7df
