### ISSUE TITLE
[BLM] Opener breaks on interruptions

### ISSUE THREAD

**Issue by grimgal** [Nik-Potokar/XIVSlothCombo#375]
The opener breaks if it's interrupted. It shouldn't do that.

**Comment by Sylvansnake** [comment]
I've noticed that the BLM AOE Combo Feature seems to also affect the single target rotation. It seems to be a bug in which activating the AOE feature changes Scathe. I don't think it's supposed to do that. It may be part of the reason the single target combo keeps breaking.

**Comment by Iaotle** [comment]
probably something to do with OriginalHook again...

**Comment by S13XIII** [comment]
Most likely, I had an issue with Simple Dragoon on an ability that calls on OriginalHook.

**Comment by k-kz** [comment]
Fixed in #382
