### ISSUE TITLE
[BLM] if at level 58 but having not done quest blizzard IV adds Blizzard 3 to einochen stance switch++

### ISSUE THREAD

**Issue by AoiYui** [Nik-Potokar/XIVSlothCombo#379]
details: when i leveled up to 58 mid dungeon i noticed the stance switcher added blizard IV to the rotation despite me not having done the quest. I know this is a pretty minor bug and thus likely is low priority but since the conditions are kinda hard to meet and as a result is unlikely to be discovered I thought I'd let you know.

How to replicate: 
step 1: level up to 58 on a black mage without doing the level 58 quest
step 2: go through your rotation until you bit blizard 4 
that's it as far as i know it was seemingly 100% successful
 
PS: completely unrelated but can you put the changelog somewhere easier to find I can't seem to find it.

**Comment by k-kz** [comment]
Also, I'm not entirely sure whether we can check for something like quest completion - the only solution may well be to just go and get `Blizzard IV` unlocked.
Even if it's a plausible thing to check for, it's an extreme edge-case and is unlikely to be addressed.

I'm going to leave the thread open for the time being, as there are more experienced devs who can potentially weigh in, but I'm likely to close this in the near future.
