### ISSUE TITLE
[BLM] [Feature Request] manafont during aoe combo for triple flare

### ISSUE THREAD

**Issue by AoiYui** [Nik-Potokar/XIVSlothCombo#381]
hey i was wondering if you could add manafont to aoe combo after the second flare so i can 1 button triple flare not sure if that's added later on since i'm only level 58 but i thought it'd be a cool feature

**Comment by nativepapaya** [comment]
On the subject of AoE combos, could Foul be added as well?

**Comment by k-kz** [comment]
Addressed in #425
