### ISSUE TITLE
[BLM] Combo sometimes breaks on Fire IV Blizzard IV

### ISSUE THREAD

**Issue by Sylvansnake** [Nik-Potokar/XIVSlothCombo#395]
Seems like it's not checking properly for the existence of Astral/Umbral?

Also, sometimes Ley Lines gets activated even though I turned off the feature.

**Comment by grimgal** [comment]
Hey, could I get more details (level + features enabled)? Is this with the Simple BLM feature? Also, the opener will always include Ley Lines, are you seeing Ley Lines outside of the opener with the setting disabled?

**Comment by Sylvansnake** [comment]
Well, I have been noticing the combo breaking for the last few days as I've leveled from late 70s, Now level 84. It happens with the Simple BLM Feature, yes. It seems to happen most often if combat ends while Fire IV or Blizzard IV are queued up. If Astral/Umbral status changes the spell queue doesn't seem to refresh. I've also noticed it happen sometimes during combat if Fire I/III doesn't queue up in time to refresh Astral Fire and it drops in the middle of a Fire IV cast. Then the combo gets locked and I have to manually cast Fire to restart the chain.

**Comment by Sylvansnake** [comment]
I don't remember exactly when it started happening. I had BLM sitting at around level 70 for a while. Started leveling it again when I recently noticed the new Simple BLM feature which seemed to have better options than the original Enochian switcher.

At the moment I have Simple Casts (#39), Simple Buffs(#41) and Simple Buffs Pooling (#42) options enabled.

**Comment by grimgal** [comment]
Could you see if you're still having this issue with the recent new update?

**Comment by Sylvansnake** [comment]
I've been testing it the last few days and I have noticed the issue doesn't come up very often during normal activity anymore. I was able to clear a few dungeons with party and with Trust with no problems, so it would seem the issue is mostly resolved in the recent updates.

**Comment by k-kz** [comment]
Fixed in #416 (?)
