### ISSUE TITLE
[gnb]Now No mercy is placed in main combo when do not checked The No mercy to main combo option

### ISSUE THREAD

**Issue by hayde0096** [Nik-Potokar/XIVSlothCombo#397]
Now No mercy is placed in main combo when do not checked The No mercy to main combo option

**Comment by NikkoToska** [comment]
Which options do you have checked for GNB?

**Comment by hayde0096** [comment]
> Which options do you have checked for GNB?

![image](https://user-images.githubusercontent.com/24946425/161927116-db2aba5e-0967-4fe1-92ec-bc087bda7930.png)

**Comment by NikkoToska** [comment]
I think I have a fix for that, just need to test it.

**Comment by damolitionn** [comment]
It's literally that I coded the option in the presets but I forgot to add it to the actual code because I'm actually stupid. I'll PR it now.

**Comment by hayde0096** [comment]
Thanks for fix that
