### ISSUE TITLE
[BLM] Feature Request: Option to not recast Thunder when switching from AOE to Single

### ISSUE THREAD

**Issue by Sylvansnake** [Nik-Potokar/XIVSlothCombo#403]
So, as BLM if I'm using AOE on a group until they are near death and then I switch to single target to finish them off, the combo will immediately queue Thunder even if they already have the AOE Thunder debuff on them. Can we get the option for Simple BLM to skip Thunder, if AOE Thunder is already on the target?

**Comment by AoiYui** [comment]
i second this it would be really nice

**Comment by k-kz** [comment]
Should be an easy fix - along the lines of just doing an extra check

**Comment by Sylvansnake** [comment]
On a related note, could we also get a Target HP check for Triplecast usage? I waste a lot of Triplecasts when the buff queues at like 2% HP and the mob is dead before I can use it.

**Comment by NikkoToska** [comment]
On the Triplecast thing, are you talking about in dungeons?  If we implement a check for the target's HP, that could mean that in raids or on bosses that it may not proc when the boss is at 25%.  I can think of a possible workaround, but just as an example of one difficulty with that.

**Comment by Sylvansnake** [comment]
Well, I think in the case of Triplecast, you could add the minimum HP just as an option. People can disable it for raids or trials if they want. I usually keep Triplecast on my hotbar anyway so if I'm on a boss, tapping it manually is no problem.

**Comment by k-kz** [comment]
Addressed in #425
