### ISSUE TITLE
[BRD] Bug when all songs are up 

### ISSUE THREAD

**Issue by Megasder** [Nik-Potokar/XIVSlothCombo#404]
I found a bug that every time at the start of a fight I got 2 of my songs of cooldown instantly using the main combo

![image](https://user-images.githubusercontent.com/92712466/162087839-ca84e617-37e8-4d2a-9d52-998f8783f765.png)

So latter I waited for all the cooldowns to refresh and in the end I noticed that when all songs are up to use, it instantly uses Mage Ballad and Wanderer's Minuet, being Mage the one that is active in the end. After that it works normally going Wanderer > Mage > Army.

I also noticed that if Army Paeon is on cooldown and Mage and Wanderer are not presing the main combo works fine, it will use Wanderer and wait to use Mage.

Another thing that I noticed, while having all 3 songs up to use I started Army manually and then pressed the main combo, it used Wanderer instantly
![image](https://user-images.githubusercontent.com/92712466/162088359-8c260e96-71ea-4bad-a1e3-d71f35fe0ce1.png)

If I use Mage or Wanderer Manually while having all 3 songs, it works (presing the main combo doesn't trigger the next song)
![image](https://user-images.githubusercontent.com/92712466/162088614-7d16025d-7d1b-437a-8de1-96511289e443.png)
![image](https://user-images.githubusercontent.com/92712466/162089729-5a8f8b0b-41e8-44ad-b7a0-4b346a50ff21.png)
But later when using the second song from the main combo (when the first song wears off) it will use the last song instantly
![image](https://user-images.githubusercontent.com/92712466/162088670-006f8aed-0385-4b99-932c-85fd42c30a56.png)
![image](https://user-images.githubusercontent.com/92712466/162089774-e521047b-4eed-432f-ac31-4490b9130545.png)

So the problem is most likely be in the begining of the combo, since is always at the start when its bugged

My settings
![image](https://user-images.githubusercontent.com/92712466/162088466-7c6c5279-1acb-462b-8874-35c145957149.png)

I tried to explain it the best I could, if you have any questions please ask.

**Comment by k-kz** [comment]
Have you tested without PvP combos enabled?
I'm not particularly familiar with the songs, but I know the PvP stuff is kinda borked at the moment.

**Comment by Megasder** [comment]
Oh Maybe its the Songs Feature from the pvp, I will try it later

**Comment by augporto** [comment]
@Megasder could you do me a favor and try with `Simple AoE Bard Song Options` disabled? i think that is the offender, is the only thing i dont use, and here never had that problem.

**Comment by Megasder** [comment]
With only this options it still doesn't work
 
![image](https://user-images.githubusercontent.com/92712466/162207308-d48668bc-73bd-4c8b-a731-a18facf23dbe.png)

Also doing the AOE combo with the option Simple AoE Bard Song Option enabled makes the same problem.

Maybe the problem is from plugins like noClippy so I use OGCD too fast? 
Yep, pressing it slowly make it works.

<a href="https://gyazo.com/18cefdd8a849b1d9764ffe500d151645"><img src="https://i.gyazo.com/18cefdd8a849b1d9764ffe500d151645.gif" alt="Image from Gyazo" width="50"/></a>
I can see from the hotbars that while pressing the combo and I use WM, MB appears for a moment and dissapear, that moment in which the skill appears is enough to use 2 songs at the same time.

**Comment by augporto** [comment]
What is the your settings on noclippy? less then 0.4 ? you are not using noclippy together with alexander right?

I use noclippy with 0.4 settings and have no problems ... i really cant reproduce on my side :(

**Comment by augporto** [comment]
oh , i could replicate it

its the pairing of simple opener with simple songs,  thats why i was not getting the error, since simple opener uses the songs in the right order, enforces it, somehow it does not change as rapid.

ill investigate the cause now, thx o/

**Comment by Megasder** [comment]
Its still bugged in my end, but I suposse I will press slowly the first time in combat since later it works fine, not a big deal.
