### ISSUE TITLE
[WAR] Infuriate gets stuck on Storm's path bug

### ISSUE THREAD

**Issue by Dedoooo** [Nik-Potokar/XIVSlothCombo#405]
Infuriate will get stuck on Storm's Path's combo for 30 seconds and sometimes sets itself on main combo randomly before combat starts.

there's a way to break this and see for yourself 100% of the time by going to a low level zone and finding a single mob that isn't linked to other mobs and attacking it (Heavy Swing > Mob Dies > Infuriate gets on Main Combo and will stay for 30 seconds( which is the time for the gcd combo to wear off > goes back to Heavy Swing)

**Comment by k-kz** [comment]
fixed in #414 and #412
