### ISSUE TITLE
[MCH] Simple Machinist does not use wildfire after the first cast.

### ISSUE THREAD

**Issue by Korosys** [Nik-Potokar/XIVSlothCombo#410]
![image](https://user-images.githubusercontent.com/1356894/162138274-da244c47-2f3c-4ec3-bfdb-30fc551343b2.png)
These are the options I have enabled and everything functions normally until wildfire comes off cooldown the first time, at which point it will not cast wildfire, hypercharge, or barrel stabilizer. If I manually cast wildfire normal operation resumes but will break again when wildfire comes off cooldown again.

This is on level 80 MCH, in case that matters.

Version 3.0.8.11

**Comment by Cadwgan** [comment]
Looking through the code, it's checking the cooldown of Chain Saw without any level checks, so it'll break under lv90.

**Comment by augporto** [comment]
You are both right, a fix should go up sooner or later today for this, after 6 hours of dummy beating my brain melted and that skipped, in the middle of testing the fix.

Thx for reporting o/

**Comment by k-kz** [comment]
Fixed in #413

**Comment by Korosys** [comment]
all good with the update, thanks for your hard work!
