### ISSUE TITLE
[MCH] Simple Assembling max charges bug

### ISSUE THREAD

**Issue by Cadwgan** [Nik-Potokar/XIVSlothCombo#411]
![image](https://user-images.githubusercontent.com/8039241/162140675-49aa9f8e-9e11-43d7-aaff-fe74536242d2.png)

These options are currently checking for specifically 2 charges, rather than when you're capped, so break when synced below lv84.

**Comment by augporto** [comment]
You are right, a fix should go up sooner or later today for this, after 6 hours of dummy beating my brain melted and that skipped, in the middle of testing the fix.

Thx for reporting o/

**Comment by k-kz** [comment]
Fixed in #413
