### ISSUE TITLE
[BRD] [DNC] Assigning different buttons from main GCDs for Simple DNC and Simple BRD

### ISSUE THREAD

**Issue by cidoliveira** [Nik-Potokar/XIVSlothCombo#415]
Enhancement: Being able to still use your main GCD combo like Burst Shot and its procs would solve buff-holding issues. We could work around doing something similar to how Simple BLM works, with its combo not assigned directly to a main skill but with Scathe, a secondary, not included in the main combo. If the starting button for Simple Bard and Simple DNC could be something like a Ranged DPS role action we don't use in raids like Foot Graze or something or a skill we only use during procs like Starfall/FDIV, it would give us the option to use your standard GCD combo during times we wouldn't like to use buffs like P2S limit cut and P3S adds.

**Comment by dawn-star** [comment]
Would love to see this, it would also enable the use of ST combo on trash in Alliance Raids (and to a lesser extent dungeons) whilst reserving CDs for proper opener on bosses

**Comment by k-kz** [comment]
> it would give us the option to use your standard GCD combo during times we wouldn't like to use buffs like P2S limit cut and P3S adds.

It's highly unlikely this will happen (at least for the time being) - there have been two posts requesting this, and both times they have been centred around the use of "Simple Modes" in Savage raiding niche scenarios, which is not their intended purpose. Simple modes are designed for casual use.

That being said, we plan to review "Simple Mode(s)" in general and possibly remove some of them altogether in favour of baking things into main combos, so we'll see.
