### ISSUE TITLE
[DRK] Level Check issue with oGCD Feature

### ISSUE THREAD

**Issue by Dismes** [Nik-Potokar/XIVSlothCombo#423]
![image](https://user-images.githubusercontent.com/19319649/162334360-ae54cfea-e1c9-4832-ad52-aaebeaa48b25.png)

if you have the oGCD feature enabled with Shadowbringers Feature enabled at lower levels, the combo goes Salted Earth -> Shadowbringers, which you don't have unlocked yet. 

I am currently level 57 and can't use abyssal drain with the Shadowbringers Feature enabled

**Comment by Dismes** [comment]
Another issue I ran into is, at level 60, the oGCD feature prioritizes abyssal drain over Carve and spit

**Comment by k-kz** [comment]
Addressed in #561
