### ISSUE TITLE
[SGE] Eukrasian Diagnosis option

### ISSUE THREAD

**Issue by Dedoooo** [Nik-Potokar/XIVSlothCombo#426]
for Diagnosis it will only swap to Eukrasian Diagnosis if you target and thats how it's supposed to work, i know.. :D what i'd like is for it to be always Eukrasian Diagnosis so mouse over users can still shield their targets on mouse over and once they target and it detects the shield on target only then it'll swap to Diagnosis

Thanks! ❤️

**Comment by k-kz** [comment]
Duplicate with more detail/comments in #445
