### ISSUE TITLE
[SGE] [Enhancement] Phlegma into Dyskrasia/Toxikon with no target & range check

### ISSUE THREAD

**Issue by matt8100** [Nik-Potokar/XIVSlothCombo#434]
For the Phlegma into Dyskrasia feature, I think it'd be useful if it stayed as Dyskrasia when no target is selected. Right now when spamming Dyskrasia and a Phlegma charge comes up, you end up stopping for a moment when you don't have a target selected. Same goes for when combined with Phlegma into Toxikon feature.

Also for Phlegma into Toxikon, it'd be nice if it changed into Toxikon if the target is not within range of Phlegma, and together with Phelgma into Dyskrasia, turn into Dyskrasia when no addersting and not in range as well.

**Comment by Dedoooo** [comment]
Great point! 👍 you beat me to it 😃

**Comment by NikkoToska** [comment]
One of the features coming in 6.1 is:
```An option to automatically target enemies when executing target-based attacks has been added.```

So it should auto-target after the patch, even if you don't have anything selected.  But I can still see a reason people might not turn this on, or if they're out of Phlegma range.

But Dyskrasia is only around you.  If you're out of range for Phlegma (6y) then casting Dyskrasia (5y) isn't really helpful.  I think that Toxikon should have priority over Phlegma when you are out of range for Phlegma and have Addersting, though.

**Comment by Tsusai** [comment]
Waiting on the ability to test the no-target code before I send in a pull request

**Comment by Tsusai** [comment]
Fixed in 781c1c710307828b927c28bc76833b39a531ab8c
Can be closed
