### ISSUE TITLE
[AST] "Simple Heal" Aspected Benefic issue

### ISSUE THREAD

**Issue by Eclipsum** [Nik-Potokar/XIVSlothCombo#440]
"Simple Heal" enables "Aspected Benefic Feature" in the background without you yourself having enabled the feature whiles in the menu the feature is still listed as disabled also making that other features of "Simple Heal" only work if the target is procced with "Aspected Benefic"

**Comment by Eclipsum** [comment]
Video Demonstration:
https://imgur.com/a/VwuLK3n

**Comment by Taurenkey** [comment]
Looking at the code and testing myself, `Aspected Benefic Feature` is not enabled when `Simple Heal` is turned on as is intended. When you tick `Aspected Benefic Feature` though it will enable `Simple Heal` as it is considered the parent combo.

However I see an issue with the code where it's not actually grouping the conditions for it correctly so there's a feature issue as opposed to a plugin issue. Will address with our AST guy.
