### ISSUE TITLE
[RPR] Soul Slice/Scythe stack use

### ISSUE THREAD

**Issue by Offskee** [Nik-Potokar/XIVSlothCombo#441]
Been messing for the past hour or so, combo will not consume both stacks of Soul Slice/Scythe until the second stack is fully recharged.

Regardless of if SoD/DD is present and under 50 gauge.

**Comment by k-kz** [comment]
This is currently the intended function (code-wise, it may be poorly described) - a full rework of RPR is on the way and will address this as an option, and more!
