### ISSUE TITLE
[SGE] Phelgma into X Feature doesn't turn into Dyskrasia

### ISSUE THREAD

**Issue by Runeart13** [Nik-Potokar/XIVSlothCombo#451]
The extra feature of Phlegma to Dyskrasia does not work unless you also have Phlegma into Toxikon ticked as well.

**Comment by k-kz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[SGE] Phelgma into X Feature doesn't turn into Dyskrasia](https://trello.com/c/nO6EKltv/1-sge-phelgma-into-x-feature-doesnt-turn-into-dyskrasia)

**Comment by Tsusai** [comment]
I'm a dumb dumb. I will be testing multiple fixes to this feature when XIVLauncher/Dalamud support is up and running

**Comment by k-kz** [comment]
Handled in #469
