### ISSUE TITLE
[Multiple Jobs]  Deep Dungeon support for "Simple" Job features.

### ISSUE THREAD

**Issue by Arpheec** [Nik-Potokar/XIVSlothCombo#453]
Currently the "simple" job feature locks up when an ability is no longer available due to certain status effects found primarily in Deep Dungeon content such as Pacify, Silence, and Amnesia or while not yet unlocked after meeting lvl requirements. (Things locked behind job quests for instance.)

I believe it'd be possible to update the logic to detect when these status effects are inflicted to filter out skills/abilities that cant be used under them. However, I'm unsure if detecting and filtering for skills not unlocked yet would even be a possibility.

**Comment by Taurenkey** [comment]
Yes it's possible to update these features, however like most things with Sloth we're aiming for general gameplay first and _then_ tackling niche cases like this. It might be something I look into at a later date.

@k-kz Slap this bad boy with a backlog tag please.

**Comment by k-kz** [comment]
Addressed, same as #731
