### ISSUE TITLE
[WAR] Can't have a separate storms path combo

### ISSUE THREAD

**Issue by Azuresk** [Nik-Potokar/XIVSlothCombo#48]
Its currently not possible to have storms path and storms eye combos be separated, instead of the all-in-one button. being able to separate them and still have the overcap feature work would be nice

**Comment by Iaotle** [comment]
Unless you have a good reason for why this should be made (e.g. give us a situation where this is terrible for the rotation) I don't think it's an issue.
Or feel free to make a pull request with your suggested changes though and we can review it.
