### ISSUE TITLE
[MNK] Perfect Balance Opo-opo Suggestion - Bootshine Combo

### ISSUE THREAD

**Issue by Xiniox** [Nik-Potokar/XIVSlothCombo#480]
Currently while using _Bootshine Combo_ it'll always do DK -> BS -> DK to get a Lunar Nadi, even if I've used a DK right before Perfect Balance. Is there a way to make it do BS -> DK -> BS if it notices that I have Leaden Fist and then use DK instead of BS after the Blitz to restart the rotation?

**Comment by grimgal** [comment]
Added in #500

**Comment by Xiniox** [comment]
Awesome work, thank you!
