### ISSUE TITLE
[Multiple jobs] Issues I found so far

### ISSUE THREAD

**Issue by NonlooSmol** [Nik-Potokar/XIVSlothCombo#481]
WHM : CDs on glare/stone : Does not work, it only uses Dia and when the DOT feature is disabled, it doesn't use OGCDs.
SCH : Same as WHM, only uses Bio (Dot) when ticked in the DPS Feature
BRD : Simple BRD gets stuck on Wanderer's minuet
DNC : Simple Dancer does not work, if standard step is ticked it gets stuck on it, if not it does the basic 1 2 3 rotation and nothing else
MNK : Simple MNK does not work, it gets stuck on Form shift

I'll edit this once I tried other feature or other jobs.

**Comment by k-kz** [comment]
Spoke with user on discord, issues were caused by other plugins.
