### ISSUE TITLE
[WHM] 2.32 SPS + Presence of Mind

### ISSUE THREAD

**Issue by Dainichi22** [Nik-Potokar/XIVSlothCombo#490]
Using the 2.32 SPS BiS for WHM and Popping PoM will make certain OGCD's get ignored because the WHM is casting too fast making the plugin think you cant weave it, but you can, making Assize/Lucid not get used on CD

**Comment by NikkoToska** [comment]
What skillspeed do you need to have to get that low?  I'll see what I can do to replicate and fix.

**Comment by Dainichi22** [comment]
1.86 Recast, Here are the melds, https://etro.gg/gearset/848869dc-ea7b-42e0-a0a5-1bfdeae8d7e2
It says SCH but just replicated the melds to WHM including weapon melds

**Comment by k-kz** [comment]
addressed in #496 and #508
