### ISSUE TITLE
[MNK] AoE Combo improvement

### ISSUE THREAD

**Issue by Stiopka** [Nik-Potokar/XIVSlothCombo#493]
I played MNK with the new update and i think the Aoe Combo can have some Improvements.

- The AoE Combo has the option for Masterful Blitz but not using Perfect Balance. (Dmg that is not getting used)
- Dmg CD's in the AoE Combo - Riddle of Wind, Riddle of Fire, Brotherhood. (At the moment they are not getting used in the Combo)

**Comment by grimgal** [comment]
Added in #500
