### ISSUE TITLE
NIN, MNK and PLD features

### ISSUE THREAD

**Issue by Alkeyd** [Nik-Potokar/XIVSlothCombo#494]
Ninja:
![image](https://user-images.githubusercontent.com/94228374/163673502-abf18ad8-021e-4250-bc83-eba29628383b.png)
![image](https://user-images.githubusercontent.com/94228374/163673503-20ba79ee-8189-4aac-a841-39cbba9d47ec.png)
Paladin:
![image](https://user-images.githubusercontent.com/94228374/163673507-5be239df-5289-4209-88d5-de542aec9948.png)
Monk:
![image](https://user-images.githubusercontent.com/94228374/163673508-40193a16-5264-4eb3-8cf8-09bfd29ee5ba.png)

Can we have these same features here? I use another combo plugin because of these features, everything else I use in Sloth Combo and I think they would be very good here too

**Comment by Nyuuuwu** [comment]
For paladin we have the "Standalone Holy Spirit Feature", does this not do the same thing? It should replace Requiescat with Confiteor when you're either at the last stack of req, 2000 mana or lower or when the timer is almost expiring.

**Comment by Taurenkey** [comment]
For NIN feature 1, that's already baked into Simple AoE. If you use these settings:
![image](https://user-images.githubusercontent.com/30053704/163673941-51acf28d-e6b9-48d4-a24e-acd70cf69073.png)

You just get the simple 1-2 combo for NIN AoE. If you add in the Mudra feature it will do your jutsus for you which may not be to your liking I understand however I will have to consider feature bloat given our other jutsu based features. I can probably add in the Huraijin feature just fine though.

I can't speak on the other jobs however, just NIN.

**Comment by Alkeyd** [comment]
Thanks for your attention, the AOE combo option to turn the Jutsu when I have some Mudra active, helps to save keys on my Joystick bar

**Comment by Stiopka** [comment]
i tested for the monk
![image](https://user-images.githubusercontent.com/73742622/163675082-9b3a370f-0cc8-4de4-87c7-49fd1acf2b69.png)
with the bootshine combo option it will use snap punch if demolish has 6s or above

**Comment by Alkeyd** [comment]
> i tested for the monk ![image](https://user-images.githubusercontent.com/73742622/163675082-9b3a370f-0cc8-4de4-87c7-49fd1acf2b69.png) with the bootshine combo option it will use snap punch if demolish has 6s or above

Thank you!

**Comment by k-kz** [comment]
Addressed in #497
