### ISSUE TITLE
[WHM] Afflatus Rapture Overcap Feature

### ISSUE THREAD

**Issue by Dainichi22** [Nik-Potokar/XIVSlothCombo#495]
Misery/Lily buffs make them dps neutral to use now and using Misery under raid buff is a dps gain, overcapping on Lillies is a dps loss so a feature where your glare turns into Aff. Rapture when capping Lillies would be nice

**Comment by NikkoToska** [comment]
Should be good.  Added an option for Afflatus Misery to go on Glare too so all DPS is in one place.

**Comment by k-kz** [comment]
Addressed in #496
