### ISSUE TITLE
Double Addle/Feint Protection Feature

### ISSUE THREAD

**Issue by TheGreatAce** [Nik-Potokar/XIVSlothCombo#509]
I noticed that tanks already have a double reprisal protection feature, I think doing the same for Addle/Feint would be a great idea especially for those who do content in party finder.

**Comment by k-kz** [comment]
This is coming to other jobs in a future update!

**Comment by TheGreatAce** [comment]
Nice! Thank you!

**Comment by TheGreatAce** [comment]
> This is coming to other jobs in a future update!

It also occurred to me, can this also apply to phys ranged mitigation? (Troubadour/Shield Samba/Tactician)

**Comment by k-kz** [comment]
> > This is coming to other jobs in a future update!
> 
> It also occurred to me, can this also apply to phys ranged mitigation? (Troubadour/Shield Samba/Tactician)

It's something that's been talked about a lot on the Discord, and will likely be implemented soon as well.
