### ISSUE TITLE
I ran into an error every time i try to open plugin configuration

### ISSUE THREAD

**Issue by impalep0** [Nik-Potokar/XIVSlothCombo#515]
it says I should contact the plugin dev so I posted it here
[dalamud.log](https://github.com/Nik-Potokar/XIVSlothCombo/files/8505146/dalamud.log)

**Comment by impalep0** [comment]
System.UnauthorizedAccessException: Access to the path 'C:\Users\ASUS\AppData\Roaming\XIVLauncher\pluginConfigs\XIVSlothCombo.json' is denied.   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)   at System.IO.StreamWriter..ctor(String path)   at System.IO.File.WriteAllText(String path, String contents)   at Dalamud.Configuration.PluginConfigurations.Save(IPluginConfiguration config, String pluginName) in C:\goatsoft\companysecrets\dalamud\Configuration\PluginConfigurations.cs:line 35
Info continued
   at XIVSlothComboPlugin.ConfigWindow.Draw() in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\ConfigWindow.cs:line 174   at Dalamud.Interface.Windowing.Window.DrawInternal() in C:\goatsoft\companysecrets\dalamud\Interface\Windowing\Window.cs:line 195   at Dalamud.Interface.Windowing.WindowSystem.Draw() in C:\goatsoft\companysecrets\dalamud\Interface\Windowing\WindowSystem.cs:line 117   at Dalamud.Interface.UiBuilder.OnDraw() in C:\goatsoft\companysecrets\dalamud\Interface\UiBuilder.cs:line 305
Context
["XIVSlothCombo"] UiBuilder OnBuildUi caught exception

**Comment by impalep0** [comment]
This is the error when i posted it on the xivlauncher discord, they wouldnt help because they say it was a third party plugin

**Comment by Taurenkey** [comment]
Hi, it looks like a permission error.

If you go to your `C:\Users\ASUS\AppData\Roaming\XIVLauncher\pluginConfigs` folder and right click the `XIVSlothCombo.json` file and select properties, make sure it doesn't have "Read Only" checked.

**Comment by impalep0** [comment]
Thx for the reply! however my json doesnt have "Read Only" checked. The error still occurs.

**Comment by Taurenkey** [comment]
The error can occur on 4 different outcomes:
- The program doesn't have permission to access it.
- The file is an exe already in use
- The file is actually a folder
- The file is read-only

As such, the only likely suspect now is checking the first one there. Again, right click the file and select properties. This time look at the security tab at the top. Ensure that each of the listed users have been allowed all the permissions. If they don't, click edit and set it from deny to allow.
