### ISSUE TITLE
[MCH] Heat Blast level check

### ISSUE THREAD

**Issue by MarcoMDF** [Nik-Potokar/XIVSlothCombo#516]
Not a huge issue but Simple Machinist breaks in Brayflox's Longstop after using Hypercharge since Heat Blast is only unlocked at 35.

**Comment by k-kz** [comment]
@augporto

**Comment by augporto** [comment]
I was looking at it and the the level check already exists on Simple Machinist, did you have Single Button Heat Blast Active too? Thats a conflict on simple features.

@k-kz  I'll be making the conflict explicit on it.

**Comment by k-kz** [comment]
fixed in #529
