### ISSUE TITLE
[WHM] Opener

### ISSUE THREAD

**Issue by Dainichi22** [Nik-Potokar/XIVSlothCombo#519]
Would it be possible to add a WHM opener as a feature?
Heres the Non-swift opener
![image](https://user-images.githubusercontent.com/83427930/163848316-0fba40da-5584-4f12-8ec9-fc83a4947779.png)
Rightnow it uses glare > glare^pom^assize > glare > dot so your PoM/Assize don't fall under raid buffs and you lose dps

**Comment by k-kz** [comment]
Added in #508
