### ISSUE TITLE
Discussion: Scholar

### ISSUE THREAD

**Issue by Tsusai** [Nik-Potokar/XIVSlothCombo#520]
ScholarSeraphConsolationFeature

- 	No change

ScholarEnergyDrainFeature

- 	No Change

SchRaiseFeature

- 	Remove. Doesn't follow "Trait" logic. Raise comes first in levels, then Swiftcast

SCHAlternateRaiseFeature

- 	Rename ScholarAlternateRaiseFeature to keep consistent, remove "Alternative" naming?

ScholarFairyFeature

- 	Replace Direct Dalamud code with HasPetPresent

ScholarDPSFeature

- 	Overhaul similar to Sage

SCHDPSAlternateFeature

- 	This uses Ruin 2 instead of Ruin/Broils. Should this code be merged together for with DPSFeature for sanity sake (Similar to Sage Phlegma Merges), and just have the player select options for what which of the two attacks (or both) to use?

**Comment by ita238124** [comment]
Hey there! I'd like to ask if it could be possible to implement something like sage's 'Fine Tune Diosis' into scholar Biolysis DPS Feature. It's really useful to be able to input those HP values and define when the dot is gonna be applied.

As a second request (and it's a little silly, I apologize in advance), would it be possible to select which fairy in the FairyFeature (every fairy action changes to summon fairy if they're absent)? Today the actions change to summon selene only, and I'd like it to summon eos instead.

Thank you very much!

**Comment by Tsusai** [comment]
> Hey there! I'd like to ask if it could be possible to implement something like sage's 'Fine Tune Diosis' into scholar Biolysis DPS Feature. It's really useful to be able to input those HP values and define when the dot is gonna be applied.
> 
> As a second request (and it's a little silly, I apologize in advance), would it be possible to select which fairy in the FairyFeature (every fairy action changes to summon fairy if they're absent)? Today the actions change to summon selene only, and I'd like it to summon eos instead.
> 
> Thank you very much!

First request is being worked on, second request has been added

Closing this discussion thread for now, overhaul coming soon
