### ISSUE TITLE
Discussion: Sage

### ISSUE THREAD

**Issue by Tsusai** [Nik-Potokar/XIVSlothCombo#521]
SageRhizomataFeature
- Should a slider be added, or just use Rhizomatta when Addersgall is a fixed 0

SageTauroDruoFeature

- 	Should this be reversed? Using the SE concept of traits, Tauro (big heal, CD) a later skill similar to Druo (insta heal)
- 	ie stack Tauro on top of Druo as it's a later/better ability (in scholar speak, stacking Excog ontop of Lustrate instead of the opposite). For someone leveling and this feature is on, Druo would upgrade like a trait

SagePhlegmaFeature

- 	In order to merge the two near identical code together, a parent fake option was made in the GUI
- 	The fake parent can be removed by using `protected internal override CustomComboPreset Preset { get; } = CustomComboPreset.SgeAny;` and let the Gui switches check inside like it is now (but I think this is bad for performance in milliseconds)

SageDPSFeature

- 	Some Discord talk about LucidDreaming suboption being slightly different on other Healers. Does this need updating?
- 	Is a Phlegma suboption worth investigating (if in melee range)

SageEgeiroFeature

- 	Remove. Following SE trait concept, Raise comes before Swiftcast. SageAlternativeEgiroFeature is this concept.

SageSingleTargetHeal & SageAoEHeal	

- 	Not comfortable touching at this time

**Comment by k-kz** [comment]
>SageTauroDruoFeature
Should this be reversed? Using the SE concept of traits, Tauro (big heal, CD) a later skill similar to Druo (insta heal)
ie stack Tauro on top of Druo as it's a later/better ability (in scholar speak, stacking Excog ontop of Lustrate instead of the opposite). For someone leveling and this feature is on, Druo would upgrade like a trait

I added it this way personally on the basis that I wanted to prioritise the similar, yet stronger heal - but primarily just to get teh 45s cooldown rolling.
More than happy to include a conflicting `Druo --> Tauro` feature alongside the current `Tauro --> Druo`.
Definitely makes sense from a levelling perspective!

**Comment by k-kz** [comment]
>SageEgeiroFeature
Remove. Following SE trait concept, Raise comes before Swiftcast. SageAlternativeEgiroFeature is this concept.

To be honest, I think we're going to do this all at once, for all healers and other relevant jobs in the near future. Just sit tight on this one :]

**Comment by Tsusai** [comment]
> > SageTauroDruoFeature
> > Should this be reversed? Using the SE concept of traits, Tauro (big heal, CD) a later skill similar to Druo (insta heal)
> > ie stack Tauro on top of Druo as it's a later/better ability (in scholar speak, stacking Excog ontop of Lustrate instead of the opposite). For someone leveling and this feature is on, Druo would upgrade like a trait
> 
> I added it this way personally on the basis that I wanted to prioritise the similar, yet stronger heal - but primarily just to get the 45s cooldown rolling.
> 
> More than happy to include a conflicting `Druo --> Tauro` feature alongside the current `Tauro --> Druo`. Definitely makes sense from a levelling perspective!

It would be the same effect, as it is now, Tauro prioritized over Druo (stronger cooldown on top). It would just be affecting Druo's actionID/button instead of Tauro's (again, thinking how traits upgrade actions, this would "upgrade" Druo, and slap the upgraded Tauro on top of it)

**Comment by k-kz** [comment]
>It would be the same effect, as it is now, Tauro prioritized over Druo (stronger cooldown on top). It would just be affecting Druo's actionID/button instead of Tauro's. Thinking how traits upgrade actions, this would "upgrade" Druo, by putting later level Tauro on top of it. When Tauro is on cooldown, show Druo

Oh yeah, of course lmao. Yeah, we can definitely do that - I've seen one of the other forks offering both ways (I think?) which was what came to mind.
