### ISSUE TITLE
[MNK] Forbidden Chakra Feature

### ISSUE THREAD

**Issue by KB119NZ** [Nik-Potokar/XIVSlothCombo#526]
'Adds Forbidden Chakra/Enlightenment to the Main/AoE feature combo'
Does not seem to be working at all with the Arm of the Destroyer combo or Bootshine combo, and is not tagged as a conflicting feature.
![chakra1](https://user-images.githubusercontent.com/100903017/163952305-5881da31-0ff3-4671-8fec-e4e4179d42e9.png)
'Meditation on Main combo' and 'Meditation on AoE combo' seem to do the job instead, however they are not available without enabling 'CDs on Main/AoE combo' feature which forces Riddle of Fire onto the AoE/Main combos. 
![chakra2](https://user-images.githubusercontent.com/100903017/163953179-9432a6bd-6ef0-446d-a1d4-a86fe48b9aab.png)
I suppose this can be a request for a Riddle of Fire toggle for the 'CDs on Main/AoE combo' feature.

**Comment by grimgal** [comment]
#532

**Comment by k-kz** [comment]
Addressed in #532
