### ISSUE TITLE
Possibility of adding condensed RDM single target/aoe?

### ISSUE THREAD

**Issue by Genesis-Nova** [Nik-Potokar/XIVSlothCombo#53]
In another fork, (https://github.com/PrincessRTFM/XIVComboPlugin)
Was wondering if you would consider adding something similar to yours as some other single button rotations have been coming in.
https://github.com/PrincessRTFM/XIVComboPlugin/blob/4ce3cd6dd5eb550144ef4f0d69fdc12b7fb5c334/Combos/RDM.cs#L254
https://github.com/PrincessRTFM/XIVComboPlugin/blob/4ce3cd6dd5eb550144ef4f0d69fdc12b7fb5c334/Combos/RDM.cs#L281

**Comment by Nik-Potokar** [comment]
Added!
Please let me know if anything else needs adding
