### ISSUE TITLE
[PLD] Fight or Flight Feature Weave Window

### ISSUE THREAD

**Issue by DurzoThorn** [Nik-Potokar/XIVSlothCombo#534]
Currently the FoF feature on main combo is being weaved a fraction of a second to soon for the BiS 2.44 GCD it causes the final Goring Blade to fall just outside the buff window this skipping it and swapping to Holy Spirit. Adjusting the usage of FoF by .1-.2 of a second back in the weave window ie .65-.75 instead of whatever it is now should fix the issue.

**Comment by DurzoThorn** [comment]
Bigger issue appears to be that the Paladin code was reverted to an earlier build since the Atonement drop slider is gone and the FoF custom GCD inputs are back.

**Comment by k-kz** [comment]
Atonement Drop issue fixed in #539
