### ISSUE TITLE
[SAM] Request: Shoha II on Tenka Goken 

### ISSUE THREAD

**Issue by Dedoooo** [Nik-Potokar/XIVSlothCombo#54]
have Shoha 1 instead of Shoha 2(AoE) when Tenka Goken(AoE) is on Tsubame-Gaesha when meditation is at 3 and keep Shoha 1 on Midare

**Comment by Nik-Potokar** [comment]
Can you please explain again what option you want me added since i find this confusing to read
Sorry 

You want on Iaijutsu? > Tsubame gaeshi>Tenka Goken>Shoha2

**Comment by Dedoooo** [comment]
Yes. Sorry for the confusion, i tried to word it as best i could. it would be Shoha 2 when meditation is at 3 which would make both of them AoE and oGCD AoE(Shoha2) instead of the original AoE and oGCD Single target(Shoha 1) 

Exactly the way you said it
