### ISSUE TITLE
[BRD] Simple Bard Feature issue

### ISSUE THREAD

**Issue by JayfieldAlfred** [Nik-Potokar/XIVSlothCombo#541]
Having the Simple Bard Song Option checked does not trigger the songs on a single button (Heavy/Burst Shot) and just loops through DoTs/Iron Jaw -> Sidewinder/Empyreal Arrow -> Heavy/Burst Shot (Straight Shot) and I had to manually press one of the songs (eg Wanderer's Minuet) in order to trigger the rest of the Simple Bard sub features. Once the all 3 songs are played the first song does not show up on the button and have to manually press the song button again.

**Comment by Taurenkey** [comment]
Already been fixed in the upcoming release.
