### ISSUE TITLE
[PVP General] Guard spam protection 

### ISSUE THREAD

**Issue by Offskee** [Nik-Potokar/XIVSlothCombo#542]
Is it possible to, after using the emergency guard option in pvp, to then have a second option we can enable that would allow us to "lock out" the one button option to prevent accidently clicking off the guard buff?

**Comment by Taurenkey** [comment]
I'm adding a feature in the next update to prevent mashing causing you to cancel your guard. If you want to cancel your guard with the feature on, you'll be able to use Guard again manually to cancel it.

**Comment by k-kz** [comment]
Addressed in #565
