### ISSUE TITLE
[BRD] Simple Bard Song Rotations

### ISSUE THREAD

**Issue by Niahmie** [Nik-Potokar/XIVSlothCombo#543]
It seems like since the new release version, simple bard's song rotations (if they fall out of sync such as downtime in a dungeon), will begin overwriting each other quickly. This seems to consistently happen with AP. If AP begins, and WM or MB is coming up shortly after, it instantly overwrites AP and leaves you without a song for ~30s at a time. 

Upon testing this further, it is only AP that is overwritten, and it gets overwritten by both WM and MB (In the Simple Bard AoE rotation). It seems to behave as though AP isn't active, as it keeps putting the other two songs into the skill slot as if no song was currently playing; which it does not do when WM or MB is active.

This does only occur during raids with random downtime or dungeons, so it's not the highest priority but I figured it was worth mentioning. Thank you for all the hard work that you do.

**Comment by augporto** [comment]
Should be fixed on the next update. Ty! o/

**Comment by k-kz** [comment]
Addressed in #552
