### ISSUE TITLE
[All Jobs] Clear hotbar button assignments for combo features

### ISSUE THREAD

**Issue by Sylvansnake** [Nik-Potokar/XIVSlothCombo#545]
Many of the combo feature descriptions don't clearly name which action button they are linked to. Could you possibly mark which hotbar button to use for each combo so we can find it easily? Perhaps add it to the title line of the main feature.

Example:
Simple Summoner [hotbar: Ruin]

**Comment by Taurenkey** [comment]
This has been worked on and should be implemented shortly. I just have to get around to getting through all of our features to hook this up properly, and with over 200 features, some of which don't even describe what they replace properly (which has prompted this whole thing) needless to say it's something I'm approaching in smaller bursts than all at once.

**Comment by k-kz** [comment]
This has been implemented in the form of a mouseover popup on relevant features. Let us know if you see anything missing or incorrect!
