### ISSUE TITLE
[PVP General] Emergency Heals & Guard

### ISSUE THREAD

**Issue by gwynnS** [Nik-Potokar/XIVSlothCombo#548]
I think change every button when certain HP meets condition for Heal & Guard is kinda too force because I can't weave any skill before use heal or guard

If I'm in safe position to use potion I can't even use it and have to use heal or guard first

**Comment by Offskee** [comment]
Agreed, heals for example is blocking out my manual guard button. preventing me from guarding

**Comment by Taurenkey** [comment]
I can look at changing the feature to not change certain actions, such as the common abilities, however until we have PVP features for every job this is the only way to basically enable global features for jobs that don’t have any features.

**Comment by gwynnS** [comment]
Thank you so much

and if it have an option to only use Quick purify when HP under certain point would be great!

**Comment by Taurenkey** [comment]
A fix has been put out for this in the last update to not affect the common abilities.

If this has solved your problem, we will close this issue.

**Comment by gwynnS** [comment]
It's kinda okay but I feeling odd too

IMO I think it should be affect only the ability you spam the most (like 1-2-3 combo) because if you need to emergency heal/guard/purify while you spamming on that key but that key doesn't change to guard/heal/purify I think it's not emergency

I still have to change key to press and can't weave other skill but guard/heal/purify (It's great when in panic and press all the button in same time)

**Comment by k-kz** [comment]
Addressed in #554
