### ISSUE TITLE
[AST] Aspected Benefic feature no longer functioning

### ISSUE THREAD

**Issue by segfaultvicta** [Nik-Potokar/XIVSlothCombo#553]
Prior to the most recent set of updates (between Sloth being available after 6.1 and a patch a few days ago as of 22 April), Benefic 2 was switching to Aspected Benefic when I targeted someone who was not currently under the effects of Aspected Benefic. The Essential Dignity under an HP threshold feature is still working just fine for me, so I know it's not that I have the wrong base ability somehow; this was working for me last week when I first started using Sloth, and stopped working. Let me know if there's anything I can provide to help debug the issue! <3 Thank you for all of your hard work.

**Comment by k-kz** [comment]
Addressed in #556
