### ISSUE TITLE
[RDM} Verproc into Jolt Plus does not switch with Acceleration

### ISSUE THREAD

**Issue by PurpleMentat** [Nik-Potokar/XIVSlothCombo#555]
Verproc into Jolt Plus replaces Verstone/Verfire with Veraero/Verthunder when under the effects of Dualcast and Swiftcast, but not Acceleration. With the change to Acceleration in 6.0 it should be added to this feature.

**Comment by NikkoXIV** [comment]
RDM is getting cleaned up and this will be fixed.  Please look forward to it!

**Comment by NikkoXIV** [comment]
@k-kz Can be closed, fixed with RDM rewrite.
