### ISSUE TITLE
Emergency heals slider

### ISSUE THREAD

**Issue by Astariz** [Nik-Potokar/XIVSlothCombo#557]
Unable to click and drag "A". "B" can be clicked and dragged to select a number.

![image](https://user-images.githubusercontent.com/80979216/164814079-d4971adf-9c22-4421-8ce4-76e79829895d.png)

**Comment by Genesis-Nova** [comment]
Can confirm this behavior.
Heals slider will not drag when clicked, also behaves weirdly when control+clicking (auto accepts value after 1 number, try to type 30 but it closes automatically after typing '3')
Guard slider works as expected.

**Comment by k-kz** [comment]
We believe we know the fix for this - just need to pass it by the relevant dev to make sure we're not removing something we shouldn't be, etc.

Should be sorted soon!

**Comment by k-kz** [comment]
Addressed in #565
