### ISSUE TITLE
How do I contribute code?

### ISSUE THREAD

**Issue by ryankhart** [Nik-Potokar/XIVSlothCombo#573]
How do I contribute code? I can't fork the project. I would like to submit a pull request.

**Comment by ryankhart** [comment]
Oh, I'm dumb. After Google searching around, I stumbled on someone explaining that you can't fork a project that you're already forked. So I checked my repos, and found it there, already forked. It just didn't specify that in the GitHub UI when I clicked the fork button.

**Comment by Spanglish1337** [comment]
Hi!

I am quite curious about the pull you mentioned, is there anything specific you want to add? You can add it as a suggestion here and the devs will take a look at how it can be done as soon as possible.

**Comment by ryankhart** [comment]
I've already coded it up, I'm just playing with it for a few hours to test before I submit a pull request.

I just added a WHM feature for using Thin Air before Medica 2 if available and not already under the effect. Medica 2 is one of the more expensive MP abilities, and it just seemed like a good idea.
