### ISSUE TITLE
SCH dps feature issues

### ISSUE THREAD

**Issue by excalibert** [Nik-Potokar/XIVSlothCombo#575]
neither the lucid dreaming feature nor the chain strat buttons seem to be activating for me, even without any somewhat known offending plugins not installed. Issue arises on my level 90 SCH in both instances and target dummies. This isn't present on my other 3 healers.

**Comment by excalibert** [comment]
I made sure to test without any other plugins installed as well on a fresh installation of the launcher

**Comment by Dedoooo** [comment]
Make sure you have the correct action on hotbar and if you do have it, try replacing it and or messing with the mp slider if that nothing works work

**Comment by excalibert** [comment]
Turns out that was the issue; I had ruin something autoupgraded to broil 3 instead of baseline broil 3. Resolved.
