### ISSUE TITLE
[All Healers] Option to use Target of Target for DPS combos if a friendly player is targeted

### ISSUE THREAD

**Issue by Sylvansnake** [Nik-Potokar/XIVSlothCombo#578]
Target of Target would be very useful for tank healing without switching targets for DPS.

**Comment by k-kz** [comment]
This is currently being trialled and tweaked on SGE - expect to see it on all healers in the future when things get ironed out 😃

**Comment by Sylvansnake** [comment]
Another idea is an option to only use Regen/Barrier effects if the target has high HP (like 70% or more). If target has high HP and already Regen/Barrier on them, disable any further healing to prevent wasting MP or cooldowns on overhealing.

Also: If target is below 40% HP, do not cast Regen, but prioritize instant cast heals (Lily, Cooldowns, etc) followed by slow-cast normal heals.
