### ISSUE TITLE
Samurai st and aoe one button test

### ISSUE THREAD

**Issue by Stein121** [Nik-Potokar/XIVSlothCombo#58]
hey, this is what I have so far for one button rotation for single target rotation on samurai. Think we could optimize?

ST:

    internal class SamuraiYukikazeCombo : CustomCombo
    {
        protected override CustomComboPreset Preset => CustomComboPreset.SamuraiYukikazeCombo;

        protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level)
        {
            if (actionID == SAM.Yukikaze)
            {
                if (HasEffect(SAM.Buffs.MeikyoShisui))
                {
                    var gauge = GetJobGauge<SAMGauge>();
                    if (level >= SAM.Levels.Kasha && gauge.Sen.HasFlag(Sen.KA) == false)
                        return SAM.Kasha;
                    if (level >= SAM.Levels.Gekko && gauge.Sen.HasFlag(Sen.GETSU) == false)
                        return SAM.Gekko;
                    if (level >= SAM.Levels.Yukikaze && gauge.Sen.HasFlag(Sen.SETSU) == false)
                        return SAM.Yukikaze;
                }

                if (comboTime > 0 && level >= SAM.Levels.Shifu)
                {
                    var gauge = GetJobGauge<SAMGauge>();
                    if (lastComboMove == SAM.Hakaze)
                    {
                        if (level >= SAM.Levels.Shifu && gauge.Sen.HasFlag(Sen.KA) == false && FindEffect(SAM.Buffs.Shifu)?.RemainingTime < 10)
                            return SAM.Shifu;
                        if (level >= SAM.Levels.Jinpu && gauge.Sen.HasFlag(Sen.GETSU) == false && FindEffect(SAM.Buffs.Jinpu)?.RemainingTime < 10)
                            return SAM.Jinpu;
                        if (level >= SAM.Levels.Yukikaze && gauge.Sen.HasFlag(Sen.SETSU) == false)
                            return SAM.Yukikaze;
                        if (level >= SAM.Levels.Shifu && FindEffect(SAM.Buffs.Shifu)?.RemainingTime < 10 || gauge.Sen.HasFlag(Sen.KA) == false)
                            return SAM.Shifu;
                        if (level >= SAM.Levels.Jinpu)
                            return SAM.Jinpu;
                    }

                    if (lastComboMove == SAM.Shifu && level >= SAM.Levels.Kasha)
                        return SAM.Kasha;
                    if (lastComboMove == SAM.Jinpu && level >= SAM.Levels.Gekko)
                        return SAM.Gekko;
                }

                return SAM.Hakaze;
            }

            return actionID;
        }
    }

AOE:

    internal class SamuraiOkaCombo : CustomCombo
    {
        protected override CustomComboPreset Preset => CustomComboPreset.SamuraiOkaCombo;

        protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level)
        {
            if (actionID == SAM.Oka)
            {
                if (HasEffect(SAM.Buffs.MeikyoShisui))
                    return SAM.Oka;

                if (comboTime > 0 && lastComboMove == SAM.Fuga && level >= SAM.Levels.Mangetsu)
                {
                    var gauge = GetJobGauge<SAMGauge>();
                    if (level >= SAM.Levels.Oka && gauge.Sen.HasFlag(Sen.KA) == false && FindEffect(SAM.Buffs.Shifu)?.RemainingTime < 10)
                        return SAM.Oka;
                    if (level < SAM.Levels.Oka || gauge.Sen.HasFlag(Sen.GETSU) == false || FindEffect(SAM.Buffs.Jinpu)?.RemainingTime < FindEffect(SAM.Buffs.Shifu)?.RemainingTime)
                        return SAM.Mangetsu;
                    if (level >= SAM.Levels.Oka)
                        return SAM.Oka;
                }

                return SAM.Fuga;
            }

            return actionID;
        }
    }

**Comment by Nik-Potokar** [comment]
Yes this way of doing it is way better than my thinking! (alternating combos)
I've added a check if you don't have buffs since otherwise it would start with yukikaze combo. (For failsafe/Lowlvl stuff) 


Thank you!!!

**Comment by Stein121** [comment]
Np! I was thinking of adding something like this to cast Iajutsu when all 3 sens are up, could include kaiten right before as well, do you think that would be possible?


if (level >= SAM.Levels.Iaijutsu && gauge.Sen.HasFlag(Sen.KA | Sen.GETSU | Sen.SETSU) == true)
                        return OriginalHook(SAM.Iaijutsu);

**Comment by Nik-Potokar** [comment]
I've just added Kaiten feature but just without checking for any Sen incase you want to use it for something else (probably not)
Currently its just checking if you are in GCD

Maybe best way is to check for GCD + all the Sens or
Checking for 1/2/3 Sen + GCD since i assume you would use it on AoE and DoT?

**Comment by Stein121** [comment]
I personally like it but only at 3 sen cause you might not always want to apply the dot but you always want to use finisher at 3 sen.

**Comment by Nik-Potokar** [comment]
Il add as options for 1/2/3 Sen

**Comment by Nik-Potokar** [comment]
Updated with multiple Sen  [d14b54c](https://github.com/Nik-Potokar/XIVSlothCombo/commit/d14b54cebb8b528bd777124477d6c6f9eb3da50a)

**Comment by nativepapaya** [comment]
I've been testing the kaiten & single-button features and they seems to be working well, good job!

I have notice one side-effect. If you have the 

> iaijutsu to tsubame-geshi

 feature turned on, it conflicts with the kaiten feature (does not use kaiten)

**Comment by Nik-Potokar** [comment]
The issue should be now fixed
