### ISSUE TITLE
[AST] Prioritize Aspected Helios for AOE Heal

### ISSUE THREAD

**Issue by Sylvansnake** [Nik-Potokar/XIVSlothCombo#580]
Not sure why Celestial Opposition is first cast for AOE. I like to keep Regen up on my party during bosses or big pulls. I can't even put Aspected on a separate button because this combo uses Aspected as its base. Putting this combo on normal Helios might be a good idea too.

**Comment by k-kz** [comment]
We looked into this and won't be changing the order of casting, as it's less optimal to use your GCD first here.
We will consider moving the base button of the combo at some point in the future, though.
