### ISSUE TITLE
[AST] New feature return to previous target after Play doesn't work

### ISSUE THREAD

**Issue by Sylvansnake** [Nik-Potokar/XIVSlothCombo#588]
I enabled this option and instead of going back to my previous target, I end up targeting a random party member. I set up a macro as a workaround with Play and then /assist <2> but that's not a perfect solution, of course.

**Comment by Taurenkey** [comment]
I'll investigate once the game comes back online, however the feature leverages the game's `Last Target` value so unless you have other plugins such as ReAction installed it should always switch you back to your last target. This can be either a party member, enemy or random NPC, just whatever is registered as your target prior to targeting your current target.

**Comment by k-kz** [comment]
Addressed in #594
