### ISSUE TITLE
[SAM] Alternate positionals instead of having back>side priority 

### ISSUE THREAD

**Issue by Iaotle** [Nik-Potokar/XIVSlothCombo#598]
Duplicate of https://github.com/Nik-Potokar/XIVSlothCombo/issues/340, but basically the logic should be that you don't have a priority for positionals. They would alternate. So for example after pressing Gekko your next positional would be Kasha, no matter what the Sen count.

This would reduce the annoying behavior of using Meikyo->Gekko->Higanbana->Gekko->Kasha, and instead cause the combo to look like Meikyo->Gekko->Higanbana->Kasha->Gekko, similar to how Reaper works.

**Comment by k-kz** [comment]
The current logic doesn't have a "priority" per se, it's just the way it is based on [the opener from The Balance](https://cdn.discordapp.com/attachments/959778428024926258/968711127544496228/unknown.png).

Considering the use of `Higanbana` expends the single seal you have to execute it, you're left in a position where either positional is sufficient for the follow-up.
The current code follows up with `Gekko`, without making you need to reposition for your next positional after `Higanbana` as per your suggestion.
