### ISSUE TITLE
[SCH] Recitation Feature

### ISSUE THREAD

**Issue by dawn-star** [Nik-Potokar/XIVSlothCombo#605]
Could we possibly see a feature where Indomitability and Excogitation can be replaced by Recitation when available?

Ideally separate toggles for each, possibly with an option to only trigger with no AF stacks?

As always, thanks for the constant work on this amazing tech :)

**Comment by Tsusai** [comment]
Interesting.........
Coming soon (tm)

**Comment by k-kz** [comment]
Addressed in #636
