### ISSUE TITLE
[PVE] Melee DPS class "Use ranged attack when out of range"

### ISSUE THREAD

**Issue by Yaboije** [Nik-Potokar/XIVSlothCombo#607]
I noticed gunbreaker has a lightning shot feature when out of range and was wondering if this could be extended to the other melee classes that have a ranged attack filler.

**Comment by Dedoooo** [comment]
only jobs that don't have that currently are ninja and monk(monk doesn't have a ranged action)

so you're just asking for ninja to have it as well?

**Comment by Yaboije** [comment]
that sounds about right

would it conflict with mudras at a distance?

**Comment by Dedoooo** [comment]
if its coded right it shouldn't

**Comment by k-kz** [comment]
Nothing to add for `MNK`, and `Throwing Dagger Uptime Feature` exists for `NIN` now.
