### ISSUE TITLE
[BLM] Thunder, Fire1 options not working

### ISSUE THREAD

**Issue by dnorthrupva** [Nik-Potokar/XIVSlothCombo#61]
Thunder IV is being injected into the AoE, but the Enochian combo is ignoring Thunder entirely. Max level.

Upon additional testing, I think the 'Thunder' checkbox is actually calling the Blizzard Paradox function. Disabling it removes Paradox from casting after Blizzard, and the final checkbox (Blizzard Paradox) actually does nothing.

Additionally, unchecking Fire 1/3 makes it so Paradox is no longer part of the Enochian Stances. I'm unsure the relevance of Fire 1 in the rotation, so I wanted to uncheck it.

**Comment by Nik-Potokar** [comment]
Could you provide more details?
According to my friend there isn't any issues and it works as intended since its all made to be working with ALL options enabled.

And yes unchecking fire1/3 will make paradox no longer work since fire1 upgrades to paradox

**Comment by dnorthrupva** [comment]
Sure - Thunder III will never get inserted into the single targets Enochian rotation for me.
With everything checked it'll go 
Blizzard III, (Paradox is possible), B4, then B4 repeat until I go fire, then F4 x 3, Paradox, F4x3, Despair, stufck on F4 with no mana.

Thunder IV never finds its way in regardless of proc, or if it's not on target.

The rotation should be B3 -> B4 -> T3 -> Paradox -> F3 -> F4x3 -> Paradox -> F4 -> Despair.

Is there something I can check on my end to see the logic it's tracking?

**Comment by Nik-Potokar** [comment]
So thunder 3 is not in that combo at all unless you have a thunder cloud proc then it will change to thunder 3 if the debuff is about to expire on the target

Current logic behind it (This is not an automated version you have to swap stances yourself)

Prepull sharpcast > B3 > Thunder3 > B4 > F3(Manually swap to fire)> F4x3 > Fire1/Paradox > F4(Until less than 2.4k mana) > Despair > B3(Manually swap to fire) > Paradox > B4  > F3(Manually swap to fire)...Repeat
And the thunder will pop up whenever Debuff on target is about to expire < 4

**Comment by dnorthrupva** [comment]
Yep, I'm tracking. Should only happen if debuff is missing, or if proc is about to expire.

However, I am not seeing it at all. I tried toggling different settings, w
![thunderOff](https://user-images.githubusercontent.com/13740813/147422708-953a82b9-486e-4e18-b566-1330e8537a28.PNG)
hich is what my end comment is about.

If I enable 'Thunder' - It ACTUALLY is enabling the Blizzard -> Paradox effect. I am unsure what to use to record a GIF that isn't 200MB to show you, but I took two quick images.

For me it is B3 -> Paradox (if able) B4 -> ManualSwap -> F4x3 -> Paradox -> F4.
I am on v1.7.36

is there a file I maybe should delete to repopulate rules or something? While I do'nt have conflicts enabled now, I used to use XIVCombo, and later tried Grammer's


![thunderOn](https://user-images.githubusercontent.com/13740813/147422711-459633c6-ac09-4755-b6c9-7f4354741d97.PNG)

**Comment by dnorthrupva** [comment]
Seems my comment got deleted :D Your logic makes sense, and how I would expect. However, it isn't that way for me. I'm unsure how to get a small GIF but I took two images to show what's happening. (I got GIF Recorder but it's ~200MB for 2 seconds).

For me it's B3 > B4 > F3 > F4x3 > Paradox > F4x3 > Despair - Never triggering Thunder.

And my last comment in my original post is these images - I think it's rule isn't working for me at all. The 'Thunder' toggle is actually toggling the Blizzard -> Paradox rule, and the Blizzard Paradox rule isn't doing anything.
![thunderOff](https://user-images.githubusercontent.com/13740813/147423010-5de7b192-738e-4387-8e91-bf7eeec293f1.PNG)
![thunderOn](https://user-images.githubusercontent.com/13740813/147423011-0863cf33-5bdc-4f82-b358-c67b90787388.PNG)

This is on v1.7.36

**Comment by Nik-Potokar** [comment]
Do you have a thundercloud buff on you ? 
If yes then it will check if targets thunder is about to expire <4 sec and if so it will use the proc thunder 
If no it won't do anything 

Maybe the toggle got mixed up but as long as you got all enabled it should still work as intended.

I can take a video in the morning to demonstrate but I'm am unsure why it would act differently for you.

**Comment by dnorthrupva** [comment]
Well, it never initially applies Thunder either. It ignores procs and the initial cast.  Sure, that'd be good. Not sure how it'll help me solve my issue, but it'll be nice knowing it's isolated to me!

**Comment by dnorthrupva** [comment]
Ahhh, I think I figured it out.

```
 if (gauge.ElementTimeRemaining >= 0 && CustomCombo.IsEnabled(CustomComboPreset.BlackThunderFeature))
                    {
                        if (HasEffect(BLM.Buffs.Thundercloud))
                        {
                            if ((TargetHasEffect(BLM.Debuffs.Thunder3) && thunderdebuffontarget.RemainingTime < 4) || (!thunder3DebuffOnTarget && HasEffect(BLM.Buffs.Thundercloud) && thundercloudduration.RemainingTime > 0 && thundercloudduration.RemainingTime < 35))
                                return BLM.Thunder3;
                        }
```

This part works - If I apply it myself, and it's about to expire, the next spell will return as Thunder in the ice window.
It's respective fire part also works.


So looking at the code, maybe it is working as intended. And re-reading Enochian maybe it is working as intended, also. I thought it would apply the first ever Thunder as well
![image](https://user-images.githubusercontent.com/13740813/147427831-90053ae9-669d-411f-9d36-c6f593c4b03d.png)

But I see now it says it'll use "procs". So I guess this isn't a bug. Would it be considered a recommendation/is there a reason the initial time it doesn't cast Thunder? Is it just in case it won't live long and you don't 'want' to Thunder it?

**Comment by Nik-Potokar** [comment]
Il improve the description to make it more clear since that's why i think it confused you a bit and I'm sorry about that.

But currently you are meant to do 1st Thunder Manually and from on then it should be automated unless you get unlucky/downtime 
I could add thunder in as an initial cast and there will be 1 button combo coming.

**Comment by dnorthrupva** [comment]
Understood - Thanks for walking it through with me. Sorry for flagging it as a bug, was a misunderstanding on my part.
