### ISSUE TITLE
[PLD] #126 Atonement Feature bug

### ISSUE THREAD

**Issue by Tykku** [Nik-Potokar/XIVSlothCombo#613]
Atonement replaces Royal authority without Rule 126 on

Steps to reproduce:
Have Rule 123 on
Go through royal authority combo
Press Requiescat
royal authority gets replaced with atonement even though Rule 126 is not checked

Other Rules that are checked
122
123
135
141
142

Also tested with just Rule 123, still bugs

**Comment by k-kz** [comment]
Addressed in #614 

For future reference, the feature numbers are dynamic and change based on what you have selected/displayed throughout the plugin's entire list! We can't do anything with that info!
