### ISSUE TITLE
[SAM] update combos including Fuga to be Fuko at 86

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/XIVSlothCombo#62]
Any combos that include Fuga don't work past 86, as it upgrades to Fuko

**Comment by sauronshotdogs** [comment]
In addition, the SimpleSamuraiAOE just changes Oka to Fuko, will keep spamming Fuko

**Comment by Nik-Potokar** [comment]
I've updated it!
Please let me know if it works now since I cannot test it yet with fuko if not il add another fix

**Comment by sauronshotdogs** [comment]
for 2.0.1.2 it's still stuck on Fuko

**Comment by sauronshotdogs** [comment]
All working, thanks!
