### ISSUE TITLE
[SCH] DPS Feature Buff Option

### ISSUE THREAD

**Issue by hokeenthong** [Nik-Potokar/XIVSlothCombo#626]
Hi, 

Chain Stratagem does not seem to fire off for this option.  

Thanks for looking at this.

**Comment by Tsusai** [comment]
I had a feeling about this when I was reviewing/redoing the DPS feature last night & this morning. I believe it would  suffer from this same issue you described, just like lucid dreaming did on Sage.  I'm currently working on Scholar, and already have a potential fix on my end.

**Comment by hokeenthong** [comment]
Thank you very much Tsusai.

**Comment by k-kz** [comment]
Addressed in #636
