### ISSUE TITLE
[NIN] Raiju stacking feature?

### ISSUE THREAD

**Issue by Yaboije** [Nik-Potokar/XIVSlothCombo#627]
Hello, thank you for the recent additions (ninki pooling) they have been working great! That said I have a new suggestion:

Raiju proc is currently the top priority right after using Raiton, would it be possible to allow the stacking of the procs and maybe have it dump @ 3 stacks so it can be controlled to be dumped during burst phases. This also gives Forked Raiju a chance to shine outside of trick attack as an uptime/mobility feature rather than having procs used instantly.

**Comment by Taurenkey** [comment]
Will be adding Raiju pooling to the next update. Select from 1-3 stacks to have before spending.

**Comment by Yaboije** [comment]
That's unfortunate :(

Thanks for looking into it anyway!

**Comment by k-kz** [comment]
> Is there anything that can be done about the first Raiton that always comes before using Kassatsu during the opener? I find that I have to manually trigger Kassatsu right after Suiton to avoid using raiton/raiju before hyosho.

We may re-address this in the future once we've implemented some new stuff for openers down the road - currently, the logic is messed with a bit on the opener due to the animation locks from Trick Attack.
