### ISSUE TITLE
[RDM] Embolden/Manafication/Swiftcast CD toggles in Smartcasting feature

### ISSUE THREAD

**Issue by Yaboije** [Nik-Potokar/XIVSlothCombo#628]
As the name suggests, can we have these cooldowns added as a toggle in the smartcasting feature? (single/aoe)

**Comment by NikkoXIV** [comment]
Yes.  Everything is getting reworked right now with RDM, so it might look a little different, but there will be options for all those.

**Comment by Yaboije** [comment]
Thank you :)

**Comment by k-kz** [comment]
Currently being addressed in a job rework.
