### ISSUE TITLE
[NIN-PVP] Feature to use Goka Mekkyaku

### ISSUE THREAD

**Issue by Soupbreadv** [Nik-Potokar/XIVSlothCombo#629]
It would be nice to have an option to use Goka Mekkyaku in the burst mode feature instead of stun. In many situations I don't like using the stun! Goka is also more raw DPS than Raiju
Thank you for consideration!

**Comment by Taurenkey** [comment]
That is part of the AoE Burst mode feature instead.

**Comment by Soupbreadv** [comment]
I've used the AOE but If it were possible I'd want to use it in the normal burst combo instead.Since aoe does Doton > goka. What I would want is Hyosho > goka.

Its ok if not just an idea :)

**Comment by k-kz** [comment]
Features probably staying as ST/AoE going forward. Will re-address if necessary
