### ISSUE TITLE
[MNK] Unreachable code

### ISSUE THREAD

**Issue by Iaotle** [Nik-Potokar/XIVSlothCombo#63]
MNK has some unreachable code:

https://github.com/Nik-Potokar/XIVSlothCombo/blob/2b106c279aa3c30a567815693fc3a121df9fc275/XIVSlothCombo/Combos/MNK.cs#L207-L208

**Comment by damolitionn** [comment]
I haven't played MNK for a while, but isn't that unreachable code repetitive? It looks like it does the same thing in line 199. If so, it can just be deleted:

`                if (HasEffect(MNK.Buffs.FormlessFist))
                {
                    if(!HasEffect(MNK.Buffs.LeadenFist))
                        return MNK.DragonKick;
                }`

**Comment by Nik-Potokar** [comment]
Yep was just a leftover from testing deleted now
