### ISSUE TITLE
[SMN] AoE options skipping abilities and early egi summons

### ISSUE THREAD

**Issue by Tiamat114** [Nik-Potokar/XIVSlothCombo#630]
I'm lazy and just copy pasting from discord. This issue seems to have started with either the most recent or update just prior to the most recent.

On the first bahamut, it doesnt seem to when using the AoE option to use enkindle or astral flow. Seems to happen with even the smallest amount of options checked to consolidate buttons to 1 button. Those being Enable AOE combo features, demi Summons AOE Combo, and AOE Demi Attacks on Combo. No other options are checked for testing purposes. Most options are checked normally. It WILL use them however when the equivalent Single Target options are checked for the single target combo.

Also once into the egi summoning phase, summoning the next egi takes priority over finishing the Precious Brilliance cast of the current egi. I.e. it summons Garuda while it would have been able to cast 2 more Topaz Catastrophes. It blows them all very quickly and leaves you spamming Ruin until bahamut/phoenix comes back up.

**Comment by Taurenkey** [comment]
I've addressed this in the upcoming update.

**Comment by Tiamat114** [comment]
Ok cool, thank you.

**Comment by k-kz** [comment]
Addressed in #631
