### ISSUE TITLE
Consider removing PvP combos

### ISSUE THREAD

**Issue by halcyonight** [Nik-Potokar/XIVSlothCombo#634]
As we all well know, the advantages bestowed by PvP plugins — however slight — are a highly contentious issue amongst the FFXIV PvP community. While the developers have hitherto turned a blind eye to PvE plugins (even if such plugins blatantly cross the line to cheating territory), PvP is a completely different beast and the devs are no doubt scrutinizing this issue closely. 

There's no reason to give the devs any more ammo than they need to shut down plugins. I've enjoyed XIVCombo on PvE content thus far, and it will be a real pity if the devs actually do eradicate XIVCombo and even Dalamud over this issue.

**Comment by Taurenkey** [comment]
No. PvP features have existed for a long time. The devs don't need ammo to shut down plugins, they're perfectly within their rights to do so at any time for any reason. I highly doubt the PvP features we're putting out will somehow be the straw that breaks the camel's back.

**Comment by k-kz** [comment]
This would be a more serious consideration if there weren't literal bots and hacks crawling the PvP scene (and PvE, but that's another topic). XIVSlothCombo is not even close to doing what some things out there offer - your concerns seem misguided.
