### ISSUE TITLE
[BLM] Level check missing on Thunder3 causing lv <45 BLM to try to cast Thunder3

### ISSUE THREAD

**Issue by egerritse** [Nik-Potokar/XIVSlothCombo#647]
https://github.com/Nik-Potokar/XIVSlothCombo/blob/987c1fcf215771743fc034437eda760f51ffea4e/XIVSlothCombo/Combos/BLM.cs#L603

[BLM] Level check missing on Thunder3 causing lv <45 BLM to try to cast Thunder3

**Comment by grimgal** [comment]
#646

**Comment by k-kz** [comment]
Addressed in #646
