### ISSUE TITLE
[DRG] Simple AOE

### ISSUE THREAD

**Issue by Alkeyd** [Nik-Potokar/XIVSlothCombo#653]
If I turn on the Simple AOE DRG option, only it, I can't use the two Spineshatter Dive charges, the second one stay locked

**Comment by Taurenkey** [comment]
Hi.

Please do `/scombo debug` in chat ingame and paste the file it makes here so we can take a look.

**Comment by Taurenkey** [comment]
You need to enable one of the sub options to enable the use of dives. However, there's bigger issues with our DRG code so even turning them on you'll likely experience issues until I can address it for one of the next updates.

**Comment by Alkeyd** [comment]
Yes yes, I prefer to use the Dives manually, but it is preventing me from spending the two Spineshatter Dive charges from the original skill =/

**Comment by Alkeyd** [comment]
Yes, before the 6.1 update I didn't have this problem =/

**Comment by k-kz** [comment]
Can't replicate this at all - the code should have no effect on manual use of the skill whatsoever.
