### ISSUE TITLE
[BLM] #55 Simlpe AoE Feature gets stuck below lvl 50 on casting Flare when below 7000MP

### ISSUE THREAD

**Issue by egerritse** [Nik-Potokar/XIVSlothCombo#656]
https://github.com/Nik-Potokar/XIVSlothCombo/blob/f00493b27dd55037dc7ba8468fff7a9e75e8ac19/XIVSlothCombo/Combos/BLM.cs#L388

                // Fire 2 / Flare
                if (gauge.InAstralFire)
                {
                    if (currentMP >= 7000)
                    {
                        if (gauge.UmbralHearts == 1)
                        {
                            return BLM.Flare;
                        }
                        return level >= BLM.Levels.HighFire2 ? BLM.HighFire2 : BLM.Fire2;
                    }
                    else if (currentMP >= BLM.MP.Despair)
                    {
                        return BLM.Flare;
                    }
                }

Current logic causes this rotation when below 7000MP to check if current MP is high enough for despair and tries to cast Flare.
When below lvl 50 you don't have Flare and below 72 no Despair.
As a lvl 48 BLM this rotation gets stuck after 2 Fire2 casts when MP drops below 7000 and does not recover.

**Comment by grimgal** [comment]
#658 658

**Comment by k-kz** [comment]
Addressed in #658
