### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by ShadowCid** [Nik-Potokar/XIVSlothCombo#676]
Repeatable memory leak that pauses when this plugin is disabled. Memory allocation to FFXIV goes up by about 1.5 - 2 MB / sec with no reclamation. When the plugin is disabled the memory leak is paused but the allocation is not lowered until FFXIV is restarted. 

Version 3.0.14.0
Settings enabled
All Jobs: Global Tank Features (all checked)
Global Magical Features (all checked)
Reaper: Slice combo and Scythe combo all checked
Summoner: Enable Single Target Combo checked - > Burst phase unchecked, Titan choice for summon, swiftcast options unchecked, Searing light on ruin, no burst, Demi summons all checked. Enable AOE all checked, option 1. everything below checked.
Warrior: all checked except melee onslaught
White Mage: all checked except oGCD Heals/Shields and No Swift Opener

PVP:
All jobs - Prevent Mash Cancelling and Quick Purify (all options) checked
Warrior: Burst Mode checked, bloodwhetting and blota option unchekced.

**Comment by F0xbit** [comment]
Seconding this. 

Issue persists after unchecking every single option.

**Comment by abranon** [comment]
The following error was repeating:

> System.NotImplementedException: The method or operation is not implemented.
>    at XIVSlothComboPlugin.ConfigWindow.Debug.Invoke(UInt32 actionID, UInt32 lastComboActionID, Single comboTime, Byte level) in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\ConfigWindow.cs:line 137
>    at XIVSlothComboPlugin.Combos.CustomCombo.TryInvoke(UInt32 actionID, Byte level, UInt32 lastComboMove, Single comboTime, UInt32& newActionID) in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\CustomCombo.cs:line 151
>    at XIVSlothComboPlugin.IconReplacer.GetIconDetour(IntPtr actionManager, UInt32 actionID) in D:\a\XIVSlothCombo\XIVSlothCombo\XIVSlothCombo\IconReplacer.cs:line 77
> 2022-05-09 10:10:43.132 -05:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wNS0wOVQxMDoxMDo0My4xMzI1MTEtMDU6MDAiLCJJbmZvIjoiU3lzdGVtLk5vdEltcGxlbWVudGVkRXhjZXB0aW9uOiBUaGUgbWV0aG9kIG9yIG9wZXJhdGlvbiBpcyBub3QgaW1wbGVtZW50ZWQuXHJcbiAgIGF0IFhJVlNsb3RoQ29tYm9QbHVnaW4uQ29uZmlnV2luZG93LkRlYnVnLkludm9rZShVSW50MzIgYWN0aW9uSUQsIFVJbnQzMiBsYXN0Q29tYm9BY3Rpb25JRCwgU2luZ2xlIGNvbWJvVGltZSwgQnl0ZSBsZXZlbCkgaW4gRDpcXGFcXFhJVlNsb3RoQ29tYm9cXFhJVlNsb3RoQ29tYm9cXFhJVlNsb3RoQ29tYm9cXENvbmZpZ1dpbmRvdy5jczpsaW5lIDEzN1xyXG4gICBhdCBYSVZTbG90aENvbWJvUGx1Z2luLkNvbWJvcy5DdXN0b21Db21iby5UcnlJbnZva2UoVUludDMyIGFjdGlvbklELCBCeXRlIGxldmVsLCBVSW50MzIgbGFzdENvbWJvTW92ZSwgU2luZ2xlIGNvbWJvVGltZSwgVUludDMyJiBuZXdBY3Rpb25JRCkgaW4gRDpcXGFcXFhJVlNsb3RoQ29tYm9cXFhJVlNsb3RoQ29tYm9cXFhJVlNsb3RoQ29tYm9cXEN1c3RvbUNvbWJvLmNzOmxpbmUgMTUxXHJcbiAgIGF0IFhJVlNsb3RoQ29tYm9QbHVnaW4uSWNvblJlcGxhY2VyLkdldEljb25EZXRvdXIoSW50UHRyIGFjdGlvbk1hbmFnZXIsIFVJbnQzMiBhY3Rpb25JRCkgaW4gRDpcXGFcXFhJVlNsb3RoQ29tYm9cXFhJVlNsb3RoQ29tYm9cXFhJVlNsb3RoQ29tYm9cXEljb25SZXBsYWNlci5jczpsaW5lIDc3IiwiQ29udGV4dCI6IltYSVZTbG90aENvbWJvXSBEb24ndCBjcmFzaCB0aGUgZ2FtZSJ9
> 2022-05-09 10:10:43.132 -05:00 [ERR] [XIVSlothCombo] Don't crash the game

**Comment by Nyuuuwu** [comment]
The memory leak issue has been addressed in #678, and a hotfix update should be made soon.
