### ISSUE TITLE
Something going wrong 

### ISSUE THREAD

**Issue by BrakTap** [Nik-Potokar/XIVSlothCombo#677]
The game went from 75 fps to 30fps  when checking the launcher log i got these error lines being send every 0.001 second.
Disabling the plugin fixed the issue.

![tAQ3Q7Y](https://user-images.githubusercontent.com/98245129/167452122-ae2ebc06-3d84-45e7-94b1-73d8e1e4336d.png)

**Comment by Nyuuuwu** [comment]
The memory leak issue has been addressed in https://github.com/Nik-Potokar/XIVSlothCombo/pull/678, and a hotfix update should be made soon.
