### ISSUE TITLE
"Single button heatblast on main combo" feature

### ISSUE THREAD

**Issue by KullaniciAdiAlinmis** [Nik-Potokar/XIVSlothCombo#679]
"Single button heatblast on main combo" feature or any other heat blast feature does not work correctly. It can't even do 6 gcds during wildfire window.

**Comment by augporto** [comment]
@KullaniciAdiAlinmis i just tried it in game , did not had problems, could you log it on a dummy and post a img of the of wildfire section of xivanalysis ? ty

**Comment by KullaniciAdiAlinmis** [comment]
I have no idea why it was not working properly and I can't even recreate the problem cause reinstalling xivlauncher and all the addons fixed it. It works perfectly now. 
Just to explain the problem I had, it was trying to double weave ricochet and gauss round during wildfire window and it was failing to do so resulting in less than 6 gcds used.
Strange thing is I had not changed anything nor installed a new addon etc. when this problem occurred and reinstalling evertyhing fixed it.

**Comment by k-kz** [comment]
Sounds like it might have been an issue relating to re-slotting a skill, or similar. Feel free to re-open the issue if this occurs again and isn't solved via re-slot!
