### ISSUE TITLE
[SAM] Remove Seigan to Third Eye

### ISSUE THREAD

**Issue by dnorthrupva** [Nik-Potokar/XIVSlothCombo#68]
[Seigan was removed](https://ffxiv.gamerescape.com/wiki/Hissatsu:_Seigan). I believe it's safe to remove #127

**Comment by dnorthrupva** [comment]
https://github.com/Nik-Potokar/XIVSlothCombo/blob/main/XIVSlothCombo/CustomComboPreset.cs#L402

Assuming it just needs to be deleted from here? Trying to understand structure more to help with PRs

**Comment by Nik-Potokar** [comment]
Yes just needs to be deleted since it seems I missed it
