### ISSUE TITLE
[SAM] Iaijutsu to Ogi Namikiri

### ISSUE THREAD

**Issue by Alkeyd** [Nik-Potokar/XIVSlothCombo#680]
The option to transform Iaijutsu to Ogi Namikiri is not transforming into Kaeshi: Namiriki

![image](https://user-images.githubusercontent.com/94228374/167544255-3388ae7c-85fc-4cc0-b9a6-43a726c9e84d.png)

But if I turn off the Iaijutsu option for Tsubame then it works correctly

**Comment by k-kz** [comment]
Addressed in #687
