### ISSUE TITLE
Certain Rotation Categories breaking skills with more than one charge to them

### ISSUE THREAD

**Issue by LazzyWazzy** [Nik-Potokar/XIVSlothCombo#682]
I've noticed that the Simple Dragoon AOE category option makes me unable to use spinesplitter dive when said skill's charges aren't on cooldown. I tried to find out what exact option in the category breaks the skill, but it seems the category itself is breaking the skill. I had an almost identical issue with dancer's Ev Avant skill that stopped after I turned off the  Combined Dance Feature under the Dance Feature category, but at the moment I can't seem to replicate the issue, so there's probably a bug somewhere that I triggered unknowingly after completing a lvl 80 dungeon run. If I find out the direct cause, I'll make sure to report it.

**Comment by k-kz** [comment]
Can't comment on the DRG stuff personally, but I'm surprised to hear about the DNC one - there's no code relating to En Avant, at all (outside of its ID and required level being listed in the file).

It seems like something else you've installed might be interfering?

**Comment by LazzyWazzy** [comment]
Oh sorry, didn't realize someone replied to this. No I'm more than certain that there aren't any other plugins interfering with the dash skill.  Also I just now found out that the triple cast skill for black mage is broken in a similar manner, except it's broken entirely regardless of what settings I have enabled and only works when I disable the sloth plugin.

**Comment by k-kz** [comment]
Unable to replicate - closing for now. Please let us know if the issue re-occurs.
