### ISSUE TITLE
[WHM] Thin Air Raise Feature + Global

### ISSUE THREAD

**Issue by Critiko** [Nik-Potokar/XIVSlothCombo#683]
Using the WHM Thin Air Raise Feature with the Global Healer: Raise Feature makes you cast cast Raise before Thin Air when spamming the button.

It works correctly if you use it with WHM Alternative Raise Feature.

**Comment by Taurenkey** [comment]
I've tweaked the global feature to be more responsive overall, so it should now immediately go into Thin Air instead of waiting for the Swiftcast buff to apply. Fixed for the next update.
