### ISSUE TITLE
[NIN] Huraijin / Armor Crush x Huraijin / Raiju

### ISSUE THREAD

**Issue by Alkeyd** [Nik-Potokar/XIVSlothCombo#686]
![image](https://user-images.githubusercontent.com/94228374/167766498-921176b4-4172-473d-b49a-e2299d2dea52.png)

Armor Crush is taking priority over Raiju if both options are on, would it be possible to invert this priority? Because if I use any skill while I have Raiju's buff I lose the buff.

**Comment by k-kz** [comment]
@Taurenkey let me know if your upcoming rework covers this and I'll deal with the post accordingly.
