### ISSUE TITLE
[AST] Possible to put play card / divination on dps single button option?

### ISSUE THREAD

**Issue by kryuzei** [Nik-Potokar/XIVSlothCombo#689]
Is it possible to do this?

**Comment by Tsusai** [comment]
Divination added, not sure about the play card feature (I don't play the class all that much)

**Comment by k-kz** [comment]
Reopening due to accidental closure on PR merge.
Play Card not yet addressed.

**Comment by Taurenkey** [comment]
Completed in #1170
