### ISSUE TITLE
[WHM] Add check for Cure II Proc

### ISSUE THREAD

**Issue by dnorthrupva** [Nik-Potokar/XIVSlothCombo#69]
I thought when I found this (under it's old name) there was a check similar to the Medica II one, but for Cure II procs.

Something like "Replace Cure 1 when Free Cure is proceed".

Am I mis-remembering that, or was it removed for a reason? I was quite a fan of the idea and wanted to try it out.

**Comment by Nik-Potokar** [comment]
Only cure feature there ever was is the level sync one 

Also I am not going to be adding free cure proc feature since there is no reason to use cure 1 over 2 like ever 
(Cure1 spammers PTSD)
