### ISSUE TITLE
[RDM] AoE Melee Combo gets stuck on enchanted moulinet at lvl70 synced content

### ISSUE THREAD

**Issue by Iaotle** [Nik-Potokar/XIVSlothCombo#694]

**Comment by NikkoXIV** [comment]
What other options do you have checked?  Verflare/Verholy should be available as soon as you have 3 stacks.  If you're not using the Melee Finisher option on Scatter/Impact, it will stay as Enchanted Moulinet as long as you have mana so you don't lose your stacks.

**Comment by Iaotle** [comment]
Like all of them. Anyway I run out of mana and it stays enchanted moulinet.

**Comment by NikkoXIV** [comment]
Check to see if you have the Melee finisher on at least scatter/impact (option 2 or option 3).  Then it should change to verflare and verholy, then scorch at 80 and resolution at 90.  Or just activate verflare/verholy manually on any of the Veraero/Verthunder versions, that's an SE thing.

**Comment by Iaotle** [comment]
Combos shouldn't break no matter what option you choose. If there is a conflicting option that makes the aoe combo get stuck on moulinet at level 70 then it should be fixed.
