### ISSUE TITLE
v2.0.0.2?

### ISSUE THREAD

**Issue by dnorthrupva** [Nik-Potokar/XIVSlothCombo#70]
I logged on earlier to a failed download, but relaunching it successfully grabbed '2.0.0.2' - I think it was 1.6 last night. I don't see anything different, and the releases tab shows a release 14 days ago. Is there a patch notes area, or is it just assumed anything on main branch == installed?

(I'm thinking v2 might be part of the rebranding?)

**Comment by Nik-Potokar** [comment]
Currently anything thats on main branch is also in-game, you can always check whats been added if you go under the commits section on main page [Here](https://github.com/Nik-Potokar/XIVSlothCombo/commits/main)

And you could say that v2 is a part of the rebranding yeah and some other stuff that has been added thanks to @Iaotle such as automation for deployment

**Comment by dnorthrupva** [comment]
Got it - Thanks for replying. Very interested in this project, so going to clone a dev branch and mess with it also. Wanted to ensure I didn't somehow get AFKIfiied or something.
