### ISSUE TITLE
[All Healers] Request to add an un-comboed dps button on DOT skill

### ISSUE THREAD

**Issue by abranon** [Nik-Potokar/XIVSlothCombo#703]
Alternatively moving the combo entirely onto their dot skill and leaving the main dps skill unchanged.
Intention behind this request is to prevent wasting CDs on a singular trash mob when you stop AOE'ing, similar to your "Main Combo on Demolish" option on MNK.  

I believe SGE would be the natural exclusion of this request.

**Comment by Tsusai** [comment]
Combo option to put the on the DPS feature set on the DoT already somewhat exists for most healers. I took it out of SCH a while back, but it's been submitted in a new way similarly to AST. I have a plan for SGE but it needs testing.
- [X] SCH #740  
- [ ] WHM
- [X] AST #716 
- [ ] SGE

**Comment by abranon** [comment]
Wanted to say that they work exactly how I hoped they would, I doesn't let you prepull Malefic/Broil but that's perfectly fine, I don't mind. Can't wait for WHM and to see how you plan on doing this for sage

**Comment by Tartarga** [comment]
- [ ] SGE #908

**Comment by Tartarga** [comment]
[X] WHM #1282
