### ISSUE TITLE
[PVE] [RPR] AOE Enshroud Combo Sub-options not working

### ISSUE THREAD

**Issue by JayfieldAlfred** [Nik-Potokar/XIVSlothCombo#707]
Checking "Enshroud Option -> Lemure's Slice Option and Communio Finisher Option" in the Scythe Combo Feature when Enshroud only Grim Reaping was shown and does not trigger Lemure's Scythe and Communio when the conditions were met. So during the AOE enshroud phase Spinning Scythe becomes "Grim Reaping -> Grim Reaping -> Grim Reaping -> Grim Reaping -> Grim Reaping" instead of "Grim Reaping -> Grim Reaping -> Lemure's Scythe -> Grim Reaping -> Grim Reaping -> Lemure's Scythe -> Communio"

**Comment by Dedoooo** [comment]
this was fixed in the latest PR. wait for the next update 😃
