### ISSUE TITLE
Triple Cast on BLM is broken

### ISSUE THREAD

**Issue by LazzyWazzy** [Nik-Potokar/XIVSlothCombo#708]
When there's less than 2 charges of triple cast, it becomes unusable with a notification saying "Not yet ready" and breaks the entire skill rotation of BLM.

**Comment by grimgal** [comment]
Which features were enabled when this happened? Did the simple BLM rotation just get stuck at triplecast, or were you just unable to use triplecast during the simple BLM rotation when it was less than 2 charges? What level were you as well when this occurred?

**Comment by LazzyWazzy** [comment]
Without the Triplecast/Swift Cast pool option, Blackmage would be unusable when using the simple blackmage feature. It doesn't matter what settings I have disabled or enabled, as long as the Sloth Combo plugin is still installed on my client, I can't use Triplecast without there being 2 charges available.

**Comment by LazzyWazzy** [comment]
Wait nvm it's no longer forcing me to use triplecast when there's no GCD.

**Comment by k-kz** [comment]
Seems to be a plugin conflict issue as discussed with others on the Discord. Closing for now.
