### ISSUE TITLE
BRD: one button oGCDs

### ISSUE THREAD

**Issue by asevrinsky** [Nik-Potokar/XIVSlothCombo#71]
I only tried this with single target, but this option seems to ignore the fact that Bloodletter has stacks.  It'll go Bloodletter, Empyreal Arrow, Sidewinder, and then swap back to Empyreal Arrow and sit on that cooldown even though I have more stacks of Bloodletter.

I think the default behavior for this should be to always have Bloodletter/Rain of Death up unless one of the other oGCDs is off cooldown.  Just prioritizing the shortest cooldown doesn't work because of Ballad, so that's why you always want Bloodletter/RoD available unless something else is actually off cooldown.

**Comment by Nik-Potokar** [comment]
Reworked this a bit please check it out and let me know

**Comment by asevrinsky** [comment]
Seems to have fixed the original complaint.  It would be nice if having the songs on there too was optional, sometimes you want to prioritize specific ones for specific moments.

**Comment by Nik-Potokar** [comment]
Will add songs as optional option toggle
And RoD feature option 

Thank you

**Comment by Nik-Potokar** [comment]
Added songs and optional toggle and RoD Function 
Let me know if it needs any adjustments
