### ISSUE TITLE
[RDM] Smart Aoe & smart single target feature

### ISSUE THREAD

**Issue by SkyAurora** [Nik-Potokar/XIVSlothCombo#72]
With the smart AOE feature, if your black mana is higher you can't use Verholy or Scorsh after your AOE melee combo because Veraero II is not turning into it. It still works fine the other way around with Verthunder II turning into Verflare, except it doesn't switch to Scorch after the Verflare.

The smart single target feature just doesn't work at all when you get the upgraded spells Verthunder III and Veraero III at level 82. It also doesn't switch to the Verstone/Verfire procs when you get them.

**Comment by hokeenthong** [comment]
What does the smart single target feature do? Sorry but it does not explain in the setup.

**Comment by Nik-Potokar** [comment]
> With the smart AOE feature, if your black mana is higher you can't use Verholy or Scorsh after your AOE melee combo because Veraero II is not turning into it. It still works fine the other way around with Verthunder II turning into Verflare, except it doesn't switch to Scorch after the Verflare.
> 
> The smart single target feature just doesn't work at all when you get the upgraded spells Verthunder III and Veraero III at level 82. It also doesn't switch to the Verstone/Verfire procs when you get them.

Can you do me a favor and test it in lvl 80 content since that's what I've tested on and it worked (also only enable smart options and nothing else)

**Comment by Nik-Potokar** [comment]
> What does the smart single target feature do? Sorry but it does not explain in the setup.

It does the mana balancing for you and proc management depending on mana

**Comment by Nik-Potokar** [comment]
I've added checks with the latest update that conflict with the smart cast option (Since that was most likely the issue here) so the issue should be fixed now!

But do let me know if any other issues come up

Thanks

**Comment by SkyAurora** [comment]
Everything in smart aoe/single seems to be working fine except Verthunder II and Veraero II don't turn into Impact when swift cast is used.

**Comment by Nik-Potokar** [comment]
Ahh seems like I missed that will add in later today

**Comment by Nik-Potokar** [comment]
Added swiftcast check into the aoe feature so now it should work

**Comment by SkyAurora** [comment]
Works. Thanks.
