### ISSUE TITLE
[PLD] Can the simple combos be moved to Fast Blade / Total Eclipse instead of the combo enders?

### ISSUE THREAD

**Issue by Yaboije** [Nik-Potokar/XIVSlothCombo#723]
As the title suggests, I like having agency on whether I use Royal Authority or Goring Blade depending on the combat situation similar to MNK Snap Punch and Demolish.

**Comment by k-kz** [comment]
Will look into it, but typically if you want agency you shouldn't be using any Simple modes in the first place.

**Comment by Yaboije** [comment]
Fair point !
