### ISSUE TITLE
[ALL] PotD `Amnesia` protection

### ISSUE THREAD

**Issue by k-kz** [Nik-Potokar/XIVSlothCombo#731]
Should probably implement this on a per-job basis, without a toggle (always on).
Thanks to KyaXIV for pointing out the initial issue and some edge-case stuff!

##
- [x] ~~Confirm `Amnesia` debuff is `PotD`/`HoH` exclusive~~ Exists elsewhere
- [x] Build list of skills that remain available under `Amnesia` for each job
- [x] Create base "rotations"
- [x] Ensure proper level checks

##
- [x] ~~Check debuff was removed from `All-seeing Eye` fight (`Dzemael Darkhold`)~~ Still present
- [x] Check debuff was removed from `Amon` fight (`Syrcus Tower`)

##
- [x] Test on a couple of jobs
- [x] Implement across all jobs

**Comment by duckfeets** [comment]
I have a few :

1 - It is not PoTD / HoH exclusive
2 - For skills afaik anything labeled an ability becomes unusable. Weaponskills and spells are fine.
—
1 - It is still present in All-seeing Eye fight (Dzemael Darkhold) -- Tested on 2022-05-19

**Comment by k-kz** [comment]
> I have a few :
> 
> 1 - It is not PoTD / HoH exclusive
> 2 - For skills afaik anything labeled an ability becomes unusable. Weaponskills and spells are fine.
> —
> 1 - It is still present in All-seeing Eye fight (Dzemael Darkhold) -- Tested on 2022-05-19

Thanks for your input! This is very much backlogged but we already have all the details surrounding the checkboxes above + more (it's already been looked at by testers in our Discord) so please don't worry about looking any further!!

**Comment by k-kz** [comment]
Implemented in a global fashion.

**Comment by ibigfire** [comment]
This seems to be no longer working entirely.  I was running Heaven on High as a MCH and when hit by the floor status effect that removes all abilities SlothCombo did not adapt to do a weaponskill only rotation.  It stayed on an ability that could not be used instead.

**Comment by Taurenkey** [comment]
The code to detect the statuses are in the plugin, but not really wired up properly. Amnesia for example isn't actually hooked up to anything.

Given how Sloth works, it might take a bit before these checks are actually applied to every job properly.

**Comment by ibigfire** [comment]
Ah, I see.  Gotcha, thank you for the info!  I suspect this is likely to become a lot more relevant to people once the new Deep Dungeon drops next patch.
