### ISSUE TITLE
[All Melees] Add True North option before positionals

### ISSUE THREAD

**Issue by KalasB** [Nik-Potokar/XIVSlothCombo#743]
I feel like a feature that adds TN before positionals (if there are no higher priority weaves) would really suit the sloth playstyle.

**Comment by Yaboije** [comment]
I noticed that some of the melee dps role features are implemented but only for these two:

samurai has true north on cd with during meikyo windows
reaper has bloodbath on a % threshold

would be very cool if these were universal for all melee dps

**Comment by Rabalaba** [comment]
or add them if your not in the correct position so charges are not wasted

**Comment by Rabalaba** [comment]
here is the code to check if player is in rear positional, i can work the math out for flank as well if its needed.

var entityAngle = Math.Atan2(LocalPlayer.Position.X - CurrentTarget.Position.X, LocalPlayer.Position.Z - CurrentTarget.Position.Z);
var deviation = entityAngle - CurrentTarget.Rotation;
var absDeviation = Math.Abs(deviation);
var leftover = Math.Abs(absDeviation - Math.PI);

if (leftover > (Math.PI * 1.75) || leftover < (Math.PI * .25))  // you are behind target

**Comment by k-kz** [comment]
We might add further features to expend excess TN stacks, but we have 0 intention of adding positional math to Sloth.
It's something we tested and considered a while back, but there are (or, certainly will be) other plugins better suited for handling positionals.

**Comment by halcyonight** [comment]
Old thread but whats wrong with Rabalaba's positional detection code above? I used it to detect when my ninja is on the flank or rear of the enemy and modified the ninja code to use the appropriate positional accordingly (always armor crush on flank, and always aeolian edge on rear unless ninki is falling off, in which case I'd armor crush), and it worked like a charm. 

Unless the math is considered too heavy for the plugin?

**Comment by Rabalaba** [comment]
I don't think it is computationally heavy, I use a modified version on bard to detect how many targets are within a 45 degree cone in front of me to detect if quick knock / ladensbite would be a dps increase over single target skill and do not notice any slow downs.  I do believe its a rabbit hole that would begin having sloth be more automated than it aught to be.

**Comment by halcyonight** [comment]
lol this plugin went down the rabbit hole long ago, reached the center of the earth, and already emerged from the other side

**Comment by k-kz** [comment]
`True North` options have been added to all melee jobs except DRG at this point 👍🏼

**Comment by Kagekazu** [comment]
TN is also added in my DRG PR, so all melees have TN option now

**Comment by Kagekazu** [comment]
can be closed, is on all melee jobs.
