### ISSUE TITLE
[WHM] Assize feature doesn't work on Holy 3 but working on Holy 1

### ISSUE THREAD

**Issue by kryuzei** [Nik-Potokar/XIVSlothCombo#744]
I'm not sure if it's just me, but for some reason my assize features isn't working on Holy 3 but was working on holy 1 .. the afflatus features and lucid dreaming works though.

edit+
Lucid dreaming isn't working too for holy 1 ..

**Comment by Tsusai** [comment]
Is this if you drag/drop Holy 1 to your hotbar or is this a level sync issue?
