### ISSUE TITLE
[RPR] Add buffer to regress feature to prevent accidental activation

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/XIVSlothCombo#75]
It might just be me, but whenever I activate it, I accidentally press it twice, causing it to teleport back again accidentally. Giving it a small buffer, just to prevent the queued input from activating the 2nd part

**Comment by Nik-Potokar** [comment]
This plugin dosent change the default buffer(skill queue) so there is not much I could do other than checking for it's cooldown but iirc it already does that.

Are you using noclippy by any chance or any other plugin that manipulates the buffer window/time?

**Comment by sauronshotdogs** [comment]
I am using noclippy. It seems I am just accidentally pressing it still during the teleport, which queues the regress. I will try being more careful

**Comment by Nik-Potokar** [comment]
From personal experience anything above 1.2sec will have some drawbacks when it comes to quick desicison making.

0.8-1.2 seems the best imo

**Comment by sauronshotdogs** [comment]
Do you mean buffer in the combo, or noclippy stuff?

**Comment by Nik-Potokar** [comment]
No clippy

**Comment by sauronshotdogs** [comment]
Gotcha, will try out .8-1.2 and see if that works better. Thanks!
