### ISSUE TITLE
[RPR] Gluttony takes over Lemure’s Slice if enshroud

### ISSUE THREAD

**Issue by Calvaire** [Nik-Potokar/XIVSlothCombo#750]
If you toggle Gluttony on Blood Stalk option, then in enshroud you can not use Lemure’s Slice because there is Gluttony on CD instead. I find it a bit confused because in enshroud you definitely can not use gluttony. The way I can see to solve it is to toggle other enshroud combo option but I don't want to add all enshroud combos on Blood Stalk or GIbbet/Gallow.
By the way, I also want the option back which replaces Gibbet/Gallow with Communio when there is only 1 orb left.

**Comment by damolitionn** [comment]
Already fixed in #732, just hasn't been pushed to live yet for some reason.

**Comment by Calvaire** [comment]
Thanks, I saw it a AOE fix. So in single target it's also fixed right?

**Comment by damolitionn** [comment]
Actually, the fix was already implemented last week. What version of the plugin are you using?

**Comment by Calvaire** [comment]
It's 3.0.15.1 and that's what I toggle.
![image](https://user-images.githubusercontent.com/4760425/170171985-42988a84-7f01-4cb0-b11b-afcbe459c644.png)

**Comment by damolitionn** [comment]
Oh I see now, fixed. Next time if you have an issue, remember to state what options you have selected otherwise it's hard to understand what you mean

**Comment by Calvaire** [comment]
Thanks a lot!

**Comment by k-kz** [comment]
Addressed in #752
