### ISSUE TITLE
[ALL]　"/scombo toggle {features}" needs to be changed back to the original.

### ISSUE THREAD

**Issue by Ninningozaru** [Nik-Potokar/XIVSlothCombo#759]
I would like to be able to use "/scombo toggle {features}" during combat.
I used to be able to do it normally, but when I tried to use it after a while, it said "Features cannot be toggled in combat."
I loved the style of fighting while switching between features in combat, so please bring it back!

**Comment by k-kz** [comment]
No. It enabled people to circumvent purposeful restrictions put in place, so it's been removed during combat. Sorry!
