### ISSUE TITLE
[All] Accounting for fight downtime

### ISSUE THREAD

**Issue by akiff14** [Nik-Potokar/XIVSlothCombo#763]
Toggle, set, and unset feature commands are now prohibited by the update.
I heard that this was the cause of bugs and other problems, so I think it is inevitable.

However, there are some scenes where you may want to save buffs at the following times.

1. before switching phases of the raid boss.
-> For example, the timing of Fenex's flight in "Pandemonium3rd" or the timing of Primals' changeover in "The Weapon's Refrain (Ultimate)".
2. Before the boss in the instance dungeon.

...etc.

Regardless, I would like a way to avoid using buffs at times when I want to preserve them.
I would be glad if you could consider this.

Thank you for always Sloth Team and Testers

**Comment by k-kz** [comment]
After consideration, we've got no current plans to account for specific occurrences in Savage/Ultimate content.
