### ISSUE TITLE
[NIN] Simple Mudras bug 

### ISSUE THREAD

**Issue by creepysnake** [Nik-Potokar/XIVSlothCombo#765]
The mudra path of simple mudras has an issue in my 70lv ninja
The Mudra Path set 1 of Ten Mudras which is supposed to be: Fuma Shuriken > Raiton/ Hyosho Ranryu, Suiton 
But it delivers this sequence: Fuma Shuriken > Hyoton > Hyoton

Actually, It was no problem yesterday before I wrongly clicked the update button

**Comment by Taurenkey** [comment]
Fixed in the next update.
