### ISSUE TITLE
"Hide to Mug" on NInja adds Trick Attack to the button

### ISSUE THREAD

**Issue by Karapian** [Nik-Potokar/XIVSlothCombo#767]
[SlothDebug.txt](https://github.com/Nik-Potokar/XIVSlothCombo/files/8795265/SlothDebug.txt)

**Comment by Taurenkey** [comment]
The description on the feature is perhaps a bit incomplete. The feature only puts Mug onto the button whilst in combat (which the description says) however it should add that it will put Trick Attack on the button whenever you're hidden or have the Suiton buff. I have removed the Suiton check as that would prioritise whilst in combat and changed the description to reflect that it will add Trick Attack to the button when hidden (i.e out of combat).
