### ISSUE TITLE
[NIN] Suggestion: Keep Kassatsu 

### ISSUE THREAD

**Issue by Karapian** [Nik-Potokar/XIVSlothCombo#768]
for Expandest has the button where Kassatsu and TA (and DWAD)  on the same button, but when you have Suiton Kassatsu stays present until Kassatsu is triggered. in the NIN openner you start with Suiton, then hit Kasstsu, then 3 GCDs before hitting Trick Attack. However with how the current shortcuts work, its impossible to put Trick Attack on a shortcut without sacrificing TA to be earlier then when you should press it

**Comment by Taurenkey** [comment]
Possibly closed due to job rework within Sloth. Please re-open if you feel the current implementation is insufficient.
