### ISSUE TITLE
[WHM] Plenary Indulgence & Regen feature

### ISSUE THREAD

**Issue by nativepapaya** [Nik-Potokar/XIVSlothCombo#772]
In regards to Plenary Indulgence, would it be possible to add an option to automatically insert it before an AoE heal such as Medica/Rapture.

As for Regen, an option to add it to Cure 2 feature set if Regen is not on the target, with less priority then the OGCDs.

Thank you for the great plugin!

**Comment by NikkoXIV** [comment]
I was thinking about this, and while it's not a hard thing to add, I'm worried that it will lead to it being used at the wrong time.  It's a 60-second cooldown that gives a 10-second buff which only responds to AoE healing.  It seems too situational to just be used on cooldown.

**Comment by k-kz** [comment]
Discussed this among the devs and decided it's too open to "bad use" and would likely cause more problems than it solves.
