### ISSUE TITLE
[NIN] Plz add Opener option

### ISSUE THREAD

**Issue by onenightgirl** [Nik-Potokar/XIVSlothCombo#774]
Simple Ninja does not have Opener option.
This makes it impossible to become a sloth in high difficulty content.
Would it be possible to consider adding an Opener option?

Or the quickest way to do this would be if Simple Ninja would replace Aeolian Edge instead of Spinning Edge.
Then we can run Opener manually.
![YIL6Egz](https://user-images.githubusercontent.com/10812176/171555581-a3f2af78-fa51-4c90-922f-9d8123177d60.png)

**Comment by k-kz** [comment]
We have no current plans to add this, as it's a bit of a logistical nightmare what with cooldown dependency and so on.
We'll try to look into it sometime near the end of the month.
