### ISSUE TITLE
[NIN] addon randomly stops using mudras in aoe combos

### ISSUE THREAD

**Issue by Pekkerst** [Nik-Potokar/XIVSlothCombo#775]
as title says. The addon will randomly stop using mudras during the aoe combo. Meaning doton and katon wont be used.
Using a mudra manually will sometimes fix the issue.

**Comment by GibXIV** [comment]
@Taurenkey  this is the issue reported on discord https://discord.com/channels/957680331056615506/957949182319157269/980887241725472788
I believe you got a fix locally that might help with this?

**Comment by MTTGamer** [comment]
> as title says. The addon will randomly stop using mudras during the aoe combo. Meaning doton and katon wont be used. Using a mudra manually will sometimes fix the issue.

I have noticed this too. Started happening at lvl 76 when we get Goka Mekkyaku.
