### ISSUE TITLE
[BRD] Iron Jaws returning Caustic Bite once Stormbite applies, regardless

### ISSUE THREAD

**Issue by dnorthrupva** [Nik-Potokar/XIVSlothCombo#78]
Will check the code in a bit but something in newest version broke Iron Jaws.

Applies Stormbite, goes to Caustic, then stays on Caustic.

**Comment by Nik-Potokar** [comment]
Its due to some testing will be fixed/reverted shortly

**Comment by Stein121** [comment]
I think I have a potential fix, it should only refresh duration with iron jaws if either stormbite or caustic is at 4 seconds left else it will cast gcd single target rotation. Might be dependent on other features, need some testing:

internal class BardIronJawsFeature : CustomCombo
    {
        protected override CustomComboPreset Preset => CustomComboPreset.BardIronJawsFeature;

        protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level)
            {
                if (actionID == BRD.IronJaws)
                {
                if (level < BRD.Levels.IronJaws)
                {
                    var venomous = TargetHasEffect(BRD.Debuffs.VenomousBite);
                    var windbite = TargetHasEffect(BRD.Debuffs.Windbite);
                    var venomousDuration = FindTargetEffect(BRD.Debuffs.VenomousBite);
                    var windbiteDuration = FindTargetEffect(BRD.Debuffs.Windbite);
                    if ((venomous && windbite) && (venomousDuration.RemainingTime < 4 || windbiteDuration.RemainingTime < 4))
                        return BRD.IronJaws;

                    if (!windbite)
                        return BRD.Windbite;
                    if (!venomous)
                        return BRD.VenomousBite;
                    else if (HasEffect(BRD.Buffs.StraightShotReady))
                        return OriginalHook(BRD.RefulgentArrow);
                    return OriginalHook(BRD.BurstShot);
                }

                if (level < BRD.Levels.BiteUpgrade)
                {
                    var venomous = TargetHasEffect(BRD.Debuffs.VenomousBite);
                    var windbite = TargetHasEffect(BRD.Debuffs.Windbite);
                    var venomousDuration = FindTargetEffect(BRD.Debuffs.VenomousBite);
                    var windbiteDuration = FindTargetEffect(BRD.Debuffs.Windbite);
                    if ((venomous && windbite) && (venomousDuration.RemainingTime < 4 || windbiteDuration.RemainingTime < 4))
                        return BRD.IronJaws;

                    if (!windbite)
                        return BRD.Windbite;
                    if (!venomous)
                        return BRD.VenomousBite;
                    else if (HasEffect(BRD.Buffs.StraightShotReady))
                        return OriginalHook(BRD.RefulgentArrow);
                    return OriginalHook(BRD.BurstShot);
                }

                var caustic = TargetHasEffect(BRD.Debuffs.CausticBite);
                var stormbite = TargetHasEffect(BRD.Debuffs.Stormbite);
                var causticDuration = FindTargetEffect(BRD.Debuffs.CausticBite);
                var stormbiteDuration = FindTargetEffect(BRD.Debuffs.Stormbite);
                var gauge = GetJobGauge<BRDGauge>();

                if ((caustic && stormbite) && (causticDuration.RemainingTime < 4 || stormbiteDuration.RemainingTime < 4))
                    return BRD.IronJaws;
                if (!caustic)
                    return BRD.CausticBite;
                if (!stormbite)
                    return BRD.Stormbite;
                else if (gauge.SoulVoice == 100)
                    return BRD.ApexArrow;

                if (HasEffect(BRD.Buffs.StraightShotReady))
                    return OriginalHook(BRD.RefulgentArrow);
                return OriginalHook(BRD.BurstShot);
            }
        return actionID;
        }
    }

**Comment by Iaotle** [comment]
@Stein121, could you make a pull request with the changes outlined? All you have to do is fork the repo and change the relevant file.

**Comment by Stein121** [comment]
Hey, seems like Nik already incorporated the fix, no need for pull request :)
