### ISSUE TITLE
Matra Magic Missing from Blue Mage Moon Flute Opener

### ISSUE THREAD

**Issue by MHWalker94** [Nik-Potokar/XIVSlothCombo#799]
When using the Moon Flute Opener feature for Blue Mage, the text of it does mention that Matra Magic is required for use. However, I took the opener very slow and without Moon Flute to compare it to the opener on the Balance BLU section, and found out that it's actually skipping using Matra Magic entirely. 

The whole opener itself is fine (Triple Trident and Rose of Destruction are swapped, but that really doesn't matter), and it even weaves Swiftcast meant for Matra Magic, it just doesn't use it (which in turn also wastes the use of Bristle earlier in the opener). 

If this is user error (which is likely), I'm going to apologize in advance. The only thing I can think of is that it uses some kind of internal timer separate from the Moon Flute buff and I may not be spamming the button fast enough to get Matra Magic out in time.

**Comment by Taurenkey** [comment]
According to the code, you need both Matra Magic active _and_ DPS mimicry for it to work. I can remove the DPS mimicry check if need be.

**Comment by MHWalker94** [comment]
THAT is the issue, thank you. I was testing on a target dummy and didn't have the mimicry active. 

Like I said, user error lol. Thank you

**Comment by k-kz** [comment]
@MHWalker94 Do let us know if there's any benefit from an option to disable need for mimicry. Ty! o/

**Comment by MHWalker94** [comment]
Might be worth it if anything just to avoid similar confusion like this, but ultimately you shouldn't be using Matra Magic if you don't have the DPS mimic active anyway.

**Comment by k-kz** [comment]
If there's no optimisation to be gained, then it sounds like we can sort it out by updating the description to stress that point more. Thank you!
