### ISSUE TITLE
[PLD] Solution for problem 18s pre-pull

### ISSUE THREAD

**Issue by JACHROEN** [Nik-Potokar/XIVSlothCombo#802]
There is an issue with the 18s FoF pre-pull opener where it will Royal Authority twice during the second and all consequent FoF windows. I've looked into the "code" and it seems to be an issue with one of the checks on the Drop atonement feature. This requiescat check:
```
if ((IsEnabled(CustomComboPreset.PLD_AtonementDrop) &&
                             GetCooldownRemainingTime(FightOrFlight) <= 15 && GetBuffStacks(Buffs.SwordOath) > 1) ||
                            (HasEffect(Buffs.Requiescat) && GetCooldownRemainingTime(FightOrFlight) <= 49))
                            return Atonement;
```

You will not have requiescat till very late in your FoF window during this opener as you start the fight with only 8 seconds of FoF left. So even though fight or flight will be under 15 seconds left and you will have 3 sword oath stacks, because you won't have requiescat it will just loop the royal authority until you use requiescat. Which will be with only 6-7 seconds left in the FoF window thus ruining your dps completely.

**Comment by grimgal** [comment]
#817 should fix this.
