### ISSUE TITLE
[RPR] Soulsow QoL Adjustments

### ISSUE THREAD

**Issue by Lexentale** [Nik-Potokar/XIVSlothCombo#805]
**1. Allow which skills `#408: Soulsow Reminder Feature` should replace.**
It currently replaces Slice, Spinning Scythe, Shadow of Death, Harpe and Blood Stalk. The issue this creates is, when out of combat and running up to a monster to attack, instead of initiating combat with Slice or Shadow of Death, you use Soulsow and have to wait an awkward GCD while auto-attacking the target.

Allowing it to only replace Harpe, for example, would address this. Quick mock-up:
![48567948](https://user-images.githubusercontent.com/107435698/173438925-823bb1dd-d555-485a-8e80-6d000850c5d7.jpg)

**2. Add `Soulsow Reminder Feature (Combat)`**
Allow Harpe to be replaced with Soulsow during combat ***if you have no target selected***. This would normally only occur during periods of downtime. It's important that it does not replace AoE skills (like above) as there are cases where you might use those without a target.

**Comment by k-kz** [comment]
Will consider adding some radio buttons to address point 1 soon - it's like that way currently due to single target openers.

Point 2 sounds good 👍
