### ISSUE TITLE
[BLM] Thunder III and IV overwrite each other between simple modes

### ISSUE THREAD

**Issue by ghost** [Nik-Potokar/XIVSlothCombo#809]
## Overview
This occurs specifically when using both `#69 Simple BLM Feature` and `#85: Simple AoE Feature` in unison. Each mode has adequate protection against overwriting their own respective thunders (III for Single, IV for AoE); however when swapping between modes, they often overlap when pressing buttons fast enough.

## Examples
- **Slowcasting Thunder III with your single-target button and swapping to your AoE button causes sloth to use Thunder IV.**

While undesirable, this is still serviceable in cases where new adds spawn, for example.

- **Slowcasting Thunder IV with your AoE button and swapping to your single-target button causes sloth to use Thunder III.**

The main culprit. Sloth actually knows you shouldn't cast Thunder III right after IV, but it doesn't realize it fast enough:

![2022-06-17-06-43-36](https://user-images.githubusercontent.com/107435698/174234768-d496f710-aca2-4847-81eb-600f6a377663.gif)

The button on the left is the single-target button; note the delay. The AoE button on the right, however, changes immediately.

**Comment by grimgal** [comment]
#815

**Comment by k-kz** [comment]
Addressed in #815
