### ISSUE TITLE
[RPR] True North

### ISSUE THREAD

**Issue by RoyBoiPlays** [Nik-Potokar/XIVSlothCombo#814]
Was thinking this would be a decent addition to add in though its not the biggest deal since things are fine as they are already.
Option to enable of one True North charge with proc of Gluttony so that the next Gibbet and Gallows are ez pz. 
Keep the second charge for manual usage too.
True North takes 45 seconds to get the charge back and Gluttony is 60 so it makes sense to me. Similar to what Samurai has as an option.

**Comment by damolitionn** [comment]
You mean this?

![image](https://user-images.githubusercontent.com/87623949/174468301-2b607cf5-312f-47d3-9ee3-0c2a64f0819b.png)

**Comment by RoyBoiPlays** [comment]
Oh yes thank you I should have noticed, so sorry for this.
________________________________
