### ISSUE TITLE
plugin unistalled itself and refuses to reinstall

### ISSUE THREAD

**Issue by AoiYui** [Nik-Potokar/XIVSlothCombo#819]
I have no idea what caused this so i can't say how to reproduce but the plugin unistalled itself and whenever i try to reinstall it it says "Failed to install plugin XIVSlothCombo. Please restart your game and try again. if this error occurs again, please contact the plugin author." Well i restarted and the error is still there so here i am.

**Comment by Genesis-Nova** [comment]
I know you closed the issue, but this is probably due to the recent staging build of dalamud's update. They did some clientstructs updates.

**Comment by k-kz** [comment]
^ Came here to say the same. We'll ship a fix soon. For now, stop using the Dalamud Beta.

**Comment by AoiYui** [comment]
> I know you closed the issue, but this is probably due to the recent staging build of dalamud's update. They did some clientstructs updates.

yep i close it cause someone on the discord told me about that which fixed my problem
