### ISSUE TITLE
[Request] Emote Toggle/Combo

### ISSUE THREAD

**Issue by E-Ballard** [Nik-Potokar/XIVSlothCombo#826]
With the new Draw/Sheathe emotes in the gold saucer it would be nice to have them cycle if you used one or the other.
![image](https://user-images.githubusercontent.com/59059387/175778719-025f84d0-1963-46c0-85fc-708120555a8b.png)

**Comment by k-kz** [comment]
This doesn't fall under the scope of what XIVSlothCombo does as a plugin (emotes and actions are not the same thing).
