### ISSUE TITLE
[GNB] Danger/Blasting Zone on AOE Combo

### ISSUE THREAD

**Issue by dstormcaller** [Nik-Potokar/XIVSlothCombo#831]
Something I noticed in testing out the plugin on Gunbreaker is that Blasting Zone doesn't come up on the Demon Slaughter Combo. If there aren't any hitches I'm not seeing, could you add it as an option?

Very grateful for the work you've put into this btw! My fingers have been in way less pain since I found it.

**Comment by k-kz** [comment]
@damolitionn
