### ISSUE TITLE
[MNK] Issues with Seconds Remaining Sliders and Thunderclap

### ISSUE THREAD

**Issue by Fawkes-Allen** [Nik-Potokar/XIVSlothCombo#832]
Monk currently seems to have a few issues when using it's features.

The first is that the Seconds Remaining sliders don't work in the `Bootshine` combo. The current action will always be `True Strike` until the time is up and the buff disappears. It does work however with the hardcoded 6 of the `Twin Snakes` Feature.

The second is that when at lower levels `Thunderclap` will never show up when out of combat. A quick look at the code seems to suggest this is due to it checking if `Formless Fist` is up, but not whether or not the player is high enough level to even have `Form Shift`.

**Comment by k-kz** [comment]
> The first is that the Seconds Remaining sliders don't work in the Bootshine combo. The current action will always be True Strike until the time is up and the buff disappears. It does work however with the hardcoded 6 of the Twin Snakes Feature.

Fixed in #836
Other issue still remaining

**Comment by k-kz** [comment]
Addressed in #836 and #844
