### ISSUE TITLE
[AST] #24 Simple Heals (Single Target)

### ISSUE THREAD

**Issue by zbee** [Nik-Potokar/XIVSlothCombo#840]
This doesn't seem to work with any targeting method I tried; and by not work I mean it just tries to constantly do Aspected Benefic and nothing else - If I disable option 27 then 28 still doesn't work.

My usual flow is mouse-over targeting, that didn't work, that's okay.
I also usually have my tank on focus target, this didn't work, that's weird.
I tried hard targeting them and refreshing the regen before moving on to the rest of the combo, this also did not work, that seems broken.

I wouldn't be surprised if mouse-over was never supported, or if targeting via the [Redirect plugin by Cair](https://github.com/cairthenn/Redirect) was not supported; but it should definitely support one of the options mentioned.

---

Optimally AST option 24 would have a drop-down to indicate who the "single target" will be (especially since it's not clear how it expects you to target your party member) where you can select hard-target, soft-target, focus-target (🤞 also mouse-over, or Redirect).

**Comment by k-kz** [comment]
Appreciate the write-up.
You're correct that we don't currently offer mouseover support, and also ReAction is known to cause some issues (though I'll struggle to elaborate, as I've never used it!) But what you're describing definitely doesn't sound like intended function.

That being said (I also don't play AST) if the options you're talking about are the ones I think they are, then they should be compatible with hard/soft/focus targeting.

Will look into this further, thanks for the report!

**Comment by Taurenkey** [comment]
I've looked into it and the features definitely work as intended. We only operate these features using hard targeting only. However as @k-kz has said it's not unknown to us that certain plugins interfere with the way it works. Unfortunately, there's not a whole lot we can really do about it as we don't use targeting hooks like they do.

**Comment by zbee** [comment]
Understood then, sounds like it is just some overlap between the two plugins that wouldn't be resolved without switching to targeting hooks.

Is this something you are looking to add? Or could a drop-down option still be added as suggested to also do focus-target?

**Comment by zbee** [comment]
Understood, that's fair enough then.

And what of an option to choose how you target your tank? I don't know how other keyboard+mouse users target heal to be quite honest, but I know at least that hard targeting wouldn't work for controller healers.
Or did I misunderstand and that would also require targeting hooks?
