### ISSUE TITLE
[RPR] Shadow of Death not triggering on both combo 

### ISSUE THREAD

**Issue by Mara-Li** [Nik-Potokar/XIVSlothCombo#846]
Shadow of death doesn't appear on both rotation (AOE + single target). Here are my parameters : 
![image](https://user-images.githubusercontent.com/30244939/176910529-396a051f-e3e6-4c82-818c-a02090bfcd9e.png)
Also, my debug : 
```
START DEBUG LOG
Plugin Version: 3.0.16.1
Current Job: faucheur
Current Zone: 340
Current Party Size: 0
START ENABLED FEATURES
12001 - RPR_ST_SliceCombo
12003 - RPR_ST_SliceCombo_SoD
12020 - RPR_AoE_ScytheCombo
12022 - RPR_AoE_ScytheCombo_WoD
12026 - RPR_AoE_ScytheCombo_Enshroud
12041 - RPR_GluttonyBloodSwathe
12051 - RPR_ArcaneCirclePlentifulHarvest
12052 - RPR_Regress
12058 - RPR_CommunioOnGGG
12059 - RPR_EnshroudCommunio
100031 - ALL_Melee_TrueNorth
100096 - ALL_Melee_Menu
END ENABLED FEATURES
Redundant IDs found: 3
START REDUNDANT IDs
12030
12031
12050
END REDUNDANT IDs
Status Effect Count: 2
START STATUS EFFECTS
ID: 365, COUNT: 10, SOURCE: 3758096384
ID: 364, COUNT: 30, SOURCE: 3758096384
END STATUS EFFECTS
END DEBUG LOG
```

**Comment by k-kz** [comment]
@Mara-Li my initial attempts to reproduce this issue were unsuccessful.

Could you try changing your sliders to different values (and then back to your desired ones) to make sure they're setting their values properly?
Thanks!

**Comment by Mara-Li** [comment]
Well, I updated everything and now the shadow of death works! Thank you :)
