### ISSUE TITLE
Dancer feedback

### ISSUE THREAD

**Issue by ImRingo** [Nik-Potokar/XIVSlothCombo#854]
I would like to see an option within the Dancer options (most notably within the "Simple Dancer (Single Target)/(AoE) Feature" option) to exclude Saber Dance from being auto-added to the single button rotation keybind for both Single Target and AoE Target. Right now, if this option is enabled and Saber Dance gets above...I think 80 or 85 gauge, it will be swapped into that Single/AoE Target rotation keybind automatically. While this might be desirable most of the time, I'm finding that, especially in stop-and-go situations in some fights (notably some DSR phases as well as a lot of dungeon trash pulls), having this behavior ends up using a Saber Dance when it should have been saved. For instance, saving a Saber Dance even with the chance of over-capping on the resource for a boss burn multiple seconds or even a minute down the road. 

As it currently stands, unless I am uber dumb, I do not see a way to exclude Saber Dance from being auto-added to the Single/AoE Target feature within the add-on. If possible, please add a sub-option within the "Simple Dancer (Single Target)/(AoE) Feature" that allows us to de-couple Saber Dance from this feature set.

**Comment by k-kz** [comment]
It's unlikely I'll add this, but DNC will be getting reworked to provide both Simple and Advanced modes in the near future, so I'll keep it in mind for Advanced mode.
