### ISSUE TITLE
[BRD] Burst Mode

### ISSUE THREAD

**Issue by KouGithub2022** [Nik-Potokar/XIVSlothCombo#865]
burst mode (Raging Strikes, Barrage, Battle Voice Radiant Finale) Cannot be used.

**Comment by Taurenkey** [comment]
Burst mode is a PvP feature. Those are not PvP actions. This is not an issue.

**Comment by k-kz** [comment]
+1 to the comment above - not quite sure what problem it is you're having.

Please try to explain the issue in greater detail, and optionally provide us with the contents of the file output when you type `/scombo debug BRD` in-game.

**Comment by k-kz** [comment]
Closing this for now - feel free to reopen the issue with some clarification in the future :)
