### ISSUE TITLE
[BLU] Primal Feature (Moon Flute Burst friendly)

### ISSUE THREAD

**Issue by Zelminar** [Nik-Potokar/XIVSlothCombo#866]
Use Glass Dance for icon replacement logic?

SAME AS current "Primal Feature", however:
Observing current cooldown of EITHER [Surpanakha x4, Nightbloom, Matra Magic, or Phantom Flurry] as the control, don't allow primal abilities to be displayed/used which their cooldown would exceed that of observed control cooldown upon usage.

Observing the Nightbloom timer (120 seconds total) would be BEST as it's the earliest 120 second cooldown in the whole burst. Next earliest observed 120 second cooldown would be Supranahka, followed by Matra Magic just behind Phantom Flurry.

Given this logic, between moon flute bursts, this button should be able to display/use:
(Priority order displayed below is to keep same order as moon flute burst order)
- J-Kick x1                       (300 Potency)
- Rose of Destruction x2-3? (400 potency ea.)
- Feather Rain x3            (300 Potency ea.)
- Shock Strike x1             (400 potency)

**SUB OPTION:** (For safety/positional reasons)
Include J-Kick

**ADDITONALLY** A slider could be added for the player to adjust for a leeway of their desire. This slider, if set to 5 seconds would extend the ALLOWED time for a primal ability to be used per the rules above. The player would then need to realize they extended their potential wait of executing the MF Burst though. (Default to 0 seconds, for maximum laziness)

```csharp
        internal class BLU_PrimalComboMFSafe : CustomCombo
        {
            protected internal override CustomComboPreset Preset { get; } = CustomComboPreset.BLU_PrimalComboMFSafe;

            protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level)
            {
                if (actionID is GlassDance)
                {
                    if (IsEnabled(CustomComboPreset.BLU_AddJKick) && IsOffCooldown(JKick) && GetCooldownRemainingTime(NightBloom) > 60 && IsSpellActive(JKick))
                        return JKick;
                    if (IsOffCooldown(RoseOfDestruction) && GetCooldownRemainingTime(NightBloom) > 30 && IsSpellActive(RoseOfDestruction))
                        return RoseOfDestruction;
                    if (IsOffCooldown(FeatherRain) && GetCooldownRemainingTime(NightBloom) > 30 && IsSpellActive(FeatherRain))
                        return FeatherRain;
                    if (IsOffCooldown(ShockStrike) && GetCooldownRemainingTime(NightBloom) > 60 && IsSpellActive(ShockStrike))
                        return ShockStrike;
                    if (IsOffCooldown(GlassDance) && GetCooldownRemainingTime(NightBloom) > 90 && IsSpellActive(GlassDance))
                        return GlassDance;
                }

                return actionID;
            }
        }
```
**NOTE:** The `GetCooldownRemainingTime(NightBloom)` values could be fine tuned to better sync with the actual time these moves would happen within the burst. I'm bad at math on this.

**Comment by Taurenkey** [comment]
The current version of the BLU Moon Flute opener is based off [this](https://i.imgur.com/faKFpASh.jpg) rotation. BLU rotation relies on using its cooldowns ASAP, so we're unlikely to implement something that deliberately interferes with that. The advice given if you want to do a Moon Flute reopener is just to use the primal spells off cooldown, but you shouldn't save them just for that.

**Comment by Zelminar** [comment]
Link doesnt work

**Comment by k-kz** [comment]
Please consider adding this as a [Pull Request](https://github.com/Nik-Potokar/XIVSlothCombo/pulls) so it can be reviewed by one of the devs that works on BLU, and continue any discussion to be had there. Thanks!

Also, @Taurenkey, he's right - link doesn't work.

**Comment by Zelminar** [comment]
https://i.imgur.com/Hh0WMAl.png

I don't understand...

**Comment by Taurenkey** [comment]
@k-kz is asking you to put a pull request in if you've already done the work for the request. Most folks posting suggestions don't code but for those that can we encourage you to put pull requests in.
