### ISSUE TITLE
[WHM] Thin air Overcap feature

### ISSUE THREAD

**Issue by Dainichi22** [Nik-Potokar/XIVSlothCombo#872]
Would be nice to have a Thin air feature that leaves 1 stack that would be used after opener/reopener

**Comment by NikkoXIV** [comment]
When is it getting used now?

**Comment by Dainichi22** [comment]
Anywhere really, I made mine use it if PoM and Assize is ON CD, so those two are above the priority system when it comes to ogcd ussage

**Comment by k-kz** [comment]
Seems like you're looking for a fix for implementations on your own fork/code - this proposition bears no relevance to existing features in the main project.
