### ISSUE TITLE
[BLM] Low level Firestarter concern

### ISSUE THREAD

**Issue by Cadwgan** [Nik-Potokar/XIVSlothCombo#877]
Currently when synced to lv50 content, Firestarter procs are being used instantly, this isn't humanly possible to react to and is a dead giveaway of tool usage.

While it isn't technically optimal it may be wise to add an option to delay the Firestarter check and use of it slightly, it may be possible to achieve this by checking if Firestarter has 29 or 28 seconds or less remaining, depending on how the cooldown is read internally.

**Comment by k-kz** [comment]
@grimgal thoughts?

**Comment by Kagekazu** [comment]
I'll take a look at it to see if I can delay the proc at lower lvls 😃

**Comment by k-kz** [comment]
> I'll take a look at it to see if I can delay the proc at lower lvls 😃 

I'm not familiar with the action in question, but if you can get away with applying a delayed weave, do that, if not, give us a shout on discord and we can discuss a hard delay function.

**Comment by Kagekazu** [comment]
> > I'll take a look at it to see if I can delay the proc at lower lvls 😃
> 
> I'm not familiar with the action in question, but if you can get away with applying a delayed weave, do that, if not, give us a shout on discord and we can discuss a hard delay function.

made it like the normal code - if fire phase is 3 secs or lower, use the proc, otherwise just cast fire, should solve the tool usage behavior (firestarter is an instant fire refresh proc that u can get)

**Comment by Cadwgan** [comment]
With the BLM rework / rewrite, this issue is back.
