### ISSUE TITLE
[MNK] AOE Blitz

### ISSUE THREAD

**Issue by StevieCoops** [Nik-Potokar/XIVSlothCombo#88]
Is it possible to get an option for an optimal AOE masterful blitz?

**Comment by Iaotle** [comment]
You're gonna have to describe what you mean by that. Preferably even make a lil request.

**Comment by StevieCoops** [comment]
My apologies. The AOE combo under PB should be similar to the existing single target logic. Triple Shadow/Rockbreaker to use Elixir Field and Shadow, Fury, Rockbreaker to Rising Phoenix/Flint Strike, and another triple Shadow/Rockbreaker for Phantom/Tornado

**Comment by Nik-Potokar** [comment]
Added but needs testing
Also  Shadow, Fury, Rockbreaker does not return FlintStrike so i adjusted it (Not sure if its optimal)
And the skill is on Leg Sweep! (For now)

**Comment by StevieCoops** [comment]
Ok, I tested it and it does work, but since the solar combo does rock, fury, rock you get Celestial Revolution which is non-optimal. Doing shadow, fury, rock manually still gives me Flint/Phoenix so not sure what happened

**Comment by Nik-Potokar** [comment]
Right i see the issue now, Will adjust and update later today!

**Comment by StevieCoops** [comment]
No, order shouldn't matter

**Comment by Nik-Potokar** [comment]
Added test and let me know if it needs any adjustments please!

**Comment by StevieCoops** [comment]
It seems like if you do the AOE combo slow it works, but if you press and queue the actions for solar nadi, it does shadow, fury, shadow. I think maybe it's not being replaced fast enough? Maybe try starting the combo replacement with shadow

**Comment by Nik-Potokar** [comment]
Can you turn off "monk aoe combo feature" and let me know if that fixes it.

If so might need to rework some stuff for monk

**Comment by StevieCoops** [comment]
Yes, turning off the normal AOE seems to fix the problem! As a sidenote, at level 81 and below it currently does triple Arm, but it should be triple Rockbreaker for Lunar until Shadow at level 82

**Comment by Nik-Potokar** [comment]
Another update should fix the spamming issue also adjusted for low and higher lvl but do let me know if something is still not working as intended

**Comment by StevieCoops** [comment]
Did some quick tests, and I couldn't get it to mess the combo up so I'd say it's working. Also level synced rockbreaker worked as well
