### ISSUE TITLE
[BLU] Perpetual Ray -> Sharpened Knife (good filler DMG where applicable)

### ISSUE THREAD

**Issue by Zelminar** [Nik-Potokar/XIVSlothCombo#880]
Request by 4D in discord #blu 06/26/2022
"Perpetual ray + Sharpened knife?
Guaranteed 1s stun (if not immune) into 0.99s cast that deals over double the dmg for stunned targets"

```c#
public const uint
    SharpenedKnife = 11400,
    PerpetualRay = 18314,
```
```c#
        public static class Debuffs
        {
            public const ushort
                Stun = ???????;
        }
```
I'm not sure how to figure the stun debuff id
```c#
        internal class BLU_PerpetualKnife : CustomCombo
        {
            protected internal override CustomComboPreset Preset { get; } = CustomComboPreset.BLU_PerpetualKnife;

            protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level)
            {
                if (actionID is PerpetualRay)
                {
                    if (InMeleeRange() && TargetHasEffectAny(Debuffs.Stun) && IsSpellActive(SharpenedKnife)) 
                        return SharpenedKnife;
                }
                
                return actionID;
            }
        }
```

**Comment by k-kz** [comment]
Please consider adding this as a [Pull Request](https://github.com/Nik-Potokar/XIVSlothCombo/pulls) so it can be reviewed by one of the devs that works on BLU. Thanks!

**Comment by Zelminar** [comment]
https://i.imgur.com/Hh0WMAl.png

I don't understand...

**Comment by k-kz** [comment]
> https://i.imgur.com/Hh0WMAl.png
> 
> I don't understand...

Your issue presents code, which would be better formatted as a pull request, where you can directly request a merge of said code.
