### ISSUE TITLE
[Healers] Shielding not included in HP values

### ISSUE THREAD

**Issue by Rabalaba** [Nik-Potokar/XIVSlothCombo#882]
Scholar and Sage have slider options for setting threshold for healing but do not include shielding on target, it may be beneficial to include a check if shield value is greater than x to the slider as well.

**Comment by k-kz** [comment]
We've added the baseline code to the framework to add options relating to `ShieldPercentage`, `RawShieldValue` and `HasShield`. Will look into making some related features and options in the future.

#900
