### ISSUE TITLE
[NIN] #333 Assassinate/Dream issue within Aeolian Edge Combo

### ISSUE THREAD

**Issue by Tester122333** [Nik-Potokar/XIVSlothCombo#883]
At v3.0.16.4
When checked [# 332] and [# 333], Assassinate/Dream keeps always view in Aeolian Edge Combo during GCD even if during recast.
![image](https://user-images.githubusercontent.com/109010811/178132345-407ed9e9-af3c-4bf0-9a94-faa530699eb8.png)

**Could you disappear Assassinate/Dream in Aeolian Edge Combo during recast after skill used?**
If recast comes back, it should be displayed.

**Comment by k-kz** [comment]
We have a complete NIN rework on the way, which hopefully will address this issue.

Going to leave this thread open in the meantime - @Taurenkey let me know if your pending rework covers this issue, please.

**Comment by Tester122333** [comment]
@k-kz , Thanks for confirmation.
I hope fixed by next release from @Taurenkey.
