### ISSUE TITLE
[SAM] Higanbana problem in Gekko Combo

### ISSUE THREAD

**Issue by acgzone1** [Nik-Potokar/XIVSlothCombo#884]
I have a promble when using Gekko Combo to boss in 48 ppl raid like DRS first boss or mob like ovni in Eureka Hydatos, the combo keep doing Higanbana combo. May it related to having too much DoT/debuff on them? Sometime i have the same issue by using BRD, looping 2 Dot again and again.

**Comment by k-kz** [comment]
It's likely that the boss you're targeting has greater than the maximum amount of readable debuffs. XIVSlothCombo reads this as the target not having your applied debuff, even if you've just hit with it.

Unfortunately it's a quirk of the game's debuff handling, and to my knowledge, we can't do anything to address it directly.
