### ISSUE TITLE
[BLM] Ley Lines on Simple BLM bug

### ISSUE THREAD

**Issue by MTTGamer** [Nik-Potokar/XIVSlothCombo#885]
Hi, I noticed after the last 2 updates that Ley Lines are being used even if you uncheck the option.

![image](https://user-images.githubusercontent.com/98697810/178143754-870cc280-a0cb-49fa-bdc1-4f97e31137ae.png)

**Comment by Taurenkey** [comment]
Can you also check if you have the opener option enabled? Ley Lines are a part of that feature too.

**Comment by MTTGamer** [comment]
> Can you also check if you have the opener option enabled? Ley Lines are a part of that feature too.

You mean this opener? If it this, then yes. I didn't know Ley Lines were a part of this. 

![image](https://user-images.githubusercontent.com/98697810/178144519-9ab85046-c52a-4d04-b33b-01c69e5157e6.png)

**Comment by MTTGamer** [comment]
I was under the impression that if I disable the Ley Lines option it would be removed from the entire combo. Strange that I only noticed that it was being used after the last 2 updates that occurred in this plugin. During some fights I saw that Ley Lines was being activated and I didn't want to. After turning off this Opener option, Ley Lines stopped being used.

**Comment by k-kz** [comment]
I don't have any involvement with the BLM code, nor play the job, so I can't speak for the intended/expected functions, but BLM hasn't been updated since ab24030968cd9438fa14a79b3c42a47552cf675d - which was 21 days ago, and (I think) part of the `v3.0.16.1` release.

**Comment by MTTGamer** [comment]
If it's not a bug, maybe as a suggestion then: if we uncheck the Ley Lines option, would you be able to remove the whole combo, including this opener? There are some situations that Ley Lines ends up being used unnecessarily, such as after killing groups of enemies, 1 or 2 are left and you switch to single target and end up using Ley Lines on an almost dead enemy.

**Comment by Taurenkey** [comment]
We can work on the wording, however opener style features are very specific and will use whatever it needs to in order to do it. It would be unfeasible to rely on specific settings set elsewhere, otherwise we might get bugs in the openers.

**Comment by MTTGamer** [comment]
> We can work on the wording, however opener style features are very specific and will use whatever it needs to in order to do it. It would be unfeasible to rely on specific settings set elsewhere, otherwise we might get bugs in the openers.

Ah ok then. Thank you for all hard work.

**Comment by GibXIV** [comment]
As the LeyLines is an integral part of the (Balance) Opener to get everything off in time, i would (and do) use it differently:

-uncheck leylines
-uncheck opener when doing normal dungeon/world content, even on a dungeon boss the perfect balance opener would not be too important
-check opener (which includes leylines) whenever you do single boss content, raids, trials etc and expect the opener to use a leylines so be in the right position at the start

**Comment by MTTGamer** [comment]
> As the LeyLines is an integral part of the (Balance) Opener to get everything off in time, i would (and do) use it differently:
> 
> -uncheck leylines -uncheck opener when doing normal dungeon/world content, even on a dungeon boss the perfect balance opener would not be too important -check opener (which includes leylines) whenever you do single boss content, raids, trials etc and expect the opener to use a leylines so be in the right position at the start

Yes, doing that now. Thank you.

**Comment by MTTGamer** [comment]
Thank you everyone!
