### ISSUE TITLE
[MCH] Battery overcap should take into account GCD

### ISSUE THREAD

**Issue by Iaotle** [Nik-Potokar/XIVSlothCombo#89]
Don't interrupt gcd with OGCDs. Should be as easy as adding a GCD > 0.7 check.

**Comment by Codemned** [comment]
Pointless feature added.

**Comment by Iaotle** [comment]
It's kinda sad to see someone acting this way honestly.

1. Combat could end right after you hit 100 energy and your reopener is messed up.
2. You could be CC'ed or prevented from acting in some way (e.g. paralysis, stun, etc).
3. You might want to hold the cooldown to use it on the boss if you hit 100 energy right at the end of an add phase.

I'm sure it doesn't make sense to put this in because your "perfect" machinist rotation  that you practice on a dummy doesn't need it. That doesn't mean you should talk shit about a feature that I find useful. If you conclusively explained why you thought it wasn't needed and respectfully declined to work on it that would be fine. Instead you're acting like a know-it-all.

IMO you should stop acting like this. It's not constructive.

**Comment by Iaotle** [comment]
Just in general - oGCDs should never prevent you from using your GCD skills, it's pretty simple stuff.
