### ISSUE TITLE
[Suggestion][GNB] No Mercy into Double Down

### ISSUE THREAD

**Issue by RRage1** [Nik-Potokar/XIVSlothCombo#896]
What is thy suggestion?

In order to improve the button bloat of GNB this measure can be adopted to diminish by a button the keybinds required for the job to function optimally. The plugin already has different options, but this one could be an interesting alternative to others.

Are abilities in question must be truly mutually exclusive?
While it is not a requirement by the game (like Primal Rend and Inner Release) there is no reason why anyone would ever want to Double Down outside of No Mercy. Yes, you might just want to suck but then you can disable this option; for all intended a decent use of GNB having No Mercy and Double Down on the same button is only a help on a very bloated job.

Does this actually saves you button space?
Yes, it does save you a keybind

Is it wild and wacky?
Not really since,a s stated before, you only even Double Down inside No Mercy windows anyway

Is the overall level of intelligence required to execute is about as low as the floor?
It is on the floor as you just need to use your most powerful weaponskill within your damage buff

**Comment by Daemeous** [comment]
Oh my sweet summer child, I think you're looking for this Repo: https://github.com/attickdoor/XIVComboPlugin
We don't believe in placing such...distasteful...limitations on combos here...
