### ISSUE TITLE
[DRG] Disembowel / Chaosthrust / life surge added to full thrust combo for a one button ST combo

### ISSUE THREAD

**Issue by Stein121** [Nik-Potokar/XIVSlothCombo#91]
Hey! I noticed that you didn't have a one button single target rotation combo for dragoon (to alternate when disembowel or Chaos Thrust buff/debuff is not applied, also adding life surge into the mix for a juicy crit on full thrust. I tested it and it works like a charm at all levels, cheers! love your work btw :)

            if (actionID == DRG.FullThrust)
            {
                var Disembowel = FindEffectAny(DRG.Buffs.PowerSurge);
                if (comboTime > 0)
                {
                    if ((lastComboMove == DRG.TrueThrust || lastComboMove == DRG.RaidenThrust) && level >= DRG.Levels.Disembowel && (Disembowel == null || (Disembowel.RemainingTime < 10)))
                        return DRG.Disembowel;

                    if (lastComboMove == DRG.Disembowel && level >= DRG.Levels.ChaosThrust)
                        return DRG.ChaosThrust;

                    if ((lastComboMove == DRG.TrueThrust || lastComboMove == DRG.RaidenThrust) && level >= DRG.Levels.VorpalThrust)
                        return DRG.VorpalThrust;

                    if (lastComboMove == DRG.VorpalThrust && !HasEffect(DRG.Buffs.LifeSurge) && !GetCooldown(DRG.LifeSurge).IsCooldown)
                        return DRG.LifeSurge;

                    if (lastComboMove == DRG.VorpalThrust && level >= DRG.Levels.FullThrust)
                        return DRG.FullThrust;
                }

                if (HasEffect(DRG.Buffs.SharperFangAndClaw) && level >= DRG.Levels.FangAndClaw)
                    return DRG.FangAndClaw;

                if (HasEffect(DRG.Buffs.EnhancedWheelingThrust) && level >= DRG.Levels.WheelingThrust)
                    return DRG.WheelingThrust;

                return OriginalHook(DRG.TrueThrust);
            }

            return actionID;

**Comment by Stein121** [comment]
Tested it on a level 20 lancer and it works well for disembowel / life surge, once I hit 50 i'll test for chaos thrust but it should work. Don't forget to add the missing var, Cheers! :)

**Comment by Nik-Potokar** [comment]
Thank you! 
It was added as an separate option

If there are any other request for DRG please do let me know (Since i cannot test DRG myself)

**Comment by Stein121** [comment]
public const short needs to have: PowerSurge = 2720,
instead of  PowerSurge = 120,

**Comment by Nik-Potokar** [comment]
Fixed
