### ISSUE TITLE
[Bug][Global] IsMoving does not work correctly

### ISSUE THREAD

**Issue by worstpersoneuw** [Nik-Potokar/XIVSlothCombo#913]
I noticed when playing Summoner that my icon is buzzing when moving.
[See here](https://i.gyazo.com/1e69b729485b41a5ce0eb8c96a8cec62.gif)

I then noticed it's using IsMoving
[See here](https://github.com/Nik-Potokar/XIVSlothCombo/blob/799529ae999525c744465d02dd0379a6cb7ec9b1/XIVSlothCombo/Combos/PvE/SMN.cs#L308)

Originating from this code
[See here](https://github.com/Nik-Potokar/XIVSlothCombo/blob/799529ae999525c744465d02dd0379a6cb7ec9b1/XIVSlothCombo/CustomCombo/Functions/Movement.cs#L19)

that causes issue for me even when using only 36 fps.

May I propose you use the actual local playerspeed (float) at

`ffxiv_dx11.exe+1F62730+44`

You'll find it near the Sig

`E8 ?? ?? ?? ?? 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? EB 7D `

**Comment by Taurenkey** [comment]
I'm currently testing a rewrite of the code at this very moment. I've tried using the signature you've provided but I can't get any results from it unfortunately. This rewrite should hopefully be better at lower FPS, but given the feature has always worked flawlessly for me I cannot say for certain until people that have issues test it for me.

**Comment by worstpersoneuw** [comment]
I thought of something like this but I'm really not an expert in C# so this might not be the best way to do this

`var playerSpeedResolve = Service.SigScanner.ScanModule("48 8D 0D 0C 03 DB 00");`
`StringBuilder hexOffset = new();`
`for (int i = 0; i < 4; i++) hexOffset.AppendFormat("{0:x2}", Marshal.ReadByte(playerSpeedResolve, (6 - i)));`
`playerSpeedResolve += Convert.ToInt32(hexOffset.ToString(), 16) + 0x4B;`
`PluginLog.Warning("Is Player Walking: " + (Marshal.ReadInt32(playerSpeedResolve) > 0));`

**Comment by Rabalaba** [comment]
public unsafe bool IsMeMoving()
    {
        var map = FFXIVClientStructs.FFXIV.Client.UI.Agent.AgentMap.Instance();
        if (map->IsPlayerMoving > 0)
            return true;
        else return false;
    }

use the map to check if your moving all the code is already there thanks to aers
