### ISSUE TITLE
Suggestion [All Battle Classes] Include Potions for burst / burst windows

### ISSUE THREAD

**Issue by Rabalaba** [Nik-Potokar/XIVSlothCombo#915]
something like 
public unsafe void UseItem(uint itemId)
    {
        FFXIVClientStructs.FFXIV.Client.Game.ActionManager.Instance()->UseAction(FFXIVClientStructs.FFXIV.Client.Game.ActionType.Item, itemId, 0xE0000000, 65535, 0, 0, null);
    }

then in the combat routine

if (conditions met blah blah)
                {
                    this.UseItem(1_036_112); // itemid for grade 6 int pot hq
                }

**Comment by Taurenkey** [comment]
We're never using items in Sloth.
