### ISSUE TITLE
[Global] Emulate level

### ISSUE THREAD

**Issue by Ratio805** [Nik-Potokar/XIVSlothCombo#916]
Add a way to emulate (lower) levels for either testing/optimizing a rotation or for when doing class quests that unlock abilities. Ex: Level 60 Ninja quest unlocks Huraijin which is the opener for the Simple Ninja Single Target and the Simple Ninja AoE. Being able to emulate level 59 for the duration of the 60 class quest would make it easier than potentially turning off scombo and/or rearranging hotbars.

**Comment by Rabalaba** [comment]
just check if the quest for unlocking the skill is complete FFXIVClientStructs.FFXIV.Client.Game.QuestManager.IsQuestComplete, if not then don't pass as a valid skill to replace icon with, rather than just straight level check.
