### ISSUE TITLE
[SAGE] DPS Feature Dosis3

### ISSUE THREAD

**Issue by Gestridens** [Nik-Potokar/XIVSlothCombo#92]
So while Dosis 1, and Dosis 2 automatically lead to Eukrasia Dosis and work as intended, Dosis 3 does not, when you manually activate Eukrasia and use Eukrasia Dosis, the icon does change with the countdown  as if it is working, and even lights up as intended when the timer runs out. However it still does not automatically switch to Eukrasia.

**Comment by Gestridens** [comment]
https://gyazo.com/3b94f87daf6bb6df07b0a18980fb99ee Short example.

**Comment by damolitionn** [comment]
Strange, I just tested it now on a level 82 and a level 90 Sage on a training dummy and everything seems to be working.

I've tested it:
- Manually casting Eukrasia
- Using the 1 button combo at the beginning so it goes Dosis 3 -> Eukrasia -> Eukrasian Dosis 3
- Waiting for the DoT to tick down to 4 seconds for the reapply condition to be met.

The only thing I can think of is to drag the spell again from the spell book or you're hitting a level 90 dummy while you're sub level 90 and the cast missed.

**Comment by Iaotle** [comment]
There's an issue sometimes when you're slotting an old ability on your bar. While visually it looks like an ability its ID is actually the ID of an old ability (e.g. Dosis 2 can look like Dosis 3 and have the ID of Dosis 2). So try re-slotting the correct skill and see if that fixes your issue.

**Comment by Gestridens** [comment]
Ok upon doing some tests, yeah I did manage to fix it, but doing som emoer tests this is what I've noticed

Dosis III slotted in Manually for me = Doesn't Auto Combo it
Dosis II --> III slotted in manually forme = Doesn't Auto Combo into it
Dosis I --> III when slotted in manually  = Does work for me.

Not sure if that's how it's intended to work, but yeah fixed the issue by slotting in Dosis I instead of II or III

**Comment by damolitionn** [comment]
Yeah that's not right. I just logged in to test, in my own personal fork there's no issue but I switch to this I have the same issue you have. I'm gonna take a look around.

**Comment by Nik-Potokar** [comment]
I just pushed an update can you give it a try again? @Gestridens

**Comment by Gestridens** [comment]
Yup that update fixed it, works as intended now!
