### ISSUE TITLE
[bug][SAM] #490 Yukikaze combo doesn't activate when ka & getsu sens lit up

### ISSUE THREAD

**Issue by thoccavelli** [Nik-Potokar/XIVSlothCombo#920]
For Samurai at level 59, I noticed #490 Yukikaze combo doesn't activate when ka & getsu sens are lit up. Instead it just repeats the Gekko combo. Thus, cannot light up all 3 sens to perform Midare.  I don't know if this is a problem at level 90 SAM.

[SAM] sloth setup:
#488 490 505 506 512 all on
#504 off

Changing #504 to ON doesn't seem to make #490 to work properly either.  Thank you

**Comment by damolitionn** [comment]
Have you tried reslotting your Gekko slot or turning 490 off then on?

**Comment by thoccavelli** [comment]
I found out my Dalamud was running attick's /pcombo concurrently with Sloth Combo, with SAM options checked on in both plugins. After I disabled attick's XIV combo /pcombo, Sloth Combo worked fine including #490. Thanks!
