### ISSUE TITLE
[SCH] Suggestion - Chain Stratagem

### ISSUE THREAD

**Issue by hokeenthong** [Nik-Potokar/XIVSlothCombo#93]
Hi, as I always forget to apply chain stratagem whenever it is up, can I suggest that an option is provided to apply chain stratagem when it is up during the broil 4 spam. 

Thank you.

**Comment by Iaotle** [comment]
Isn't Chain Stratagem supposed to be used during the party buff window? I suppose it's on 120s CD tho so it's fine to use on CD.

**Comment by Nik-Potokar** [comment]
Will be added today along with DPS option for SCH that is fully functional

**Comment by Nik-Potokar** [comment]
Added along with few other features!
Test and let me know if it needs any adjustments

**Comment by hokeenthong** [comment]
> Isn't Chain Stratagem supposed to be used during the party buff window? I suppose it's on 120s CD tho so it's fine to use on CD.

Yeah, you are absolutely correct and thus this suggestion.

**Comment by hokeenthong** [comment]
> Added along with few other features! Test and let me know if it needs any adjustments

Tested and it works. Thank you very much.

**Comment by Nik-Potokar** [comment]
Awesome thank you!

If there is anything else that you want added do let me know!
