### ISSUE TITLE
[BRD] Simple Bard is using Empyreal Arrow at the wrong spot in its opener

### ISSUE THREAD

**Issue by gimleey** [Nik-Potokar/XIVSlothCombo#930]
EA should be used _after_ Raging Strikes in the opener but Simple Bard is using EA inbetween GCD 1 and 2 and RS inbetween 2 and 3.

**Comment by augporto** [comment]
After taking a look at this , it indeed had a little bug that under some circumstances made EA or BL fire before having RS up on the opener, fixed it on #931.

Should be up on the next release. 

Weirdly enough I have never noticed it 🤔 

Thx for reporting it.
