### ISSUE TITLE
[MNK] Demolish option is gone

### ISSUE THREAD

**Issue by iluvrust** [Nik-Potokar/XIVSlothCombo#932]
There used to be an option where you can press Demolish if you just want to do your rotation without CDs. This option was helpful in fights where you need to delay your 1 or 2 minute buffs. Could this Demolish option please be re-added? Thanks.

**Comment by Genesis-Nova** [comment]
The demolish option got removed intentionally.
This is not something that we're looking to add back into the plugin.

**Comment by iluvrust** [comment]
Why was it removed?

**Comment by Genesis-Nova** [comment]
Because that kind of micro `endgame`-only optimization is not something we're looking to focus on with our plugin.

**Comment by iluvrust** [comment]
Is there a way to use an older version of the plugin?

**Comment by iluvrust** [comment]
Other classes still have the option to save their bursts.

**Comment by Genesis-Nova** [comment]
Which jobs have options to continue comboing but ignore buff usage?
Pretty sure MNK was the only one that had that option
Now there are options to *not* include buffs in your combo, but that's not the same as giving a separate button that just excludes buffs beside one that includes everything.

**Comment by k-kz** [comment]
#925 #911 #759 #763 

It's exactly as @Genesis-Nova and @GibXIV put it, really.
