### ISSUE TITLE
[SAM] Combos are a little bit different after patch, don't know if this is intended.

### ISSUE THREAD

**Issue by AceAkechi123** [Nik-Potokar/XIVSlothCombo#942]
I believe something may be fucky wucky inside SAM. Was doing some fiddling and have noticed that the combo chains after the opener are being done Gekko -> Kasha -> Yukihaze when iirc before patch it was being done Yukihaze -> Gekko -> Kasha.

**Comment by Manic21Man** [comment]
To add to this the filler option doesn't seem to be firing at all for me. It'll just skip over and continue the combos as normal. I'll do more testing later but thought I'd give a heads up on a potential issue.
