### ISSUE TITLE
[NIN] Mudras not working

### ISSUE THREAD

**Issue by MTTGamer** [Nik-Potokar/XIVSlothCombo#947]
When enabling Simple Mudra or enabling Ninjutsu in Advanced Mode, or enabling Simple Mode, after 2 Mudras then it will change to Ninjutsu Ability  (Simple Mudra) or iit will change back to the first Mudra used (Simple and Advanced Mode).

**Comment by Taurenkey** [comment]
Unable to replicate, please provide more details or a video clip if possible.

**Comment by MTTGamer** [comment]
> Unable to replicate, please provide more details or a video clip if possible.

I found what was causing the issue. It's the NoClippy Addon i was using to mitigate my high latency problems (Similiar to XIVAlexander). It has a function to "predict mudras". It was enabled and causing the issue. After disabling it it worked again.

![image](https://user-images.githubusercontent.com/98697810/187040293-4f0bd73b-3082-43ff-9407-d14e5f836cdb.png)
