### ISSUE TITLE
[Nin] Armor Crush no longer activates

### ISSUE THREAD

**Issue by realmrwu** [Nik-Potokar/XIVSlothCombo#956]
scombo stops incorporating Armor Crush into the attacks if too long time passes from Huton timer threshold.

Advanced Mode ST
Armor Crush enabled and set to trigger at 30sec
Attack a dummy, wait for Huton timeleft to fall below 24 second
scombo just ignores Armor Crush and keeps using Aeolian Edge instead

**Comment by Taurenkey** [comment]
No longer seems to be an issue. Feel free to re-open if you disagree.
