### ISSUE TITLE
[RPR] Choice between Early Gluttony and Early Enshroud opener.

### ISSUE THREAD

**Issue by ArcanaXVIII** [Nik-Potokar/XIVSlothCombo#958]
Hi everyone,

Sloth currently default to the Early Gluttony opener.

According to the Balance, Early Gluttony is more situational and Early Enshroud is generally the go-to option to default to : 
![image](https://user-images.githubusercontent.com/54767189/187696364-257f0d25-665d-4bb7-8506-7af137b6e5bf.png)

Would it be possible to implement a toggle to select which opener Sloth should do? 

Furthermore, the Early Gluttony opener used right now puts Arcane Circle before Soul Slice, which is the optimal choice if you have a GCD <=2.47. Seeing as the current starter sets/BiS for 6.2 are looking at a 2.49/2.5 GCD where it'd be more optimal to weave AC after Soul Slice, would it also be possible to implement as a toggle? 
![image](https://user-images.githubusercontent.com/54767189/187697393-50538e3b-3d34-46b6-9ef5-307d4e7ca3aa.png)

Thanks!

**Comment by k-kz** [comment]
Just a note to say that the current opener as it exists only puts AC before SS if you're spamming the button - if you use a tincture in the correct spot it will align everything else according to the image you posted.

**Comment by ArcanaXVIII** [comment]
> 

Thanks for the heads up, yeah I didn't test with potions. So the Early Gluttony should be good.

Still it would be great to have an Early Enshroud option as it's recommended as the default opener, Early Gluttony being more on a fight by fight basis.

**Comment by k-kz** [comment]
Addressed in #965
