### ISSUE TITLE
SAM - 2.14 filler in ST combo uses the fast sam 1.99-2.01 filler

### ISSUE THREAD

**Issue by Kagekazu** [Nik-Potokar/XIVSlothCombo#959]
Hey,

i noticed that while having the 2.14 filler selected, it does double hagakure instead of once. 
i can post logs and my settings if u need them.

**Comment by shoryukenpizza** [comment]
https://user-images.githubusercontent.com/112630314/187910421-33706450-986e-4640-a153-84a08c601578.mp4

More interestingly, the problem occurs either while fighting with a party with both Burst features on, but not with a training dummy. Additionally, I've replicated the problem with a training dummy by turning the Burst features off as shown above.

**Comment by Kagekazu** [comment]
https://www.fflogs.com/reports/V2YWFCJjLbfGyxH8#fight=last

in this log of p6s is had the issue again, on the new test .dll

idk if its an issue on my end or something interfering..
If u need me to test something/sent a debug file from my settings, lemme know :)

**Comment by Kagekazu** [comment]
apparently it doesnt disable main dll when u load in dev plugin. Manually disabled main plugin and now everything works as intented!
