### ISSUE TITLE
[BRD] Request - Turn Burst Shot into Iron Jaws when dots about to expire

### ISSUE THREAD

**Issue by stevanhi** [Nik-Potokar/XIVSlothCombo#96]
Basically the way the #22 "SimpleBard" option works, but ONLY for iron jaws when dots are about to expire, and not the ogcds.

edit: did not mean to mention that issue, was just referring to the number beside the SimpleBard option.

**Comment by Nik-Potokar** [comment]
Not a bad idea will add a toggle for it!
