### ISSUE TITLE
[All Jobs] Secondary combo that holds CDs

### ISSUE THREAD

**Issue by Mentholman112** [Nik-Potokar/XIVSlothCombo#960]
In the event of a fight transition where CDs/resources are better held for a reset instead of getting partial usage. Would it be possible to bind a combo to a different ability (e.g. 2nd combo skill like Syphon Strike) that holds all CDs and resources (apart from capping).

**Comment by Spanglish1337** [comment]
Have you tried just pressing the button when the global cooldown ends, not during oGCD weave windows at all? It works for all the jobs I have played so far

**Comment by Mentholman112** [comment]
Ah I see the last 15% or so of the gcd will always prio a gcd instead of an ogcd so as not to clip and it wont use anything, well notice thats a good tip thanks

**Comment by k-kz** [comment]
#932 #925 #911 #759 #763
