### ISSUE TITLE
[NIN] Advanced Mode - Single Target Problems

### ISSUE THREAD

**Issue by Megasder** [Nik-Potokar/XIVSlothCombo#974]
Hi, have been trying ninja with the advanced mode and I really like it, but it has some problems.

- Even with "Kassatsu Feature" Checked, it never uses Kassatsu, however if you check "Kassatsu Feature - Use Hyosho Ranryu" and use Kassatsu manually, it uses Hyosho ranryu.
Edit: Nevermind, it only uses Kassatsu if you have the Suiton Buff, but I dont know if that is intentional.

- If "Ninjutsu Feature - Use Raiton" and "Kassatsu Feature - Use Hyosho Ranryu" is up, when you use kassatsu, it will use raiton instead of hyosho ranryu
Edit: Same as before, if you have the Suiton Buff it works fine, it uses hyosho ranryu.

- When "Bunshin Feature - Phantom kamaitachi Feature" is cheked, it never uses phantom kamaitachi (however it appears like 0,5 seconds after you use bunshin, but it dissapears before you are able to use it and it never appears again)
<a href="https://gyazo.com/99eaef84a34d09da3be362c3f03d07d3"><img src="https://i.gyazo.com/99eaef84a34d09da3be362c3f03d07d3.gif" alt="Image from Gyazo" width="113.99999999999994"/></a>
Edit: Same as the others, if you have the Suiton Buff phantom kamaitachi doesn't dissapear and it uses it.

Edit2: I Tried with the same settings checked having Suiton Up and Suiton Down and the 3 problems I posted above only work when Suiton is Up, never when Suiton is down.
Edit3: Okay they also work if the target has Trick Attack debuff, WTF.
Edit4: It doesn't work with the meisui buff, only with trick attack and suiton buff.

Okay, my setting 
![1](https://user-images.githubusercontent.com/92712466/188940519-dff6298c-aa92-4d69-8fb7-63b72e009325.JPG)
![2](https://user-images.githubusercontent.com/92712466/188940532-d39a1b05-9808-4780-92db-355bdc12ab43.JPG)
![3](https://user-images.githubusercontent.com/92712466/188940549-02dd3cb2-440e-478a-a9c9-2842c9c149e5.JPG)

**Comment by Daemeous** [comment]
Enabling "use Suiton" under the Ninjustu feature would make the main combo use all these abilities, just be aware that Ninja is a job based around it's burst windows so the logic may be saving some of your heavy hitting abilities for use during Trick Attack for the increased damage, and without letting the plugin use Suiton it'll never put Trick Attack up so these abilities go unused.

**Comment by Megasder** [comment]
Yeah I know XD but the thing is I use suiton manually only to bosses, and not waste them on normal enemies. So I can understand not using kassatsu on normal enemies, but If my character uses Bunshin, at least use Phantom without the need to use Suiton XD or if I manually use kassatsu on normal enemies, use the improved highest damage skill, not Raiton.

**Comment by ArcanaXVIII** [comment]
I mean, you rarely fight a single normal enemy by itself. Normal enemy would be dungeon packs, and in this case it falls under Advanced AOE where you can disable CDs, and leave CDs enabled on Advanced ST.

It's what I do, I don't enable big CDs on AOE and they end up available when I reach the boss and used by Advanced ST. And if there are only two enemies left, I'll keep AOEing, it's dungeons anyway lol.

**Comment by Taurenkey** [comment]
Not bugs.
