### ISSUE TITLE
Requesting DRK Auto Blackest Night Feature and Hold Button Option

### ISSUE THREAD

**Issue by SomeRandomFinalFantasyer** [Nik-Potokar/XIVSlothCombo#976]
I'd like to have a toggle for Dark Night where it automatcally casts Blackest Night on yourself everytime it's up on the main DPS combos.

Another option I'd like is the ability to hold button instead of having to click it constantly to help with my arthritus thank you. im a controller user.

**Comment by k-kz** [comment]
I don't know DRK well enough to comment on the first part, but re: the latter - you can definitely get hold of some external software to achieve this, but it's not something we would look to directly implement in Sloth.

If you haven't already joined the discord, I'd recommend doing so and dropping a message in general chat. We have plenty of controller players who do xyz to skirt around this sort of thing :)

**Comment by damolitionn** [comment]
No, it just seems too unoptimal. What if you're off tanking, what if you don't take enough damage, what if you need TBN for a TB at a specific point in the fight but now you can't use it because you used it on CD seconds ago. This doesn't account for the fact that what if your TBN didn't pop, now it's a waste of 3000MP.

**Comment by SomeRandomFinalFantasyer** [comment]
It's optional. It would be useful for me for soloing in Eureka and Bozja and various other solo scenarios. I'm not trying to be optimal anyways i just want to stay alive.

**Comment by k-kz** [comment]
His point is that it's particularly niche, and the vast majority of our users would see zero use of it for most, if not all of their gameplay.
