### ISSUE TITLE
[SCH] Ruin II Moving Option not working

### ISSUE THREAD

**Issue by Hazado** [Nik-Potokar/XIVSlothCombo#986]
Scholar - Single Target DPS Feature - Ruin II Moving Option

![image](https://user-images.githubusercontent.com/416114/189492043-92ceef76-8797-4c8b-aa9e-beb7cbd92e6a.png)

When im moving and using Ruin it just keeps trying to use Ruin

**Comment by Tartarga** [comment]
Cannot reproduce
As you're saying it's still trying to use Ruin, are you below level 38?

**Comment by Hazado** [comment]
Lvl 50, ill test in combat as well. 
I was just trying to start combat with ruin and running.

**Comment by Hazado** [comment]
Right, got it working once i was in combat.
Thank you for that clarification
