### ISSUE TITLE
[DNC] Feature: Overcap protection for SP and AOE combo at lv76

### ISSUE THREAD

**Issue by sauronshotdogs** [Nik-Potokar/XIVSlothCombo#99]
Add Saber Dance to SP and AOE rotation at lvl 76 when at about to overcap.

Since there is a random element to it, putting it at 90 would seem safe.

![image](https://user-images.githubusercontent.com/95890035/147908211-aaee754b-e3f2-44a9-9016-82388384c882.png)
![image](https://user-images.githubusercontent.com/95890035/147908227-7f2ba795-f280-4408-9f65-fca7c82db89f.png)

Adding Overcap protection to feathers would be nice as well

**Comment by Nik-Potokar** [comment]
Esprit overcap added but feathers overcap wont be added at this time since they can proc into another feather and they are already on one button by default.

**Comment by sauronshotdogs** [comment]
Thanks. Tested at 90 and works great!
