### ISSUE TITLE
Potion in main rotation

### ISSUE THREAD

**Issue by drazeal** [Nik-Potokar/XIVSlothCombo#993]
Since potions are frustrating and  for many people with high ping or animation locks ruins the rotations i'd like to ask if its posible to add it in main combo for Jobs.
Like set a fixed No. at a specific hotbar (to eliminate writing the same part for all pots taht every Job uses) and include it in the rotation.
I know that not all jobs have the same starting point for pot but it will be better than no pot at all or a messed up rotation cause of a delayed activation.
1st time posting smthing so sry if there is anything missing.  Its just that i got that recently with animation locks and it kinda messed up.

**Comment by nativepapaya** [comment]
The devs have no intention of support item use. What you can do though is install ReAction. It has an option that lets you queue potions, which makes weaving them much easier.
