### ISSUE TITLE
[MNK]   Auto CD's

### ISSUE THREAD

**Issue by TheFallenZX** [Nik-Potokar/XIVSlothCombo#996]
Not sure what happened or where it could be, but something is making Monk automatically just burn though all the Riddle of Earth Stacks.
also Automatically using True north.

I do NOT have either of those settings turn on

Riddle of Earth should not be included in any of this, it gives 0 benefits to rotation, it DOES NOT give True North effect anymore, hasn't for a long time.
If it Purely a defensive and with it being included into this without valid reason it screws things over

**Comment by ArcanaXVIII** [comment]
We had a discussion over on Discord about this. Some people seem to have a repo installed with a forked version of Sloth that has some weird/outdated options. 

Please make sure your Sloth comes from the official repo, which is : https://raw.githubusercontent.com/Nik-Potokar/MyDalamudPlugins/main/pluginmaster.json

In general, make sure the plugins you use come from their respective official repo and some weird aggregator repo like Akurosia.

**Comment by TheFallenZX** [comment]
I'll give it a check when i get a chance, thank you for the reply!
