### ISSUE TITLE
[BLM] Xenoglossy feature not working

### ISSUE THREAD

**Issue by italomato** [Nik-Potokar/XIVSlothCombo#997]
Hey there! The xenoglossy feature (replaces scathe with xenoglossy when available) doesn't seem to be working. Scathe keeps being itself even when there are polyglots. None of the simple features are active to avoid conflict. 
Thank you very much!

**Comment by k-kz** [comment]
Could you go in-game and type `/scombo debug BLM` and upload the file (or its contents) here so we can attempt to replicate the issue?

Thanks :]

**Comment by italomato** [comment]
Hey there, sure thing. I just did the command and it generated a .txt file called 'SlothDebug' on my desktop. I didn't manage to find how to upload a file here, so I will paste the text.

START DEBUG LOG

Plugin Version: 3.0.17.2

Current Job: black mage / Black Mage / BLM
Current Job Index: 7

Current Zone: 134
Current Party Size: 0

START ENABLED FEATURES
2002 - BLM_LeyLines
2003 - BLM_Blizzard
2004 - BLM_ScatheXeno
2005 - BLM_Fire_1to3
100010 - ALL_Healer_Raise
100098 - ALL_Healer_Menu
END ENABLED FEATURES

Redundant IDs found: 0
Status Effect Count: 3
START STATUS EFFECTS
ID: 1411, COUNT: 0, SOURCE: 3758096384
ID: 365, COUNT: 10, SOURCE: 3758096384
ID: 364, COUNT: 30, SOURCE: 3758096384
END STATUS EFFECTS
END DEBUG LOG

Thank you very much!

**Comment by k-kz** [comment]
That's the one, thanks for uploading. We'll take a look into it soon!
